remote_theme: pages-themes/architect@v0.2.0
name: Nelson
description: Nelson
author: Allan CORNET
author_email: nelson.numerical.computation@gmail.com
github:
  is_project_page: false
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
