Nelson: Nelson::Dimensions Class Reference
Nelson::Dimensions Class Reference
#include <Dimensions.hpp>
Public Member Functions
Dimensions ()
Dimensions (indexType dimCount) throw (Exception)
Dimensions (indexType nrows, indexType ncols)
indexType & operator[] (indexType i) throw (Exception)
indexType getLength () const
indexType getElementCount () const
indexType mapPoint (const Dimensions &point) throw (Exception)
indexType getRows () const
indexType getColumns () const
indexType getDimensionLength (sizeType arg) const
void setDimensionLength (indexType dim, indexType len)
void expandToCover (const Dimensions &resize)
void incrementModulo (const Dimensions &limit, int ordinal)
bool inside (const Dimensions &limit)
bool equals (const Dimensions &alt)
void simplify ()
void printMe (Interface *io) const
void reset ()
void zeroOut ()
void makeScalar ()
indexType getMax ()
const bool isScalar () const
const bool isVector () const
const bool isRowVector () const
const bool isColumnVector () const
const bool is2D () const
Detailed Description
The Dimensions class is used to keep track of the number of dimensions for a given ArrayOf. The Dimensions class represents an N-tuple of integers (each non-negative). N can be made arbitrarily large. The '[]' operator is overloaded to return a reference to the dimension of interest. Indexing beyond the number of current dimensions automatically increases the length of the dimension vector, and pads it with 1's. For example if our current contents are $$[3,5,2,1]$$, and we index element 5, the dimension vector is automatically padded to $$[3,5,2,1,1,1]$$. Calling simplify() removes the trailing '1's.
Definition at line 67 of file Dimensions.hpp.
Constructor & Destructor Documentation
Dimensions() [1/3]
Nelson::Dimensions::Dimensions ()
The default constructor - length is set to zero.
Definition at line 56 of file Dimensions.cpp.
     {
         std::uninitialized_fill_n(data, maxDims, 0);
         length = 0;
     }
Dimensions() [2/3]
Nelson::Dimensions::Dimensions (indexType dimCount) throw (Exception)
Initialize the object with the given number of dimensions and all contents set to zero. Throws an Exception if the dimension count is negative.
Definition at line 70 of file Dimensions.cpp.
     {
         if (dimCount < 0)
         {
             throw Exception(_W("Illegal argument to Dimensions constructor"));
         }
         memset(data, 0, sizeof(indexType)*dimCount);
         length = dimCount;
     }
Dimensions() [3/3]
Nelson::Dimensions::Dimensions (indexType nrows, indexType ncols)
Return a 2-D dimension object with the specified number of rows and columns.
Definition at line 63 of file Dimensions.cpp.
     {
         data[0] = rows;
         data[1] = cols;
         length = 2;
     }
Member Function Documentation
equals()
bool Nelson::Dimensions::equals (const Dimensions & alt)
Returns true if we match the argument (exactly).
Definition at line 280 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::resize(), Nelson::ArrayOf::structConstructor(), and Nelson::TypeCheck().
     {
         bool retval;
         retval = (length == alt.length);
         for (sizeType i = 0; i < length; i++)
         {
             retval = retval && (data[i] == alt.data[i]);
         }
         return retval;
     }
expandToCover()
void Nelson::Dimensions::expandToCover (const Dimensions & resize)
Expand our dimensions so as to include the given point. This operation involves a sequence of operations. Let $$b$$ denote the argument, and $$a$$ denote this object. Then first we update the length of $$a$$ as $$ |a| (|a|,|b|) $$. Next, we loop over each dimension and apply the following algorithm:
if $$a_i$$ is undefined but $$b_i$$ is defined, $$a_i b_i$$.
if $$a_i$$ is defined but $$b_i$$ is undefined, $$a_i a_i$$.
if $$a_i$$ and $$b_i$$ are both defined, $$a_i (a_i,b_i)$$.
First, compute the larger of the two: the number of current dimensions and the number of requested dimensions.
Allocate a dimension vector to hold the new dimensions. It should be of size sze.
Now we loop over the dimensions. For each dimensions, we could have three cases to deal with:
a[i] is undefined but dimensions[i] is -> newsize[i] = dimensions[i];
a[i] is defined but dimensions[i] is not -> newsize[i] = a[i];
a[i] and dimensions[i] are both defined -> newsize[i] = max(a[i],dimensions[i]);
Case 1:
Case 2:
Definition at line 203 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::resize().
     {
         sizeType sze;
         sizeType i;
         Dimensions dimensions(*this);
         sze = (a.length > length) ? a.length : dimensions.length;
         reset();
         for (i=0; i<sze; i++)
         {
             if (i >= a.length)
             {
                 (*this)[i] = dimensions[i];
             }
             else if (i >= dimensions.length)
             {
                 (*this)[i] = a.data[i];
             }
             else
             {
                 (*this)[i] = (a.data[i] > dimensions[i]) ? a.data[i] : dimensions[i];
             }
         }
     }
getColumns()
indexType Nelson::Dimensions::getColumns () const
Returns the second dimension value (or zero if no dimensions have been defined yet).
Definition at line 143 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::getContentAsWideStringVector(), Nelson::ArrayOf::isEmpty(), Nelson::ArrayOf::summarizeCellEntry(), and Nelson::Transpose().
     {
         if (length == 0)
         {
             return 0;
         }
         else if (length == 1)
         {
             return 1;
         }
         else
         {
             return data[1];
         }
     }
getDimensionLength()
indexType Nelson::Dimensions::getDimensionLength (sizeType arg) const
Returns the requested dimension, or a 1 if the requested dimension exceeds the currently allocated number of dimensions. Unlike the access operator, this call does not modify the contents of the class.
Definition at line 159 of file Dimensions.cpp.
Referenced by Nelson::Evaluator::expressionList(), and Nelson::ArrayOf::isEmpty().
     {
         if (length <= arg)
         {
             return 1;
         }
         else
         {
             return data[arg];
         }
     }
getElementCount()
indexType Nelson::Dimensions::getElementCount () const
Return the total number of elements in the associated ArrayOf object. calculated via $${i=0}^{L-1} a_i$$, where $$L$$ is the value of length, and $$a_i$$ is equivalent to data[i].
Definition at line 116 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::allReal(), Nelson::And(), Nelson::ArrayOf::cellConstructor(), Nelson::ArrayOf::deleteNDimSubset(), Nelson::ArrayOf::diagonalConstructor(), Nelson::DotRightDivide(), Nelson::ArrayOf::emptyConstructor(), Nelson::Equals(), Nelson::Evaluator::expressionList(), Nelson::ArrayOf::getContentAsWideStringColumnVector(), Nelson::ArrayOf::getContentAsWideStringRowVector(), Nelson::ArrayOf::getContentAsWideStringVector(), Nelson::ArrayOf::getLength(), Nelson::GreaterEquals(), Nelson::GreaterThan(), isScalar(), isVector(), Nelson::LessEquals(), Nelson::LessThan(), Nelson::NotEquals(), Nelson::Or(), Nelson::ArrayOf::promoteType(), Nelson::ArrayOf::reshape(), Nelson::ArrayOf::resize(), Nelson::ArrayOf::setDataPointer(), Nelson::ArrayOf::setFieldAsList(), and Nelson::ArrayOf::structConstructor().
     {
         indexType retval;
         if (length == 0)
         {
             return 0;
         }
         retval = 1;
         for (sizeType i = 0; i<length; i++)
         {
             retval *= data[i];
         }
         return retval;
     }
getLength()
indexType Nelson::Dimensions::getLength () const
Get the number of currently allocated dimensions.
Definition at line 111 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::deleteNDimSubset(), Nelson::ArrayOf::isEmpty(), Nelson::ArrayOf::resize(), Nelson::Evaluator::rhsExpression(), Nelson::ArrayOf::setNDimContentsAsList(), and Nelson::ArrayOf::setNDimSubset().
     {
         return length;
     }
getMax()
indexType Nelson::Dimensions::getMax ()
$$.
Definition at line 80 of file Dimensions.cpp.
     {
         sizeType maxL = 0;
         for (sizeType i=0; i < length; i++)
         {
             maxL = (maxL > data[i]) ? maxL : data[i];
         }
         return maxL;
     }
getRows()
indexType Nelson::Dimensions::getRows () const
Returns the first dimension value (or zero if no dimensions have been defined yet).
Definition at line 131 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::getContentAsWideStringVector(), Nelson::ArrayOf::isEmpty(), and Nelson::Transpose().
     {
         if (length == 0)
         {
             return 0;
         }
         else
         {
             return data[0];
         }
     }
incrementModulo()
void Nelson::Dimensions::incrementModulo (const Dimensions & limit, int ordinal)
Increment our current value in the given dimension (ordinal), modulo the limit. This is equivalent to first incrementing the $$n$$-th dimension (where $$n$$ is the second argument) via $$a_n a_n + 1$$. Then, $$a_n$$ is checked against the limit $$b_n$$. If $$a_n >= b_n$$, then $$a_n 0$$, and the algorithm is repeated with ordinal+1.
Definition at line 249 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::deleteNDimSubset(), Nelson::ArrayOf::getNDimContentsAsList(), Nelson::ArrayOf::setNDimContentsAsList(), and Nelson::ArrayOf::setNDimSubset().
     {
         sizeType n;
         data[ordinal]++;
         for (n = ordinal; n<length - 1; n++)
             if (data[n] >= limit.data[n])
             {
                 data[n] = 0;
                 data[n+1]++;
             }
     }
inside()
bool Nelson::Dimensions::inside (const Dimensions & limit)
Returns comparison of $$a_n < b_n$$, where $$n$$ is the maximum defined dimension in $$a$$ (this object), and $$b$$ is the given argument.
Definition at line 261 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::deleteNDimSubset(), Nelson::ArrayOf::getNDimContentsAsList(), Nelson::ArrayOf::setNDimContentsAsList(), and Nelson::ArrayOf::setNDimSubset().
     {
         return (data[length-1] < limit.data[length-1]);
     }
is2D()
const bool Nelson::Dimensions::is2D () const
Returns true if we have exactly 2 dimensions allocated.
Definition at line 378 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::is2D(), and Nelson::ArrayOf::reshape().
     {
         return length <= 2;
         //return (getElementCount() == (getRows()*getColumns()));
     }
isScalar()
const bool Nelson::Dimensions::isScalar () const
Returns true if and only if we are equal to $$[1,1]$$.
Definition at line 358 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::isScalar(), Nelson::ArrayOf::reshape(), Nelson::ArrayOf::setDataPointer(), and Nelson::ArrayOf::vectorResize().
     {
         return (getElementCount() == 1);
     }
isVector()
const bool Nelson::Dimensions::isVector () const
Returns true if and only if we are equal to $$[1,n]$$ or $$[n,1]$$ for some value of $$n$$.
Definition at line 363 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::isVector(), Nelson::ArrayOf::reshape(), and Nelson::ArrayOf::vectorResize().
     {
         return (isRowVector() || isColumnVector());
     }
makeScalar()
void Nelson::Dimensions::makeScalar ()
Force the contents to be $$[1,1]$$.
Definition at line 350 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::complexConstructor(), Nelson::ArrayOf::dcomplexConstructor(), Nelson::ArrayOf::doubleConstructor(), Nelson::ArrayOf::doubleVectorConstructor(), Nelson::ArrayOf::int16Constructor(), Nelson::ArrayOf::int32Constructor(), Nelson::ArrayOf::int32VectorConstructor(), Nelson::ArrayOf::int64Constructor(), Nelson::ArrayOf::int64VectorConstructor(), Nelson::ArrayOf::int8Constructor(), Nelson::ArrayOf::logicalConstructor(), Nelson::Evaluator::simpleSubindexExpression(), Nelson::ArrayOf::singleConstructor(), Nelson::ArrayOf::uint16Constructor(), Nelson::ArrayOf::uint32Constructor(), Nelson::ArrayOf::uint64Constructor(), and Nelson::ArrayOf::uint8Constructor().
     {
         reset();
         length = 2;
         data[0] = 1;
         data[1] = 1;
     }
mapPoint()
indexType Nelson::Dimensions::mapPoint (const Dimensions & point) throw (Exception)
Map the given point using the current Dimensions. If the argument values are denoted as $$b_i$$, and our dimensions are $$a_i$$, then this member function computes $${i=0}^{L-1} b_i {j=0}^{j=i} a_j$$. Throws an exception if:
the argument has more dimensions than the current object
any of the arguments are outside the valid range, i.e., $$b_i < 0$$ or $$b_i >= a_i$$.
Definition at line 176 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::getNDimContents(), Nelson::ArrayOf::getNDimContentsAsList(), Nelson::ArrayOf::getNDimSubset(), Nelson::ArrayOf::resize(), Nelson::ArrayOf::setNDimContents(), Nelson::ArrayOf::setNDimContentsAsList(), and Nelson::ArrayOf::setNDimSubset().
     {
         indexType retval;
         indexType nextCoeff;
         indexType testableDims;
         retval = 0;
         nextCoeff = 1;
         testableDims = (point.length < length) ? point.length : length;
         for (indexType i = 0; i < testableDims; i++)
         {
             if ((point.data[i] < 0) || (point.data[i] >= data[i]))
             {
                 throw Exception(_W("Index exceeds dimensions."));
             }
             retval += nextCoeff * point.data[i];
             nextCoeff *= data[i];
         }
         for (sizeType j = testableDims; j < point.length; j++)
         {
             if (point.data[j] != 0)
             {
                 throw Exception(_W("Index exceeds dimensions."));
             }
         }
         return retval;
     }
operator[]()
indexType & Nelson::Dimensions::operator[] (indexType i) throw (Exception)
Return a reference to the ith dimension. This member function will adjust the number of dimensions present if the argument exceeds the current number allocated. The extra dimensions are padded with 1's. Thus, if our contents are $$[2,3]$$, then a reference to dimension 2 (these are zero-based indexing) converts our contents to $$[2,3,1]$$. Throws an exception if the argument is negative.
Definition at line 90 of file Dimensions.cpp.
     {
         if (i >= maxDims )
         {
             throw Exception(_("Too many dimensions! Current limit is") + " " + std::to_string(Nelson::maxDims) + ".");
         }
         if (i >= length)
         {
             indexType new_length = i + 1;
 #if defined(__NLS_WITH_OPENMP)
             #pragma omp parallel for
 #endif
             for (indexType j = length; j < new_length; j++)
             {
                 data[j] = 1;
             }
             length = new_length;
         }
         return data[i];
     }
printMe()
void Nelson::Dimensions::printMe (Interface * io) const
Print some representation of this object as a row vector, i.e., $$[a_1 a_2 a_n]$$.
Definition at line 291 of file Dimensions.cpp.
     {
         strcpy(msgBuffer, "");
         char buf[400];
         if (length > 0)
         {
             for (indexType i = 0; i < length - 1; i++)
             {
                 if (length >= 1)
                 {
                     sprintf(buf, "%dx", data[i]);
                 }
                 else
                 {
                     sprintf(buf, "%d", data[i]);
                 }
                 strcat(msgBuffer, buf);
             }
         }
         if (length >= 1)
         {
             sprintf(buf, "%d", data[length - 1]);
             strcat(msgBuffer, buf);
         }
         io->outputMessage(msgBuffer);
         /*
         snprintf(msgBuffer,MSGBUFLEN,"[");
         io->outputMessage(msgBuffer);
         for (int i=0; i<length-1; i++)
         {
             snprintf(msgBuffer,MSGBUFLEN,"%d ",data[i]);
             io->outputMessage(msgBuffer);
         }
         if (length >= 1)
         {
             snprintf(msgBuffer,MSGBUFLEN,"%d]",data[length-1]);
         }
         else
         {
             snprintf(msgBuffer,MSGBUFLEN,"]");
         }
         io->outputMessage(msgBuffer);
         */
     }
reset()
void Nelson::Dimensions::reset ()
Reset the number of allocated dimensions to zero, and reset the data pointer to NULL.
Definition at line 336 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::deleteVectorSubset(), expandToCover(), makeScalar(), Nelson::ArrayOf::structConstructor(), and Nelson::ArrayOf::vectorResize().
     {
         length = 0;
         memset(data, 0, sizeof(int)*maxDims);
     }
setDimensionLength()
void Nelson::Dimensions::setDimensionLength (indexType dim, indexType len)
A synonym for (*this)[dim] = len.
Definition at line 171 of file Dimensions.cpp.
     {
         data[dim] = len;
     }
simplify()
void Nelson::Dimensions::simplify ()
This member function trims any excess singleton (length 1) dimensions from our data array after the second dimension. Thus, the dimension vector $$[3,4,5,1,1]$$, will become $$[3,4,5]$$ after simplify() is called.
Definition at line 266 of file Dimensions.cpp.
Referenced by Nelson::ArrayOf::deleteNDimSubset(), Nelson::ArrayOf::getVectorSubset(), Nelson::ArrayOf::setField(), Nelson::ArrayOf::setFieldAsList(), Nelson::ArrayOf::setNDimContents(), Nelson::ArrayOf::setNDimContentsAsList(), Nelson::ArrayOf::setVectorContents(), Nelson::ArrayOf::setVectorContentsAsList(), and Nelson::TypeCheck().
     {
         if (length <= 2)
         {
             return;
         }
         indexType i = length - 1;
         while (i>1 && data[i] == 1)
         {
             i--;
         }
         length = i+1;
     }
zeroOut()
void Nelson::Dimensions::zeroOut ()
Set all of the allocated dimensions to zero.
Definition at line 342 of file Dimensions.cpp.
     {
         for (sizeType i = 0; i < length; i++)
         {
             data[i] = 0;
         }
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/types/src/include/Dimensions.hpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/Dimensions.cpp