Nelson: LineManager Class Reference
LineManager Class Reference
Public Types
enum outputStyle {
ERROR_OUTPUT = 0, WARNING_OUTPUT, STANDARD_OUTPUT, STANDARD_INPUT,
PROMPT_OUTPUT
}
Public Member Functions
int putCharacter (wchar_t wch, outputStyle eAsStyle=outputStyle::STANDARD_OUTPUT)
int printCharacters (std::wstring buffer, outputStyle eAsStyle=outputStyle::STANDARD_OUTPUT)
void usesColors ()
std::wstring getCurrentLine (void)
std::wstring getLineBeforeCaret (void)
std::wstring getLineAfterCaret (void)
void moveBeginningLine (void)
void moveEndLine (void)
void moveBackSingleChar (void)
void moveForwardSingleChar (void)
void moveBackSingleWord (void)
void moveForwardSingleWord (void)
void killCurrentPositionToEndLine (void)
void deletePreviousChar (void)
void deleteCurrentChar (void)
void moveBackHistory (void)
void moveForwardHistory (void)
void redrawLine (void)
void killLastWord (void)
void newLine (void)
void clearCurrentLine (void)
void setCurrentPrompt (std::wstring prompt)
std::wstring getCurrentPrompt ()
void displayPrompt (void)
void refreshLine (void)
void copyLine (std::wstring line)
void addCharacterCurrentLine (wchar_t ch)
Detailed Description
Definition at line 24 of file LineManager.hpp.
Member Function Documentation
addCharacterCurrentLine()
void LineManager::addCharacterCurrentLine (wchar_t ch)
add character to current line
Parameters
[in] character to add
Definition at line 419 of file LineManager.cpp.
 {
     for (size_t i = max_pos; i > cur_pos; i--)
     {
         if (i >= current_line_buffer.size())
         {
             current_line_buffer.push_back(L'\0');
         }
         current_line_buffer[i] = current_line_buffer[i - 1];
     }
     if (cur_pos >= current_line_buffer.size())
     {
         current_line_buffer.push_back(L'\0');
     }
     current_line_buffer[cur_pos] = ch;
     cur_pos += 1;
     max_pos += 1;
     if (max_pos >= current_line_buffer.size())
     {
         current_line_buffer.push_back(L'\0');
     }
     current_line_buffer[max_pos] = L'\0';
     if (cur_pos < max_pos)
     {
         refreshLine();
     }
 }
clearCurrentLine()
void LineManager::clearCurrentLine (void)
clear current line
Definition at line 275 of file LineManager.cpp.
Referenced by moveBackHistory(), moveForwardHistory(), and WindowsConsole::warningMessage().
 {
     current_line_buffer.clear();
     current_line_buffer.push_back(L'\0');
     moveBeginningLine();
     std::wstring blanks(max_pos, L' ');
     printCharacters(blanks, LineManager::STANDARD_INPUT);
     putCharacter(L'\r',LineManager::STANDARD_INPUT);
     displayPrompt();
     newLine();
 }
copyLine()
void LineManager::copyLine (std::wstring line)
copy line on terminal
Definition at line 409 of file LineManager.cpp.
Referenced by moveBackHistory(), moveForwardHistory(), redrawLine(), and WindowsConsole::warningMessage().
 {
     if (line.size() > 0)
     {
         printCharacters(line, LineManager::STANDARD_INPUT);
         current_line_buffer = boost::container::vector<wchar_t>(line.begin(), line.end());
         cur_pos = max_pos = (int)line.size();
     }
 }
deleteCurrentChar()
void LineManager::deleteCurrentChar (void)
deletes the current character
Definition at line 190 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (max_pos == 0)
     {
         doBeep();
     }
     else
     {
         if (cur_pos < max_pos)
         {
             for (size_t i = cur_pos; i < max_pos; i++)
             {
                 if (i + 1 < current_line_buffer.size())
                 {
                     current_line_buffer[i] = current_line_buffer[i + 1];
                 }
             }
             max_pos -= 1;
             refreshLine();
         }
     }
 }
deletePreviousChar()
void LineManager::deletePreviousChar (void)
delete the previous character
Definition at line 168 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (cur_pos > 0)
     {
         cur_pos -= 1;
         backSpace ();
         for (size_t i = cur_pos; i < max_pos; i++)
         {
             if (i + 1 < current_line_buffer.size())
             {
                 current_line_buffer[i] = current_line_buffer[i + 1];
             }
         }
         max_pos -= 1;
         refreshLine();
     }
     else
     {
         doBeep();
     }
 }
displayPrompt()
void LineManager::displayPrompt (void)
display prompt
Definition at line 380 of file LineManager.cpp.
Referenced by clearCurrentLine(), redrawLine(), and WindowsConsole::warningMessage().
 {
     /* check position */
     CONSOLE_SCREEN_BUFFER_INFO csbi;
     ::GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);
     int X = csbi.dwCursorPosition.X;
     if (X)
     {
         printCharacters(L"\n");
     }
     printCharacters(getCurrentPrompt(), LineManager::PROMPT_OUTPUT);
 }
getCurrentLine()
std::wstring LineManager::getCurrentLine (void)
returns current line
Returns
current line
Definition at line 50 of file LineManager.cpp.
Referenced by redrawLine(), and WindowsConsole::warningMessage().
 {
     boost::container::vector<wchar_t>::iterator itend = current_line_buffer.begin() + max_pos;
     std::wstring line(current_line_buffer.begin(), itend);
     return line;
 }
getCurrentPrompt()
std::wstring LineManager::getCurrentPrompt ()
get prompt used by terminal
Definition at line 287 of file LineManager.cpp.
Referenced by displayPrompt().
 {
     return currentPrompt;
 }
getLineAfterCaret()
std::wstring LineManager::getLineAfterCaret (void)
returns line after caret return line
Definition at line 69 of file LineManager.cpp.
 {
     boost::container::vector<wchar_t>::iterator itfirst = current_line_buffer.begin() + cur_pos;
     boost::container::vector<wchar_t>::iterator itend = current_line_buffer.begin() + max_pos;
     std::wstring line(itfirst, itend);
     if (cur_pos != max_pos)
     {
         line[(max_pos - cur_pos) + 1] = L'\0';
     }
     return line;
 }
getLineBeforeCaret()
std::wstring LineManager::getLineBeforeCaret (void)
returns line before caret return line
Definition at line 57 of file LineManager.cpp.
 {
     boost::container::vector<wchar_t>::iterator itend = current_line_buffer.begin() + max_pos;
     std::wstring line(current_line_buffer.begin(), itend);
     if (cur_pos >= current_line_buffer.size())
     {
         current_line_buffer.push_back(L'\0');
     }
     line[cur_pos] = L'\0';
     return line;
 }
killCurrentPositionToEndLine()
void LineManager::killCurrentPositionToEndLine (void)
kills from current position to the end of line
Definition at line 147 of file LineManager.cpp.
Referenced by killLastWord(), and WindowsConsole::warningMessage().
 {
     for (size_t i = cur_pos; i < max_pos; i++)
     {
         if (i >= current_line_buffer.size())
         {
             current_line_buffer.push_back(L'\0');
         }
         current_line_buffer[i] = L'\0';
     }
     for (size_t i = cur_pos; i < max_pos; i++)
     {
         putCharacter(VK_SPACE, LineManager::STANDARD_INPUT);
     }
     for (size_t i = cur_pos; i < max_pos; i++)
     {
         backSpace();
     }
     max_pos = cur_pos;
 }
killLastWord()
void LineManager::killLastWord (void)
kills last word
Definition at line 249 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     while ((cur_pos > 0) && (current_line_buffer[cur_pos - 1] == VK_SPACE))
     {
         cur_pos -= 1;
         backSpace ();
     }
     while ((cur_pos > 0) && (current_line_buffer[cur_pos - 1] != VK_SPACE))
     {
         cur_pos -= 1;
         backSpace ();
     }
     killCurrentPositionToEndLine();
 }
moveBackHistory()
void LineManager::moveBackHistory (void)
moves back through history
Definition at line 213 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (current_line_buffer.size() == 0)
     {
         current_line_buffer.push_back(L'\0');
     }
     std::wstring line = Nelson::History::getPreviousLine();
     clearCurrentLine();
     copyLine(line);
 }
moveBackSingleChar()
void LineManager::moveBackSingleChar (void)
moves back a single character
Definition at line 99 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (cur_pos > 0)
     {
         cur_pos -= 1;
         backSpace();
     }
 }
moveBackSingleWord()
void LineManager::moveBackSingleWord (void)
moves back a single word
Definition at line 117 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     while ((cur_pos > 0) && (isspace(current_line_buffer[cur_pos - 1])))
     {
         cur_pos -= 1;
         backSpace ();
     }
     while ((cur_pos > 0) && (!isspace(current_line_buffer[cur_pos - 1])))
     {
         cur_pos -= 1;
         backSpace ();
     }
     refreshLine();
 }
moveBeginningLine()
void LineManager::moveBeginningLine (void)
moves to the beginning of the line
Definition at line 81 of file LineManager.cpp.
Referenced by clearCurrentLine(), and WindowsConsole::warningMessage().
 {
     while (cur_pos > 0)
     {
         cur_pos -= 1;
         backSpace();
     }
 }
moveEndLine()
void LineManager::moveEndLine (void)
moves to the end of the line
Definition at line 90 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     boost::container::vector<wchar_t>::iterator itbegin = current_line_buffer.begin() + cur_pos;
     boost::container::vector<wchar_t>::iterator itend = current_line_buffer.begin() + max_pos;
     std::wstring line(itbegin, itend);
     cur_pos = max_pos;
     printCharacters(line, LineManager::STANDARD_INPUT);
 }
moveForwardHistory()
void LineManager::moveForwardHistory (void)
moves forward through history
Definition at line 224 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (current_line_buffer.size() == 0)
     {
         current_line_buffer.push_back(L'\0');
     }
     std::wstring line = Nelson::History::getNextLine();
     clearCurrentLine();
     copyLine(line);
 }
moveForwardSingleChar()
void LineManager::moveForwardSingleChar (void)
moves forward a single character
Definition at line 108 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     if (cur_pos < max_pos)
     {
         putCharacter(current_line_buffer[cur_pos],LineManager::STANDARD_INPUT);
         cur_pos += 1;
     }
 }
moveForwardSingleWord()
void LineManager::moveForwardSingleWord (void)
moves forward a single word
Definition at line 132 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     while ((cur_pos < max_pos) && !isspace(current_line_buffer[cur_pos]))
     {
         putCharacter(current_line_buffer[cur_pos], LineManager::STANDARD_INPUT);
         cur_pos++;
     }
     while ((cur_pos < max_pos) && isspace(current_line_buffer[cur_pos]))
     {
         putCharacter(current_line_buffer[cur_pos], LineManager::STANDARD_INPUT);
         cur_pos++;
     }
     refreshLine();
 }
newLine()
void LineManager::newLine (void)
initialize new line
Definition at line 264 of file LineManager.cpp.
Referenced by clearCurrentLine().
 {
     if (current_line_buffer.size() == 0)
     {
         current_line_buffer.push_back(L'\0');
     }
     current_line_buffer[0] = L'\0';
     cur_pos = 0;
     max_pos = 0;
 }
redrawLine()
void LineManager::redrawLine (void)
redraw line
Definition at line 235 of file LineManager.cpp.
Referenced by WindowsConsole::warningMessage().
 {
     std::wstring line = getCurrentLine();
     displayPrompt();
     for (size_t i = max_pos; i > cur_pos; i--)
     {
         backSpace ();
     }
     if (line.size() > 0)
     {
         copyLine(line);
     }
 }
refreshLine()
void LineManager::refreshLine (void)
refresh line
Definition at line 393 of file LineManager.cpp.
Referenced by addCharacterCurrentLine(), deleteCurrentChar(), deletePreviousChar(), moveBackSingleWord(), and moveForwardSingleWord().
 {
     /* write tail of string */
     boost::container::vector<wchar_t>::iterator itbegin = current_line_buffer.begin() + cur_pos;
     boost::container::vector<wchar_t>::iterator itend = current_line_buffer.begin() + max_pos;
     std::wstring line(itbegin, itend);
     printCharacters(line, LineManager::STANDARD_INPUT);
     /* write a space at the end of the line in case we deleted one */
     putCharacter(VK_SPACE, LineManager::STANDARD_INPUT);
     /* backup to original position */
     for (size_t i = max_pos + 1; i > cur_pos; i--)
     {
         backSpace ();
     }
 }
setCurrentPrompt()
void LineManager::setCurrentPrompt (std::wstring prompt)
set prompt used by terminal
Definition at line 292 of file LineManager.cpp.
 {
     currentPrompt = prompt;
 }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/terminal/src/include/LineManager.hpp
F:/Developpements/GitHub/nelson/modules/terminal/src/cpp/LineManager.cpp