Nelson: Nelson::Exception Class Reference
Nelson::Exception Class Reference
#include <Exception.hpp>
Public Member Functions
Exception (std::string msg_in, std::string functionname="", int line_in=-1, int position_in=-1, std::string filename_in="", std::string identifier_in="")
Exception (std::wstring msg_in, std::wstring functionname=L"", int line_in=-1, int position_in=-1, std::wstring filename_in=L"", std::wstring identifier_in=L"")
Exception (const Exception &copy)
void operator= (const Exception &copy)
~Exception ()
void printMe (Interface *io)
bool matches (std::string tst_msg)
bool matches (std::wstring tst_msg)
std::wstring getMessage ()
std::wstring getFormattedErrorMessage ()
std::wstring what ()
std::wstring getFilename ()
int getLine ()
int getPosition ()
void setLinePosition (int line_in, int position_in)
void setMessage (std::string msg_in)
void setMessage (std::wstring msg_in)
void setFunctionName (std::wstring functionname)
void setFunctionName (std::string functionname)
void setFileName (std::wstring filename)
std::wstring getFunctionName ()
bool isEmpty ()
std::wstring getIdentifier ()
void setIdentifier (std::wstring identifier_in)
void setIdentifier (std::string identifier_in)
Detailed Description
The exception class. This is a minimal class for now that allows for a hierarchical error structure (if desired) later on. Since we simply print most messages to the console, the exception types are not encoded using RTTI...
Definition at line 57 of file Exception.hpp.
Constructor & Destructor Documentation
Exception() [1/2]
Nelson::Exception::Exception (std::string msg_in, std::string functionname = "", int line_in = -1, int position_in = -1, std::string filename_in = "", std::string identifier_in = "")
Construct an exception object with a given STL-string.
Definition at line 34 of file Exception.cpp.
     {
         this->msg = utf8_to_wstring(msg_in);
         this->functionname = utf8_to_wstring(functionname);
         this->line = line_in;
         this->position = position_in;
         this->filename = utf8_to_wstring(filename_in);
         this->identifier = utf8_to_wstring(identifier_in);
         exceptionCount++;
     }
Exception() [2/2]
Nelson::Exception::Exception (const Exception & copy)
Copy constructor.
Definition at line 67 of file Exception.cpp.
     {
         this->msg = copy.msg;
         this->line = copy.line;
         this->position = copy.position;
         this->functionname = copy.functionname;
         this->filename = copy.filename;
         this->identifier = copy.identifier;
         exceptionCount++;
     }
~Exception()
Nelson::Exception::~Exception ()
Standard destructor.
Definition at line 56 of file Exception.cpp.
     {
         this->msg = L"";
         this->line = -1;
         this->position = -1;
         this->functionname = L"";
         this->filename = L"";
         this->identifier = L"";
         exceptionCount--;
     }
Member Function Documentation
getMessage()
std::wstring Nelson::Exception::getMessage ()
Get the message member function.
Definition at line 110 of file Exception.cpp.
Referenced by Nelson::Evaluator::getLastErrorString().
     {
         return msg;
     }
matches()
bool Nelson::Exception::matches (std::string tst_msg)
compares messages
Definition at line 105 of file Exception.cpp.
Referenced by Nelson::Evaluator::expressionList(), and printMe().
     {
         return (msg.compare(utf8_to_wstring(tst_msg)) == 0);
     }
operator=()
void Nelson::Exception::operator= (const Exception & copy)
Assignment operator.
Definition at line 78 of file Exception.cpp.
     {
         if (this == &copy)
         {
             return;
         }
         this->msg = copy.msg;
         this->functionname = copy.functionname;
         this->position = copy.position;
         this->line = copy.line;
         this->filename = copy.filename;
         this->identifier = copy.identifier;
     }
printMe()
void Nelson::Exception::printMe (Interface * io)
Output the contents of the exception to the console.
Definition at line 92 of file Exception.cpp.
Referenced by Nelson::Evaluator::evalCLI(), and Nelson::Evaluator::evaluateString().
     {
         if (msg != L"")
         {
             io->errorMessage(getFormattedErrorMessage());
         }
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/error_manager/src/include/Exception.hpp
F:/Developpements/GitHub/nelson/modules/error_manager/src/cpp/Exception.cpp