Nelson: Nelson::AST Class Reference
Nelson::AST Class Reference
#include <AST.hpp>
Public Member Functions
AST (void)
AST (NODE_TYPE ntype, const char *name, int context)
AST (NODE_TYPE ntype, int token, int context)
AST (OP_TYPE op, AST *lt, AST *rt, int context)
AST (OP_TYPE op, AST *lt, AST *md, AST *rt, int context)
AST (OP_TYPE op, AST *arg, int context)
~AST ()
int context ()
bool match (OP_TYPE test)
void addChild (AST *arg)
void addPeer (AST *arg)
int childCount ()
int peerCount ()
stringVector toStringList ()
bool isEmpty ()
Public Attributes
NODE_TYPE type
std::string text
int tokenNumber
int m_context
AST * down
AST * right
OP_TYPE opNum
Detailed Description
The abstract syntax tree class This class represents an abstract syntax tree class (AST). The AST node has both a "down" and "right" child.
Definition at line 123 of file AST.hpp.
Constructor & Destructor Documentation
AST() [1/6]
Nelson::AST::AST (void)
Default constructor Creates an empty AST node. All pointers are initialized to NULL, the type is set to non_terminal.
Definition at line 50 of file AST.cpp.
Referenced by Nelson::ThawAST().
     {
         type = non_terminal;
         text.clear();
         tokenNumber = 0;
         down = nullptr;
         right = nullptr;
         opNum = OP_NULL;
     }
AST() [2/6]
Nelson::AST::AST (NODE_TYPE ntype, const char * name, int context)
Text constructor Creates a node of the specified type with the text field set to a copy of the name argument.
Definition at line 60 of file AST.cpp.
     {
         type = ntype;
         text = name;
         tokenNumber = 0;
         down = nullptr;
         right = nullptr;
         opNum = OP_NULL;
         m_context = context;
     }
AST() [3/6]
Nelson::AST::AST (NODE_TYPE ntype, int token, int context)
Token constructor Creates a node of the specified type with the tokenNumber field set to the token argument. This constructor is useful for nodes that are represented by a single, numeric token (as opposed to a string).
Definition at line 71 of file AST.cpp.
     {
         type = ntype;
         tokenNumber = token;
         down = nullptr;
         right = nullptr;
         text.clear();
         opNum = OP_NULL;
         m_context = context;
     }
AST() [4/6]
Nelson::AST::AST (OP_TYPE op, AST * lt, AST * rt, int context)
Nonterminal constructor with two arguments Creates a non-terminal node with the text set to a copy of the name argument with the given left and right AST nodes. The resulting tree fragment looks like:
Definition at line 93 of file AST.cpp.
     {
         type = non_terminal;
         text.clear();
         opNum = op;
         lt->right = rt;
         tokenNumber = 0;
         down = lt;
         right = nullptr;
         m_context = context;
     }
AST() [5/6]
Nelson::AST::AST (OP_TYPE op, AST * lt, AST * md, AST * rt, int context)
Nonterminal constructor with three arguments Creates a non-terminal node with the text set to a copy of the name argument with the given three AST nodes. The resulting tree fragment looks like:
Definition at line 105 of file AST.cpp.
     {
         type = non_terminal;
         text.clear();
         opNum = op;
         lt->right = md;
         md->right = rt;
         tokenNumber = 0;
         down = lt;
         right = nullptr;
         m_context = context;
     }
AST() [6/6]
Nelson::AST::AST (OP_TYPE op, AST * arg, int context)
Nonterminal constructor with a single argument Creates a non-terminal node with the text set to a copy of the name argument with the given AST node. The resulting tree fragment looks like:
Definition at line 82 of file AST.cpp.
     {
         type = non_terminal;
         text.clear();
         tokenNumber = 0;
         down = arg;
         right = nullptr;
         opNum = op;
         m_context = context;
     }
~AST()
Nelson::AST::~AST ()
Destructor
Definition at line 118 of file AST.cpp.
     {
         text.clear();
     }
Member Function Documentation
addChild()
void Nelson::AST::addChild (AST * arg)
Add the given tree as a child to the current node Adds the argument tree as a child to the current node. If the current node has no "children" (i.e., down = nullptr) then the supplied tree is placed as a child. If there are children, then the node is added as a peer to the last such child.
Definition at line 155 of file AST.cpp.
     {
         if (down == nullptr)
         {
             down = arg;
             arg->right = nullptr;
         }
         else
         {
             AST* cp;
             cp = down;
             while (cp->right != nullptr)
             {
                 cp = cp->right;
             }
             cp->right = arg;
             arg->right = nullptr;
         }
     }
addPeer()
void Nelson::AST::addPeer (AST * arg)
Add the given tree as a peer to the current node Adds the argument tree as a peer to the current node. If the current node has no "peers" (i.e., right = nullptr) then the supplied tree is placed as a peer. If there are peers, then the node is added as a peer to the last such peer.
Definition at line 175 of file AST.cpp.
     {
         if (right == nullptr)
         {
             right = arg;
             arg->right = nullptr;
         }
         else
         {
             AST* cp;
             cp = right;
             while (cp->right != nullptr)
             {
                 cp = cp->right;
             }
             cp->right = arg;
             arg->right = nullptr;
         }
     }
childCount()
int Nelson::AST::childCount ()
Count children Returns the number of children to the current tree. This is only the number of children that are immediately below the current node (i.e., children of children are not counted).
Definition at line 209 of file AST.cpp.
     {
         AST* t;
         int count;
         count = 0;
         t = down;
         while (t != nullptr)
         {
             count++;
             t = t->down;
         }
         return count;
     }
context()
int Nelson::AST::context ()
Context string Returns the context string for this node.
Definition at line 123 of file AST.cpp.
Referenced by AST(), Nelson::Evaluator::cellDefinition(), Nelson::Evaluator::conditionedStatement(), Nelson::Evaluator::doubleColon(), Nelson::Evaluator::expression(), Nelson::Evaluator::expressionList(), Nelson::Evaluator::forStatement(), Nelson::Evaluator::functionExpression(), Nelson::Evaluator::ifStatement(), Nelson::Evaluator::matrixDefinition(), Nelson::Evaluator::multiFunctionCall(), Nelson::Evaluator::rhsExpression(), Nelson::Evaluator::rhsExpressionSimple(), Nelson::Evaluator::rowDefinition(), Nelson::Evaluator::ShortCutOr(), Nelson::Evaluator::simpleSubindexExpression(), Nelson::Evaluator::specialFunctionCall(), Nelson::Evaluator::statement(), Nelson::Evaluator::statementType(), Nelson::Evaluator::switchStatement(), Nelson::Evaluator::testCaseStatement(), Nelson::Evaluator::unitColon(), and Nelson::Evaluator::whileStatement().
     {
         return m_context;
     }
isEmpty()
bool Nelson::AST::isEmpty ()
Test for an empty tree Returns true if the current node is unallocated or is not a reserved node with an empty text string.
Definition at line 223 of file AST.cpp.
Referenced by Nelson::printAST(), and Nelson::Evaluator::statementType().
     {
         return ((type == null_node) || (type == non_terminal && opNum == OP_NULL));
     }
match()
bool Nelson::AST::match (OP_TYPE test)
Test for a match Returns true if textual content of this node matches the supplied argument (and is not NULL).
Definition at line 128 of file AST.cpp.
     {
         return (test == opNum);
     }
peerCount()
int Nelson::AST::peerCount ()
Count peers Returns the number of peers to the current tree. This is only the number of peers that are adjacent to the current node (i.e., children of peers are not counted).
Definition at line 195 of file AST.cpp.
     {
         AST* t;
         int count;
         count = 0;
         t = down;
         while (t!= nullptr)
         {
             count++;
             t = t->right;
         }
         return count;
     }
toStringList()
stringVector Nelson::AST::toStringList ()
Convert this into a string list. Builds a list of strings from the current node and its children.
Definition at line 133 of file AST.cpp.
     {
         stringVector res;
         if (text.size() > 0)
         {
             res.push_back(text);
         }
         if (down != nullptr)
         {
             AST* cp = down;
             while (cp != nullptr)
             {
                 if (cp->text.size() > 0)
                 {
                     res.push_back(cp->text);
                 }
                 cp = cp->right;
             }
         }
         return res;
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/interpreter/src/include/AST.hpp
F:/Developpements/GitHub/nelson/modules/interpreter/src/cpp/AST.cpp