Nelson: Nelson::Context Class Reference
Nelson::Context Class Reference
#include <Context.hpp>
Public Member Functions
Context ()
~Context ()
void pushScope (std::string)
void popScope () throw (Exception)
bool insertVariable (const std::string &varName, const ArrayOf &)
void insertVariableLocally (std::string varName, const ArrayOf &)
bool lookupVariable (const std::string &varName, ArrayOf &var)
bool lookupVariableLocally (std::string varName, ArrayOf &var)
void insertMacroFunctionLocally (FuncPtr)
bool lookupFunction (std::string funcName, FuncPtr &val, bool builtinOnly=false)
bool lookupFunction (std::wstring wfuncName, FuncPtr &val, bool builtinOnly=false)
bool lookupFunctionGlobally (std::string funcName, FuncPtr &val, bool builtinOnly=false)
void deleteFunctionGlobally (std::string funcName)
void addPersistentVariable (std::string var)
void addGlobalVariable (std::string var)
void deleteVariable (std::string var)
Scope * getGlobalScope ()
Scope * getCurrentScope ()
void printMe ()
void enterLoop ()
void exitLoop ()
bool inLoop ()
bool isVariableGlobal (const std::string &varName)
bool isVariablePersistent (const std::string &varName)
void bypassScope (int count)
void restoreBypassedScopes ()
Scope * getCallerScope ()
Scope * getBaseScope ()
stringVector getLockedVariables ()
bool isLockedVariable (std::string varname)
bool lockVariable (std::string varname)
bool unlockVariable (std::string varname)
bool isVariable (std::string varname)
size_t getRecursionDepth ()
bool setRecursionDepth (size_t newDepth)
size_t getMaximumRecursionDepth ()
Detailed Description
A Context is a stack of scopes with the (peculiar) property that the top and bottom of the stack (global and local scopes respectively) are searched regularly. The context is responsible for determining if variables and functions exist, and if so, for returning their values and accepting modifications to them. A context also keeps track of loop depth.
Definition at line 71 of file Context.hpp.
Constructor & Destructor Documentation
Context()
Nelson::Context::Context ()
Create a context and initialize it with a global scope and a base scope.
Definition at line 47 of file Context.cpp.
     {
         currentrecursiondepth = DEFAULT_RECURSION_FUNCTION_CALL;
         scopestack.reserve(DEFAULT_RECURSION_FUNCTION_CALL);
         pushScope("global");
         pushScope("base");
     }
~Context()
Nelson::Context::~Context ()
Delete the context
Definition at line 55 of file Context.cpp.
     {
         while (!scopestack.empty())
         {
             delete scopestack.back();
             scopestack.pop_back();
         }
     }
Member Function Documentation
addGlobalVariable()
void Nelson::Context::addGlobalVariable (std::string var)
Add a variable name into the global variable list of the current scope. If the variable does not exist in the global scope, an empty variable is added.
Definition at line 254 of file Context.cpp.
     {
         // Delete local variables with this name
         scopestack.back()->deleteVariable(var);
         // Delete global persistent variables with this name
         scopestack.front()->deleteVariable(scopestack.back()->getMangledName(var));
         // Add a point in the local scope to the global variable
         scopestack.back()->addGlobalVariablePointer(var);
         // Make sure the variable exists
         ArrayOf v;
         if (!scopestack.front()->lookupVariable(var, v))
         {
             scopestack.front()->insertVariable(var, ArrayOf::emptyConstructor());
         }
     }
addPersistentVariable()
void Nelson::Context::addPersistentVariable (std::string var)
Add a persistent variable to the local stack. This involves two steps:
the name of the variable is added to the persistent variable list in the current scope.
the global scope is checked for the mangled name of the persistent variable. If the variable does not exist in the global scope, then an empty variable is inserted.
Definition at line 240 of file Context.cpp.
     {
         // Delete local variables with this name
         scopestack.back()->deleteVariable(var);
         // Delete global variables with this name
         scopestack.front()->deleteVariable(var);
         scopestack.back()->addPersistentVariablePointer(var);
         ArrayOf v;
         if (!scopestack.front()->lookupVariable(scopestack.back()->getMangledName(var), v))
         {
             scopestack.front()->insertVariable(scopestack.back()->getMangledName(var), ArrayOf::emptyConstructor());
         }
     }
deleteVariable()
void Nelson::Context::deleteVariable (std::string var)
Delete a variable if its defined. Handles global and persistent variables also.
Definition at line 270 of file Context.cpp.
     {
         if (isVariableGlobal(var))
         {
             scopestack.front()->deleteVariable(var);
             scopestack.back()->deleteGlobalVariablePointer(var);
             return;
         }
         if (isVariablePersistent(var))
         {
             scopestack.front()->deleteVariable(scopestack.back()->getMangledName(var));
             scopestack.back()->deletePersistentVariablePointer(var);
             return;
         }
         scopestack.back()->deleteVariable(var);
     }
enterLoop()
void Nelson::Context::enterLoop ()
Increment the loop depth counter in the local scope.
Definition at line 225 of file Context.cpp.
Referenced by Nelson::Evaluator::forStatement(), and Nelson::Evaluator::whileStatement().
     {
         scopestack.back()->enterLoop();
     }
exitLoop()
void Nelson::Context::exitLoop ()
Decrement the loop depth counter in the local scope.
Definition at line 230 of file Context.cpp.
Referenced by Nelson::Evaluator::forStatement(), and Nelson::Evaluator::whileStatement().
     {
         scopestack.back()->exitLoop();
     }
getCurrentScope()
Scope * Nelson::Context::getCurrentScope ()
Get the current (active) scope
Definition at line 64 of file Context.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction(), and Nelson::Evaluator::statementType().
     {
         return scopestack.back();
     }
getGlobalScope()
Scope * Nelson::Context::getGlobalScope ()
Get the global scope off the top of the scope stack.
Definition at line 69 of file Context.cpp.
     {
         return scopestack.front();
     }
inLoop()
bool Nelson::Context::inLoop ()
Returns true if the current (local) scope indicates a non-zero loop depth.
Definition at line 235 of file Context.cpp.
Referenced by Nelson::Evaluator::statementType().
     {
         return scopestack.back()->inLoop();
     }
insertMacroFunctionLocally()
void Nelson::Context::insertMacroFunctionLocally (FuncPtr f)
Insert a function definition into the local scope (bottom of the scope stack).
Definition at line 191 of file Context.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction().
     {
         scopestack.back()->insertMacroFunctionLocally(f);
     }
insertVariable()
bool Nelson::Context::insertVariable (const std::string & varName, const ArrayOf & var)
Insert the given variable into the right scope - the global scope if the array is in the global list, and mangled in global list if it is persistent.
Definition at line 115 of file Context.cpp.
Referenced by Nelson::Evaluator::forStatement(), Nelson::Evaluator::functionExpression(), Nelson::Evaluator::multiFunctionCall(), and Nelson::Evaluator::statementType().
     {
         Scope* active;
         std::string mapName;
         if (scopestack.back()->isVariablePersistent(varName))
         {
             mapName = scopestack.back()->getMangledName(varName);
             active = scopestack.front();
         }
         else if (scopestack.back()->isVariableGlobal(varName))
         {
             mapName = varName;
             active = scopestack.front();
         }
         else
         {
             return scopestack.back()->insertVariable(varName, var);
         }
         return active->insertVariable(mapName, var);
     }
insertVariableLocally()
void Nelson::Context::insertVariableLocally (std::string varName, const ArrayOf & var)
Insert a variable into the local scope - do not check the global list.
Definition at line 110 of file Context.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction().
     {
         scopestack.back()->insertVariable(varName, var);
     }
isVariableGlobal()
bool Nelson::Context::isVariableGlobal (const std::string & varName)
Returns true if the given variable is global.
Definition at line 176 of file Context.cpp.
Referenced by deleteVariable().
     {
         return scopestack.back()->isVariableGlobal(varName);
     }
isVariablePersistent()
bool Nelson::Context::isVariablePersistent (const std::string & varName)
Returns true if the given variable is persistent
Definition at line 181 of file Context.cpp.
Referenced by deleteVariable().
     {
         return scopestack.back()->isVariablePersistent(varName);
     }
lookupFunction()
bool Nelson::Context::lookupFunction (std::string funcName, FuncPtr & val, bool builtinOnly = false)
Add a built in function to the global scope with the given name.
Definition at line 202 of file Context.cpp.
Referenced by Nelson::Evaluator::functionExpression(), insertMacroFunctionLocally(), and Nelson::Evaluator::lookupFunction().
     {
         if (scopestack.back()->lookupFunction(funcName, val, builtinOnly))
         {
             return true;
         }
         return lookupFunctionGlobally(funcName, val, false);
     }
lookupVariable()
bool Nelson::Context::lookupVariable (const std::string & varName, ArrayOf & var)
Return a pointer to the given variable. The search logic is:
If the variable is persistent in the current scope (at the bottom of the scope stack), mangle its name using the scope, and look for it in the global scope.
If the variable is global in the current scope (at the bottom of the scope stack, look for it in the global scope.
Look for the variable in the local scope. If the variable is not found, an empty variable is constructed with the given name, and inserted into the scope that was searched. A pointer to this newly created variable is returned.
Definition at line 136 of file Context.cpp.
Referenced by Nelson::Evaluator::functionExpression(), Nelson::Evaluator::multiFunctionCall(), Nelson::Evaluator::rhsExpression(), Nelson::Evaluator::rhsExpressionSimple(), Nelson::Evaluator::simpleSubindexExpression(), and Nelson::Evaluator::statementType().
     {
         Scope* active;
         std::string mapName;
         if (scopestack.back()->isVariablePersistent(varName))
         {
             mapName = scopestack.back()->getMangledName(varName);
             active = scopestack.front();
         }
         else if (scopestack.back()->isVariableGlobal(varName))
         {
             mapName = varName;
             active = scopestack.front();
         }
         else
         {
             return scopestack.back()->lookupVariable(varName, var);
         }
         return active->lookupVariable(mapName, var);
     }
lookupVariableLocally()
bool Nelson::Context::lookupVariableLocally (std::string varName, ArrayOf & var)
Look for a variable, but only locally.
Definition at line 186 of file Context.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction().
     {
         return scopestack.back()->lookupVariable(varName, var);
     }
popScope()
void Nelson::Context::popScope () throw (Exception)
Pop the bottom scope off of the scope stack. The scope is deleted. Throws an Exception if the global scope is popped.
Definition at line 100 of file Context.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction().
     {
         if (scopestack.size() == 1)
         {
             throw Exception(ERROR_POP_GLOBAL_SCOPE);
         }
         delete scopestack.back();
         scopestack.pop_back();
     }
printMe()
void Nelson::Context::printMe ()
Print the context.
Definition at line 221 of file Context.cpp.
     {
     }
pushScope()
void Nelson::Context::pushScope (std::string name)
Push the given scope onto the bottom of the scope stack.
Definition at line 74 of file Context.cpp.
Referenced by Context(), and Nelson::MacroFunctionDef::evaluateFunction().
     {
         Scope *sc = nullptr;
         if (scopestack.size() > getRecursionDepth())
         {
             throw Exception(ERROR_STACK_DEPTH_EXCEEDED);
         }
         try
         {
             sc = new Scope(name);
         }
         catch (std::bad_alloc &e)
         {
             e.what();
             throw Exception(ERROR_STACK_DEPTH_EXCEEDED);
         }
         if (sc)
         {
             scopestack.push_back(sc);
         }
         else
         {
             throw Exception(ERROR_STACK_DEPTH_EXCEEDED);
         }
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/interpreter/src/include/Context.hpp
F:/Developpements/GitHub/nelson/modules/interpreter/src/cpp/Context.cpp