Nelson: Nelson::Scope Class Reference
Nelson::Scope Class Reference
#include <Scope.hpp>
Public Member Functions
Scope (std::string scopeName)
~Scope ()
bool insertVariable (const std::string &varName, const ArrayOf &val)
void insertMacroFunctionLocally (FuncPtr a)
void deleteFunction (const std::string funcName)
bool deleteBuiltin (void *fptr)
bool lookupFunction (std::string funcName, FuncPtr &val, bool builtinOnly=false)
bool lookupVariable (const std::string &funcName, ArrayOf &val)
void addGlobalVariablePointer (std::string varName)
void deleteGlobalVariablePointer (std::string varName)
bool isVariableGlobal (const std::string &varName)
void addPersistentVariablePointer (std::string varName)
void deletePersistentVariablePointer (std::string varName)
bool isVariablePersistent (const std::string &varName)
std::string getMangledName (std::string varName)
void printMe ()
void printData ()
std::string getName ()
void enterLoop ()
void exitLoop ()
bool inLoop ()
stringVector getVariablesList ()
stringVector getBuiltinsList ()
bool deleteVariable (std::string var)
bool isPointerOnFunction (FuncPtr val)
void setNargIn (int _nargin)
int getNargIn ()
void setNargOut (int _nargout)
int getNargOut ()
stringVector getLockedVariables ()
bool isLockedVariable (std::string varname)
bool lockVariable (std::string varname)
bool unlockVariable (std::string varname)
bool isVariable (std::string varname)
Detailed Description
A Scope is a collection of functions and variables all visible at some point in the execution. The scope also keeps track of the loop level, and a list of the global and persistent variables relevant to the current scope.
Definition at line 62 of file Scope.hpp.
Constructor & Destructor Documentation
Scope()
Nelson::Scope::Scope (std::string scopeName)
Construct a scope with the given name.
Definition at line 48 of file Scope.cpp.
     {
         name = scopeName;
         loopLevel = 0;
     }
~Scope()
Nelson::Scope::~Scope ()
Default destructor.
Definition at line 54 of file Scope.cpp.
     {
     }
Member Function Documentation
addGlobalVariablePointer()
void Nelson::Scope::addGlobalVariablePointer (std::string varName)
Add a variable name to the global variables list.
Definition at line 150 of file Scope.cpp.
     {
         if (!isVariableGlobal(varName))
         {
             globalVars.push_back(varName);
         }
     }
addPersistentVariablePointer()
void Nelson::Scope::addPersistentVariablePointer (std::string varName)
Add a variable name to the persistent variables list.
Definition at line 188 of file Scope.cpp.
     {
         if (!isVariablePersistent(varName))
         {
             persistentVars.push_back(varName);
         }
     }
deleteFunction()
void Nelson::Scope::deleteFunction (const std::string funcName)
Delete a function from the current scope.
Definition at line 68 of file Scope.cpp.
     {
         BuiltInFunctionDefManager::getInstance()->remove(funcName);
     }
deleteGlobalVariablePointer()
void Nelson::Scope::deleteGlobalVariablePointer (std::string varName)
Delete a variable name from the global variables list.
Definition at line 158 of file Scope.cpp.
     {
         stringVector::iterator i = std::find(globalVars.begin(),
                                              globalVars.end(),
                                              varName);
         if (*i == varName)
         {
             globalVars.erase(i);
         }
     }
deletePersistentVariablePointer()
void Nelson::Scope::deletePersistentVariablePointer (std::string varName)
Delete a variable name from the persistent variables list.
Definition at line 196 of file Scope.cpp.
     {
         stringVector::iterator i = std::find(persistentVars.begin(),
                                              persistentVars.end(),
                                              varName);
         if (*i == varName)
         {
             persistentVars.erase(i);
         }
     }
deleteVariable()
bool Nelson::Scope::deleteVariable (std::string var)
Delete a variable in this scope. It does not simply replace the variable with an empty variable, but deletes the variable from the symbol table completely.
Definition at line 231 of file Scope.cpp.
     {
         return variablesTab.deleteVariable(var);
     }
enterLoop()
void Nelson::Scope::enterLoop ()
Increment the loop counter.
Definition at line 135 of file Scope.cpp.
     {
         loopLevel++;
     }
exitLoop()
void Nelson::Scope::exitLoop ()
Decrement the loop counter.
Definition at line 140 of file Scope.cpp.
     {
         loopLevel--;
     }
getMangledName()
std::string Nelson::Scope::getMangledName (std::string varName)
Mangle the name of a variable by prepending a "_scopename_" to the name of the variable.
Definition at line 226 of file Scope.cpp.
     {
         return (std::string("_") + name + std::string("_") + varName);
     }
getName()
std::string Nelson::Scope::getName ()
Get the name of the scope.
Definition at line 117 of file Scope.cpp.
Referenced by Nelson::Evaluator::statementType().
     {
         return name;
     }
inLoop()
bool Nelson::Scope::inLoop ()
Test the loop counter.
Definition at line 145 of file Scope.cpp.
     {
         return (loopLevel>0);
     }
insertMacroFunctionLocally()
void Nelson::Scope::insertMacroFunctionLocally (FuncPtr a)
Insert a function pointer into the current scope. The name of of the function is encoded in the FuncPtr.
Definition at line 58 of file Scope.cpp.
     {
         currentLocalFunctions.add(a->name, a);
     }
insertVariable()
bool Nelson::Scope::insertVariable (const std::string & varName, const ArrayOf & val)
Insert a variable with the given name. If the variable already exists in the Scope, then the previous definition is replaced with the given one.
Definition at line 122 of file Scope.cpp.
Referenced by Nelson::Context::insertVariable().
     {
         return variablesTab.insertVariable(varName, var);
     }
isVariableGlobal()
bool Nelson::Scope::isVariableGlobal (const std::string & varName)
Check to see if a variable is globally defined.
Definition at line 169 of file Scope.cpp.
Referenced by addGlobalVariablePointer().
     {
         bool foundName = false;
         size_t i = 0;
         if (globalVars.empty())
         {
             return false;
         }
         while (i<globalVars.size() && !foundName)
         {
             foundName = (globalVars[i] == varName);
             if (!foundName)
             {
                 i++;
             }
         }
         return foundName;
     }
isVariablePersistent()
bool Nelson::Scope::isVariablePersistent (const std::string & varName)
Check to see if a variable is defined in the persistent list.
Definition at line 207 of file Scope.cpp.
Referenced by addPersistentVariablePointer().
     {
         bool foundName = false;
         size_t i = 0;
         if (persistentVars.empty())
         {
             return false;
         }
         while (i<persistentVars.size() && !foundName)
         {
             foundName = (persistentVars[i] == varName);
             if (!foundName)
             {
                 i++;
             }
         }
         return foundName;
     }
lookupFunction()
bool Nelson::Scope::lookupFunction (std::string funcName, FuncPtr & val, bool builtinOnly = false)
Lookup a function. Return true if the function is defined, and assigns the value of the function pointer to the second argument.
Definition at line 73 of file Scope.cpp.
     {
         if (builtinOnly)
         {
             return BuiltInFunctionDefManager::getInstance()->find(funcName, val);
         }
         else
         {
             if (currentLocalFunctions.find(funcName, val))
             {
                 return true;
             }
             bool res = PathFuncManager::getInstance()->find(funcName, val);
             if (res)
             {
                 return true;
             }
             res = BuiltInFunctionDefManager::getInstance()->find(funcName, val);
             if (res)
             {
                 return true;
             }
         }
         return false;
     }
lookupVariable()
bool Nelson::Scope::lookupVariable (const std::string & funcName, ArrayOf & val)
Lookup a variable. Return true if the variable is defined, and assigns the value of the variable to the second argument.
Definition at line 112 of file Scope.cpp.
Referenced by Nelson::Context::lookupVariable().
     {
         return variablesTab.findVariable(varName, val);
     }
printData()
void Nelson::Scope::printData ()
Dump only the variables in the scope (not the functions).
Definition at line 131 of file Scope.cpp.
     {
     }
printMe()
void Nelson::Scope::printMe ()
Dump the scope.
Definition at line 127 of file Scope.cpp.
     {
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/interpreter/src/include/Scope.hpp
F:/Developpements/GitHub/nelson/modules/interpreter/src/cpp/Scope.cpp