Nelson: Nelson::Interface Class Reference
Nelson::Interface Class Reference abstract
Public Member Functions
virtual std::string getLine (std::string prompt)=0
virtual std::wstring getLine (std::wstring prompt)=0
virtual std::wstring getInput (std::wstring prompt)=0
virtual size_t getTerminalWidth ()=0
virtual void outputMessage (std::string msg)=0
virtual void outputMessage (std::wstring msg)=0
virtual void errorMessage (std::string msg)=0
virtual void errorMessage (std::wstring msg)=0
virtual void warningMessage (std::string msg)=0
virtual void warningMessage (std::wstring msg)=0
virtual void clearTerminal ()=0
Public Attributes
Diary diary
Detailed Description
Definition at line 46 of file Interface.hpp.
Member Function Documentation
errorMessage()
virtual void Nelson::Interface::errorMessage (std::string msg) pure virtual
Output the following error message.
Implemented in WindowsConsole, BasicTerminal, BsdTerminal, and GuiTerminal.
Referenced by Nelson::Exception::printMe().
getLine()
virtual std::string Nelson::Interface::getLine (std::string prompt) pure virtual
Get a line of input from the user with the given prompt.
Implemented in WindowsConsole, BasicTerminal, BsdTerminal, and GuiTerminal.
Referenced by Nelson::Evaluator::evalCLI().
getTerminalWidth()
virtual size_t Nelson::Interface::getTerminalWidth () pure virtual
Return the width of the current "terminal" in characters.
Implemented in WindowsConsole, GuiTerminal, BasicTerminal, and BsdTerminal.
outputMessage()
virtual void Nelson::Interface::outputMessage (std::string msg) pure virtual
Output the following text message.
Implemented in WindowsConsole, BasicTerminal, BsdTerminal, and GuiTerminal.
Referenced by Nelson::Evaluator::block(), Nelson::Evaluator::forStatement(), Nelson::Evaluator::functionExpression(), Nelson::Evaluator::multiFunctionCall(), Nelson::Evaluator::popID(), Nelson::MacroFunctionDef::printMe(), Nelson::Dimensions::printMe(), and Nelson::Evaluator::statementType().
warningMessage()
virtual void Nelson::Interface::warningMessage (std::string msg) pure virtual
Output the following warning message.
Implemented in WindowsConsole, BasicTerminal, BsdTerminal, and GuiTerminal.
Referenced by Nelson::MacroFunctionDef::evaluateFunction(), Nelson::Evaluator::functionExpression(), and Nelson::Evaluator::multiFunctionCall().
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/stream_manager/src/include/Interface.hpp
F:/Developpements/GitHub/nelson/modules/stream_manager/src/cpp/Interface.cpp