Nelson: Nelson::Evaluator Class Reference
Nelson::Evaluator Class Reference
#include <Evaluator.hpp>
Public Member Functions
OutputFormatDisplay getCurrentOutputFormatDisplay ()
void setCurrentOutputFormatDisplay (OutputFormatDisplay newFormat)
void setCLI (bool bCLI)
bool getCLI ()
void dbstep (int linecount)
void handleDebug (int fullcontext)
void debugCLI ()
void pushDebug (std::string fname, std::string detail)
void popDebug ()
void addBreakpoint (StackEntry bp)
bool adjustBreakpoint (StackEntry &bp, bool dbstep)
void adjustBreakpoints ()
void listBreakpoints ()
void deleteBreakpoint (int number)
void stackTrace (bool includeCurrent)
stringVector getCallers (bool includeCurrent)
bool GetInterruptPending ()
bool SetInterruptPending (bool bInterruptPending)
bool SetInterrupCallback (bool bInterruptCallback)
Evaluator (Context *aContext, Interface *aInterface, int engineMode)
~Evaluator ()
void pushID (int)
void popID ()
bool AutoStop ()
void AutoStop (bool a)
void setPrintLimit (int)
int getPrintLimit ()
void clearStacks ()
void resetState ()
State setState (State newState)
State getState ()
bool getOverloadState ()
void disableOverload ()
void enableOverload ()
int getExitCode ()
void setExitCode (int _exitCode)
ArrayOfVector rowDefinition (ASTPtr t)
ArrayOf matrixDefinition (ASTPtr t)
ArrayOf cellDefinition (ASTPtr t)
ArrayOf expression (ASTPtr t)
ArrayOf unitColon (ASTPtr t)
ArrayOf doubleColon (ASTPtr t)
ArrayOfVector expressionList (ASTPtr t, Dimensions *dim)
ArrayOfVector rhsExpression (ASTPtr t)
bool lookupFunction (std::string funcName, FuncPtr &val)
ArrayOf rhsExpressionSimple (ASTPtr t)
Interface * getInterface ()
ArrayOf simpleSubindexExpression (ArrayOf &r, ASTPtr t)
ArrayOfVector subsindex (ArrayOfVector m)
indexType countLeftHandSides (ASTPtr t)
void simpleAssign (ArrayOf &r, ASTPtr t, ArrayOf &value)
void simpleAssign (ArrayOf &r, ASTPtr t, ArrayOfVector &value)
ArrayOf assignExpression (ASTPtr t, ArrayOf &value)
ArrayOf assignExpression (ASTPtr t, ArrayOfVector &value)
ArrayOfVector functionExpression (FunctionDef *funcDef, ASTPtr t, int narg_out, bool outputOptional)
void multiFunctionCall (ASTPtr t, bool printIt)
ArrayOfVector specialFunctionCall (ASTPtr t, bool printIt)
bool conditionedStatement (ASTPtr t)
void ifStatement (ASTPtr t)
void switchStatement (ASTPtr t)
void forStatement (ASTPtr t)
void whileStatement (ASTPtr t)
void tryStatement (ASTPtr t)
bool testCaseStatement (ASTPtr t, ArrayOf x)
void statementType (ASTPtr t, bool printIt)
void statement (ASTPtr t)
void block (ASTPtr t)
void evalCLI ()
Context * getContext ()
bool evaluateString (std::string cmdToEvaluate, bool propogateException=true)
std::wstring getCurrentEvaluateFilename ()
void pushEvaluateFilenameList (const std::wstring filename)
void popEvaluateFilenameList ()
std::wstring getLastErrorString ()
Exception getLastException ()
bool setLastException (Exception e)
void setLastErrorString (std::wstring txt)
void setLastErrorString (std::string txt)
std::wstring getLastWarningString ()
void setLastWarningString (std::string msg)
void setLastWarningString (std::wstring msg)
ArrayOf ShortCutOr (ASTPtr t)
ArrayOf ShortCutAnd (ASTPtr t)
ArrayOf Or (ASTPtr t)
ArrayOf And (ASTPtr t)
std::string getCallerFunctionName ()
std::wstring getCallerFunctionNameW ()
std::string getCurrentFunctionName ()
std::wstring getCurrentFunctionNameW ()
int getDebugDepth ()
void increaseDebugDepth ()
void decreaseDebugDepth ()
int getNelsonEngineMode ()
bool haveEventsLoop ()
void setCommandLineArguments (wstringVector args)
wstringVector getCommandLineArguments ()
bool getEchoMode ()
void setEchoMode (bool _mode)
bool isQuietMode ()
void setQuietMode (bool _quiet)
Public Attributes
boost::container::vector< std::wstring > evaluatedFilenames
void * mainGuiObject = nullptr
void * FileManager = nullptr
void * RandomEngine = nullptr
void * HistoryManager = nullptr
boost::container::vector< StackEntry > cstack
bool debugActive
CommandQueue commandQueue
uint64 TimerValue = 0
Detailed Description
This is the class that implements the interpreter - it generally operates on abstract syntax trees (ASTs).
Definition at line 78 of file Evaluator.hpp.
Constructor & Destructor Documentation
Evaluator()
Nelson::Evaluator::Evaluator (Context * aContext, Interface * aInterface, int engineMode)
Construct a Evaluator object with the given context to operate in.
Definition at line 4111 of file Evaluator.cpp.
     {
         engineMode = _engineMode;
         bAllowOverload = true;
         lastException = nullptr;
         context = aContext;
         currentOutputFormatDisplay = NLS_FORMAT_SHORT;
         resetState();
         endValStackLength = 0;
         endValStack[endValStackLength] = 0;
         depth = 0;
         io = aInterface;
         ArrayOf::setArrayOfIOInterface(io);
         InterruptPending = false;
         printLimit = 1000;
         autostop = true;
         InCLI = false;
         debugActive = false;
         inStepMode = false;
         bpActive = false;
         clearStacks();
         commandLineArguments.clear();
     }
~Evaluator()
Nelson::Evaluator::~Evaluator ()
Destruct the Evaluator object.
Definition at line 4135 of file Evaluator.cpp.
     {
         clearStacks();
         commandLineArguments.clear();
         if (lastException)
         {
             delete lastException;
         }
     }
Member Function Documentation
AutoStop()
bool Nelson::Evaluator::AutoStop ()
Set the autostop flag - this flag determines what happens when an exception occurs
Definition at line 1028 of file Evaluator.cpp.
     {
         return autostop;
     }
block()
void Nelson::Evaluator::block (ASTPtr t)
Executes a sequence of statements, trapping exceptions as necessary. The AST looks like <ignored> | statement->statement->statement If an exception occurs, it is caught and rethrown. The lasterr string is also set to the contents of the exception.
Definition at line 2004 of file Evaluator.cpp.
Referenced by conditionedStatement(), Nelson::MacroFunctionDef::evaluateFunction(), evaluateString(), forStatement(), ifStatement(), switchStatement(), testCaseStatement(), tryStatement(), and whileStatement().
     {
         try
         {
             ASTPtr s = t->down;
             if (state < NLS_STATE_QUIT)
             {
                 resetState();
             }
             while ((state < NLS_STATE_QUIT) && s != nullptr)
             {
                 if (InterruptCallback)
                 {
                     InterruptCallback = false;
                     return;
                 }
                 else  if (InterruptPending)
                 {
                     io->outputMessage(L"\n" + MSG_CTRL_C_DETECTED);
                     state = NLS_STATE_ABORT;
                     InterruptPending = false;
                     return;
                 }
                 else
                 {
                     statement(s);
                     if (state == NLS_STATE_BREAK ||
                             state == NLS_STATE_CONTINUE ||
                             state == NLS_STATE_RETURN ||
                             state == NLS_STATE_ABORT ||
                             state == NLS_STATE_QUIT)
                     {
                         break;
                     }
                     s = s->right;
                 }
             }
         }
         catch (Exception &e)
         {
             if (!e.isEmpty())
             {
                 if (lastException)
                 {
                     delete lastException;
                 }
                 updateError(this, e);
                 lastException = new Exception(e);
                 throw ;
             }
         }
     }
cellDefinition()
ArrayOf Nelson::Evaluator::cellDefinition (ASTPtr t)
Convert a cell defintion of the form: {expr1,expr2;expr3;expr4} into a vector of row definitions. The first row is the vector {expr1,expr2}, and the second is the vector {expr3,expr4}. The AST input should look like: {} | ;-> ; -> ... -> NULL | | | rowDef rowDef
Definition at line 349 of file Evaluator.cpp.
Referenced by expression().
     {
         ArrayOfMatrix m;
         if (t->opNum != OP_BRACES)
         {
             Error(this, ERROR_AST_SYNTAX_ERROR);
         }
         ASTPtr s = t->down;
         pushID(s->context());
         while (s != nullptr)
         {
             m.push_back(rowDefinition(s));
             s = s->right;
         }
         ArrayOf retval(ArrayOf::cellConstructor(m));
         popID();
         return retval;
     }
clearStacks()
void Nelson::Evaluator::clearStacks ()
Clear the context stacks.
Definition at line 176 of file Evaluator.cpp.
Referenced by Evaluator(), and ~Evaluator().
     {
         //    cname = "base";
         cstack.clear();
         //        cstack.reserve(4096 * 2);
         //    gstack.push_back(cname);
     }
conditionedStatement()
bool Nelson::Evaluator::conditionedStatement (ASTPtr t)
Test a conditional expression, and if its true, evaluate the associated block of code. Used by a number of control constructs. The AST looks like: cstat | expr->codeBlock The expression output is treated as false if the real part is all zeros. Throws an Exception if the head of the AST is not a cstat.
Definition at line 905 of file Evaluator.cpp.
Referenced by ifStatement().
     {
         bool conditionState;
         if (t->opNum != OP_CSTAT)
         {
             Error(this, ERROR_AST_SYNTAX_ERROR);
         }
         ASTPtr s = t->down;
         pushID(s->context());
         ArrayOf condVar;
         condVar = expression(s);
         conditionState = !condVar.isRealAllZeros();
         ASTPtr codeBlock = s->right;
         if (conditionState)
         {
             block(codeBlock);
         }
         popID();
         return conditionState;
     }
disableOverload()
void Nelson::Evaluator::disableOverload ()
disable overload
Definition at line 4415 of file Evaluator.cpp.
     {
         bAllowOverload = false;
     }
doubleColon()
ArrayOf Nelson::Evaluator::doubleColon (ASTPtr t)
Evaluate a double colon expression. The AST input should look like: : | :->expr3 | expr1->expr2 The output is the expression expr1:expr2:expr3, which is the vector [expr1,expr1+expr2,expr1+2*expr2,...,expr1+n*expr2], where n is the largest integer such that expr1+n*expr2 <= expr3.
Definition at line 769 of file Evaluator.cpp.
Referenced by expression().
     {
         ArrayOf a, b, c;
         pushID(t->context());
         a = expression(t->down->down);
         b = expression(t->down->down->right);
         c = expression(t->down->right);
         ArrayOfVector argsOut = CallOperatorFunction(this, "colon", a, b, c, 1);
         ArrayOf retval = argsOut[0];
         /*
         ArrayOf retval(DoubleColon(a, b, c));
         */
         popID();
         return retval;
     }
enableOverload()
void Nelson::Evaluator::enableOverload ()
enable overload
Definition at line 4420 of file Evaluator.cpp.
     {
         bAllowOverload = true;
     }
evalCLI()
void Nelson::Evaluator::evalCLI ()
Start a command line interface. Statements are retrieved from the console, and executed sequentially until a "return" statement is executed or the user presses 'CTRL-D'.
Definition at line 4453 of file Evaluator.cpp.
Referenced by forStatement(), and statementType().
     {
         std::string cmdline = "\0";
         std::string dataline = "\0";
         std::string prompt = "\0";
         while (1)
         {
             if (!bpActive)
             {
                 // clear macros cache at the prompt
                 stringVector exceptedFunctionsName = this->getCallers(true);
                 PathFuncManager::getInstance()->clearCache(exceptedFunctionsName);
                 FileWatcherManager::getInstance()->update();
             }
             prompt = buildPrompt();
             if (commandQueue.isEmpty())
             {
                 cmdline = io->getLine(prompt);
                 if (cmdline.empty())
                 {
                     InCLI = false;
                     this->setState(NLS_STATE_QUIT);
                     return;
                 }
                 else
                 {
                     char ch = *cmdline.rbegin();
                     if (ch != '\n')
                     {
                         cmdline.push_back('\n');
                     }
                 }
             }
             else
             {
                 commandQueue.get(cmdline);
             }
             // scan the line and tokenize it
             resetAstBackupPosition();
             setLexBuffer(cmdline.c_str());
             try
             {
                 int lastCount = getContinuationCount();
                 bool bContinueLine = lexCheckForMoreInput(0);
                 deleteAstVector(getAstUsed());
                 resetAstBackupPosition();
                 if (bContinueLine)
                 {
                     dataline = cmdline;
                     bool enoughInput = false;
                     // Loop until we have enough input
                     while (!enoughInput)
                     {
                         cmdline = io->getLine("");
                         // User pressed ctrl-D (or equivalent) - stop looking for
                         if (cmdline.size() == 0)
{
                             if (InterruptPending)
{
                                 cmdline = "";
                                 return;
                             }
                             enoughInput = false;
                         }
                         else
{
                             char ch = *cmdline.rbegin();
                             if (ch != '\n')
{
                                 cmdline.push_back('\n');
                             }
                             // User didn't press ctrl-D -
                             // tack the new text onto the dataline
                             dataline.append(cmdline);
                             resetAstBackupPosition();
                             setLexBuffer(dataline.c_str());
                             // Update the check
                             enoughInput = !lexCheckForMoreInput(lastCount);
                             deleteAstVector(getAstUsed());
                             resetAstBackupPosition();
                             lastCount = getContinuationCount();
                             if (enoughInput)
{
                                 if (dataline[dataline.size() - 1] != '\n')
{
                                     dataline.push_back('\n');
                                 }
                             }
                             else
{
                             }
                             cmdline = dataline;
                         }
                     }
                 }
             }
             catch (Exception &e)
             {
                 e.printMe(io);
             }
             InCLI = true;
             if (cmdline.size() > 0 && cmdline != "\n")
             {
                 size_t stackdepth;
                 stackdepth = cstack.size();
                 bool tresult = evaluateString(cmdline, false);
                 while (cstack.size() > stackdepth)
                 {
                     cstack.pop_back();
                 }
                 if (!tresult || this->getState() == NLS_STATE_QUIT || this->getState() == NLS_STATE_ABORT)
                 {
                     InCLI = false;
                     return;
                 }
             }
         }
     }
evaluateString()
bool Nelson::Evaluator::evaluateString (std::string cmdToEvaluate, bool propogateException = true)
The workhorse routine - "evaluate" the contents of a string and execute it.
Definition at line 4156 of file Evaluator.cpp.
Referenced by evalCLI().
     {
         ASTPtr tree = nullptr;
         ParserState parserState = ParseError;
         InterruptPending = false;
         if (line.size() == 0)
         {
             return false;
         }
         char ch = *line.rbegin();
         std::string command;
         // we add <RETURN> at the end
         // the command need a <RETURN> to be correctly parser
         if (ch != '\n')
         {
             command = line + "\n";
         }
         else
         {
             command = line;
         }
         resetAstBackupPosition();
         boost::container::vector<ASTPtr> pt;
         try
         {
             parserState = parseString(command);
             pt = getAstUsed();
         }
         catch (Exception &e)
         {
             deleteAstVector(getAstUsed());
             resetAstBackupPosition();
             resetParser();
             if (lastException)
             {
                 delete lastException;
             }
             lastException = new Exception(e);
             if (propogateException)
             {
                 throw;
             }
             e.printMe(io);
             return false;
         }
         if (parserState != ScriptBlock)
         {
             deleteAstVector(pt);
             resetAstBackupPosition();
             resetParser();
             if (lastException)
             {
                 delete lastException;
             }
             Exception e(_W("a valid script expected."));
             lastException = new Exception(e);
             if (propogateException)
             {
                 throw;
             }
             return false;
         }
         tree = getParsedScriptBlock();
         pushDebug("EvaluateString", command);
         if (tree == nullptr)
         {
             deleteAstVector(pt);
             resetAstBackupPosition();
             popDebug();
             return false;
         }
         try
         {
             block(tree);
             deleteAstVector(pt);
             resetAstBackupPosition();
             tree = nullptr;
             if (state == NLS_STATE_RETURN)
             {
                 if (depth > 0)
                 {
                     popDebug();
                     depth--;
                     return true;
                 }
             }
             if (state == NLS_STATE_QUIT || state == NLS_STATE_ABORT)
             {
                 popDebug();
                 return true;
             }
         }
         catch (Exception &e)
         {
             deleteAstVector(pt);
             resetAstBackupPosition();
             tree = nullptr;
             if (lastException)
             {
                 delete lastException;
             }
             lastException = new Exception(e);
             if (propogateException)
             {
                 throw;
             }
             e.printMe(io);
             popDebug();
             return false;
         }
         popDebug();
         return true;
     }
expression()
ArrayOf Nelson::Evaluator::expression (ASTPtr t)
Evaluate the expression pointed to by the AST t into a variable.
Definition at line 448 of file Evaluator.cpp.
Referenced by cellDefinition(), conditionedStatement(), doubleColon(), expressionList(), forStatement(), functionExpression(), rhsExpression(), ShortCutOr(), simpleSubindexExpression(), statementType(), switchStatement(), testCaseStatement(), unitColon(), and whileStatement().
     {
         pushID(t->context());
         ArrayOf retval;
         // by default as the target we create double
         if (t->type == const_int_node)
         {
             retval = ArrayOf::doubleConstructor(atof(t->text.c_str()));
         }
         else if (t->type == const_uint64_node)
         {
             char *endptr = nullptr;
             unsigned long long int v = strtoull(t->text.c_str(), &endptr, 10);
             uint64 r = (uint64)v;
             retval = ArrayOf::uint64Constructor(r);
         }
         else if (t->type == const_float_node)
         {
             retval = ArrayOf::singleConstructor(((float)atof(t->text.c_str())));
         }
         else if (t->type == const_double_node)
         {
             retval = ArrayOf::doubleConstructor(atof(t->text.c_str()));
         }
         else if (t->type == string_const_node)
         {
             retval = ArrayOf::stringConstructor(std::string(t->text.c_str()));
         }
         else if (t->type == const_complex_node || t->type == const_dcomplex_node)
         {
             double val = atof(t->text.c_str());
             if (val == 0.)
             {
                 retval = ArrayOf::doubleConstructor(0.);
             }
             else
             {
                 retval = ArrayOf::dcomplexConstructor(0, val);
             }
         }
         else if (t->type == reserved_node)
         {
             if (t->tokenNumber == NLS_KEYWORD_END)
             {
                 if (endValStackLength == 0)
                 {
                     Error(this, ERROR_END_ILLEGAL);
                 }
                 retval = ArrayOf::doubleConstructor((double)endValStack[endValStackLength - 1]);
             }
             else
             {
                 Error(this, ERROR_UNRECOGNIZED_NODE);
             }
         }
         else
         {
             switch (t->opNum)
             {
                 case OP_COLON:
                     if ((t->down != nullptr) && (t->down->opNum == (OP_COLON)))
                     {
                         retval = doubleColon(t);
                     }
                     else
                     {
                         retval = unitColon(t);
                     }
                     break;
                 case OP_EMPTY:
                 {
                     retval = ArrayOf::emptyConstructor();
                 }
                 break;
                 case OP_EMPTY_CELL:
                 {
                     ArrayOf a(ArrayOf::emptyConstructor());
                     a.promoteType(NLS_CELL_ARRAY);
                     retval = a;
                 }
                 break;
                 case OP_BRACKETS:
                 {
                     retval = matrixDefinition(t);
                 }
                 break;
                 case OP_BRACES:
                 {
                     retval = cellDefinition(t);
                 }
                 break;
                 case OP_PLUS:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "plus", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_SUBTRACT:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "minus", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_TIMES:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "mtimes", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_RDIV:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "mrdivide", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_LDIV:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "mldivide", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_SOR:
                 {
                     retval = ShortCutOr(t);
                 }
                 break;
                 case OP_OR:
                 {
                     retval = Or(t);
                 }
                 break;
                 case OP_SAND:
                 {
                     retval = ShortCutAnd(t);
                 }
                 break;
                 case OP_AND:
                 {
                     retval = And(t);
                 }
                 break;
                 case OP_LT:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "lt", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_LEQ:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "le", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_GT:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "gt", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_GEQ:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "ge", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_EQ:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "eq", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_NEQ:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "ne", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_DOT_TIMES:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "times", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_DOT_RDIV:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "rdivide", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_DOT_LDIV:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "ldivide", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_POS:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "uplus", expression(t->down), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_NEG:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "uminus", expression(t->down), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_NOT:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "not", expression(t->down), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_POWER:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "mpower", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_DOT_POWER:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "power", expression(t->down), expression(t->down->right), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_TRANSPOSE:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "ctranspose", expression(t->down), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_DOT_TRANSPOSE:
                 {
                     ArrayOfVector argsOut = CallOperatorFunction(this, "transpose", expression(t->down), 1);
                     retval = argsOut[0];
                 }
                 break;
                 case OP_RHS:
                 {
                     // Test for simple variable lookup
                     if (t->down->down == nullptr)
                     {
                         retval = rhsExpressionSimple(t->down);
                     }
                     else
                     {
                         ArrayOfVector m(rhsExpression(t->down));
                         if (m.empty())
{
                             retval = ArrayOf::emptyConstructor();
                         }
                         else
{
                             retval = m[0];
                         }
                     }
                 }
                 break;
                 default:
                     Error(this, ERROR_UNRECOGNIZED_EXPRESSION);
             }
         }
         popID();
         return retval;
     }
expressionList()
ArrayOfVector Nelson::Evaluator::expressionList (ASTPtr t, Dimensions * dim)
Process a sequence of expressions into a vector of ArrayOfs. The input AST must be: expr1->expr2->expr3...->NULL If the dim argument is non-NULL, then before the nth expression is evaluated, the end value is set to the nth dimension length. Also, if one of the expressions is a multi-valued RHS expression, then it is expanded into the result. Also, if one of the expressions is the ':' token, then the corresponding expression is replaced with either 1:length (if the ':' is a singleton) or 1:dim->getDimensionLength(k). This is only valid if we are a subindexing expression list (i.e., VAR(exprssionlist)), in which case dim != nullptr.
An expressionList allows for expansion of cell-arrays and structure arrays. Works by first screening rhs-expressions through rhsExpression, which can return a vector of variables.
Definition at line 791 of file Evaluator.cpp.
Referenced by functionExpression(), multiFunctionCall(), rhsExpression(), rowDefinition(), and simpleSubindexExpression().
     {
         ArrayOfVector m;
         ArrayOfVector n;
         ASTPtr root;
         indexType index = 0, tmp = 0;
         indexType endVal = 0;
         if (t == nullptr)
         {
             return m;
         }
         pushID(t->context());
         root = t;
         index = 0;
         while (t != nullptr)
         {
             if (t->opNum == OP_KEYWORD)
             {
                 t = t->right;
                 continue;
             }
             if (t->type == non_terminal && t->opNum == (OP_RHS))
             {
                 try
                 {
                     n = rhsExpression(t->down);
                 }
                 catch (Exception& e)
                 {
                     if (!e.matches(ERROR_EMPTY_EXPRESSION))
                     {
                         throw;
                     }
                     else
                     {
                         n = ArrayOfVector();
                     }
                 }
                 for (size_t i = 0; i < n.size(); i++)
                 {
                     m.push_back(n[i]);
                 }
             }
             else if (t->type == non_terminal && t->opNum == (OP_ALL))
             {
                 if (dim == nullptr)
                 {
                     Error(this, ERROR_ILLEGAL_USE_COLON);
                 }
                 if (root->right == nullptr)
                 {
                     // Singleton reference, with ':' - return 1:length as column vector...
                     tmp = dim->getElementCount();
                     m.push_back(ArrayOf::integerRangeConstructor(1, 1, tmp, true));
                 }
                 else
                 {
                     tmp = dim->getDimensionLength(index);
                     m.push_back(ArrayOf::integerRangeConstructor(1, 1, tmp, false));
                 }
             }
             else
             {
                 // Set up the value of the "end" token
                 if (dim != nullptr)
                 {
                     if (root->right == nullptr)
                     {
                         endVal = dim->getElementCount();
                     }
                     else
                     {
                         endVal = dim->getDimensionLength(index);
                     }
                     // Push it onto the stack
                     endValStack[endValStackLength] = endVal;
                     endValStackLength++;
                 }
                 // Call the expression
                 m.push_back(expression(t));
                 if (dim != nullptr)
                     // Pop the endVal stack
                 {
                     endValStackLength--;
                 }
             }
             index++;
             t = t->right;
         }
         popID();
         //m =subsindex(m);
         return m;
     }
forStatement()
void Nelson::Evaluator::forStatement (ASTPtr t)
Implements the for control statement. The AST looks like ident->codeBlock | expr The identifier used as the control variable in the for statement. The variable defined by the identifier takes on each of the values in the expression. For each such assignment, the code in the codeBlock is executed.
Definition at line 1316 of file Evaluator.cpp.
Referenced by statementType().
     {
         ASTPtr  codeBlock;
         ArrayOf indexSet;
         ArrayOf indexNum;
         std::string indexVarName;
         ArrayOf indexVar;
         indexType elementCount = 0;
         if (t == nullptr)
         {
             resetState();
             context->exitLoop();
             return;
         }
         else
         {
             pushID(t->context());
         }
         /* Get the name of the indexing variable */
         indexVarName = t->text;
         /* Evaluate the index set */
         indexSet = expression(t->down);
         /* Get the code block */
         codeBlock = t->right;
         elementCount = indexSet.getLength();
         context->enterLoop();
         for (indexType elementNumber = 0; elementNumber < elementCount; elementNumber++)
         {
             //indexNum = ArrayOf::doubleConstructor(elementNumber + 1);
             //indexVar = indexSet.getVectorSubset(indexNum);
             //context->insertVariable(indexVarName, indexVar);
             indexVar = indexSet.getValueAtIndex(elementNumber);
             bool bInserted = context->insertVariable(indexVarName, indexVar);
             if (!bInserted)
             {
                 Error(this, _W("Redefining permanent variable."));
             }
             block(codeBlock);
             if (state == NLS_STATE_RETURN ||
                     state == NLS_STATE_ABORT ||
                     state == NLS_STATE_QUIT)
             {
                 break;
             }
             if (state == NLS_STATE_CONTINUE)
             {
                 resetState();
             }
             if (state == NLS_STATE_BREAK)
             {
                 resetState();
                 break;
             }
         }
         context->exitLoop();
         popID();
     }
functionExpression()
ArrayOfVector Nelson::Evaluator::functionExpression (FunctionDef * funcDef, ASTPtr t, int narg_out, bool outputOptional)
Evaluate a function and return the results of the function as an ArrayOfVector. For scripts, the body of the function is evaluated directly. Otherwise, the function evaluates itself (using the FunctionDef::evaluateFunction member function). The arguments to the function are unpacked from the AST ast follows ident | () | expr1->expr2->... The outputOptional flag allows the function to not assign an output. Throws an exception if
something other than a parenthesis pair "()" follows the identifier.
if too many arguments are passed to the function.
too many outputs are requested from the function.
Definition at line 3096 of file Evaluator.cpp.
Referenced by multiFunctionCall(), rhsExpression(), rhsExpressionSimple(), and statementType().
     {
         ArrayOfVector m, n;
         ASTPtr s, q, p;
         stringVector keywords;
         ArrayOfVector keyvals;
         ASTPtrVector keyexpr;
         int *keywordNdx = nullptr;
         int *argTypeMap = nullptr;
         pushID(t->context());
         bool CLIFlagsave = InCLI;
         try
         {
             {
                 // Look for arguments
                 if (t->down != nullptr)
                 {
                     s = t->down;
                     if (s->opNum == (OP_PARENS))
                     {
                         s = s->down;
                         // Search for the keyword uses -
                         // To handle keywords, we make one pass through the arguments,
                         // recording a list of keywords used and using ::expression to
                         // evaluate their values.
                         q = s;
                         while (q != nullptr)
{
                             if (q->opNum == OP_KEYWORD)
{
                                 keywords.push_back(q->down->text);
                                 if (q->down->right != nullptr)
{
                                     keyvals.push_back(expression(q->down->right));
                                 }
                                 else
{
                                     keyvals.push_back(ArrayOf::logicalConstructor(true));
                                 }
                                 keyexpr.push_back(q->down->right);
                             }
                             q = q->right;
                         }
                         // If any keywords were found, make another pass through the
                         // arguments and remove them.
 #if 0
                         if (keywords.size() > 0)
{
                             //      if (funcDef->type() != NLS_MACRO_FUNCTION)
                             //        throw Exception(L"out of order argument passing only supported for M files");
                             while (s != nullptr && s->opNum == OP_KEYWORD)
{
                                 s = s->right;
                             }
                             if (s != nullptr)
{
                                 q = s;
                                 while (q->right != nullptr)
{
                                     if (q->right->opNum == OP_KEYWORD)
{
                                         q->right = q->right->right;
                                     }
                                     else
{
                                         q = q->right;
                                     }
                                 }
                             }
                         }
 #endif
                         m = expressionList(s, NULL);
                         // Check for keywords
                         if (keywords.size() > 0)
{
                             // If keywords were used, we have to permute the
                             // entries of the arrayvector to the correct order.
                             stringVector arguments;
                             // Get the arguments from the MacroFunction pointer.
                             arguments = funcDef->arguments;
                             keywordNdx = new int[keywords.size()];
                             int maxndx;
                             maxndx = 0;
                             // Map each keyword to an argument number
                             for (size_t i = 0; i < (int)keywords.size(); ++i)
{
                                 int ndx;
                                 ndx = getArgumentIndex(arguments, keywords[i]);
                                 if (ndx == -1)
{
                                     Error(this, utf8_to_wstring(_("out-of-order argument /") + keywords[i] + _(" is not defined in the called function!")));
                                 }
                                 keywordNdx[i] = ndx;
                                 if (ndx > maxndx)
{
                                     maxndx = ndx;
                                 }
                             }
                             // Next, we have to determine how many "holes" there are
                             // in the argument list - we get the maximum list
                             size_t holes = maxndx + 1 - keywords.size();
                             // At this point, holes is the number of missing arguments
                             // If holes > m.size(), then the total number of arguments
                             // is just maxndx+1.  Otherwise, its
                             // maxndx+1+(m.size() - holes)
                             size_t totalCount;
                             if (holes > m.size())
{
                                 totalCount = maxndx + 1;
                             }
                             else
{
                                 totalCount = maxndx + 1 + (m.size() - holes);
                             }
                             // Next, we allocate a vector to hold the values
                             ArrayOfVector toFill(totalCount);
                             bool *filled = new bool[totalCount];
                             argTypeMap = new int[totalCount];
                             for (size_t i = 0; i < totalCount; i++)
{
                                 filled[i] = false;
                                 argTypeMap[i] = -1;
                             }
                             // Finally...
                             // Copy the keyword values in
                             for (size_t i = 0; i < keywords.size(); i++)
{
                                 toFill[keywordNdx[i]] = keyvals[i];
                                 filled[keywordNdx[i]] = true;
                                 argTypeMap[keywordNdx[i]] = (int)i;
                             }
                             // Fill out the rest of the values from m
                             size_t n = 0;
                             int p = 0;
                             while (n < m.size())
{
                                 if (!filled[p])
{
                                     toFill[p] = m[n];
                                     filled[p] = true;
                                     argTypeMap[p] = -2;
                                     n++;
                                 }
                                 p++;
                             }
                             // Finally, fill in empty matrices for the
                             // remaining arguments
                             for (size_t i = 0; i < totalCount; i++)
                                 if (!filled[i])
{
                                     toFill[i] = ArrayOf::emptyConstructor();
                                 }
                             // Clean up
                             delete[] filled;
                             // delete[] keywordNdx;
                             // Reassign
                             m = toFill;
                         }
                     }
                     else
                     {
                         ArrayOf r;
                         bool isVar = context->lookupVariable(t->text, r);
                         if (isVar)
{
                             if (r.isClassStruct())
{
                                 s = t->down;
                                 if (s)
{
                                     if (s->opNum == (OP_DOT))
{
                                         s = s->down;
                                         return scalarArrayOfToArrayOfVector(r.getField(s->text));
                                     }
                                 }
                             }
                         }
                         Error(this, ERROR_ILLEGAL_EXPRESSION_IN_FUNCTION);
                     }
                 }
                 else
                 {
                     m = ArrayOfVector();
                 }
                 //int nRhs = (int)m.size();
                 //int nLhs = funcDef->outputArgCount();
                 /*
                 if ((funcDef->inputArgCount() >= 0) &&
                 ((int)(m.size()) > funcDef->inputArgCount()))
                 Error(this, std::string("Too many inputs to function ")+t->text);
                 if ((funcDef->outputArgCount() >= 0) &&
                 (narg_out > funcDef->outputArgCount() && !outputOptional))
                 Error(this, std::string("Too many outputs to function ")+t->text);
                 */
                 CLIFlagsave = InCLI;
                 InCLI = false;
                 ArrayOf r;
                 bool isVar = context->lookupVariable(t->text, r);
                 bool haveDown = (t->down != nullptr);
                 if (isVar)
                 {
                     // if it is a class C
                     if (r.isClassStruct())
                     {
                         // C(X1, ..., XN)
                         // we call : C_extract(C, X1, ..., XN)
                         if (m.size() > 0)
{
                             m.insert(m.begin(), r);
                         }
                         else
{
                             // C() or C
                             if (t->down != nullptr)
{
                                 s = t->down;
                                 // C()
                                 if (s->opNum == (OP_PARENS))
{
                                     m.insert(m.begin(), r);
                                 }
                                 // C others ? C{}, C. ?
                                 // we do currently nothing
                             }
                             else
{
                                 // C
                                 return scalarArrayOfToArrayOfVector(r);
                                 /*
                                                                 if (r.isFunctionHandle())
{
                                                                     return scalarArrayOfToArrayOfVector(r);
                                                                 }
                                 */
                             }
                         }
                     }
                     n = funcDef->evaluateFunction(this, m, narg_out);
                 }
                 else
                 {
                     n = funcDef->evaluateFunction(this, m, narg_out);
                 }
                 InCLI = CLIFlagsave;
                 if (state == NLS_STATE_ABORT)
                 {
                     return n;
                 }
                 // Check for any pass by reference
                 if (!haveDown && (funcDef->arguments.size() > 0))
                 {
                     // Get the argument list
                     stringVector arguments;
                     arguments = funcDef->arguments;
                     // M functions can modify their arguments
                     size_t maxsearch = m.size();
                     if (maxsearch > arguments.size())
                     {
                         maxsearch = arguments.size();
                     }
                     if (maxsearch != 0)
                     {
                         q = s;
                     }
                     for (size_t i = 0; i < maxsearch; i++)
                     {
                         // Was this argument passed out of order?
                         if (argTypeMap)
{
                             if ((keywords.size() > 0) && (argTypeMap[i] == -1))
{
                                 continue;
                             }
                             if ((keywords.size() > 0) && (argTypeMap[i] >= 0))
{
                                 p = keyexpr[argTypeMap[i]];
                             }
                             else
{
                                 p = q;
                                 if (q != nullptr)
{
                                     q = q->right;
                                 }
                             }
                         }
                         std::string args(arguments[i]);
                         if (args[0] == '&')
{
                             args.erase(0, 1);
                             // This argument was passed by reference
                             if (p == nullptr || !(p->type == non_terminal && p->opNum == OP_RHS))
{
                                 Error(this, ERROR_MUST_HAVE_LVALUE);
                             }
                             if (p->down->down == nullptr && p->down->type == id_node)
{
                                 bool bInserted = context->insertVariable(p->down->text, m[i]);
                                 if (!bInserted)
{
                                     Error(this, _W("Redefining permanent variable."));
                                 }
                             }
                             else
{
                                 ArrayOf c(assignExpression(p->down, m[i]));
                                 bool bInserted = context->insertVariable(p->down->text, c);
                                 if (!bInserted)
{
                                     Error(this, _W("Redefining permanent variable."));
                                 }
                             }
                         }
                     }
                 }
             }
             // Some routines (e.g., min and max) will return more outputs
             // than were actually requested... so here we have to trim
             // any elements received that we didn't ask for.
             //    narg_out = (int)n.size();
             /*
             while ((int)n.size() > narg_out)    n.pop_back();
             */
             popID();
             return n;
         }
         catch (Exception& e)
         {
             e.what();
             InCLI = CLIFlagsave;
             throw ;
         }
         popID();
         delete[] keywordNdx;
         delete[] argTypeMap;
     }
getContext()
Context * Nelson::Evaluator::getContext ()
Get the context we are running with.
Definition at line 2057 of file Evaluator.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction().
     {
         return context;
     }
getExitCode()
int Nelson::Evaluator::getExitCode ()
Get exit code.
Definition at line 196 of file Evaluator.cpp.
     {
         return exitCode;
     }
getLastErrorString()
std::wstring Nelson::Evaluator::getLastErrorString ()
Get the last error that occurred.
Definition at line 4270 of file Evaluator.cpp.
     {
         return lastException->getMessage();
     }
getLastWarningString()
std::wstring Nelson::Evaluator::getLastWarningString ()
Get the last warning that occurred.
Definition at line 4320 of file Evaluator.cpp.
     {
         return lastwarn;
     }
getOverloadState()
bool Nelson::Evaluator::getOverloadState ()
Get current overload state (enabled by default)
Definition at line 4410 of file Evaluator.cpp.
     {
         return bAllowOverload;
     }
getPrintLimit()
int Nelson::Evaluator::getPrintLimit ()
Get the print limit (number of element printed prior to truncation).
Definition at line 166 of file Evaluator.cpp.
     {
         return(printLimit);
     }
getState()
State Nelson::Evaluator::getState ()
Get the state of the tree walker.
Definition at line 191 of file Evaluator.cpp.
Referenced by evalCLI(), and Nelson::MacroFunctionDef::evaluateFunction().
     {
         return state;
     }
ifStatement()
void Nelson::Evaluator::ifStatement (ASTPtr t)
Handles an if statement, corresponding to an if, a number of elseif blocks and an optional else statement. The AST looks like cstat->elseIfBlock->elseCode | | | cstat->cstat->cstat expr->codeBlock where each of the elseIf blocks are tested sequentially until one of them succeeds.
Definition at line 1170 of file Evaluator.cpp.
Referenced by statementType().
     {
         pushID(t->context());
         bool condStat = conditionedStatement(t);
         if (!condStat)
         {
             t = t->right;
             // Check for additional conditions
             if (t != nullptr)
             {
                 bool elseifMatched = false;
                 if (t->opNum == (OP_ELSEIFBLOCK))
                 {
                     ASTPtr s = t->down;
                     while (!elseifMatched && s != nullptr)
                     {
                         elseifMatched = conditionedStatement(s);
                         s = s->right;
                     }
                     t = t->right;
                 }
                 if (!(elseifMatched || t == nullptr))
                 {
                     block(t);
                 }
             }
         }
         popID();
     }
lookupFunction()
bool Nelson::Evaluator::lookupFunction (std::string funcName, FuncPtr & val)
Look up an identifier as a potential function name
Definition at line 3649 of file Evaluator.cpp.
Referenced by multiFunctionCall(), rhsExpression(), rhsExpressionSimple(), specialFunctionCall(), and statementType().
     {
         return context->lookupFunction(funcName, val);
     }
matrixDefinition()
ArrayOf Nelson::Evaluator::matrixDefinition (ASTPtr t)
Convert a matrix definition of the form: [expr1,expr2;expr3;expr4] into a vector of row definitions. The first row is the vector [expr1,expr2], and the second is the vector [expr3,expr4]. The AST input should look like: [] | ;-> ; -> ... -> NULL | | | rowDef rowDef
Definition at line 280 of file Evaluator.cpp.
Referenced by expression().
     {
         ArrayOfMatrix m;
         //m.reserve(4096);
         if (t->opNum != OP_BRACKETS)
         {
             Error(this, ERROR_AST_SYNTAX_ERROR);
         }
         ASTPtr s = t->down;
         pushID(s->context());
         while (s != nullptr)
         {
             m.push_back(rowDefinition(s));
             s = s->right;
         }
         ArrayOfVector v;
         for (indexType k = 0; k < m.size(); k++)
         {
             ArrayOf h = HorzCat(this, m[k]);
             v.push_back(h);
         }
         ArrayOf res = VertCat(this, v);
         //ArrayOf retval(ArrayOf::matrixConstructor(m));
         popID();
         //return retval;
         return res;
     }
multiFunctionCall()
void Nelson::Evaluator::multiFunctionCall (ASTPtr t, bool printIt)
A multifunction call is an expression of the sort [expr1,expr2,...,exprn] = func(args). The AST is multiCall | []->functionExpression_AST | ;->NULL | rowDefs When calculating the number of left hand sides for the multifunction, single variables without subindexing expressions are counted as a single left hand side. Thus, an expression such as [A{1:3},B] = func(args) counts for four left hand sides, regardless of the contents of B. If the printIt flag is set, each of the outputs is to be written to the console. Throws an exception if the AST is malformed (i.e., the '[]' is missing, or there are multiple rows in the left hand side.).
Definition at line 2509 of file Evaluator.cpp.
Referenced by statementType().
     {
         ArrayOfVector m;
         ASTPtr s, fAST, saveLHS, cAST;
         ArrayOf c;
         //int lhsSize;
         FunctionDef *fptr;
         cAST = t;
         fAST = t->right;
         bool bDeal = false;
         pushID(fAST->context());
         ArrayOf r;
         if (!lookupFunction(fAST->text, fptr))
         {
             bool isVar = context->lookupVariable(fAST->text, r);
             if (isVar)
             {
                 if (r.isClassStruct())
                 {
                     std::string className = r.getStructType();
                     std::string extractionFunctionName = className + "_extraction";
                     bool isFun = lookupFunction(extractionFunctionName, fptr);
                     if (!isFun)
                     {
                         Error(this, utf8_to_wstring(_("Undefined function") + " " + extractionFunctionName));
                     }
                 }
                 else if (r.isCell())
                 {
                     // C = {rand(3),nan(3),zeros(3),inf(3)}
                     // [a, b, c, d] = C{ : }
                     if (t->opNum != OP_BRACKETS)
                     {
                         Error(this, ERROR_ILLEGAL_LEFT_MULTIFUNCTION_EXPRESSION);
                     }
                     bDeal = true;
                 }
                 else
                 {
                     Error(this, utf8_to_wstring(_("Undefined function") + " " + fAST->text));
                 }
             }
             else
             {
                 Error(this, utf8_to_wstring(_("Undefined function") + " " + fAST->text));
             }
         }
         if (t->opNum != OP_BRACKETS)
         {
             Error(this, ERROR_ILLEGAL_LEFT_MULTIFUNCTION_EXPRESSION);
         }
         s = t->down;
         if (s->opNum != OP_SEMICOLON)
         {
             Error(this, ERROR_ILLEGAL_LEFT_MULTIFUNCTION_EXPRESSION);
         }
         if (s->right != nullptr)
         {
             Error(this, ERROR_MULTIPLE_ROWS_NOT_ALLOWED);
         }
         // We have to make multiple passes through the LHS part of the AST.
         // The first pass is to count how many function outputs are actually
         // being requested.
         // Calculate how many lhs objects there are
         //lhsSize = s->peerCount();
         s = s->down;
         saveLHS = s;
         // Get the lhs objects into rset
         indexType lhsCount = 0;
         ASTPtr mptr = s;
         while (mptr != nullptr)
         {
             indexType dmp = countLeftHandSides(mptr->down);
             lhsCount += dmp;
             mptr = mptr->right;
         }
         if (bDeal)
         {
             // C = {rand(3),nan(3),zeros(3),inf(3)}
             // [a, b, c, d] = C{ : }
             Dimensions rhsDimensions;
             rhsDimensions = r.getDimensions();
             m = expressionList(fAST->down->down, &rhsDimensions);
             if (m.size() == 0)
             {
                 Error(this, ERROR_INDEX_EXPRESSION_EXPECTED);
             }
             else if (m.size() == 1)
             {
                 ArrayOfVector m2 = r.getVectorContentsAsList(m[0]);
                 if ((indexType)m2.size() < lhsCount)
                 {
                     Error(this, _W("Insufficient number of outputs."));
                 }
                 else
                 {
                     m = m2;
                 }
             }
             else
             {
                 Error(this, _W("Case not managed."));
             }
         }
         else
         {
             m = functionExpression(fptr, fAST, (int)lhsCount, false);
         }
         s = saveLHS;
         while ((s != nullptr) && (m.size() > 0))
         {
             ArrayOf c(assignExpression(s->down, m));
             bool bInserted = context->insertVariable(s->down->text, c);
             if (!bInserted)
             {
                 Error(this, _W("Redefining permanent variable."));
             }
             if (printIt)
             {
                 io->outputMessage(s->down->text);
                 io->outputMessage(L" =\n\n");
                 OverloadDisplay(this, c);
             }
             s = s->right;
         }
         if (s != nullptr)
         {
             io->warningMessage(WARNING_OUTPUTS_NOT_ASSIGNED);
         }
         popID();
     }
popID()
void Nelson::Evaluator::popID ()
Pop a location ID off the stack
Definition at line 149 of file Evaluator.cpp.
Referenced by cellDefinition(), conditionedStatement(), doubleColon(), expression(), expressionList(), forStatement(), functionExpression(), ifStatement(), matrixDefinition(), multiFunctionCall(), rhsExpression(), rhsExpressionSimple(), rowDefinition(), ShortCutOr(), simpleSubindexExpression(), specialFunctionCall(), statement(), statementType(), switchStatement(), testCaseStatement(), unitColon(), and whileStatement().
     {
         if (!cstack.empty())
         {
             cstack.pop_back();
         }
         else
         {
             io->outputMessage("IDERROR\n");
         }
     }
pushID()
void Nelson::Evaluator::pushID (int a)
Push the given location ID onto the stack
Definition at line 133 of file Evaluator.cpp.
Referenced by cellDefinition(), conditionedStatement(), doubleColon(), expression(), expressionList(), forStatement(), functionExpression(), ifStatement(), matrixDefinition(), multiFunctionCall(), rhsExpression(), rhsExpressionSimple(), rowDefinition(), ShortCutOr(), simpleSubindexExpression(), specialFunctionCall(), statement(), statementType(), switchStatement(), testCaseStatement(), unitColon(), and whileStatement().
     {
         if (!cstack.empty())
         {
             if (cstack.size() > cstack.capacity() - 100)
             {
                 cstack.reserve(cstack.capacity() * 2);
             }
             cstack.push_back(StackEntry(cstack.back().cname, cstack.back().detail, a));
         }
         else
         {
             cstack.push_back(StackEntry("base", "base", a));
         }
     }
resetState()
void Nelson::Evaluator::resetState ()
Reset the state of the tree walker.
Definition at line 171 of file Evaluator.cpp.
Referenced by block(), Nelson::MacroFunctionDef::evaluateFunction(), Evaluator(), forStatement(), statementType(), and whileStatement().
     {
         state = NLS_STATE_OK;
     }
rhsExpression()
ArrayOfVector Nelson::Evaluator::rhsExpression (ASTPtr t)
The RHS expression is used to represent an rvalue in an assignment statement (or an implicit assignment such as –>2+3). The form of the AST depends on the head. If the head identifier is a function name, then the form of the AST is: ident | () | expr1->expr2->... On the other hand, if the identifier represents a variable (variables are checked for first, incidentally), then the AST looks like: ident | ()->{}->. | | | | | field | expr3->... expr1->expr2->... Throws an Exception
if the identifier cannot be matched to either a variable or function.
Definition at line 3880 of file Evaluator.cpp.
Referenced by expression(), expressionList(), and statementType().
     {
         ArrayOf r, q;
         ArrayOf n, p;
         ArrayOfVector m;
         ArrayOfVector rv;
         bool isVar;
         bool isFun = false;
         Dimensions rhsDimensions;
         FunctionDef *funcDef = nullptr;
         pushID(t->context());
         // Try to satisfy the rhs expression with what functions we have already
         // loaded.
         isVar = context->lookupVariable(t->text, r);
         if (isVar)
         {
             if (r.isClassStruct())
             {
                 std::string className = r.getStructType();
                 std::string extractionFunctionName = className + "_extraction";
                 isFun = lookupFunction(extractionFunctionName, funcDef);
                 if (isFun)
                 {
                     m = functionExpression(funcDef, t, 1, false);
                     popID();
                     return m;
                 }
                 else
                 {
                     Error(this, utf8_to_wstring(_("Undefined function:") + " " + extractionFunctionName));
                 }
             }
             else
             {
                 if (t->down == nullptr)
                 {
                     ArrayOfVector rv;
                     rv.push_back(r);
                     popID();
                     return rv;
                 }
                 else
                 {
                     ASTPtr tt;
                     tt = t->down;
                     if (tt->opNum == OP_PARENS)
                     {
                         if (tt->down == nullptr)
{
                             if (tt->right)
{
                                 tt = tt->right;
                                 if (tt->opNum == OP_DOT)
{
                                     ArrayOfVector rv;
                                     rv.push_back(r.getField(tt->down->text));
                                     popID();
                                     return rv;
                                 }
                             }
                         }
                     }
                 }
             }
         }
         else
         {
             isFun = lookupFunction(t->text, funcDef);
             if (isFun)
             {
                 if (funcDef->outputArgCount() == 0)
                 {
                     throw Exception(ERROR_WRONG_NUMBERS_OUTPUT_ARGS, utf8_to_wstring(funcDef->name));
                 }
                 m = functionExpression(funcDef, t, 1, false);
                 popID();
                 return m;
             }
             else
             {
                 Error(this, utf8_to_wstring(_("Undefined variable or function:") + " " + t->text));
             }
         }
         t = t->down;
         while (t != nullptr)
         {
             rhsDimensions = r.getDimensions();
             if (!rv.empty())
             {
                 Error(this, _W("Cannot reindex an expression that returns multiple values."));
             }
             if (t->opNum == (OP_PARENS))
             {
                 m = expressionList(t->down, &rhsDimensions);
                 if (rhsDimensions.getLength() > (indexType)m.size())
                 {
                     Dimensions nDim;
                     if (m.size() >= 2)
                     {
                         size_t d = 0;
                         for (d = 0; d < m.size() - 1; d++)
{
                             nDim[d] = rhsDimensions[d];
                         }
                         indexType L = 1;
                         for (indexType k = d; k < rhsDimensions.getLength(); k++)
{
                             L = L * rhsDimensions[k];
                         }
                         nDim[d] = L;
                         r.reshape(nDim);
                         rhsDimensions = r.getDimensions();
                         m = expressionList(t->down, &rhsDimensions);
                     }
                 }
                 if (m.size() == 0)
                 {
                     if (t->right == nullptr)
                     {
                         ArrayOfVector rv;
                         rv.push_back(r);
                         popID();
                         return rv;
                     }
                     else
                     {
                         Error(this, _W("index expected."));
                     }
                 }
                 else if (m.size() == 1)
                 {
                     q = r.getVectorSubset(m[0]);
                     r = q;
                 }
                 else
                 {
                     q = r.getNDimSubset(m);
                     r = q;
                 }
             }
             if (t->opNum == (OP_BRACES))
             {
                 m = expressionList(t->down, &rhsDimensions);
                 if (rhsDimensions.getLength() > (indexType)m.size())
                 {
                     Dimensions nDim;
                     if (m.size() >= 2)
                     {
                         size_t d = 0;
                         for (d = 0; d < m.size() - 1; d++)
{
                             nDim[d] = rhsDimensions[d];
                         }
                         indexType L = 1;
                         for (indexType k = d; k < rhsDimensions.getLength(); k++)
{
                             L = L * rhsDimensions[k];
                         }
                         nDim[d] = L;
                         r.reshape(nDim);
                         rhsDimensions = r.getDimensions();
                         m = expressionList(t->down, &rhsDimensions);
                     }
                 }
                 if (m.size() == 0)
                 {
                     Error(this, ERROR_INDEX_EXPRESSION_EXPECTED);
                 }
                 else if (m.size() == 1)
                 {
                     rv = r.getVectorContentsAsList(m[0]);
                 }
                 else
                 {
                     rv = r.getNDimContentsAsList(m);
                 }
                 if (rv.size() == 1)
                 {
                     r = rv[0];
                     rv = ArrayOfVector();
                 }
                 else if (rv.size() == 0)
                 {
                     Error(this, ERROR_EMPTY_EXPRESSION);
                     r = ArrayOf::emptyConstructor();
                 }
             }
             if (t->opNum == (OP_DOT))
             {
                 rv = r.getFieldAsList(t->down->text);
                 if (rv.size() == 1)
                 {
                     r = rv[0];
                     rv = ArrayOfVector();
                 }
                 else if (rv.size() == 0)
                 {
                     r = ArrayOf::emptyConstructor();
                     rv = ArrayOfVector();
                 }
             }
             if (t->opNum == (OP_DOTDYN))
             {
                 std::string field;
                 try
                 {
                     ArrayOf fname(expression(t->down));
                     field = fname.getContentsAsCString();
                 }
                 catch (Exception &e)
                 {
                     e.what();
                     Error(this, _W("dynamic field reference to structure requires a string argument"));
                 }
                 rv = r.getFieldAsList(field);
                 if (rv.size() <= 1)
                 {
                     r = rv[0];
                     rv = ArrayOfVector();
                 }
             }
             t = t->right;
         }
         if (rv.empty())
         {
             rv.push_back(r);
         }
         popID();
         return rv;
     }
rhsExpressionSimple()
ArrayOf Nelson::Evaluator::rhsExpressionSimple (ASTPtr t) inline
Special case the single assignment statement 'A = B' for speed.
Definition at line 3654 of file Evaluator.cpp.
Referenced by expression().
     {
         ArrayOf r;
         ArrayOfVector m;
         bool isVar;
         bool isFun;
         FunctionDef *funcDef;
         pushID(t->context());
         // Try to satisfy the rhs expression with what functions we have already
         // loaded.
         isVar = context->lookupVariable(t->text, r);
         if (isVar && (t->down == nullptr))
         {
             popID();
             return r;
         }
         if (!isVar)
         {
             isFun = lookupFunction(t->text, funcDef);
         }
         if (!isVar && isFun)
         {
             m = functionExpression(funcDef, t, 1, false);
             if (m.empty())
             {
                 popID();
                 return ArrayOf::emptyConstructor();
             }
             else
             {
                 popID();
                 return m[0];
             }
         }
         if (!isVar)
         {
             Error(this, utf8_to_wstring(_("Undefined variable:") + " " + t->text));
         }
         if (!isFun)
         {
             Error(this, utf8_to_wstring(_("Undefined function:") + " " +t->text));
         }
         popID();
         return r;
     }
rowDefinition()
ArrayOfVector Nelson::Evaluator::rowDefinition (ASTPtr t)
Convert an expression list into a vector of ArrayOf variables.
Definition at line 206 of file Evaluator.cpp.
Referenced by cellDefinition(), and matrixDefinition().
     {
         pushID(t->context());
         if (t->opNum != OP_SEMICOLON)
         {
             Error(this, ERROR_AST_SYNTAX_ERROR);
         }
         ASTPtr s = t->down;
         ArrayOfVector expl = expressionList(s, NULL);
         ArrayOfVector retval(expl);
         popID();
         return retval;
     }
setExitCode()
void Nelson::Evaluator::setExitCode (int _exitCode)
Set exit code.
Definition at line 201 of file Evaluator.cpp.
     {
         exitCode = _exitCode;
     }
setLastErrorString()
void Nelson::Evaluator::setLastErrorString (std::wstring txt)
Set the text for the last error.
Definition at line 4275 of file Evaluator.cpp.
     {
         if (lastException)
         {
             lastException->setMessage(txt);
         }
     }
setLastWarningString()
void Nelson::Evaluator::setLastWarningString (std::string msg)
Set the text for the last warning.
Definition at line 4330 of file Evaluator.cpp.
Referenced by getLastWarningString().
     {
         lastwarn = utf8_to_wstring(txt);
     }
setPrintLimit()
void Nelson::Evaluator::setPrintLimit (int lim)
Set the print limit (number of element printed prior to truncation).
Definition at line 161 of file Evaluator.cpp.
     {
         printLimit = lim;
     }
setState()
State Nelson::Evaluator::setState (State newState)
Set the state of the tree walker.
Definition at line 184 of file Evaluator.cpp.
Referenced by evalCLI().
     {
         State previousState = state;
         state = newState;
         return previousState;
     }
ShortCutOr()
ArrayOf Nelson::Evaluator::ShortCutOr (ASTPtr t)
Handles the logistics of shortcut evaluation
Definition at line 386 of file Evaluator.cpp.
Referenced by expression().
     {
         pushID(t->context());
         ArrayOfVector argsOut = CallOperatorFunction(this, "shortcutor", expression(t->down), expression(t->down->right), 1);
         ArrayOf retval = argsOut[0];
         popID();
         return retval;
         /*
         ArrayOf retval;
         if (!a.isScalar())
         {
         retval = Or(a, expression(t->down->right));
         }
         else
         {
         // A is a scalar - is it true?
         a.promoteType(NLS_LOGICAL);
         if (*((const logical*)a.getDataPointer()))
         {
         retval = a;
         }
         else
         {
         retval = Or(a, expression(t->down->right));
         }
         }
         */
     }
simpleSubindexExpression()
ArrayOf Nelson::Evaluator::simpleSubindexExpression (ArrayOf & r, ASTPtr t)
Process an AST to form an lvalue in an assignment statement. The AST looks like: ident | ()->{}->. | | | | | field | expr3->... expr1->expr2->... The lhsExpression method creates a LeftHandSide object that captures the original object and the subindexing expressions applied to it. Throws an Exception if the indexing expressions are empty.
Definition at line 2062 of file Evaluator.cpp.
     {
         Dimensions rhsDimensions;
         ArrayOfVector m;
         rhsDimensions = r.getDimensions();
         if (t->opNum == (OP_PARENS))
         {
             m = expressionList(t->down, &rhsDimensions);
             if (m.size() == 0)
             {
                 Error(this, ERROR_INDEX_EXPRESSION_EXPECTED);
             }
             else if (m.size() == 1)
             {
                 if (r.isClassStruct())
                 {
                     Error(this, ERROR_NEED_OVERLOAD);
                 }
                 else
                 {
                     try
                     {
                         return(r.getVectorSubset(m[0]));
                     }
                     catch (Exception &e)
                     {
                         e.what();
                         return(ArrayOf::emptyConstructor());
                     }
                 }
             }
             else
             {
                 try
                 {
                     return(r.getNDimSubset(m));
                 }
                 catch (Exception &e)
                 {
                     e.what();
                     return(ArrayOf::emptyConstructor());
                 }
             }
         }
         if (t->opNum == (OP_BRACES))
         {
             m = expressionList(t->down, &rhsDimensions);
             if (m.size() == 0)
             {
                 Error(this, ERROR_INDEX_EXPRESSION_EXPECTED);
             }
             else if (m.size() == 1)
             {
                 try
                 {
                     return(r.getVectorContents(m[0]));
                 }
                 catch (Exception &e)
                 {
                     e.what();
                     return(ArrayOf::emptyConstructor());
                 }
             }
             else
             {
                 try
                 {
                     return(r.getNDimContents(m));
                 }
                 catch (Exception &e)
                 {
                     e.what();
                     return(ArrayOf::emptyConstructor());
                 }
             }
         }
         if (t->opNum == (OP_DOT))
         {
             try
             {
                 return(r.getField(t->down->text));
             }
             catch (Exception &e)
             {
                 e.what();
                 return(ArrayOf::emptyConstructor());
             }
         }
         if (t->opNum == (OP_DOTDYN))
         {
             std::string field = "";
             try
             {
                 ArrayOf fname(expression(t->down));
                 field = fname.getContentsAsCString();
             }
             catch (Exception &e)
             {
                 e.what();
                 Error(this, ERROR_DYNAMIC_FIELD_STRING_EXPECTED);
             }
             try
             {
                 ArrayOf R = r.getField(field);
                 return R;
             }
             catch (Exception &e)
             {
                 e.what();
                 return(ArrayOf::emptyConstructor());
             }
         }
         return(ArrayOf::emptyConstructor());
     }
specialFunctionCall()
ArrayOfVector Nelson::Evaluator::specialFunctionCall (ASTPtr t, bool printIt)
A special function call is an expression of the form
func arg1 arg2 arg3
which is represented in an AST is scall | fname->arg
Definition at line 2458 of file Evaluator.cpp.
Referenced by statementType().
     {
         ArrayOfVector m;
         stringVector args;
         args.push_back(t->text);
         ASTPtr s = t->right;
         while (s)
         {
             args.push_back(s->text);
             s = s->right;
         }
         if (args.empty())
         {
             return m;
         }
         ArrayOfVector n;
         for (size_t i = 1; i < args.size(); i++)
         {
             n.push_back(ArrayOf::stringConstructor(args[i].c_str()));
         }
         FuncPtr val;
         pushID(t->context());
         if (!lookupFunction(args[0], val))
         {
             Error(this, utf8_to_wstring(_("unable to resolve ") + args[0] + _(" to a function call")));
         }
         bool CLIFlagsave = InCLI;
         InCLI = false;
         try
         {
             m = val->evaluateFunction(this, n, 0);
         }
         catch (Exception& e)
         {
             e.what();
             InCLI = CLIFlagsave;
             popID();
             throw;
         }
         InCLI = CLIFlagsave;
         popID();
         return m;
     }
statement()
void Nelson::Evaluator::statement (ASTPtr t)
The statement method simply screens out the need for the printIt flag. It also retrieves the statement context for use in error reporting. The AST looks like: qstatement A quiet statement (printIt -> false) | context (optional) | statementBody
rstatement A normal statement (printIt -> true) | context (optional) | statementBody The context data is supplied by the parse (indicates the line number and filename if necessary).
Definition at line 1959 of file Evaluator.cpp.
Referenced by block().
     {
         try
         {
             pushID(t->context());
             if (t->opNum == (OP_QSTATEMENT))
             {
                 statementType(t->down, false);
             }
             else if (t->opNum == (OP_RSTATEMENT))
             {
                 statementType(t->down, true && bEchoMode);
             }
             else
             {
                 statementType(t->down, true && bEchoMode);
             }
             popID();
         }
         catch (Exception& e)
         {
             e.what();
             popID();
             throw ;
             /*
             if (autostop && !InCLI)
             {
             e.printMe(io);
             stackTrace(true);
             debugCLI();
             if (state < NLS_STATE_QUIT)
             {
             resetState();
             }
             popID();
             }
             else
             {
             popID();
             throw;
             }
             */
         }
     }
statementType()
void Nelson::Evaluator::statementType (ASTPtr t, bool printIt)
Execute the statement described by the AST - the printIt flag determines if the result of the statement should be printed to the console. The form of the AST required depends on the type of statement being executed. The various statement types handled are as follows: = Assignment of expression to LHS | LHS->expr
multicall Multifunction call | multicallBody
NLS_FOR For statement | forBody
NLS_WHILE While statement | whileBody
NLS_IF If statement | ifBody
NLS_BREAK Break statement - change the state of the interpreter to NLS_STATE_BREAK
NLS_CONTINUE Continue statement - change the state of the interpreter to NLS_STATE_CONTINUE
NLS_RETURN Return statement - change the state to NLS_STATE_RETURN
NLS_SWITCH Switch statement | switchBody
NLS_TRY Try statement | tryBody
NLS_PAUSE Enter another CLI session
rhs A function call being evaluated as a statement | funcName
expr An expression being evaluated as a statement
The function call is trapped before the expression to handle the special variable "ans". Throws an Exception if the statement type is not recognized.
Definition at line 1712 of file Evaluator.cpp.
Referenced by statement().
     {
         ArrayOfVector m;
         FunctionDef *fdef;
         if (haveEventsLoop())
         {
             ProcessEventsDynamicFunction(false);
         }
         if (t == nullptr)
         {
             return;
         }
         pushID(t->context());
         // check the debug flag
         int fullcontext = t->context();
         handleDebug(fullcontext);
         if (t->isEmpty())
         {
             /* Empty statement */
         }
         else if (t->opNum == (OP_ASSIGN))
         {
             if (t->down->down == nullptr)
             {
                 ArrayOf b(expression(t->down->right));
                 bool bInserted = context->insertVariable(t->down->text, b);
                 if (!bInserted)
                 {
                     Error(this, _W("Redefining permanent variable."));
                 }
                 if (printIt)
                 {
                     io->outputMessage(t->down->text);
                     io->outputMessage(L" =\n\n");
                     OverloadDisplay(this, b);
                 }
             }
             else
             {
                 ArrayOf expr(expression(t->down->right));
                 ArrayOf c(assignExpression(t->down, expr));
                 bool bInserted = context->insertVariable(t->down->text, c);
                 if (!bInserted)
                 {
                     Error(this, _W("Redefining permanent variable."));
                 }
                 if (printIt)
                 {
                     io->outputMessage(t->down->text);
                     io->outputMessage(L" =\n\n");
                     OverloadDisplay(this, c);
                 }
             }
         }
         else if (t->opNum == (OP_MULTICALL))
         {
             multiFunctionCall(t->down, printIt);
         }
         else if (t->opNum == (OP_SCALL))
         {
             ArrayOfVector m = specialFunctionCall(t->down, printIt);
             if (m.size() > 0)
             {
                 io->outputMessage(L"\nans =\n\n");
                 OverloadDisplay(this, m[0]);
                 context->insertVariable("ans", m[0]);
             }
         }
         else if (t->type == reserved_node)
         {
             switch (t->tokenNumber)
             {
                 case NLS_KEYWORD_FOR:
                     forStatement(t->down);
                     break;
                 case NLS_KEYWORD_WHILE:
                     whileStatement(t->down);
                     break;
                 case NLS_KEYWORD_IF:
                     ifStatement(t->down);
                     break;
                 case NLS_KEYWORD_BREAK:
                     if (context->inLoop())
                     {
                         state = NLS_STATE_BREAK;
                     }
                     break;
                 case NLS_KEYWORD_CONTINUE:
                     if (context->inLoop())
                     {
                         state = NLS_STATE_CONTINUE;
                     }
                     break;
                 case NLS_KEYWORD_RETURN:
                     state = NLS_STATE_RETURN;
                     break;
                 case NLS_KEYWORD_SWITCH:
                     switchStatement(t->down);
                     break;
                 case NLS_KEYWORD_TRY:
                     tryStatement(t->down);
                     break;
                 case NLS_KEYWORD_QUIT:
                     state = NLS_STATE_QUIT;
                     break;
                 case NLS_KEYWORD_ABORT:
                     state = NLS_STATE_ABORT;
                     if (depth)
                     {
                         depth = 0;
                     }
                     break;
                 case NLS_KEYWORD_PAUSE:
                     depth++;
                     evalCLI();
                     if (state < NLS_STATE_QUIT)
                     {
                         resetState();
                     }
                     depth--;
                     break;
                 case NLS_KEYWORD_ENDFUNCTION:
                     /* a workaround to have a endfunction keyword */
                     if (context->getCurrentScope()->getName() == "base")
                     {
                         Error(this, ERROR_ENDFUNCTION_WRONG_USE);
                     }
                     state = NLS_STATE_RETURN;
                     break;
                 default:
                     Error(this, ERROR_UNRECOGNIZED_STATEMENT);
             }
         }
         else
         {
             // There is a special case to consider here - when a
             // function call is made as a statement, we do not require
             // that the function have an output.
             ArrayOf b;
             bool bUpdateAns = true;
             if (t->opNum == (OP_RHS) &&
                     !context->lookupVariable(t->down->text, b) &&
                     lookupFunction(t->down->text, fdef))
             {
                 //  m = functionExpression(fdef,t->down,1,true);
                 if (fdef->type() == NLS_BUILT_IN_FUNCTION)
                 {
                     // We manage case lhs == 0 in builtin
                     // example toc or who
                     m = functionExpression(fdef, t->down, 0, true);
                 }
                 else
                 {
                     m = functionExpression(fdef, t->down, 1, true);
                 }
                 if (m.size() > 0)
                 {
                     b = m[0];
                 }
                 else
                 {
                     bUpdateAns = false;
                 }
                 if (fdef->type() == NLS_BUILT_IN_FUNCTION)
                 {
                     if (printIt && (m.size() > 0) && (state < NLS_STATE_QUIT))
                     {
                         io->outputMessage(L"\nans =\n\n");
                         OverloadDisplay(this, b);
                     }
                 }
                 else
                 {
                     if (printIt && (fdef->outputArgCount() != 0) && (state < NLS_STATE_QUIT))
                     {
                         io->outputMessage(L"\nans =\n\n");
                         OverloadDisplay(this, b);
                     }
                 }
             }
             else if (t->opNum == OP_RHS)
             {
                 m = rhsExpression(t->down);
                 if (m.size() == 0)
                 {
                     b = ArrayOf::emptyConstructor();
                 }
                 else
                 {
                     b = m[0];
                     if (printIt && (state < NLS_STATE_QUIT))
                     {
                         //io->outputMessage(L"ans =\n\n");
                         io->outputMessage("\n");
                         for (size_t j = 0; j < m.size(); j++)
{
                             if (m.size() > 1)
{
                                 char buffer[1000];
                                 sprintf(buffer, _("\n%d of %d:\n").c_str(), j + 1, m.size());
                                 io->outputMessage(buffer);
                             }
                             OverloadDisplay(this, m[j]);
                         }
                     }
                 }
             }
             else
             {
                 b = expression(t);
                 if (printIt && (state < NLS_STATE_QUIT))
                 {
                     io->outputMessage(L"\nans =\n\n");
                     OverloadDisplay(this, b);
                 }
             }
             if (state == NLS_STATE_QUIT ||
                     state == NLS_STATE_ABORT)
             {
                 popID();
                 return;
             }
             if (bUpdateAns)
             {
                 context->insertVariable("ans", b);
             }
         }
         popID();
     }
switchStatement()
void Nelson::Evaluator::switchStatement (ASTPtr t)
Handle a switch statement. The switch statement tests an expression against a number of case blocks. If a case block matches, the code in the case block is executed, and the switch statement quits. If none of the case blocks match, the otherwise code is executed. The AST looks like expr->caseBlock->otherwiseCode | testCase->testCase->...->NULL Where testCase is the AST passed to testCaseStatement. For a switch statement, the switch value must be either a scalar value or a string. The test values in each case statement can either be the same type, or a cell array. If it is a cell array, then the switch value is compared with each entry in the case expression. Throws an Exception if the switch expression is not either a scalar or a string.
Definition at line 1087 of file Evaluator.cpp.
Referenced by statementType().
     {
         ArrayOf switchVal;
         pushID(t->context());
         // First, extract the value to perform the switch on.
         switchVal = expression(t);
         // Assess its type to determine if this is a scalar switch
         // or a string switch.
         if (!switchVal.isScalar() && !switchVal.isSingleString())
         {
             Error(this, ERROR_SWITCH_STATEMENTS);
         }
         // Move to the next node in the AST
         t = t->right;
         // Check for additional conditions
         if (t != nullptr)
         {
             bool caseMatched = false;
             if (t->opNum == (OP_CASEBLOCK))
             {
                 ASTPtr s = t->down;
                 while (!caseMatched && s != nullptr)
                 {
                     caseMatched = testCaseStatement(s, switchVal);
                     s = s->right;
                 }
             }
             t = t->right;
             if (!(caseMatched || (t == nullptr)))
                 // Do the "otherwise" code
             {
                 block(t);
             }
         }
         popID();
     }
testCaseStatement()
bool Nelson::Evaluator::testCaseStatement (ASTPtr t, ArrayOf s)
This somewhat strange test is used by the switch statement. If x is a scalar, and we are a scalar, this is an equality test. If x is a string and we are a string, this is a strcmp test. If x is a scalar and we are a cell-array, this test is applied on an element-by-element basis, looking for any matches. If x is a string and we are a cell-array, then this is applied on an element-by-element basis also. The AST for this looks like: NLS_CASE | expr->codeBlock The expression is compared to x using ArrayOf::testForCaseMatch. If a match is found, then the codeBlock is executed. The result of the test is returned. Throws an exception if the AST is malformed.
This somewhat strange test is used by the switch statement. If x is a scalar, and we are a scalar, this is an equality test. If x is a string and we are a string, this is a strcmp test. If x is a scalar and we are a cell-array, this test is applied on an element-by-element basis, looking for any matches. If x is a string and we are a cell-array, then this is applied on an element-by-element basis also.
Definition at line 935 of file Evaluator.cpp.
Referenced by switchStatement().
     {
         bool caseMatched;
         ArrayOf r;
         pushID(t->context());
         if (t->type != reserved_node || t->tokenNumber != NLS_KEYWORD_CASE)
         {
             Error(this, ERROR_AST_SYNTAX_ERROR);
         }
         t = t->down;
         r = expression(t);
         caseMatched = s.testForCaseMatch(r);
         if (caseMatched)
         {
             block(t->right);
         }
         popID();
         return caseMatched;
     }
tryStatement()
void Nelson::Evaluator::tryStatement (ASTPtr t)
Implements the try statement. The AST looks like block->catchBlock The code in block is executed. If an exception occurs, then the code in catchBlock is executed.
Definition at line 997 of file Evaluator.cpp.
Referenced by statementType().
     {
         // Turn off autostop for this statement block
         bool autostop_save = autostop;
         autostop = false;
         // Get the state of the IDnum stack and the
         // contextStack and the cnameStack
         size_t stackdepth = cstack.size();
         try
         {
             block(t);
         }
         catch (Exception &e)
         {
             e.what();
             while (cstack.size() > stackdepth)
             {
                 cstack.pop_back();
             }
             //      cname = cstack.back().cname;
             t = t->right;
             if (t != nullptr)
             {
                 autostop = autostop_save;
                 block(t);
             }
         }
         autostop = autostop_save;
     }
unitColon()
ArrayOf Nelson::Evaluator::unitColon (ASTPtr t)
Evaluate a unit colon expression. The AST input should look like: : | expr1->expr2
The output is the expression expr1:expr2, which is the vector [expr1,expr1+1,expr1+2,...,expr1+n], where n is the largest integer such that expr1+n <= expr2.
Definition at line 754 of file Evaluator.cpp.
Referenced by expression().
     {
         ArrayOf a, b;
         pushID(t->context());
         a = expression(t->down);
         b = expression(t->down->right);
         /*
         ArrayOf retval(UnitColon(a, b));
         */
         ArrayOfVector argsOut = CallOperatorFunction(this, "colon", expression(t->down), expression(t->down->right), 1);
         ArrayOf retval = argsOut[0];
         popID();
         return retval;
     }
whileStatement()
void Nelson::Evaluator::whileStatement (ASTPtr t)
Implements the while control statement. The AST looks like expr->codeBlock The test expression is evaluated until it fails, and for each successful expression, the codeBlock is executed.
Definition at line 1226 of file Evaluator.cpp.
Referenced by statementType().
     {
         ASTPtr testCondition;
         ArrayOf condVar;
         ASTPtr codeBlock;
         bool conditionTrue;
         bool breakEncountered;
         pushID(t->context());
         testCondition = t;
         codeBlock = t->right;
         breakEncountered = false;
         condVar = expression(testCondition);
         conditionTrue = !condVar.isRealAllZeros();
         context->enterLoop();
         while (conditionTrue && !breakEncountered)
         {
             block(codeBlock);
             if (state == NLS_STATE_RETURN ||
                     state == NLS_STATE_ABORT ||
                     state == NLS_STATE_QUIT)
             {
                 break;
             }
             if (state == NLS_STATE_CONTINUE)
             {
                 resetState();
             }
             breakEncountered = (state == NLS_STATE_BREAK);
             if (!breakEncountered)
             {
                 condVar = expression(testCondition);
                 conditionTrue = !condVar.isRealAllZeros();
             }
             else
             {
                 resetState();
             }
         }
         context->exitLoop();
         popID();
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/interpreter/src/include/Evaluator.hpp
F:/Developpements/GitHub/nelson/modules/interpreter/src/cpp/Evaluator.cpp