var annotated_dup =
[
    [ "Nelson", "namespace_nelson.html", "namespace_nelson" ],
    [ "abuf", "structabuf.html", "structabuf" ],
    [ "BasicTerminal", "class_basic_terminal.html", "class_basic_terminal" ],
    [ "BsdTerminal", "class_bsd_terminal.html", "class_bsd_terminal" ],
    [ "dlmOptions", "structdlm_options.html", "structdlm_options" ],
    [ "footnote_item", "structfootnote__item.html", "structfootnote__item" ],
    [ "footnote_list", "structfootnote__list.html", "structfootnote__list" ],
    [ "footnote_ref", "structfootnote__ref.html", "structfootnote__ref" ],
    [ "GuiTerminal", "class_gui_terminal.html", "class_gui_terminal" ],
    [ "hoedown_buffer", "structhoedown__buffer.html", "structhoedown__buffer" ],
    [ "hoedown_document", "structhoedown__document.html", "structhoedown__document" ],
    [ "hoedown_html_renderer_state", "structhoedown__html__renderer__state.html", "structhoedown__html__renderer__state" ],
    [ "hoedown_renderer", "structhoedown__renderer.html", "structhoedown__renderer" ],
    [ "hoedown_renderer_data", "structhoedown__renderer__data.html", "structhoedown__renderer__data" ],
    [ "hoedown_stack", "structhoedown__stack.html", "structhoedown__stack" ],
    [ "LineManager", "class_line_manager.html", "class_line_manager" ],
    [ "linenoiseCompletions", "structlinenoise_completions.html", "structlinenoise_completions" ],
    [ "linenoiseState", "structlinenoise_state.html", "structlinenoise_state" ],
    [ "link_ref", "structlink__ref.html", "structlink__ref" ],
    [ "module", "structmodule.html", "structmodule" ],
    [ "nelsonObject", "classnelson_object.html", "classnelson_object" ],
    [ "option_data", "structoption__data.html", "structoption__data" ],
    [ "qt_meta_stringdata_nelsonObject_t", "structqt__meta__stringdata__nelson_object__t.html", "structqt__meta__stringdata__nelson_object__t" ],
    [ "qt_meta_stringdata_QtMainWindow_t", "structqt__meta__stringdata___qt_main_window__t.html", "structqt__meta__stringdata___qt_main_window__t" ],
    [ "qt_meta_stringdata_QtTerminal_t", "structqt__meta__stringdata___qt_terminal__t.html", "structqt__meta__stringdata___qt_terminal__t" ],
    [ "QtMainWindow", "class_qt_main_window.html", "class_qt_main_window" ],
    [ "QtTerminal", "class_qt_terminal.html", "class_qt_terminal" ],
    [ "smartypants_data", "structsmartypants__data.html", "structsmartypants__data" ],
    [ "WindowsConsole", "class_windows_console.html", "class_windows_console" ],
    [ "yyalloc", "unionyyalloc.html", "unionyyalloc" ]
];