var dir_316f5fb7b98ff7a818e13fa8232c0a7d = [
  ["cdBuiltin.hpp", "cd_builtin_8hpp_source.html", null],
  ["copyfileBuiltin.hpp", "copyfile_builtin_8hpp_source.html", null],
  ["diff_fileBuiltin.hpp", "diff__file_builtin_8hpp_source.html", null],
  ["dirBuiltin.hpp", "dir_builtin_8hpp_source.html", null],
  ["filepartsBuiltin.hpp", "fileparts_builtin_8hpp_source.html", null],
  ["filesepBuiltin.hpp", "filesep_builtin_8hpp_source.html", null],
  ["isdirBuiltin.hpp", "isdir_builtin_8hpp_source.html", null],
  ["isfileBuiltin.hpp", "isfile_builtin_8hpp_source.html", null],
  ["mkdirBuiltin.hpp", "mkdir_builtin_8hpp_source.html", null],
  [
    "nlsFiles_folders_functions_builtin_exports.h",
    "nls_files__folders__functions__builtin__exports_8h_source.html",
    null,
  ],
  ["pathsepBuiltin.hpp", "pathsep_builtin_8hpp_source.html", null],
  ["pwdBuiltin.hpp", "pwd_builtin_8hpp_source.html", null],
  ["relativepathBuiltin.hpp", "relativepath_builtin_8hpp_source.html", null],
  ["rmdirBuiltin.hpp", "rmdir_builtin_8hpp_source.html", null],
  ["rmfileBuiltin.hpp", "rmfile_builtin_8hpp_source.html", null],
  ["tempdirBuiltin.hpp", "tempdir_builtin_8hpp_source.html", null],
  ["userdirBuiltin.hpp", "userdir_builtin_8hpp_source.html", null],
];
