var dir_ef5908e05f06bc199b981de924b124d4 = [
  ["HeadComments.hpp", "_head_comments_8hpp_source.html", null],
  ["HtmlTags.hpp", "_html_tags_8hpp_source.html", null],
  [
    "HtmlToPdf.hpp",
    "help__tools_2src_2include_2_html_to_pdf_8hpp_source.html",
    null,
  ],
  ["ImageTagHelpers.hpp", "_image_tag_helpers_8hpp_source.html", null],
  ["Markdown.hpp", "_markdown_8hpp_source.html", null],
  ["nlsHelp_tools_exports.h", "nls_help__tools__exports_8h_source.html", null],
  ["QtHelpProject.hpp", "_qt_help_project_8hpp_source.html", null],
  ["XmlDocAuthorItem.hpp", "_xml_doc_author_item_8hpp_source.html", null],
  ["XmlDocAuthors.hpp", "_xml_doc_authors_8hpp_source.html", null],
  [
    "XmlDocBibliographyItem.hpp",
    "_xml_doc_bibliography_item_8hpp_source.html",
    null,
  ],
  [
    "XmlDocChapterDescriptionItem.hpp",
    "_xml_doc_chapter_description_item_8hpp_source.html",
    null,
  ],
  [
    "XmlDocChapterIndexItem.hpp",
    "_xml_doc_chapter_index_item_8hpp_source.html",
    null,
  ],
  ["XmlDocChapterItem.hpp", "_xml_doc_chapter_item_8hpp_source.html", null],
  ["XmlDocChapterNamer.hpp", "_xml_doc_chapter_namer_8hpp_source.html", null],
  [
    "XmlDocChapterRefItem.hpp",
    "_xml_doc_chapter_ref_item_8hpp_source.html",
    null,
  ],
  [
    "XmlDocCheckIfLinkExists.hpp",
    "_xml_doc_check_if_link_exists_8hpp_source.html",
    null,
  ],
  ["XmlDocCopyrightItem.hpp", "_xml_doc_copyright_item_8hpp_source.html", null],
  [
    "XmlDocDescriptionItem.hpp",
    "_xml_doc_description_item_8hpp_source.html",
    null,
  ],
  ["XmlDocDirectory.hpp", "_xml_doc_directory_8hpp_source.html", null],
  ["XmlDocDocument.hpp", "_xml_doc_document_8hpp_source.html", null],
  ["XmlDocExampleItem.hpp", "_xml_doc_example_item_8hpp_source.html", null],
  ["XmlDocExamples.hpp", "_xml_doc_examples_8hpp_source.html", null],
  ["XmlDocGenericItem.hpp", "_xml_doc_generic_item_8hpp_source.html", null],
  ["XmlDocHistory.hpp", "_xml_doc_history_8hpp_source.html", null],
  ["XmlDocHistoryItem.hpp", "_xml_doc_history_item_8hpp_source.html", null],
  ["XmlDocImageItem.hpp", "_xml_doc_image_item_8hpp_source.html", null],
  ["XmlDocKeywordItem.hpp", "_xml_doc_keyword_item_8hpp_source.html", null],
  ["XmlDocLanguageItem.hpp", "_xml_doc_language_item_8hpp_source.html", null],
  ["XmlDocLinkItem.hpp", "_xml_doc_link_item_8hpp_source.html", null],
  [
    "XmlDocListOfDirectories.hpp",
    "_xml_doc_list_of_directories_8hpp_source.html",
    null,
  ],
  ["XmlDocListOfFiles.hpp", "_xml_doc_list_of_files_8hpp_source.html", null],
  ["XmlDocMainIndex.hpp", "_xml_doc_main_index_8hpp_source.html", null],
  [
    "XmlDocModuleNameItem.hpp",
    "_xml_doc_module_name_item_8hpp_source.html",
    null,
  ],
  ["XmlDocParamInput.hpp", "_xml_doc_param_input_8hpp_source.html", null],
  [
    "XmlDocParamInputItem.hpp",
    "_xml_doc_param_input_item_8hpp_source.html",
    null,
  ],
  ["XmlDocParamOutput.hpp", "_xml_doc_param_output_8hpp_source.html", null],
  [
    "XmlDocParamOutputItem.hpp",
    "_xml_doc_param_output_item_8hpp_source.html",
    null,
  ],
  ["XmlDocResolveLink.hpp", "_xml_doc_resolve_link_8hpp_source.html", null],
  ["XmlDocSeeAlso.hpp", "_xml_doc_see_also_8hpp_source.html", null],
  ["XmlDocSeeAlsoItem.hpp", "_xml_doc_see_also_item_8hpp_source.html", null],
  [
    "XmlDocShortDescriptionItem.hpp",
    "_xml_doc_short_description_item_8hpp_source.html",
    null,
  ],
  ["XmlDocSyntax.hpp", "_xml_doc_syntax_8hpp_source.html", null],
  ["XmlDocSyntaxItem.hpp", "_xml_doc_syntax_item_8hpp_source.html", null],
  ["XmlDocTitleItem.hpp", "_xml_doc_title_item_8hpp_source.html", null],
  ["XmlDocumentTags.hpp", "_xml_document_tags_8hpp_source.html", null],
  [
    "XmlDocUsedFunctionItem.hpp",
    "_xml_doc_used_function_item_8hpp_source.html",
    null,
  ],
  ["XmlHelpers.hpp", "_xml_helpers_8hpp_source.html", null],
];
