var dir_87350b19f7eb4489183678a482bcfb25 = [
  ["HorzCatString.hpp", "_horz_cat_string_8hpp_source.html", null],
  ["IntegerToString.hpp", "_integer_to_string_8hpp_source.html", null],
  ["MatrixToString.hpp", "_matrix_to_string_8hpp_source.html", null],
  ["nlsString_exports.h", "nls_string__exports_8h_source.html", null],
  ["StringCompare.hpp", "_string_compare_8hpp_source.html", null],
  ["StringDisplay.hpp", "_string_display_8hpp_source.html", null],
  ["StringFind.hpp", "_string_find_8hpp_source.html", null],
  ["StringFormat.hpp", "_string_format_8hpp_source.html", null],
  ["StringIsEqual.hpp", "_string_is_equal_8hpp_source.html", null],
  ["StringPrintf.hpp", "_string_printf_8hpp_source.html", null],
  ["StringToDouble.hpp", "_string_to_double_8hpp_source.html", null],
  [
    "StringToDoubleComplex.hpp",
    "_string_to_double_complex_8hpp_source.html",
    null,
  ],
  ["ToChar.hpp", "_to_char_8hpp_source.html", null],
  ["ToLower.hpp", "_to_lower_8hpp_source.html", null],
  ["ToUpper.hpp", "_to_upper_8hpp_source.html", null],
  ["VertCatString.hpp", "_vert_cat_string_8hpp_source.html", null],
];
