var dir_62f0981559e712ac115b32b912ec774c = [
  ["ArrayOf.hpp", "_array_of_8hpp_source.html", null],
  ["ClassName.hpp", "_class_name_8hpp_source.html", null],
  ["Data.hpp", "_data_8hpp_source.html", null],
  ["Dimensions.hpp", "_dimensions_8hpp_source.html", null],
  ["HandleGenericObject.hpp", "_handle_generic_object_8hpp_source.html", null],
  ["HandleManager.hpp", "_handle_manager_8hpp_source.html", null],
  ["IsValidFieldname.hpp", "_is_valid_fieldname_8hpp_source.html", null],
  ["IsValidVariableName.hpp", "_is_valid_variable_name_8hpp_source.html", null],
  ["MakeValidFieldname.hpp", "_make_valid_fieldname_8hpp_source.html", null],
  ["nlsConfig.h", "nls_config_8h_source.html", null],
  ["nlsMath.h", "nls_math_8h_source.html", null],
  ["nlsTypes_exports.h", "nls_types__exports_8h_source.html", null],
  [
    "SparseDynamicFunctions.hpp",
    "_sparse_dynamic_functions_8hpp_source.html",
    null,
  ],
  ["StringToClass.hpp", "_string_to_class_8hpp_source.html", null],
  ["Types.hpp", "_types_8hpp_source.html", null],
];
