var hierarchy =
[
    [ "abuf", "structabuf.html", null ],
    [ "Addrblock", "struct_addrblock.html", null ],
    [ "Akind", "struct_akind.html", null ],
    [ "alist", "structalist.html", null ],
    [ "arg_info", "structarg__info.html", null ],
    [ "Argtypes", "struct_argtypes.html", null ],
    [ "Nelson::ArrayOf", "class_nelson_1_1_array_of.html", null ],
    [ "Nelson::AST", "class_nelson_1_1_a_s_t.html", null ],
    [ "Atype", "struct_atype.html", null ],
    [ "Nelson::BuiltInFunctionDefManager", "class_nelson_1_1_built_in_function_def_manager.html", null ],
    [ "Nelson::Calendar", "class_nelson_1_1_calendar.html", null ],
    [ "Chain", "struct_chain.html", null ],
    [ "cilist", "structcilist.html", null ],
    [ "cllist", "structcllist.html", null ],
    [ "Nelson::ComEngine", "class_nelson_1_1_com_engine.html", null ],
    [ "Nelson::CommandQueue", "class_nelson_1_1_command_queue.html", null ],
    [ "comment_buf", "structcomment__buf.html", null ],
    [ "complex", "structcomplex.html", null ],
    [ "Constant", "union_constant.html", null ],
    [ "Constblock", "struct_constblock.html", null ],
    [ "Nelson::Context", "class_nelson_1_1_context.html", null ],
    [ "Nelson::contextOrPointer", "union_nelson_1_1context_or_pointer.html", null ],
    [ "Ctlframe", "struct_ctlframe.html", null ],
    [ "Nelson::Data", "class_nelson_1_1_data.html", null ],
    [ "dcomplex", "structdcomplex.html", null ],
    [ "defines", "structdefines.html", null ],
    [ "Nelson::Diary", "class_nelson_1_1_diary.html", null ],
    [ "Dimblock", "struct_dimblock.html", null ],
    [ "dimen", "structdimen.html", null ],
    [ "Nelson::Dimensions", "class_nelson_1_1_dimensions.html", null ],
    [ "Dims", "struct_dims.html", null ],
    [ "dL", "uniond_l.html", null ],
    [ "dlmOptions", "structdlm_options.html", null ],
    [ "Dotlist", "struct_dotlist.html", null ],
    [ "doublecomplex", "structdoublecomplex.html", null ],
    [ "Nelson::endData", "class_nelson_1_1end_data.html", null ],
    [ "Entrypoint", "struct_entrypoint.html", null ],
    [ "Equivblock", "struct_equivblock.html", null ],
    [ "Eqvchain", "struct_eqvchain.html", null ],
    [ "Errorblock", "struct_errorblock.html", null ],
    [ "Nelson::ErrorInfo", "class_nelson_1_1_error_info.html", null ],
    [ "Nelson::Evaluator", "class_nelson_1_1_evaluator.html", null ],
    [ "Nelson::Exception", "class_nelson_1_1_exception.html", null ],
    [ "Exprblock", "struct_exprblock.html", null ],
    [ "Expression", "union_expression.html", null ],
    [ "Extsym", "struct_extsym.html", null ],
    [ "Nelson::File", "class_nelson_1_1_file.html", null ],
    [ "Nelson::FileFunc", "class_nelson_1_1_file_func.html", null ],
    [ "Nelson::FileInfo", "class_nelson_1_1_file_info.html", null ],
    [ "Nelson::FilesManager", "class_nelson_1_1_files_manager.html", null ],
    [ "Nelson::FileWatcherManager", "class_nelson_1_1_file_watcher_manager.html", null ],
    [ "FileWatchListener", null, [
      [ "Nelson::UpdatePathListener", "class_nelson_1_1_update_path_listener.html", null ]
    ] ],
    [ "flex", "unionflex.html", null ],
    [ "Fmtlist", "struct_fmtlist.html", null ],
    [ "footnote_item", "structfootnote__item.html", null ],
    [ "footnote_list", "structfootnote__list.html", null ],
    [ "footnote_ref", "structfootnote__ref.html", null ],
    [ "Nelson::FunctionDef", "class_nelson_1_1_function_def.html", [
      [ "Nelson::BuiltInFunctionDef", "class_nelson_1_1_built_in_function_def.html", null ],
      [ "Nelson::MacroFunctionDef", "class_nelson_1_1_macro_function_def.html", null ]
    ] ],
    [ "Nelson::HandleGenericObject", "class_nelson_1_1_handle_generic_object.html", [
      [ "Nelson::ComHandleObject", "class_nelson_1_1_com_handle_object.html", null ],
      [ "Nelson::MPI_CommHandleObject", "class_nelson_1_1_m_p_i___comm_handle_object.html", null ],
      [ "Nelson::QmlHandleObject", "class_nelson_1_1_qml_handle_object.html", null ]
    ] ],
    [ "Nelson::HandleManager", "class_nelson_1_1_handle_manager.html", null ],
    [ "hashentry", "structhashentry.html", null ],
    [ "Hashentry", "struct_hashentry.html", null ],
    [ "hashtab", "structhashtab.html", null ],
    [ "Headblock", "struct_headblock.html", null ],
    [ "Nelson::HelpBrowser", "class_nelson_1_1_help_browser.html", null ],
    [ "Nelson::HistoryManager", "class_nelson_1_1_history_manager.html", null ],
    [ "hoedown_buffer", "structhoedown__buffer.html", null ],
    [ "hoedown_document", "structhoedown__document.html", null ],
    [ "hoedown_html_renderer_state", "structhoedown__html__renderer__state.html", null ],
    [ "hoedown_renderer", "structhoedown__renderer.html", null ],
    [ "hoedown_renderer_data", "structhoedown__renderer__data.html", null ],
    [ "hoedown_stack", "structhoedown__stack.html", null ],
    [ "icilist", "structicilist.html", null ],
    [ "Impldoblock", "struct_impldoblock.html", null ],
    [ "Inclfile", "struct_inclfile.html", null ],
    [ "inlist", "structinlist.html", null ],
    [ "Nelson::Interface", "class_nelson_1_1_interface.html", [
      [ "BasicTerminal", "class_basic_terminal.html", null ],
      [ "BsdTerminal", "class_bsd_terminal.html", null ],
      [ "GuiTerminal", "class_gui_terminal.html", null ],
      [ "WindowsConsole", "class_windows_console.html", null ]
    ] ],
    [ "Intrbits", "struct_intrbits.html", null ],
    [ "Intrblock", "struct_intrblock.html", null ],
    [ "Intrpacked", "struct_intrpacked.html", null ],
    [ "io_setup", "structio__setup.html", null ],
    [ "iob_data", "structiob__data.html", null ],
    [ "Ioclist", "struct_ioclist.html", null ],
    [ "Keylist", "struct_keylist.html", null ],
    [ "Nelson::keywordStruct", "struct_nelson_1_1keyword_struct.html", null ],
    [ "Labelblock", "struct_labelblock.html", null ],
    [ "LineManager", "class_line_manager.html", null ],
    [ "linenoiseCompletions", "structlinenoise_completions.html", null ],
    [ "linenoiseState", "structlinenoise_state.html", null ],
    [ "link_ref", "structlink__ref.html", null ],
    [ "Listblock", "struct_listblock.html", null ],
    [ "Literal", "struct_literal.html", null ],
    [ "Nelson::LocalFunctionsTable", "class_nelson_1_1_local_functions_table.html", null ],
    [ "Nelson::Localization", "class_nelson_1_1_localization.html", null ],
    [ "memblock", "structmemblock.html", null ],
    [ "module", "structmodule.html", null ],
    [ "Nelson::ModulesManager", "class_nelson_1_1_modules_manager.html", null ],
    [ "Nelson::MPI_CommObject", "class_nelson_1_1_m_p_i___comm_object.html", null ],
    [ "Multitype", "union_multitype.html", null ],
    [ "Nameblock", "struct_nameblock.html", null ],
    [ "Namelist", "struct_namelist.html", null ],
    [ "Nelson::nlsGatewayStructType", "struct_nelson_1_1nls_gateway_struct_type.html", null ],
    [ "olist", "structolist.html", null ],
    [ "Nelson::Option", "class_nelson_1_1_option.html", null ],
    [ "option_data", "structoption__data.html", null ],
    [ "Paramblock", "struct_paramblock.html", null ],
    [ "Nelson::ParseRHS", "struct_nelson_1_1_parse_r_h_s.html", null ],
    [ "Nelson::PathFunc", "class_nelson_1_1_path_func.html", null ],
    [ "Nelson::PathFuncManager", "class_nelson_1_1_path_func_manager.html", null ],
    [ "Primblock", "struct_primblock.html", null ],
    [ "Nelson::ProgramOptions", "class_nelson_1_1_program_options.html", null ],
    [ "Punctlist", "struct_punctlist.html", null ],
    [ "QMainWindow", null, [
      [ "QtMainWindow", "class_qt_main_window.html", null ],
      [ "QtTextEditor", "class_qt_text_editor.html", null ]
    ] ],
    [ "Nelson::QmlEngine", "class_nelson_1_1_qml_engine.html", null ],
    [ "QObject", null, [
      [ "nelsonObject", "classnelson_object.html", null ],
      [ "QtTextIndent", "class_qt_text_indent.html", null ]
    ] ],
    [ "QSyntaxHighlighter", null, [
      [ "Highlighter", "class_highlighter.html", null ]
    ] ],
    [ "qt_meta_stringdata_Highlighter_t", "structqt__meta__stringdata___highlighter__t.html", null ],
    [ "qt_meta_stringdata_nelsonObject_t", "structqt__meta__stringdata__nelson_object__t.html", null ],
    [ "qt_meta_stringdata_QtEditPane_t", "structqt__meta__stringdata___qt_edit_pane__t.html", null ],
    [ "qt_meta_stringdata_QtLineNumber_t", "structqt__meta__stringdata___qt_line_number__t.html", null ],
    [ "qt_meta_stringdata_QtMainWindow_t", "structqt__meta__stringdata___qt_main_window__t.html", null ],
    [ "qt_meta_stringdata_QtTerminal_t", "structqt__meta__stringdata___qt_terminal__t.html", null ],
    [ "qt_meta_stringdata_QtTextEdit_t", "structqt__meta__stringdata___qt_text_edit__t.html", null ],
    [ "qt_meta_stringdata_QtTextEditor_t", "structqt__meta__stringdata___qt_text_editor__t.html", null ],
    [ "qt_meta_stringdata_QtTextIndent_t", "structqt__meta__stringdata___qt_text_indent__t.html", null ],
    [ "QTextBrowser", null, [
      [ "QtTerminal", "class_qt_terminal.html", null ]
    ] ],
    [ "QTextEdit", null, [
      [ "QtTextEdit", "class_qt_text_edit.html", null ]
    ] ],
    [ "Nelson::QtHelpProject", "class_nelson_1_1_qt_help_project.html", null ],
    [ "QWidget", null, [
      [ "QtEditPane", "class_qt_edit_pane.html", null ],
      [ "QtLineNumber", "class_qt_line_number.html", null ]
    ] ],
    [ "Nelson::RandomInterface", "class_nelson_1_1_random_interface.html", [
      [ "Nelson::RandomLaggedFibonacci607", "class_nelson_1_1_random_lagged_fibonacci607.html", null ],
      [ "Nelson::RandomMersenneTwister", "class_nelson_1_1_random_mersenne_twister.html", null ],
      [ "Nelson::RandomMersenneTwister64", "class_nelson_1_1_random_mersenne_twister64.html", null ]
    ] ],
    [ "Rplblock", "struct_rplblock.html", null ],
    [ "Nelson::Scope", "class_nelson_1_1_scope.html", null ],
    [ "Nelson::ScopeStack", "struct_nelson_1_1_scope_stack.html", null ],
    [ "Nelson::Serialize", "class_nelson_1_1_serialize.html", null ],
    [ "smartypants_data", "structsmartypants__data.html", null ],
    [ "Specblock", "struct_specblock.html", null ],
    [ "Nelson::StackEntry", "class_nelson_1_1_stack_entry.html", null ],
    [ "Nelson::Stream", "class_nelson_1_1_stream.html", [
      [ "Nelson::FileStream", "class_nelson_1_1_file_stream.html", null ]
    ] ],
    [ "syl", "structsyl.html", null ],
    [ "Nelson::SymbolTable< T >", "class_nelson_1_1_symbol_table.html", null ],
    [ "table_entry", "structtable__entry.html", null ],
    [ "Nelson::TestTags", "class_nelson_1_1_test_tags.html", null ],
    [ "ufloat", "unionufloat.html", null ],
    [ "Uint", "union_uint.html", null ],
    [ "unit", "structunit.html", null ],
    [ "Vardesc", "struct_vardesc.html", null ],
    [ "Nelson::VariablesTable", "class_nelson_1_1_variables_table.html", null ],
    [ "Nelson::XmlDocDirectory", "class_nelson_1_1_xml_doc_directory.html", null ],
    [ "Nelson::XmlDocDocument", "class_nelson_1_1_xml_doc_document.html", null ],
    [ "Nelson::XmlDocGenericItem", "class_nelson_1_1_xml_doc_generic_item.html", [
      [ "Nelson::XmlDocAuthorItem", "class_nelson_1_1_xml_doc_author_item.html", null ],
      [ "Nelson::XmlDocAuthors", "class_nelson_1_1_xml_doc_authors.html", null ],
      [ "Nelson::XmlDocBibliographyItem", "class_nelson_1_1_xml_doc_bibliography_item.html", null ],
      [ "Nelson::XmlDocChapterDescriptionItem", "class_nelson_1_1_xml_doc_chapter_description_item.html", null ],
      [ "Nelson::XmlDocChapterIndexItem", "class_nelson_1_1_xml_doc_chapter_index_item.html", null ],
      [ "Nelson::XmlDocChapterItem", "class_nelson_1_1_xml_doc_chapter_item.html", null ],
      [ "Nelson::XmlDocChapterRefItem", "class_nelson_1_1_xml_doc_chapter_ref_item.html", null ],
      [ "Nelson::XmlDocCopyrightItem", "class_nelson_1_1_xml_doc_copyright_item.html", null ],
      [ "Nelson::XmlDocDescriptionItem", "class_nelson_1_1_xml_doc_description_item.html", null ],
      [ "Nelson::XmlDocExampleItem", "class_nelson_1_1_xml_doc_example_item.html", null ],
      [ "Nelson::XmlDocExamples", "class_nelson_1_1_xml_doc_examples.html", null ],
      [ "Nelson::XmlDocHistory", "class_nelson_1_1_xml_doc_history.html", null ],
      [ "Nelson::XmlDocHistoryItem", "class_nelson_1_1_xml_doc_history_item.html", null ],
      [ "Nelson::XmlDocImageItem", "class_nelson_1_1_xml_doc_image_item.html", null ],
      [ "Nelson::XmlDocKeywordItem", "class_nelson_1_1_xml_doc_keyword_item.html", null ],
      [ "Nelson::XmlDocLanguageItem", "class_nelson_1_1_xml_doc_language_item.html", null ],
      [ "Nelson::XmlDocLinkItem", "class_nelson_1_1_xml_doc_link_item.html", null ],
      [ "Nelson::XmlDocModuleNameItem", "class_nelson_1_1_xml_doc_module_name_item.html", null ],
      [ "Nelson::XmlDocParamInput", "class_nelson_1_1_xml_doc_param_input.html", null ],
      [ "Nelson::XmlDocParamInputItem", "class_nelson_1_1_xml_doc_param_input_item.html", null ],
      [ "Nelson::XmlDocParamOutput", "class_nelson_1_1_xml_doc_param_output.html", null ],
      [ "Nelson::XmlDocParamOutputItem", "class_nelson_1_1_xml_doc_param_output_item.html", null ],
      [ "Nelson::XmlDocSeeAlso", "class_nelson_1_1_xml_doc_see_also.html", null ],
      [ "Nelson::XmlDocSeeAlsoItem", "class_nelson_1_1_xml_doc_see_also_item.html", null ],
      [ "Nelson::XmlDocShortDescriptionItem", "class_nelson_1_1_xml_doc_short_description_item.html", null ],
      [ "Nelson::XmlDocSyntax", "class_nelson_1_1_xml_doc_syntax.html", null ],
      [ "Nelson::XmlDocSyntaxItem", "class_nelson_1_1_xml_doc_syntax_item.html", null ],
      [ "Nelson::XmlDocTitleItem", "class_nelson_1_1_xml_doc_title_item.html", null ],
      [ "Nelson::XmlDocUsedFunctionItem", "class_nelson_1_1_xml_doc_used_function_item.html", null ]
    ] ],
    [ "Nelson::XmlDocListOfDirectories", "class_nelson_1_1_xml_doc_list_of_directories.html", null ],
    [ "Nelson::XmlDocListOfFiles", "class_nelson_1_1_xml_doc_list_of_files.html", null ],
    [ "Nelson::XmlDocMainIndex", "class_nelson_1_1_xml_doc_main_index.html", null ],
    [ "yyalloc", "unionyyalloc.html", null ],
    [ "YYSTYPE", "union_y_y_s_t_y_p_e.html", null ]
];