Nelson: Nelson Namespace Reference
Nelson Namespace Reference
Classes
class ArrayOf
class AST
class BuiltInFunctionDef
class BuiltInFunctionDefManager
class Calendar
class CommandQueue
class Context
union contextOrPointer
class Data
class Diary
class Dimensions
class ErrorInfo
class Evaluator
class Exception
class File
class FileFunc
class FileInfo
class FilesManager
class FileStream
class FileWatcherManager
class FunctionDef
class HelpBrowser
class HistoryManager
class Interface
struct keywordStruct
class LocalFunctionsTable
class Localization
class MacroFunctionDef
class ModulesManager
struct nlsGatewayStructType
class Option
struct ParseRHS
class PathFunc
class PathFuncManager
class ProgramOptions
class QtHelpProject
class RandomInterface
class RandomLaggedFibonacci607
class RandomMersenneTwister
class RandomMersenneTwister64
class Scope
struct ScopeStack
class Serialize
class StackEntry
class Stream
class SymbolTable
class TestTags
class UpdatePathListener
class VariablesTable
class XmlDocAuthorItem
class XmlDocAuthors
class XmlDocBibliographyItem
class XmlDocChapterDescriptionItem
class XmlDocChapterIndexItem
class XmlDocChapterItem
class XmlDocChapterRefItem
class XmlDocCopyrightItem
class XmlDocDescriptionItem
class XmlDocDirectory
class XmlDocDocument
class XmlDocExampleItem
class XmlDocExamples
class XmlDocGenericItem
class XmlDocHistory
class XmlDocHistoryItem
class XmlDocImageItem
class XmlDocKeywordItem
class XmlDocLanguageItem
class XmlDocLinkItem
class XmlDocListOfDirectories
class XmlDocListOfFiles
class XmlDocMainIndex
class XmlDocModuleNameItem
class XmlDocParamInput
class XmlDocParamInputItem
class XmlDocParamOutput
class XmlDocParamOutputItem
class XmlDocSeeAlso
class XmlDocSeeAlsoItem
class XmlDocShortDescriptionItem
class XmlDocSyntax
class XmlDocSyntaxItem
class XmlDocTitleItem
class XmlDocUsedFunctionItem
Typedefs
typedef void * library_handle
typedef void * generic_function_ptr
typedef void(* vvfun) (indexType length, void *result, const void *arg1, const int stride1, const void *arg2, const int stride2)
typedef AST * ASTPtr
typedef boost::container::vector< ASTPtr > ASTPtrVector
typedef ArrayOfVector APtr
typedef APtr(* BuiltInFuncPtr) (Evaluator *, int, const APtr &)
typedef FunctionDef * FuncPtr
typedef struct Nelson::nlsGatewayStructType nlsGateway
typedef std::set< uint32, std::less< uint32 > > intSet
typedef boost::container::vector< ArrayOf > ArrayOfVector
typedef boost::container::vector< ArrayOfVector > ArrayOfMatrix
typedef int sizeType
typedef int signedIndexType
typedef int indexType
typedef uint8_t logical
typedef int8_t int8
typedef uint8_t uint8
typedef int16_t int16
typedef uint16_t uint16
typedef int32_t int32
typedef uint32_t uint32
typedef int64_t int64
typedef uint64_t uint64
typedef wchar_t charType
typedef float single
typedef const indexType * constIndexPtr
typedef size_t function_handle
typedef long nelson_handle
typedef boost::container::vector< std::string > stringVector
typedef boost::container::vector< std::wstring > wstringVector
Enumerations
enum HEADCOMMENTS_ERROR { NO_ERROR, NOT_A_MACRO, FILE_NOT_EXIST }
enum XMLDOC_ITEMS_ID {
ERROR_ID = -1, XML_COMMENT_TAG_ID = 0, XMLDOC_TAG_ID, LANGUAGE_TAG_ID,
TITLE_TAG_ID, KEYWORD_TAG_ID, SHORT_DESCRIPTION_TAG_ID, COPYRIGHT_TAG_ID,
SYNTAX_TAG_ID, PARAM_INPUT_TAG_ID, PARAM_OUTPUT_TAG_ID, DESCRIPTION_TAG_ID,
USED_FUNCTION_TAG_ID, BIBLIOGRAPHY_TAG_ID, EXAMPLES_TAG_ID, SEE_ALSO_TAG_ID,
HISTORY_TAG_ID, AUTHORS_TAG_ID, CHAPTER_TAG_ID, CHAPTER_DESCRIPTION_TAG_ID,
CHAPTER_INDEX_TAG_ID, MODULE_NAME_TAG_ID, IMAGE_TAG_ID
}
enum NODE_TYPE {
non_terminal, id_node, const_int_node, const_double_node,
const_float_node, string_const_node, null_node, reserved_node,
const_dcomplex_node, const_complex_node, const_uint64_node
}
enum OP_TYPE {
OP_BLOCK, OP_CASEBLOCK, OP_RHS, OP_CSTAT,
OP_ELSEIFBLOCK, OP_ASSIGN, OP_MULTICALL, OP_COLON,
OP_PLUS, OP_SUBTRACT, OP_TIMES, OP_RDIV,
OP_LDIV, OP_OR, OP_AND, OP_SOR,
OP_SAND, OP_LT, OP_LEQ, OP_GT,
OP_GEQ, OP_EQ, OP_NEQ, OP_DOT_TIMES,
OP_DOT_RDIV, OP_DOT_LDIV, OP_NEG, OP_POS,
OP_NOT, OP_POWER, OP_DOT_POWER, OP_TRANSPOSE,
OP_DOT_TRANSPOSE, OP_EMPTY, OP_EMPTY_CELL, OP_PARENS,
OP_BRACES, OP_BRACKETS, OP_DOT, OP_ALL,
OP_INDEX_LIST, OP_ROW_DEF, OP_SEMICOLON, OP_NULL,
OP_RSTATEMENT, OP_QSTATEMENT, OP_SCALL, OP_CCALL,
OP_SAVE, OP_LOAD, OP_KEYWORD, OP_DOTDYN
}
enum SCOPE_LEVEL { GLOBAL_SCOPE, BASE_SCOPE, CALLER_SCOPE, LOCAL_SCOPE }
enum OutputFormatDisplay {
NLS_FORMAT_SHORT, NLS_FORMAT_LONG, NLS_FORMAT_SHORTE, NLS_FORMAT_LONGE,
NLS_FORMAT_HEX
}
enum State {
NLS_STATE_OK = 0, NLS_STATE_BREAK = 1, NLS_STATE_CONTINUE = 2, NLS_STATE_RETURN = 3,
NLS_STATE_QUIT = 4, NLS_STATE_ABORT = 5
}
enum FunctionType { NLS_MACRO_FUNCTION, NLS_BUILT_IN_FUNCTION }
enum ParserState { ScriptBlock, FuncDef, ParseError }
enum MODULEPATH_OPTION {
GET_BINARY_PATH, GET_ROOT_PATH, GET_ETC_PATH, GET_DYNLIB_FULLPATH,
GET_SCRIPT_PATH
}
enum OVERLOAD_TYPE { FUNCTION = 0, UNARY, BINARY, TRINARY }
enum RNG_DISTRIBUTION_TYPE { RNG_DISTRIBUTION_ERROR = -1, RNG_DISTRIBUTION_UNIFORM_REAL = 0, RNG_DISTRIBUTION_UNIFORM_INT, RNG_DISTRIBUTION_NORMAL }
enum RNG_TYPE { RNG_ERROR = -1, RNG_TWISTER = 0, RNG_TWISTER64, RNG_LAGGED_FIBONACCI_607 }
enum FOPEN_ERROR_TYPE {
FOPEN_NO_ERROR, FOPEN_INVALID_NAME, FOPEN_INVALID_MODE, FOPEN_IMPOSSIBLE_TO_ADD_FILE,
FOPEN_CANNOT_OPEN
}
enum FWRITE_ERROR_TYPE {
FWRITE_NO_ERROR, FWRITE_DATA_TYPE_NOT_SUPPORTED, FWRITE_FILE_DESTINATION_NOT_SUPPORTED, FWRITE_ALLOCATION_MEMORY,
FWRITE_INVALID_FILE, FWRITE_ENDIAN_CONVERSION_NOT_SUPPORTED
}
enum Class {
NLS_HANDLE, NLS_CELL_ARRAY, NLS_STRUCT_ARRAY, NLS_LOGICAL,
NLS_UINT8, NLS_INT8, NLS_UINT16, NLS_INT16,
NLS_UINT32, NLS_INT32, NLS_UINT64, NLS_INT64,
NLS_SINGLE, NLS_DOUBLE, NLS_SCOMPLEX, NLS_DCOMPLEX,
NLS_STRING
}
Functions
void CheckNumeric (ArrayOf &A, ArrayOf &B, std::string opname) throw (Exception)
bool MatrixCheck (ArrayOf &A, ArrayOf &B, std::string opname) throw (Exception)
void TypeCheck (ArrayOf &A, ArrayOf &B, bool isDivOrMatrix)
bool SameSizeCheck (Dimensions Adim, Dimensions Bdim)
void VectorCheck (ArrayOf &A, ArrayOf &B, bool promote, std::string opname) throw (Exception)
void BoolVectorCheck (ArrayOf &A, ArrayOf &B, std::string opname) throw (Exception)
ArrayOf ToCellStringAsRow (wstringVector vectorStr)
ArrayOf ToCellStringAsColumn (wstringVector vectorStr)
ArrayOf ToCellStringAsRow (stringVector vectorStr)
ArrayOf ToCellStringAsColumn (stringVector vectorStr)
bool Assert_CheckError (Evaluator *eval, std::wstring command, std::wstring expectedmsg, std::wstring &msg)
bool Assert_IsApprox (Evaluator *eval, ArrayOf computedArray, ArrayOf expectedArray, double precision, std::wstring &msg)
bool Assert_IsEqual (Evaluator *eval, ArrayOf computedArray, ArrayOf expectedArray, std::wstring &msg)
logical Assert_IsFalse (logical value, std::wstring modifiedmsg, std::wstring &msg)
logical Assert_IsTrue (logical value, std::wstring modifiedmsg, std::wstring &msg)
std::wstring utf8_to_wstring (const std::string &str)
std::string wstring_to_utf8 (const std::wstring &str)
std::wstring utf8_to_wstring (const char *str)
std::string wstring_to_utf8 (const wchar_t *str)
void ClearConsole (Evaluator *eval)
template<class T >
T nextafter (T x, T y)
double Epsilon (double X)
single Epsilon (single X)
ArrayOf Eye (indexType n, indexType m, Class classDest, bool bIsSparse)
ArrayOf Inf (void)
ArrayOf Inf (uint32 m, uint32 n)
ArrayOf NaN (void)
ArrayOf NaN (indexType m, indexType n)
ArrayOf Ones (Evaluator *eval, Class cl)
ArrayOf Ones (Evaluator *eval, Dimensions dims, Class cl)
ArrayOf Zeros (Evaluator *eval, Class cl)
ArrayOf Zeros (Evaluator *eval, Dimensions dims, Class cl)
void Banner (Evaluator *eval)
bool EvaluateCommand (Evaluator *eval, std::wstring command, bool bCatch)
bool EvaluateCommand (Evaluator *eval, std::string command, bool bCatch)
bool EvaluateScriptFile (Evaluator *eval, const wchar_t *filename, bool bChangeDirectory)
std::wstring GetCurrentNFilenameW (Evaluator *eval)
NLSCORE_IMPEXP std::string GetCurrentNFilenameU (Evaluator *eval)
std::wstring GetNelsonBinariesPath ()
std::string get_basepathU ()
ArrayOf GetRootFolder ()
std::wstring GetRootPath ()
std::wstring GetPreferencesPath ()
bool ComputePreferencesPath ()
bool IsEmptyScriptFile (std::wstring filename)
int NargIn (Evaluator *eval, std::wstring functionName)
int NargOut (Evaluator *eval, std::wstring functionName)
wstringVector VersionCompilerFlags ()
bool IsCellOfString (ArrayOf cellarr)
ArrayOf colon_double (ArrayOf a, ArrayOf b)
ArrayOf colon_double (ArrayOf a, ArrayOf b, ArrayOf c)
ArrayOf double_colon (double low, double high, double step)
std::wstring double2hexastr (double d)
void DoubleDisplay (Evaluator *eval, ArrayOf A)
bool double_isequal (ArrayOf a, ArrayOf b)
bool double_isequaln (ArrayOf a, ArrayOf b)
ArrayOf double_gt_double (ArrayOf a, ArrayOf b)
ArrayOf HorzCatDouble (ArrayOf A, ArrayOf B)
ArrayOf HorzCatNdArrayDouble (ArrayOf A, ArrayOf B)
ArrayOf double_le_double (ArrayOf a, ArrayOf b)
ArrayOf double_lt_double (ArrayOf a, ArrayOf b)
ArrayOf double_subtraction (ArrayOf a, ArrayOf b)
ArrayOf dcomplex_subtraction (ArrayOf a, ArrayOf b)
ArrayOf double_minus_double (ArrayOf a, ArrayOf b)
ArrayOf double_mtimes_double (ArrayOf a, ArrayOf b)
ArrayOf double_ne_double (ArrayOf a, ArrayOf b)
ArrayOf double_addition (ArrayOf a, ArrayOf b)
ArrayOf dcomplex_addition (ArrayOf a, ArrayOf b)
ArrayOf double_plus_double (ArrayOf a, ArrayOf b)
ArrayOf double_times_double (ArrayOf a, ArrayOf b)
template<class T >
ArrayOf ToDouble (ArrayOf A)
ArrayOf double_uminus (ArrayOf a)
ArrayOf VertCatDouble (ArrayOf A, ArrayOf B)
ArrayOf VertCatNdArrayDouble (ArrayOf A, ArrayOf B)
void AddGateway (Evaluator *eval, std::wstring dynlibname)
std::wstring FindDynamicLibraryName (std::wstring directoryName, std::wstring initialLibraryName, bool bCaseSensitive)
bool GatewayInfo (std::wstring dynlibname, std::wstring &moduleName, stringVector &functionsList, std::wstring &errorMessage)
void RemoveGateway (Evaluator *eval, std::wstring dynlibname)
library_handle load_dynamic_library (const char *library_name)
generic_function_ptr get_function (library_handle handle, const char *function_name)
bool close_shared_library (library_handle handle)
std::string get_dynamic_library_extension ()
std::string get_dynamic_library_error ()
void boolean_and (indexType N, logical *C, const logical *A, int Astride, const logical *B, int Bstride)
ArrayOf And (ArrayOf A, ArrayOf B)
template<class T >
void ComplexArrayArray (T *A, T *B, T *C, size_t len)
template<class T >
void ComplexScalarArray (T A, T *B, T *C, size_t len)
template<class T >
void ComplexArrayScalar (T *A, T B, T *C, size_t len)
ArrayOf ComplexConstructor (ArrayOf arrayA, ArrayOf arrayB)
ArrayOf ComplexConstructor (ArrayOf arrayA)
ArrayOf ConcatenateNdArray (ArrayOfMatrix &m, Class destClass)
ArrayOf DotLeftDivide (ArrayOf A, ArrayOf B)
template<class T >
T complex_abs (T real, T imag)
template<class T >
void complex_divide (T *c, const T *a, const T *b)
void power_zi (double *p, double *a, int b)
void power_zz (double *c, double *a, double *b)
double power_di (double a, int b)
double power_dd (double a, double b)
void cicpower (int n, float *c, float *a, int stride1, int *b, int stride2)
void cfcpower (int n, float *c, float *a, int stride1, float *b, int stride2)
void zdzpower (int n, double *c, double *a, int stride1, double *b, int stride2)
void cccpower (int n, float *c, float *a, int stride1, float *b, int stride2)
void zzzpower (int n, double *c, double *a, int stride1, double *b, int stride2)
void zizpower (int n, double *c, double *a, int stride1, int *b, int stride2)
void didpower (int n, double *c, double *a, int stride1, int *b, int stride2)
void dddpower (int n, double *c, double *a, int stride1, double *b, int stride2)
void fifpower (int n, float *c, float *a, int stride1, int *b, int stride2)
void fffpower (int n, float *c, float *a, int stride1, float *b, int stride2)
ArrayOf doPowerAssist (ArrayOf A, Class AClass, ArrayOf B, Class BClass, Class CClass, vvfun exec)
ArrayOf DoPowerTwoArgFunction (ArrayOf A, ArrayOf B) throw (Exception)
ArrayOf DotPower (ArrayOf A, ArrayOf B)
template<class T >
void dividefullreal (indexType N, T *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void dividefullcomplex (indexType N, T *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf DotRightDivide (ArrayOf A, ArrayOf B)
ArrayOf DotTranspose (ArrayOf A)
template<class T >
void equalsfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void equalsfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf Equals (ArrayOf A, ArrayOf B)
template<class T >
void greaterequalsfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void greaterequalsfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf GreaterEquals (ArrayOf A, ArrayOf B)
template<class T >
void greaterthanfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void greaterthanfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf GreaterThan (ArrayOf A, ArrayOf B)
ArrayOf ImagPart (ArrayOf arrayIn)
template<class T >
boost::container::vector< indexType > nanIndices (T *values, indexType nbElements)
template<class T >
boost::container::vector< indexType > infIndices (T *values, indexType nbElements)
template<class T >
boost::container::vector< indexType > ninfIndices (T *values, indexType nbElements)
template<class T >
bool IsApprox (T *ptrA, T *ptrB, Dimensions dims, double precision)
bool IsApprox (ArrayOf A, ArrayOf B, double precision)
ArrayOf LeftDivide (ArrayOf A, ArrayOf B) throw (Exception)
template<class T >
void lessequalsfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void lessequalsfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf LessEquals (ArrayOf A, ArrayOf B)
template<class T >
void lessthanfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void lessthanfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf LessThan (ArrayOf A, ArrayOf B)
template<class T >
void negate (indexType N, T *C, const T *A)
ArrayOf Negate (ArrayOf A) throw (Exception)
void boolean_not (indexType N, logical *C, const logical *A)
ArrayOf Not (ArrayOf A)
template<class T >
void notequalsfuncreal (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
template<class T >
void notequalsfunccomplex (indexType N, logical *C, const T *A, int stride1, const T *B, int stride2)
ArrayOf NotEquals (ArrayOf A, ArrayOf B)
void boolean_or (indexType N, logical *C, const logical *A, int Astride, const logical *B, int Bstride)
ArrayOf Or (ArrayOf A, ArrayOf B)
ArrayOf Power (ArrayOf A, ArrayOf B) throw (Exception)
ArrayOf RealPart (ArrayOf arrayIn)
ArrayOf RightDivide (ArrayOf A, ArrayOf B)
ArrayOf Transpose (ArrayOf A)
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf DotMultiply (ArrayOf A, ArrayOf B)
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf MultiplyOperator (ArrayOf A, ArrayOf B) throw (Exception)
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Multiply2D (ArrayOf A, ArrayOf B) throw (Exception)
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf MultiplySparse (ArrayOf A, ArrayOf B) throw (Exception)
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Multiply (ArrayOf A, ArrayOf B) throw (Exception)
void CloseAllFiles (void)
bool FinishNelsonUserScript (Evaluator *eval)
Evaluator * createMainEvaluator (Interface *io, NELSON_ENGINE_MODE _mode, std::wstring lang)
Evaluator * createMainEvaluator (NELSON_ENGINE_MODE _mode, std::wstring lang)
Evaluator * getMainEvaluator ()
bool destroyMainEvaluator ()
void InitGuiObjectsDynamic (void)
void * CreateGuiEvaluatorDynamic (void *vcontext, NELSON_ENGINE_MODE _mode)
void DestroyMainGuiObjectDynamic (void *term)
void * GetMainGuiObjectDynamic (void)
size_t setRecursionStacksize (size_t sizerstack)
size_t getRecursionStacksize ()
bool SetNelSonEnvironmentVariables ()
bool StartNelsonUserScript (Evaluator *eval)
void timeout (void)
bool TimeoutThread (uint64 _timeoutseconds)
bool IsErrorStruct (ArrayOf arg, Exception &e)
bool IsErrorStruct (const ArrayOf arg)
void Error (Evaluator *eval, std::wstring msg)
void Error (Evaluator *eval, std::wstring msg, std::wstring functionname)
void Error (Evaluator *eval, std::string msg)
void Error (Evaluator *eval, std::string msg, std::string functionname)
void updateError (Evaluator *eval, Exception &e)
ArrayOf ErrorToStruct (Exception e)
void printExceptionCount ()
template<class T >
T * new_with_exception (size_t len)
void Warning (Evaluator *eval, std::wstring msg)
void Warning (Evaluator *eval, std::string msg)
ArrayOf Cd (std::wstring newpath)
ArrayOf Cd (std::string newpath)
bool ChangeDirectory (std::wstring newpath)
bool CopyFile (std::wstring srcFile, std::wstring destFileOrDirectory, bool bForce, std::wstring &message)
bool CopyDirectory (std::wstring srcDir, std::wstring destDir, bool bForce, std::wstring &message)
bool CopyFiles (wstringVector srcFiles, std::wstring destDir, bool bForce, std::wstring &message)
bool FileDiff (std::wstring filename1, std::wstring filename2, logical eolcompare, std::wstring &res)
std::wstring FilePartsPath (std::wstring fullpath)
std::wstring FilePartsFilename (std::wstring fullpath)
std::wstring FilePartsExtension (std::wstring fullpath)
void FileParts (std::wstring fullpath, std::wstring &path, std::wstring &filename, std::wstring &extension)
std::wstring GetCurrentDirectory ()
ArrayOf TempDir ()
std::wstring GetSystemTemporaryDirectory ()
ArrayOf UserDir ()
std::wstring GetUserDirectory ()
bool IsDirectory (std::wstring str)
bool IsFile (std::wstring str)
boost::container::vector< FileInfo > ListFilesWithWildcard (std::wstring mask, bool bSubdirectories)
boost::container::vector< FileInfo > ListFiles (const std::wstring directory, bool bSubdirectories)
bool MakeDirectory (std::wstring parentDir, std::wstring newDir, std::wstring &message)
bool MakeDirectory (std::wstring newDir, std::wstring &message)
std::wstring RelativePath (std::wstring path1, std::wstring path2, bool &bSuccess)
bool RemoveDirectory (std::wstring folderName, bool bSubfolder, std::wstring &message)
bool RemoveFile (std::wstring filename, std::wstring &message)
NLSFILES_FOLDERS_FUNCTIONS_IMPEXP bool ChangeDirectory (std::string newpath)
void FunctionHandleDisplay (Evaluator *eval, ArrayOf Var)
bool FunctionHandleIsEqual (ArrayOf A, ArrayOf B)
function_handle StringToFunctionHandle (Evaluator *eval, std::wstring functionName)
bool ClearBuiltin (std::wstring builtinName)
bool ClearAllBuiltin ()
bool ClearMacroCache (Evaluator *eval)
bool ClearMacroCache ()
bool MacroArguments (Evaluator *eval, std::wstring functionname, wstringVector &Inputs, wstringVector &Outputs)
wstringVector WhatW (Evaluator *eval, bool bWithPrivateFunction, bool bSorted)
wstringVector WhichAll (std::wstring functionname)
std::wstring Which (std::wstring functionname)
wstringVector WhichModule (std::wstring functionname)
bool CreateConsole (void)
bool DestroyConsole (void)
std::wstring GetQtPath (std::wstring libraryLocation)
bool HtmlFileToPdfFile (std::wstring htmlsrcfilename, std::wstring pdfdestfilename)
bool HtmlStreamToPdfFile (std::wstring htmlstream, std::wstring pdfdestfilename)
void ProcessEvents (bool bWaitEvents)
QString TR (std::string str)
bool UiGetDirectory (std::wstring pathOrigin, std::wstring title, std::wstring &pathSelected)
NLSGUI_IMPEXP std::wstring QStringTowstring (QString qstr)
NLSGUI_IMPEXP QString wstringToQString (std::wstring wstr)
wstringVector HeadComments (Evaluator *eval, std::wstring filename, HEADCOMMENTS_ERROR &headError)
bool isValidImageTag (std::wstring tag)
bool parseImageTag (std::wstring tag, std::wstring srcDirectory, std::wstring &oldPath, std::wstring &newPath)
bool findImageTag (std::wstring text, wstringVector &imagesTag)
bool copyImages (wstringVector srcImages, wstringVector dstImages)
bool copyImage (std::wstring srcImage, std::wstring dstImage)
std::wstring crcFile (std::wstring filename)
std::wstring XmlDocChapterNamer (std::wstring dstDirectory)
bool XmlDocCheckIfLinkExists (std::wstring directorysource, std::wstring linkname, std::wstring language)
bool XmlDocResolveLink (std::wstring directorysource, std::wstring linkname, bool isQtHelp, std::wstring language, std::wstring &resolvedlink)
std::wstring getXmlFileEncoding (std::wstring filename)
void errorFunction (void *ctx, const char *msg,...)
xmlParserCtxt * initContext (std::wstring &error, bool validate)
xmlDoc * readDocument (const std::string &xmlCode, bool validate, std::wstring &error)
NLSHELP_TOOLS_IMPEXP bool MarkdownFile (std::wstring inputMarkdownString, std::wstring outputHtmlString)
NLSHELP_TOOLS_IMPEXP bool MarkdownString (std::wstring inputMarkdownString, std::wstring &outputHtmlString)
NLSHELP_TOOLS_IMPEXP bool MarkdownString (std::string inputMarkdownString, std::string &outputHtmlString)
std::wstring gettextw (std::wstring S)
std::wstring gettextw (std::string S)
std::string gettext (std::string S)
template<class T >
ArrayOf HorzCatIntTemplate (ArrayOf A, ArrayOf B, Dimensions dimsRes)
ArrayOf HorzCatInteger (ArrayOf A, ArrayOf B)
ArrayOf HorzCatNdArrayInteger (ArrayOf A, ArrayOf B)
template<class T >
bool IntegerIsEqualTemplate (ArrayOf A, ArrayOf B)
bool IntegerIsEqual (ArrayOf A, ArrayOf B)
int16 ToInt16 (int8 a)
int16 ToInt16 (float a)
int16 ToInt16 (double a)
int16 ToInt16 (uint8 a)
int16 ToInt16 (int16 a)
int16 ToInt16 (uint16 a)
int16 ToInt16 (int32 a)
int16 ToInt16 (uint32 a)
int16 ToInt16 (int64 a)
int16 ToInt16 (uint64 a)
ArrayOf ToInt16 (ArrayOf a)
int32 ToInt32 (int8 a)
int32 ToInt32 (float a)
int32 ToInt32 (double a)
int32 ToInt32 (uint8 a)
int32 ToInt32 (int16 a)
int32 ToInt32 (uint16 a)
int32 ToInt32 (int32 a)
int32 ToInt32 (uint32 a)
int32 ToInt32 (int64 a)
int32 ToInt32 (uint64 a)
ArrayOf ToInt32 (ArrayOf a)
int64 ToInt64 (int8 a)
int64 ToInt64 (float a)
int64 ToInt64 (double a)
int64 ToInt64 (uint8 a)
int64 ToInt64 (int16 a)
int64 ToInt64 (uint16 a)
int64 ToInt64 (int32 a)
int64 ToInt64 (uint32 a)
int64 ToInt64 (int64 a)
int64 ToInt64 (uint64 a)
ArrayOf ToInt64 (ArrayOf a)
int8 ToInt8 (int8 a)
int8 ToInt8 (float a)
int8 ToInt8 (double a)
int8 ToInt8 (uint8 a)
int8 ToInt8 (int16 a)
int8 ToInt8 (uint16 a)
int8 ToInt8 (int32 a)
int8 ToInt8 (uint32 a)
int8 ToInt8 (int64 a)
int8 ToInt8 (uint64 a)
ArrayOf ToInt8 (ArrayOf a)
uint16 ToUint16 (int8 a)
uint16 ToUint16 (float a)
uint16 ToUint16 (double a)
uint16 ToUint16 (uint8 a)
uint16 ToUint16 (int16 a)
uint16 ToUint16 (uint16 a)
uint16 ToUint16 (int32 a)
uint16 ToUint16 (uint32 a)
uint16 ToUint16 (int64 a)
uint16 ToUint16 (uint64 a)
ArrayOf ToUint16 (ArrayOf a)
uint32 ToUint32 (int8 a)
uint32 ToUint32 (float a)
uint32 ToUint32 (double a)
uint32 ToUint32 (uint8 a)
uint32 ToUint32 (int16 a)
uint32 ToUint32 (uint16 a)
uint32 ToUint32 (int32 a)
uint32 ToUint32 (uint32 a)
uint32 ToUint32 (int64 a)
uint32 ToUint32 (uint64 a)
ArrayOf ToUint32 (ArrayOf a)
uint64 ToUint64 (int8 a)
uint64 ToUint64 (float a)
uint64 ToUint64 (double a)
uint64 ToUint64 (uint8 a)
uint64 ToUint64 (int16 a)
uint64 ToUint64 (uint16 a)
uint64 ToUint64 (int32 a)
uint64 ToUint64 (uint32 a)
uint64 ToUint64 (int64 a)
uint64 ToUint64 (uint64 a)
ArrayOf ToUint64 (ArrayOf a)
uint8 ToUint8 (int8 a)
uint8 ToUint8 (float a)
uint8 ToUint8 (double a)
uint8 ToUint8 (uint8 a)
uint8 ToUint8 (int16 a)
uint8 ToUint8 (uint16 a)
uint8 ToUint8 (int32 a)
uint8 ToUint8 (uint32 a)
uint8 ToUint8 (int64 a)
uint8 ToUint8 (uint64 a)
ArrayOf ToUint8 (ArrayOf a)
ArrayOf integer_uminus (ArrayOf a)
int8 integer_uminus (int8 a)
int16 integer_uminus (int16 a)
int32 integer_uminus (int32 a)
int64 integer_uminus (int64 a)
uint8 integer_uminus (uint8 a)
uint16 integer_uminus (uint16 a)
uint32 integer_uminus (uint32 a)
uint64 integer_uminus (uint64 a)
template<class T >
ArrayOf VertCatIntTemplate (ArrayOf A, ArrayOf B, Dimensions dimsRes)
ArrayOf VertCatInteger (ArrayOf A, ArrayOf B)
ArrayOf VertCatNdArrayInteger (ArrayOf A, ArrayOf B)
void doExit (void)
void doHelp (void)
void doPause (void)
void doStop (void)
void outTabs ()
void printAST (ASTPtr t)
void FreezeAST (ASTPtr t, Serialize *s)
ASTPtr ThawAST (Serialize *s)
void resetAstBackupPosition ()
boost::container::vector< ASTPtr > getAstUsed ()
bool deleteAst (ASTPtr pt, boost::container::vector< ASTPtr > v)
void deleteAstVector (boost::container::vector< ASTPtr > v)
ASTPtr allocateAbstractSyntaxTree (void)
ASTPtr allocateAbstractSyntaxTree (NODE_TYPE ntype, const char *name, int context)
ASTPtr allocateAbstractSyntaxTree (NODE_TYPE ntype, int token, int context)
ASTPtr allocateAbstractSyntaxTree (OP_TYPE op, ASTPtr lt, ASTPtr rt, int context)
ASTPtr allocateAbstractSyntaxTree (OP_TYPE op, ASTPtr lt, ASTPtr md, ASTPtr rt, int context)
ASTPtr allocateAbstractSyntaxTree (OP_TYPE op, ASTPtr arg, int context)
void CodeToByte (std::wstring nlf_filename)
void CodeToByte (MacroFunctionDef *fptr, Serialize *s)
MacroFunctionDef * ByteToCode (std::wstring nlb_filename)
MacroFunctionDef * ByteToCode (Serialize *s)
ArrayOfVector CallOperatorFunction (Evaluator *eval, std::string functionName, ArrayOf a, size_t nLhs)
ArrayOfVector CallOperatorFunction (Evaluator *eval, std::string functionName, ArrayOf a, ArrayOf b, size_t nLhs)
ArrayOfVector CallOperatorFunction (Evaluator *eval, std::string functionName, ArrayOf a, ArrayOf b, ArrayOf c, size_t nLhs)
ArrayOfVector CallOperatorFunction (Evaluator *eval, std::string functionName, ArrayOfVector ArgsIn, size_t nLhs)
void getSupportedCommentSymbols (stringVector &comments)
void getSupportedCommentSymbols (wstringVector &comments)
bool isCommentedLine (std::string line)
bool isCommentedLine (std::wstring line)
ArrayOfVector EvaluateBuiltinCatchRuntimeException (Evaluator *eval, BuiltInFuncPtr fptr, ArrayOfVector &inputs, int nargout)
void sigInterrupt (int arg)
int getArgumentIndex (stringVector list, std::string t)
int COST (int a, int b)
int GetClosestLineNumber (ASTPtr t, int lineno)
void setParserFilename (std::string filename)
void setParserFilename (std::wstring filename)
std::string getParserFilenameU ()
std::wstring getParserFilenameW ()
ArrayOf HorzCat (Evaluator *eval, const ArrayOfVector &v)
int compareKeyword (const void *a, const void *b)
wstringVector GetKeywords (bool bSorted)
bool isKeyword (std::wstring key)
void setLexBuffer (const char *buf)
void setLexFile (FILE *fp)
bool lexCheckForMoreInput (int ccount)
int getContinuationCount ()
void OverloadDisplay (Evaluator *eval, ArrayOf a)
ParserState ParseFile (Evaluator *eval, std::wstring filename, bool bIgnoreException)
boost::container::vector< ErrorInfo > StackError (Evaluator *eval)
ArrayOf VertCat (Evaluator *eval, const ArrayOfVector &v)
void chainFunction (MacroFunctionDef *r)
void yyerror (const char *s)
std::string decodeline (ParseRHS val)
int yyxpt (std::string xStr, ParseRHS val)
void resetParser ()
ASTPtr getParsedScriptBlock ()
MacroFunctionDef * getParsedFunctionDef ()
ParserState parseState ()
ParserState parseString (std::string txt)
ParserState parseFile (FILE *fp, const char *fname)
NLSINTERPRETER_IMPEXP void ExitInterrupt (int arg)
void lexSetAdditionalInput (char *buffer)
void GetLexTokenDescription (char *buffer)
NLSINTERPRETER_IMPEXP void FreezeMacroFunction (MacroFunctionDef *fptr, Serialize *s)
NLSINTERPRETER_IMPEXP MacroFunctionDef * ThawMacroFunction (Serialize *s)
ArrayOf AllLogical (ArrayOf A, indexType dim)
void boolAnd (size_t n, logical *c, const logical *a, const int stride1, const logical *b, const int stride2)
ArrayOf AndLogical (ArrayOf A, ArrayOf B)
ArrayOf AnyLogical (ArrayOf A, indexType dim)
ArrayOf HorzCatLogical (ArrayOf A, ArrayOf B)
ArrayOf HorzCatNdArrayLogical (ArrayOf A, ArrayOf B)
bool logical_isequal (ArrayOf a, ArrayOf b)
ArrayOf TrueConstructor (Dimensions dim, bool bIsSparse)
ArrayOf FalseConstructor (Dimensions dim, bool bIsSparse)
ArrayOf NotLogical (ArrayOf A)
void boolOr (size_t n, logical *c, const logical *a, const int stride1, const logical *b, const int stride2)
ArrayOf OrLogical (ArrayOf A, ArrayOf B)
ArrayOf ToLogical (ArrayOf A)
ArrayOf VertCatLogical (ArrayOf A, ArrayOf B)
ArrayOf VertCatNdArrayLogical (ArrayOf A, ArrayOf B)
ArrayOf XorLogical (ArrayOf A, ArrayOf B)
bool ClearVariable (Evaluator *eval, std::wstring variable)
bool ClearVariable (Evaluator *eval, std::string variable)
bool ClearAllVariables (Evaluator *eval)
bool ClearGlobalVariable (Evaluator *eval, std::wstring variable)
bool ClearGlobalVariable (Evaluator *eval, std::string variable)
bool ClearAllGlobalVariables (Evaluator *eval)
bool LockVariable (std::wstring variable, Scope *scope)
bool LockVariable (std::string variable, Scope *scope)
bool UnlockVariable (std::wstring variable, Scope *scope)
bool UnlockVariable (std::string variable, Scope *scope)
bool IsLockedVariable (std::wstring variable, Scope *scope)
bool IsLockedVariable (std::string variable, Scope *scope)
stringVector GetLockedVariables (std::string variable, Scope *scope)
double getTotalVirtualMemory ()
double getTotalVirtualMemoryUsed ()
double getTotalVirtualMemoryByNelson ()
double getTotalPhysicalMemory ()
double getTotalPhysicalMemoryUsed ()
double getTotalPhysicalMemoryByNelson ()
stringVector Who (Evaluator *eval, SCOPE_LEVEL scopeLevel)
void AddModule (Evaluator *eval, std::wstring modulerootpath, std::wstring moduleshortname)
std::wstring ModulePath (std::wstring moduleshortname)
std::wstring ModulePath (std::wstring modulerootpath, std::wstring moduleshortname, MODULEPATH_OPTION option)
std::wstring ConstructBinariesPath (std::wstring modulerootpath)
std::wstring ConstructDynamicLibraryName (std::wstring moduleshortname)
std::wstring ConstructEtcName (std::wstring modulerootpath, std::wstring moduleshortname)
std::wstring ConstructRootName (std::wstring modulerootpath, std::wstring moduleshortname)
std::wstring ConstructScriptName (std::wstring modulerootpath, std::wstring moduleshortname)
std::wstring ConstructDynamicLibraryFullname (std::wstring modulerootpath, std::wstring moduleshortname)
bool RegisterModule (std::wstring moduleshortname, std::wstring modulerootpath)
bool UnregisterModule (std::wstring moduleshortname)
bool IsExistingModuleName (std::wstring moduleshortname)
bool IsExistingModulePath (std::wstring modulerootpath)
boost::container::vector< module > GetModules (bool bReverse)
wstringVector GetModulesName (bool bReverse)
wstringVector GetModulesPath (bool bReverse)
std::wstring GetModulePath (std::wstring moduleshortname)
bool RemoveModule (Evaluator *eval, std::wstring moduleshortname)
std::wstring concateEnvironmentPath (boost::container::vector< std::wstring > listPath)
template<class InputIterator , class T >
InputIterator localfind (InputIterator first, InputIterator last, const T &val)
bool AddPathToEnvironmentVariable (std::wstring envVar, std::wstring pathToAdd)
std::wstring CreateGUID ()
wstringVector CreateGUID (size_t nbGUID)
std::wstring GetVariableEnvironment (std::wstring envVarName, std::wstring defaultValue)
ArrayOf IsPc ()
ArrayOf IsMac ()
ArrayOf IsUnix ()
bool IsPcPlatform ()
bool IsMacPlatform ()
bool IsUnixPlatform ()
std::wstring GetArchitecture ()
std::wstring GetArchitectureType ()
double GetMaxArrayOfSizeSupported ()
NLSOS_FUNCTIONS_IMPEXP bool IsBigEndian ()
std::wstring SearchVariableEnvironmentW (std::wstring fileToSearch, std::wstring envVarName)
std::string SearchVariableEnvironmentU (std::string fileToSearch, std::string envVarName)
NLSOS_FUNCTIONS_IMPEXP bool SetVariableEnvironmentW (std::wstring envVarName, std::wstring Value)
NLSOS_FUNCTIONS_IMPEXP bool SetVariableEnvironmentU (std::string envVarName, std::string Value)
ArrayOf SystemCommand (std::wstring command, int &ierr)
std::wstring SystemCommandW (std::wstring command, int &ierr)
bool WinOpen (std::wstring command)
ArrayOfVector OverloadExtraction (Evaluator *eval, std::string ClassName, ArrayOfVector args)
ArrayOfVector OverloadFunction (Evaluator *eval, int nLhs, const ArrayOfVector &argIn, bool &bSuccess)
void OverloadRequired (Evaluator *eval, const ArrayOfVector &argIn, OVERLOAD_TYPE otype)
ArrayOf OverloadTrinaryOperator (Evaluator *eval, ArrayOf a, ArrayOf b, ArrayOf c, std::string functionName)
ArrayOf OverloadUnaryOperator (Evaluator *eval, ArrayOf a, std::string functionName, std::string forcedFunctionName)
ArrayOf OverloadBinaryOperator (Evaluator *eval, ArrayOf a, ArrayOf b, std::string functionName)
ArrayOf OverloadBinaryOperator (Evaluator *eval, ArrayOf a, ArrayOf b, std::string functionName, bool &bSuccess)
ArrayOf OverloadBinaryOperator (Evaluator *eval, ArrayOf a, ArrayOf b, std::string functionName, bool &bSuccess, std::string forcedFunctionName)
ArrayOf Rand (Evaluator *eval, Class cl)
ArrayOf Rand (Evaluator *eval, Dimensions dims, Class cl)
ArrayOf RandNormal (Evaluator *eval, Class cl)
ArrayOf RandNormal (Evaluator *eval, Dimensions dims, Class cl)
std::wstring RngGetType (Evaluator *eval)
void RngSetSeed (Evaluator *eval, double seed)
ArrayOf RngGetSeed (Evaluator *eval)
ArrayOf RngGetState (Evaluator *eval)
void RngSetDefault (Evaluator *eval)
void RngShuffle (Evaluator *eval)
bool RngSetEngine (Evaluator *eval, double seed, std::wstring engineName)
void RngDelete (Evaluator *eval)
bool RngSetState (Evaluator *eval, ArrayOf st)
wstringVector getSupportedRngEngineName ()
std::wstring getRngTypeAsString (RNG_TYPE rngType)
RNG_TYPE getRngType (std::wstring enginename)
bool isRngType (std::wstring enginename)
ArrayOf HorzCatSingle (ArrayOf A, ArrayOf B)
ArrayOf HorzCatNdArraySingle (ArrayOf A, ArrayOf B)
ArrayOf single_subtraction (ArrayOf a, ArrayOf b)
ArrayOf scomplex_subtraction (ArrayOf a, ArrayOf b)
ArrayOf single_minus_single (ArrayOf a, ArrayOf b)
ArrayOf single_addition (ArrayOf a, ArrayOf b)
ArrayOf scomplex_addition (ArrayOf a, ArrayOf b)
ArrayOf single_plus_single (ArrayOf a, ArrayOf b)
bool single_isequal (ArrayOf a, ArrayOf b)
bool single_isequaln (ArrayOf a, ArrayOf b)
template<class T >
ArrayOf ToSingle (ArrayOf A)
ArrayOf single_uminus (ArrayOf a)
ArrayOf VertCatSingle (ArrayOf A, ArrayOf B)
ArrayOf VertCatNdArraySingle (ArrayOf A, ArrayOf B)
bool CheckIJV (size_t ilen, size_t jlen, size_t vlen, int &istride, int &jstride, int &vstride, size_t &olen)
ArrayOf CtransposeSparseDouble (ArrayOf A)
ArrayOf CtransposeSparseLogical (ArrayOf A)
ArrayOf HorzCatSparseDouble (ArrayOf A, ArrayOf B)
ArrayOf HorzCatSparseLogical (ArrayOf A, ArrayOf B)
ArrayOf SparseConstructor (indexType m, indexType n)
ArrayOf SparseConstructor (ArrayOf a)
ArrayOf SparseConstructor (ArrayOf I, ArrayOf J, ArrayOf V)
ArrayOf SparseConstructor (ArrayOf I, ArrayOf J, ArrayOf V, indexType m, indexType n)
ArrayOf SparseConstructor (ArrayOf I, ArrayOf J, ArrayOf V, indexType m, indexType n, indexType nnz)
std::string single2hexastr (single d)
void SparseDoubleDisplay (Evaluator *eval, ArrayOf a)
void SparseDoubleComplexDisplay (Evaluator *eval, ArrayOf a)
void SparseLogicalDisplay (Evaluator *eval, ArrayOf a)
void SparseDisplay (Evaluator *eval, ArrayOf a)
ArrayOf SparseImagPart (ArrayOf a)
indexType SparseNonZeros (ArrayOf a)
ArrayOf SparseRealPart (ArrayOf a)
template<class T >
void * sparsedouble_uminus (Class dclass, indexType rows, indexType cols, const void *cp)
ArrayOf sparsedouble_uminus (ArrayOf a)
ArrayOf sparselogical_uminus (ArrayOf a)
ArrayOf VertCatSparseDouble (ArrayOf A, ArrayOf B)
ArrayOf VertCatSparseLogical (ArrayOf A, ArrayOf B)
Class precisionFromString (std::wstring str, bool &bOK)
bool isLittleEndianFormat ()
bool BITSWAP (void *ptrReadWrite, size_t count, Class destClass)
bool FileClose (FilesManager *fm, int no)
bool FileGetLine (File *fp, int nchar, bool bWithNewLine, std::wstring &result)
FOPEN_ERROR_TYPE FileOpen (FilesManager *fm, std::wstring filename, std::wstring filemode, int &fileposition)
ArrayOf FileRead (Evaluator *eval, File *fp, int64 sizeToRead, Class classPrecision, size_t skip, bool bIsLittleEndian, int &sizeReallyRead)
void FileRewind (File *fp)
bool FileSeek (File *fp, int64 offset, int origin)
int64 FileSize (File *fp)
int64 FileTell (File *fp)
FWRITE_ERROR_TYPE FileWrite (Evaluator *eval, File *fp, ArrayOf src, Class destClass, size_t skip, bool bIsLittleEndian, int &sizeWritten)
template<typename T >
T bswap (T val)
ArrayOf HorzCatString (ArrayOf A, ArrayOf B)
ArrayOf HorzCatNdArrayString (ArrayOf A, ArrayOf B)
wstringVector toString (ArrayOf A)
wstringVector uint64ToString (ArrayOf A)
bool IntegerToString (ArrayOf A, wstringVector &result, std::wstring &error_message)
ArrayOf StringCompare (ArrayOf A, ArrayOf B, bool bCaseSensitive, indexType len)
void StringDisplay (Evaluator *eval, ArrayOf Var, bool bFromBuiltin)
ArrayOf StringFind (std::wstring A, std::wstring B)
std::wstring StringFormat (const wchar_t *format,...)
std::string StringFormat (const char *format,...)
bool StringIsEqual (ArrayOf A, ArrayOf B)
bool StringPrintf (std::wstring &result, std::wstring &errormsg, Evaluator *eval, const ArrayOfVector &arg)
ArrayOf ToChar (ArrayOf A, ArrayOf B)
ArrayOf ToChar (ArrayOf A)
ArrayOf ToLower (Evaluator *eval, ArrayOf A)
std::wstring ToLower (std::wstring A)
ArrayOf ToUpper (Evaluator *eval, ArrayOf A)
std::wstring ToUpper (std::wstring A)
ArrayOf VertCatString (ArrayOf A, ArrayOf B)
ArrayOf VertCatNdArrayString (ArrayOf A, ArrayOf B)
NLSSTRING_IMPEXP std::wstring ToChar (ArrayOf A, Dimensions &dims)
NLSSTRING_IMPEXP std::wstring ToChar (ArrayOfVector A, Dimensions &dims)
bool ParseTags (Evaluator *eval, std::wstring filename, TestTags &options, std::wstring &msg)
ArrayOf Clock ()
double CpuTime ()
double DateNumber (double year, double month, double day, double hour, double minutes, double secondes)
double DateNumber (std::wstring datestring, std::wstring formatIn, bool &bParsed)
double DateNumber (std::wstring datestring, bool &bParsed)
void DateVector (double dateSerial, double &Y, double &M, double &D, double &H, double &MN, double &S, bool rf)
bool IsLeapYear (int year)
double Now ()
bool Sleep (Evaluator *eval, double tValue)
bool Tic (Evaluator *eval)
bool Toc (Evaluator *eval, double &tValue)
bool Toc (uint64 t, double &tValue)
ArrayOf Cos (ArrayOf A)
ArrayOf Sin (ArrayOf A)
ArrayOf Tan (ArrayOf A)
ArrayOf Cosh (ArrayOf A)
ArrayOf Sinh (ArrayOf A)
ArrayOf Tanh (ArrayOf A)
ArrayOf Acos (ArrayOf A)
ArrayOf Asin (ArrayOf A)
ArrayOf Atan (ArrayOf A)
ArrayOfVector scalarArrayOfToArrayOfVector (ArrayOf a)
void outputDoublePrecisionFloat (char *buf, double num)
void outputSinglePrecisionFloat (char *buf, float num)
void dumpAllArrayOfs ()
void emitElement (char *msgBuffer, const void *dp, indexType num, Class dcls)
template<class T >
indexType DoCountNNZReal (const void *dp, indexType len)
template<class T >
indexType DoCountNNZComplex (const void *dp, indexType len)
std::string ClassName (ArrayOf In)
stringVector ClassName (ArrayOfVector In)
void ClassName (ArrayOf In, std::wstring &returnedClassName)
void ClassName (ArrayOf In, std::string &returnedClassName)
bool IsValidFieldname (std::string fieldname)
bool IsValidVariableName (std::string varname)
bool IsValidVariableName (std::wstring varname)
Class StringToClass (std::wstring classname)
Variables
int exceptionCount = 0
int tabLevel = 0
bool InterruptPending = false
bool InterruptCallback = false
indexType endValStackLength = 0
indexType endValStack [1000]
keywordStruct keyWord [KEYWORDCOUNT]
const unsigned int IDENTIFIER_LENGTH_MAX = 4096
const unsigned int NLS_KEYWORD_BREAK = 0
const unsigned int NLS_KEYWORD_CASE = 1
const unsigned int NLS_KEYWORD_CATCH = 2
const unsigned int NLS_KEYWORD_CONTINUE = 3
const unsigned int NLS_KEYWORD_ELSE = 4
const unsigned int NLS_KEYWORD_ELSEIF = 5
const unsigned int NLS_KEYWORD_END = 6
const unsigned int NLS_KEYWORD_FOR = 7
const unsigned int NLS_KEYWORD_FUNCTION = 8
const unsigned int NLS_KEYWORD_IF = 9
const unsigned int NLS_KEYWORD_PAUSE = 10
const unsigned int NLS_KEYWORD_OTHERWISE = 11
const unsigned int NLS_KEYWORD_QUIT = 12
const unsigned int NLS_KEYWORD_ABORT = 13
const unsigned int NLS_KEYWORD_RETURN = 14
const unsigned int NLS_KEYWORD_SWITCH = 15
const unsigned int NLS_KEYWORD_TRY = 16
const unsigned int NLS_KEYWORD_WHILE = 17
const unsigned int NLS_KEYWORD_ENDFUNCTION = 18
intSet addresses
const unsigned int maxDims = 16
Detailed Description
A Scope is a combination of a variable hashtable and a function hashtable.
Typedef Documentation
vvfun
typedef void(* Nelson::vvfun) (indexType length, void *result, const void *arg1, const int stride1, const void *arg2, const int stride2)
This is the generic function interface into calculations that can be performed on some type.
Definition at line 393 of file DotPower.cpp.
Enumeration Type Documentation
ParserState
enum Nelson::ParserState
These are the different parser states that the parser can be in after a successful parse:
ScriptBlock corresponds to a parse of a sequence of statements
FuncDef corresponds to a parse of a function def
ParseError corresponds to a syntax error when parsing.
Definition at line 31 of file ParserState.hpp.
     {
         ScriptBlock,
         FuncDef,
         ParseError
     } ParserState;
Function Documentation
And()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::And (ArrayOf A, ArrayOf B)
Element-wise and of two arrays: C = A and B. C = A && B
Definition at line 36 of file And.cpp.
     {
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         BoolVectorCheck(A, B, "&");
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         Cp = ArrayOf::allocateArrayOf(NLS_LOGICAL, Clen);
         boolean_and(Clen, (logical*)Cp, (const logical*)A.getDataPointer(), Astride,
                     (const logical*)B.getDataPointer(), Bstride);
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
BoolVectorCheck()
NLSAPI_NELSON_IMPEXP void Nelson::BoolVectorCheck (ArrayOf & A, ArrayOf & B, std::string opname) throw (Exception)
We want to perform a vector operator between two logical data objects. The following operations are performed:
Both A & B are converted to logical types.
Either A & B must be the same size, or A is a scalar or B is a scalar.
Definition at line 127 of file MatrixCheck.cpp.
Referenced by And(), and Or().
     {
         A.promoteType(NLS_LOGICAL);
         B.promoteType(NLS_LOGICAL);
         if (!(SameSizeCheck(A.getDimensions(), B.getDimensions()) || A.isScalar() || B.isScalar()))
         {
             throw Exception(std::string(_("Size mismatch on arguments to ")) + opname);
         }
     }
CheckNumeric()
NLSAPI_NELSON_IMPEXP void Nelson::CheckNumeric (ArrayOf & A, ArrayOf & B, std::string opname) throw (Exception)
Check that both of the argument objects are numeric.
Definition at line 23 of file MatrixCheck.cpp.
Referenced by doPowerAssist(), MatrixCheck(), Power(), and VectorCheck().
     {
         bool Anumeric, Bnumeric;
         Anumeric = !A.isReferenceType();
         Bnumeric = !B.isReferenceType();
         if (!(Anumeric && Bnumeric))
             throw Exception(std::string(_("Cannot apply numeric operation ")) +
                             opname + std::string(_(" to reference types.")));
     }
compareKeyword()
int Nelson::compareKeyword (const void * , const void *)
A comparison function for the keyWord list of structures, so that the binary search algorithm used on the keywordStruct list works properly.
Definition at line 55 of file Keywords.cpp.
     {
         return strcmp(((keywordStruct*)a)->word,
                       ((keywordStruct*)b)->word);
     }
complex_abs()
template<class T > T Nelson::complex_abs (T real, T imag)
These are the power functions...
Definition at line 39 of file DotPower.cpp.
     {
         double temp;
         if (real < 0)
         {
             real = -real;
         }
         if (imag < 0)
         {
             imag = -imag;
         }
         if (imag > real)
         {
             temp = real;
             real = imag;
             imag = (T)(temp);
         }
         if ((real + imag) == real)
         {
             return(real);
         }
         temp = imag / real;
         temp = real*sqrt(1.0 + temp*temp);  /*overflow!!*/
         return (T)(temp);
     }
doPowerAssist()
ArrayOf Nelson::doPowerAssist (ArrayOf A, Class AClass, ArrayOf B, Class BClass, Class CClass, vvfun exec) inline
This structure holds pointers to functions when all types can be handled.
Definition at line 414 of file DotPower.cpp.
     {
         ArrayOf C;
         A.promoteType(AClass);
         B.promoteType(BClass);
         if (A.isScalar())
         {
             indexType Blen(B.getLength());
             C = ArrayOf(CClass, B.getDimensions(), NULL);
             void * Cp = C.allocateArrayOf(CClass, Blen);
             exec(Blen, Cp, A.getDataPointer(), 0, B.getDataPointer(), 1);
             C.setDataPointer(Cp);
         }
         else if (B.isScalar())
         {
             indexType Alen(A.getLength());
             C = ArrayOf(CClass, A.getDimensions(), NULL);
             void* Cp = C.allocateArrayOf(CClass, Alen);
             exec(Alen, Cp, A.getDataPointer(), 1, B.getDataPointer(), 0);
             C.setDataPointer(Cp);
         }
         else
         {
             indexType Alen(A.getLength());
             C = ArrayOf(CClass, A.getDimensions(), NULL);
             void* Cp = C.allocateArrayOf(CClass, Alen);
             exec(Alen, Cp, A.getDataPointer(), 1, B.getDataPointer(), 1);
             C.setDataPointer(Cp);
         }
         return C;
     }
DotLeftDivide()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::DotLeftDivide (ArrayOf A, ArrayOf B)
Element-wise left divide. DOTLEFTDIVIDE Element-wise Left-Division Operator
Definition at line 24 of file DotLeftDivide.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, true, ".\\");
         return DotRightDivide(B, A);
     }
DotMultiply()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::DotMultiply (ArrayOf A, ArrayOf B)
Element-wise multiplication. .* (DOTTIMES) Operator
DotPower()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::DotPower (ArrayOf A, ArrayOf B)
Element-wise power. A .^ B
Definition at line 564 of file DotPower.cpp.
Referenced by Power().
     {
         return(DoPowerTwoArgFunction(A, B));
     }
DotRightDivide()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::DotRightDivide (ArrayOf A, ArrayOf B)
Element-wise divide of two arrays
Definition at line 92 of file DotRightDivide.cpp.
Referenced by DotLeftDivide(), and RightDivide().
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, true, "./");
         // Get a pointer to the function we ultimately need to execute
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         //Cp = Malloc(Clen*B.getElementSize());
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 Cp = new_with_exception<int32>(Clen);
                 dividefullreal<int32>(Clen, (int32*)Cp,
                                       (int32*)A.getDataPointer(), Astride,
                                       (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 Cp = new_with_exception<float>(Clen);
                 dividefullreal<float>(Clen, (float*)Cp,
                                       (float*)A.getDataPointer(), Astride,
                                       (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 Cp = new_with_exception<double>(Clen);
                 dividefullreal<double>(Clen, (double*)Cp,
                                        (double*)A.getDataPointer(), Astride,
                                        (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 Cp = new_with_exception<float>(Clen * 2);
                 dividefullcomplex<float>(Clen, (float*)Cp,
                                          (float*)A.getDataPointer(), Astride,
                                          (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 Cp = new_with_exception<double>(Clen * 2);
                 dividefullcomplex<double>(Clen, (double*)Cp,
                                           (double*)A.getDataPointer(), Astride,
                                           (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(B.getDataClass(), Cdim, Cp);
     }
DotTranspose()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::DotTranspose (ArrayOf A)
Dot-transpose the argument.
Definition at line 22 of file DotTranspose.cpp.
     {
         //A.transpose();
         return A;
     }
Equals()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Equals (ArrayOf A, ArrayOf B)
Element-wise compare (eq) of two arrays: C = (A == B).
Definition at line 101 of file Equals.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, "==");
         int Astride = 0, Bstride = 0;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         Cp = new_with_exception<logical>(Clen);
         switch (B.getDataClass())
         {
             case NLS_LOGICAL:
             {
                 equalsfuncreal<logical>(Clen, (logical*)Cp, (logical*)A.getDataPointer(), Astride, (logical*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_UINT8:
             {
                 equalsfuncreal<uint8>(Clen, (logical*)Cp, (uint8*)A.getDataPointer(), Astride, (uint8*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_INT8:
             {
                 equalsfuncreal<int8>(Clen, (logical*)Cp, (int8*)A.getDataPointer(), Astride, (int8*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_UINT16:
             {
                 equalsfuncreal<uint16>(Clen, (logical*)Cp, (uint16*)A.getDataPointer(), Astride, (uint16*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_INT16:
             {
                 equalsfuncreal<int16>(Clen, (logical*)Cp, (int16*)A.getDataPointer(), Astride, (int16*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_UINT32:
             {
                 equalsfuncreal<uint32>(Clen, (logical*)Cp, (uint32*)A.getDataPointer(), Astride, (uint32*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_INT32:
             {
                 equalsfuncreal<int32>(Clen, (logical*)Cp, (int32*)A.getDataPointer(), Astride, (int32*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_UINT64:
             {
                 equalsfuncreal<uint64>(Clen, (logical*)Cp, (uint64*)A.getDataPointer(), Astride, (uint64*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_INT64:
             {
                 equalsfuncreal<int64>(Clen, (logical*)Cp, (int64*)A.getDataPointer(), Astride, (int64*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_SINGLE:
             {
                 equalsfuncreal<float>(Clen, (logical*)Cp, (float*)A.getDataPointer(), Astride, (float*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_DOUBLE:
             {
                 equalsfuncreal<double>(Clen, (logical*)Cp, (double*)A.getDataPointer(), Astride, (double*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_SCOMPLEX:
             {
                 equalsfunccomplex<float>(Clen, (logical*)Cp, (float*)A.getDataPointer(), Astride, (float*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_DCOMPLEX:
             {
                 equalsfunccomplex<double>(Clen, (logical*)Cp, (double*)A.getDataPointer(), Astride, (double*)B.getDataPointer(), Bstride);
             }
             break;
             case NLS_STRING:
             {
                 equalsfuncreal<charType>(Clen, (logical*)Cp, (charType*)A.getDataPointer(), Astride, (charType*)B.getDataPointer(), Bstride);
             }
             break;
             default:
             {
                 throw Exception(_W("Eq: type(s) not managed."));
             }
             break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
FreezeAST()
NLSINTERPRETER_IMPEXP void Nelson::FreezeAST (ASTPtr t, Serialize * s)
Freeze the tree Serializes an AST tree to a serialization object. The resulting stream should be portable across reasonable systems (i.e., little-vs-big endian can be handled but that's about it).
Definition at line 353 of file AST.cpp.
Referenced by FreezeMacroFunction().
     {
         if (t == nullptr)
         {
             s->putByte(0);
             return;
         }
         s->putByte(1);
         s->putByte(t->type);
         s->putInt(t->tokenNumber);
         s->putByte(t->opNum);
         s->putString(t->text);
         FreezeAST(t->down,s);
         FreezeAST(t->right,s);
     }
FreezeMacroFunction()
void Nelson::FreezeMacroFunction (MacroFunctionDef * fptr, Serialize * s)
Routine to freeze an M-function to a serializing stream.
Definition at line 334 of file MacroFunctionDef.cpp.
Referenced by Nelson::MacroFunctionDef::type().
 {
     s->putString(fptr->name.c_str());
     s->putStringVector(fptr->arguments);
     s->putStringVector(fptr->returnVals);
     s->putBool(fptr->localFunction);
     FreezeAST(fptr->code, s);
     if (fptr->nextFunction)
     {
         s->putBool(true);
         Nelson::FreezeMacroFunction(fptr->nextFunction, s);
     }
     else
     {
         s->putBool(false);
     }
 }
getContinuationCount()
int Nelson::getContinuationCount ()
Retrieve the contents of the continuationCount.
Definition at line 1057 of file NelsonLexer.cpp.
Referenced by Nelson::Evaluator::evalCLI().
     {
         return continuationCount;
     }
GetLexTokenDescription()
void Nelson::GetLexTokenDescription (char * buffer)
Get an error message that describes the current token
getParsedFunctionDef()
NLSINTERPRETER_IMPEXP MacroFunctionDef * Nelson::getParsedFunctionDef ()
Get the function definition from a parse of a function-definition.
Definition at line 3623 of file NelSonParser.cpp.
     {
         return mainMDef;
     }
getParsedScriptBlock()
NLSINTERPRETER_IMPEXP ASTPtr Nelson::getParsedScriptBlock ()
Get the AST from a parse of a script or statement sequence.
Definition at line 3618 of file NelSonParser.cpp.
Referenced by Nelson::Evaluator::evaluateString().
     {
         return mainAST;
     }
GreaterEquals()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::GreaterEquals (ArrayOf A, ArrayOf B)
Element-wise compare (ge) of two arrays: C = A >= B
Definition at line 83 of file GreaterEquals.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, ">=");
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         //Cp = Malloc(Clen*sizeof(logical));
         Cp = new_with_exception<logical>(Clen);
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 greaterequalsfuncreal<int32>(Clen, (logical*)Cp,
                                              (int32*)A.getDataPointer(), Astride,
                                              (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 greaterequalsfuncreal<float>(Clen, (logical*)Cp,
                                              (float*)A.getDataPointer(), Astride,
                                              (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 greaterequalsfuncreal<double>(Clen, (logical*)Cp,
                                               (double*)A.getDataPointer(), Astride,
                                               (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 greaterequalsfunccomplex<float>(Clen, (logical*)Cp,
                                                 (float*)A.getDataPointer(), Astride,
                                                 (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 greaterequalsfunccomplex<double>(Clen, (logical*)Cp,
                                                  (double*)A.getDataPointer(), Astride,
                                                  (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
GreaterThan()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::GreaterThan (ArrayOf A, ArrayOf B)
Element-wise compare (gt).
Definition at line 83 of file GreaterThan.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, ">");
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         //Cp = Malloc(Clen*sizeof(logical));
         Cp = new_with_exception<logical>(Clen);
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 greaterthanfuncreal<int32>(Clen, (logical*)Cp,
                                            (int32*)A.getDataPointer(), Astride,
                                            (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 greaterthanfuncreal<float>(Clen, (logical*)Cp,
                                            (float*)A.getDataPointer(), Astride,
                                            (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 greaterthanfuncreal<double>(Clen, (logical*)Cp,
                                             (double*)A.getDataPointer(), Astride,
                                             (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 greaterthanfunccomplex<float>(Clen, (logical*)Cp,
                                               (float*)A.getDataPointer(), Astride,
                                               (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 greaterthanfunccomplex<double>(Clen, (logical*)Cp,
                                                (double*)A.getDataPointer(), Astride,
                                                (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
LeftDivide()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::LeftDivide (ArrayOf A, ArrayOf B) throw (Exception)
Matrix-matrix divide LEFTDIVIDE / Operator
Definition at line 22 of file LeftDivide.cpp.
Referenced by RightDivide().
     {
         if (A.isEmpty() || B.isEmpty())
         {
             return ArrayOf::emptyConstructor();
         }
         throw Exception(_W("LeftDivide currently not implemented in Nelson."));
     }
LessEquals()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::LessEquals (ArrayOf A, ArrayOf B)
Element-wise compare (le) of two arrays: C = (A <= B)
Definition at line 85 of file LessEquals.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, "<=");
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         //Cp = Malloc(Clen*sizeof(logical));
         Cp = new_with_exception<logical>(Clen);
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 lessequalsfuncreal<int32>(Clen, (logical*)Cp,
                                           (int32*)A.getDataPointer(), Astride,
                                           (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 lessequalsfuncreal<float>(Clen, (logical*)Cp,
                                           (float*)A.getDataPointer(), Astride,
                                           (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 lessequalsfuncreal<double>(Clen, (logical*)Cp,
                                            (double*)A.getDataPointer(), Astride,
                                            (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 lessequalsfunccomplex<float>(Clen, (logical*)Cp,
                                              (float*)A.getDataPointer(), Astride,
                                              (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 lessequalsfunccomplex<double>(Clen, (logical*)Cp,
                                               (double*)A.getDataPointer(), Astride,
                                               (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
LessThan()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::LessThan (ArrayOf A, ArrayOf B)
Element-wise compare (lt) of two arrays.
Definition at line 83 of file LessThan.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, "<");
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         Cp = new_with_exception<logical>(Clen);
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 lessthanfuncreal<int32>(Clen, (logical*)Cp,
                                         (int32*)A.getDataPointer(), Astride,
                                         (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 lessthanfuncreal<float>(Clen, (logical*)Cp,
                                         (float*)A.getDataPointer(), Astride,
                                         (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 lessthanfuncreal<double>(Clen, (logical*)Cp,
                                          (double*)A.getDataPointer(), Astride,
                                          (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 lessthanfunccomplex<float>(Clen, (logical*)Cp,
                                            (float*)A.getDataPointer(), Astride,
                                            (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 lessthanfunccomplex<double>(Clen, (logical*)Cp,
                                             (double*)A.getDataPointer(), Astride,
                                             (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
lexCheckForMoreInput()
bool Nelson::lexCheckForMoreInput (int pcount)
Lex the file, and then check to see if more input is needed.
Definition at line 1040 of file NelsonLexer.cpp.
Referenced by Nelson::Evaluator::evalCLI().
     {
         try
         {
             while (yylex() > 0);
             return ((continuationCount>ccount) ||
                     ((bracketStackSize>0) && ((bracketStack[bracketStackSize - 1] == '[') || (bracketStack[bracketStackSize - 1] == '{'))) ||
                     inBlock);
         }
         catch (Exception &e)
         {
             e.what();
             continuationCount = 0;
             return false;
         }
     }
lexSetAdditionalInput()
void Nelson::lexSetAdditionalInput (char * buffer)
Set the contents of the lexical buffer, and reset the continuationCount to zero.
MatrixCheck()
NLSAPI_NELSON_IMPEXP bool Nelson::MatrixCheck (ArrayOf & A, ArrayOf & B, std::string opname) throw (Exception)
We want to perform a matrix-matrix operation between two data objects. The following checks are required:
If A or B is a scalar, then return false - this is really a vector operation, and the arguments should be passed to a vector checker (like VectorCheck).
Both A & B must be numeric
Both A & B must be the same type (if not, the lesser type is automatically promoted).
Both A & B must be 2-Dimensional.
A & B must be conformant, i.e. the number of columns in A must match the number of rows in B.
Definition at line 33 of file MatrixCheck.cpp.
Referenced by RightDivide().
     {
         // Test for either a scalar (test 1)
         if (A.isScalar() || B.isScalar())
         {
             return false;
         }
         // Test for A & B numeric
         CheckNumeric(A, B, opname);
         // Test for 2D
         if (!A.is2D() || !B.is2D())
             throw Exception(std::string(_("Cannot apply matrix operation ")) +
                             opname + std::string(_(" to N-Dimensional arrays.")));
         // Test the types
         TypeCheck(A, B, true);
         return true;
     }
MultiplyOperator()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::MultiplyOperator (ArrayOf A, ArrayOf B) throw (Exception)
Matrix-matrix multiply times operator *
Negate()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Negate (ArrayOf A) throw (Exception)
Element-wise negate.
Definition at line 31 of file Negate.cpp.
     {
         ArrayOf C;
         Class Aclass;
         if (A.isReferenceType())
         {
             throw Exception(L"Cannot negate non-numeric types.");
         }
         Aclass = A.getDataClass();
         if (A.isSingleString())
         {
             Aclass = NLS_DOUBLE;
         }
         else if (Aclass < NLS_INT32)
         {
             Aclass = NLS_INT32;
         }
         A.promoteType(Aclass);
         C = ArrayOf(Aclass, A.getDimensions(), NULL);
         void *Cp = C.allocateArrayOf(Aclass, A.getLength());
         switch (Aclass)
         {
             case NLS_INT32:
                 negate<int32>(A.getLength(), (int32*)Cp, (int32*)A.getDataPointer());
                 break;
             case NLS_SINGLE:
                 negate<float>(A.getLength(), (float*)Cp, (float*)A.getDataPointer());
                 break;
             case NLS_DOUBLE:
                 negate<double>(A.getLength(), (double*)Cp, (double*)A.getDataPointer());
                 break;
             case NLS_SCOMPLEX:
                 negate<float>(2 * A.getLength(), (float*)Cp, (float*)A.getDataPointer());
                 break;
             case NLS_DCOMPLEX:
                 negate<double>(2 * A.getLength(), (double*)Cp, (double*)A.getDataPointer());
                 break;
         }
         C.setDataPointer(Cp);
         return C;
     }
Not()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Not (ArrayOf A)
Element-wise not of argument: C = !A.
Definition at line 30 of file Not.cpp.
     {
         ArrayOf C;
         A.promoteType(NLS_LOGICAL);
         C = ArrayOf(NLS_LOGICAL, A.getDimensions(), NULL);
         void *Cp = C.allocateArrayOf(NLS_LOGICAL, A.getLength());
         boolean_not(A.getLength(), (logical*)Cp, (const logical*)A.getDataPointer());
         C.setDataPointer(Cp);
         return C;
     }
NotEquals()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::NotEquals (ArrayOf A, ArrayOf B)
EElement-wise compare (ne) of two arrays: C = A != B
Definition at line 55 of file NotEquals.cpp.
     {
         // Process the two arguments through the type check and dimension checks...
         VectorCheck(A, B, false, "~=");
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         //Cp = Malloc(Clen*sizeof(logical));
         Cp = new_with_exception<int32>(Clen);
         switch (B.getDataClass())
         {
             case NLS_INT32:
                 notequalsfuncreal<int32>(Clen, (logical*)Cp,
                                          (int32*)A.getDataPointer(), Astride,
                                          (int32*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SINGLE:
                 notequalsfuncreal<float>(Clen, (logical*)Cp,
                                          (float*)A.getDataPointer(), Astride,
                                          (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DOUBLE:
                 notequalsfuncreal<double>(Clen, (logical*)Cp,
                                           (double*)A.getDataPointer(), Astride,
                                           (double*)B.getDataPointer(), Bstride);
                 break;
             case NLS_SCOMPLEX:
                 notequalsfunccomplex<float>(Clen, (logical*)Cp,
                                             (float*)A.getDataPointer(), Astride,
                                             (float*)B.getDataPointer(), Bstride);
                 break;
             case NLS_DCOMPLEX:
                 notequalsfunccomplex<double>(Clen, (logical*)Cp,
                                              (double*)A.getDataPointer(), Astride,
                                              (double*)B.getDataPointer(), Bstride);
                 break;
         }
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
Or()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Or (ArrayOf A, ArrayOf B)
Element-wise or of two arrays: C = A or B. C = A || B
Definition at line 37 of file Or.cpp.
     {
         int Astride, Bstride;
         void *Cp = nullptr;
         indexType Clen = 0;
         Dimensions Cdim;
         BoolVectorCheck(A, B, "|");
         if (A.isScalar())
         {
             Astride = 0;
             Bstride = 1;
             Cdim = B.getDimensions();
         }
         else if (B.isScalar())
         {
             Astride = 1;
             Bstride = 0;
             Cdim = A.getDimensions();
         }
         else
         {
             Astride = 1;
             Bstride = 1;
             Cdim = A.getDimensions();
         }
         Clen = Cdim.getElementCount();
         Cp = ArrayOf::allocateArrayOf(NLS_LOGICAL, Clen);
         boolean_or(Clen, (logical*)Cp, (const logical*)A.getDataPointer(), Astride,
                    (const logical*)B.getDataPointer(), Bstride);
         return ArrayOf(NLS_LOGICAL, Cdim, Cp);
     }
parseFile()
NLSINTERPRETER_IMPEXP ParserState Nelson::parseFile (FILE * , const char *)
Parse the given file (with the given filename).
Definition at line 3649 of file NelSonParser.cpp.
     {
         resetParser();
         interactiveMode = false;
         setParserFilename(fname);
         setLexFile(fp);
         yyparse();
         ParserState pstate = parseState();
         setParserFilename("");
         return pstate;
     }
parseState()
NLSINTERPRETER_IMPEXP ParserState Nelson::parseState ()
Get the current parser state.
Definition at line 3628 of file NelSonParser.cpp.
Referenced by parseFile(), and parseString().
     {
         if (mainAST != nullptr)
         {
             return ScriptBlock;
         }
         else
         {
             return FuncDef;
         }
     }
parseString()
NLSINTERPRETER_IMPEXP ParserState Nelson::parseString (std::string txt)
Parse the given string.
Definition at line 3640 of file NelSonParser.cpp.
Referenced by Nelson::Evaluator::evaluateString().
     {
         resetParser();
         interactiveMode = true;
         setLexBuffer(txt.c_str());
         yyparse();
         return parseState();
     }
Power()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Power (ArrayOf A, ArrayOf B) throw (Exception)
Matrix to matrix power. A^B
Definition at line 24 of file Power.cpp.
     {
         if (A.isEmpty() || B.isEmpty())
         {
             return ArrayOf::emptyConstructor();
         }
         if (A.isScalar() && B.isScalar())
         {
             return DotPower(A, B);
         }
         // Check for A & B numeric
         CheckNumeric(A, B, "^");
         // Test for 2D on both A & B
         if (!A.is2D() || !B.is2D())
         {
             throw Exception(_W("Cannot apply exponential operation to N-Dimensional arrays."));
         }
         // Test the types
         TypeCheck(A, B, true);
         // Both arguments must be square
         if ((A.getDimensionLength(0) != A.getDimensionLength(1)) ||
                 (B.getDimensionLength(0) != B.getDimensionLength(1)))
         {
             throw Exception(_W("Power (^) operator can only be applied to scalar and square arguments."));
         }
         throw Exception(_W("Power (^) currently not implemented in Nelson."));
     }
printAST()
NLSINTERPRETER_IMPEXP void Nelson::printAST (ASTPtr t)
Print out the tree Print out the tree using a tab-level scheme. Peers are printed at the same tab level, children are printed at a higher tab level.
Definition at line 239 of file AST.cpp.
Referenced by Nelson::MacroFunctionDef::printMe().
     {
         if (t==NULL)
         {
             return;
         }
         if (t->isEmpty())
         {
             return;
         }
         outTabs();
         if (t->type == reserved_node)
         {
             printf("<%d,%s>\r\n",t->tokenNumber,keyWord[t->tokenNumber].word);
         }
         else if (t->type == non_terminal)
         {
             switch (t->opNum)
             {
                     cnum(OP_BLOCK,"block");
                     cnum(OP_CASEBLOCK,"caseblock");
                     cnum(OP_RHS,"rhs");
                     cnum(OP_CSTAT,"cond. statement");
                     cnum(OP_ELSEIFBLOCK,"elseifblock");
                     cnum(OP_ASSIGN,"assign");
                     cnum(OP_MULTICALL,"multicall");
                     cnum(OP_COLON,":");
                     cnum(OP_PLUS,"+");
                     cnum(OP_SUBTRACT,"-");
                     cnum(OP_TIMES,"*");
                     cnum(OP_RDIV,"/");
                     cnum(OP_LDIV,"\\");
                     cnum(OP_OR,"|");
                     cnum(OP_AND,"&");
                     cnum(OP_LT,"<");
                     cnum(OP_LEQ,"<=");
                     cnum(OP_GT,">");
                     cnum(OP_GEQ,">=");
                     cnum(OP_EQ,"==");
                     cnum(OP_NEQ,"!=");
                     cnum(OP_DOT_TIMES,".*");
                     cnum(OP_DOT_RDIV,"./");
                     cnum(OP_DOT_LDIV,".\\");
                     cnum(OP_NEG,"neg");
                     cnum(OP_POS, "pos");
                     cnum(OP_NOT,"~");
                     cnum(OP_POWER,"^");
                     cnum(OP_DOT_POWER,".^");
                     cnum(OP_TRANSPOSE,"'");
                     cnum(OP_DOT_TRANSPOSE,".'");
                     cnum(OP_EMPTY,"empty []");
                     cnum(OP_EMPTY_CELL,"empty {}");
                     cnum(OP_PARENS,"()");
                     cnum(OP_BRACES,"{}");
                     cnum(OP_BRACKETS,"[]");
                     cnum(OP_DOT,".");
                     cnum(OP_ALL,"all");
                     cnum(OP_INDEX_LIST,"index list");
                     cnum(OP_ROW_DEF,"row def");
                     cnum(OP_SEMICOLON,";");
                     cnum(OP_NULL,"null");
                     cnum(OP_RSTATEMENT,"end stat.");
                     cnum(OP_QSTATEMENT,"end quiet stat.");
                     cnum(OP_SCALL,"special call");
                     cnum(OP_KEYWORD,"keyword");
                     cnum(OP_DOTDYN,".()");
             }
             printf("\r\n");
         }
         else if (t->type == id_node)
         {
             printf("ident: %s\r\n", t->text.c_str());
         }
         else if (t->type == const_int_node)
         {
             printf("int: %s\r\n", t->text.c_str());
         }
         else if (t->type == const_uint64_node)
         {
             printf("int: %s\r\n", t->text.c_str());
         }
         else if (t->type == const_double_node)
         {
             printf("double: %s\r\n", t->text.c_str());
         }
         else if (t->type == const_float_node)
         {
             printf("single: %s\r\n", t->text.c_str());
         }
         else if (t->type == const_dcomplex_node)
         {
             printf("double: %si\r\n", t->text.c_str());
         }
         else if (t->type == const_complex_node)
         {
             printf("single: %si\r\n", t->text.c_str());
         }
         else if (t->type == string_const_node)
         {
             printf("string: '%s'\r\n", t->text.c_str());
         }
         else if (t->type == null_node)
         {
         }
         else
         {
             printf("context: %s\r\n", t->text.c_str());
         }
         tabLevel++;
         printAST(t->down);
         tabLevel--;
         printAST(t->right);
     }
resetParser()
NLSINTERPRETER_IMPEXP void Nelson::resetParser ()
Reset the parser to its default state.
Definition at line 3606 of file NelSonParser.cpp.
Referenced by Nelson::Evaluator::evaluateString(), parseFile(), and parseString().
     {
         if (mainAST)
         {
             mainAST = nullptr;
         }
         if (mainMDef)
         {
             mainMDef = nullptr;
         }
     }
RightDivide()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::RightDivide (ArrayOf A, ArrayOf B)
The right divide operation is related to the left divide operation via: B/A = (A'')'.
Definition at line 25 of file RightDivide.cpp.
     {
         ArrayOf C;
         if (A.isEmpty() || B.isEmpty())
         {
             return ArrayOf::emptyConstructor();
         }
         // Process our arguments
         if (!MatrixCheck(A, B, "/"))
             // Its really a vector product, pass...
         {
             return DotRightDivide(A, B);
         }
         //A.transpose();
         //B.transpose();
         C = LeftDivide(B, A);
         //C.transpose();
         return C;
     }
setLexBuffer()
void Nelson::setLexBuffer (const char * buffer)
Set the string buffer to be processed by the lexer.
Definition at line 997 of file NelsonLexer.cpp.
Referenced by Nelson::Evaluator::evalCLI(), and parseString().
     {
         continuationCount = 0;
         bracketStackSize = 0;
         inBlock = 0;
         lexState = Initial;
         vcStackSize = 0;
         clearTextBufferLexer();
         textbuffer = (char*) calloc(strlen(buf)+1,sizeof(char));
         datap = textbuffer;
         strcpy(textbuffer,buf);
         linestart = datap;
         lineNumber = 0;
     }
setLexFile()
void Nelson::setLexFile (FILE * fp)
Set the FILE pointer for the file to be processed by the lexer.
Definition at line 1012 of file NelsonLexer.cpp.
Referenced by parseFile().
     {
         inBlock = 0;
         struct stat st;
         clearerr(fp);
 #ifdef _MSC_VER
         fstat(_fileno(fp),&st);
 #else
         fstat(fileno(fp),&st);
 #endif
         bracketStackSize = 0;
         lexState = Initial;
         vcStackSize = 0;
         lineNumber = 0;
         long cpos = st.st_size;
         clearTextBufferLexer();
         // Allocate enough for the text, an extra newline, and null
         textbuffer = (char*) calloc(cpos+2,sizeof(char));
         if (textbuffer)
         {
             datap = textbuffer;
             size_t n = fread(textbuffer, sizeof(char), cpos, fp);
             textbuffer[n] = '\n';
             textbuffer[n + 1] = 0;
             linestart = datap;
         }
     }
ThawAST()
NLSINTERPRETER_IMPEXP ASTPtr Nelson::ThawAST (Serialize * s)
Thaw an AST tree Given a serialization object pointing to the beginning of a frozen AST, reads the AST from the serialized stream and returns a pointer to the resulting AST.
Definition at line 369 of file AST.cpp.
Referenced by ThawMacroFunction().
     {
         char flag;
         flag = s->getByte();
         if (!flag)
         {
             return nullptr;
         }
         ASTPtr t = new AST();
         if (t)
         {
             t->type = (NODE_TYPE)s->getByte();
             t->tokenNumber = s->getInt();
             t->opNum = (OP_TYPE)s->getByte();
             t->text = s->getString();
             t->down = ThawAST(s);
             t->right = ThawAST(s);
         }
         return t;
     }
ThawMacroFunction()
MacroFunctionDef * Nelson::ThawMacroFunction (Serialize * s)
Routine to thaw an M-function from a stream.
Definition at line 352 of file MacroFunctionDef.cpp.
Referenced by Nelson::MacroFunctionDef::type().
 {
     MacroFunctionDef *t = new MacroFunctionDef();
     if (t)
     {
         t->name = s->getString();
         t->arguments = s->getStringVector();
         t->returnVals = s->getStringVector();
         t->localFunction = s->getBool();
         t->code = ThawAST(s);
         bool nextFun = s->getBool();
         if (nextFun)
         {
             t->nextFunction = ThawMacroFunction(s);
             t->nextFunction->prevFunction = t;
         }
         else
         {
             t->nextFunction = nullptr;
         }
     }
     return t;
 }
Transpose()
NLSELEMENTARY_FUNCTIONS_IMPEXP ArrayOf Nelson::Transpose (ArrayOf A)
Transposes the argument.
Definition at line 23 of file Transpose.cpp.
     {
         switch (A.getDataClass())
         {
             case NLS_DOUBLE:
             {
                 ArrayOf Res(A);
                 Eigen::Map<Eigen::MatrixXd> matOrigin((double*)Res.getDataPointer(), Res.getDimensions().getColumns(), Res.getDimensions().getRows());
                 Eigen::Map<Eigen::MatrixXd> matTransposed((double*)Res.getDataPointer(), Res.getDimensions().getRows(), Res.getDimensions().getColumns());
                 matTransposed = matOrigin.transpose().eval();
                 return Res;
             }
             break;
         }
         return A;
     }
TypeCheck()
NLSAPI_NELSON_IMPEXP void Nelson::TypeCheck (ArrayOf & A, ArrayOf & B, bool isDivOrMatrix)
Check that both of the argument objects are of the same type. If not, apply conversion. Here are the rules: Float operations produce float results. Double operations produce double results. Mixtures of float and double operations produce double results. Integer operations (of any kind) produce int results - the question is what type do these objects get promoted too? The answer is a signed int (32 bits). Mixtures of real and complex operations produce complex results. Integer constants are 32 bit by default Float constants are 64 bit by default Division operations lead to promotion Character types are automatically (demoted) to 32 bit integers.
The way to accomplish this is as follows: compute the larger of the types of A and B. Call this type t_max. If t_max is not an integer type, promote both types to this type. If t_max is an integer type, promote both objects to an NLS_INT32. If this is a division operation or a matrix operation, promote both objects to an NLS_DOUBLE64!
Definition at line 51 of file MatrixCheck.cpp.
Referenced by MatrixCheck(), Power(), and VectorCheck().
     {
         Class Aclass, Bclass, Cclass;
         Aclass = A.getDataClass();
         Bclass = B.getDataClass();
         if ( (Aclass == Bclass) &&
                 ( (Aclass == NLS_LOGICAL) ||
                   (Aclass == NLS_UINT8) ||
                   (Aclass == NLS_INT8) ||
                   (Aclass == NLS_UINT16) ||
                   (Aclass == NLS_INT16) ||
                   (Aclass == NLS_UINT32) ||
                   (Aclass == NLS_INT32) ||
                   (Aclass == NLS_UINT64) ||
                   (Aclass == NLS_INT64) ||
                   (Aclass == NLS_SINGLE) ||
                   (Aclass == NLS_DOUBLE) ||
                   (Aclass == NLS_SCOMPLEX) ||
                   (Aclass == NLS_DCOMPLEX) ||
                   (Aclass == NLS_STRING)) )
         {
             return;
         }
         if ((Aclass < NLS_INT32) || (Aclass == NLS_STRING))
         {
             Aclass = NLS_INT32;
         }
         if ((Bclass < NLS_INT32) || (Bclass == NLS_STRING))
         {
             Bclass = NLS_INT32;
         }
         // Division or matrix operations do no allow integer
         // data types.  These must be promoted to doubles.
         if (isDivOrMatrix && (Aclass < NLS_SINGLE))
         {
             Aclass = NLS_DOUBLE;
         }
         if (isDivOrMatrix && (Bclass < NLS_SINGLE))
         {
             Bclass = NLS_DOUBLE;
         }
         // An integer or double mixed with a complex is promoted to a dcomplex type
         if ((Aclass == NLS_SCOMPLEX) && ((Bclass == NLS_DOUBLE) || (Bclass < NLS_SINGLE)))
         {
             Bclass = NLS_DCOMPLEX;
         }
         if ((Bclass == NLS_SCOMPLEX) && ((Aclass == NLS_DOUBLE) || (Aclass < NLS_SINGLE)))
         {
             Aclass = NLS_DCOMPLEX;
         }
         // The output class is now the dominant class remaining:
         Cclass = (Aclass > Bclass) ? Aclass : Bclass;
         A.promoteType(Cclass);
         B.promoteType(Cclass);
     }
VectorCheck()
NLSAPI_NELSON_IMPEXP void Nelson::VectorCheck (ArrayOf & A, ArrayOf & B, bool promote, std::string opname) throw (Exception)
We want to perform a vector operation between two data objects. The following checks are required:
Both A & B must be numeric
Either A & B are the same size or A is a scalar or B is a scalar.
Definition at line 114 of file MatrixCheck.cpp.
Referenced by DotLeftDivide(), DotRightDivide(), Equals(), GreaterEquals(), GreaterThan(), LessEquals(), LessThan(), and NotEquals().
     {
         stringVector dummySV;
         // Check for numeric types
         CheckNumeric(A, B, opname);
         if (!(SameSizeCheck(A.getDimensions(), B.getDimensions()) || A.isScalar() || B.isScalar()))
         {
             throw Exception(std::string(_("Size mismatch on arguments to arithmetic operator ")) + opname);
         }
         // Test the types.
         TypeCheck(A, B, promote);
     }
Variable Documentation
InterruptPending
bool Nelson::InterruptPending = false
Pending control-C
Definition at line 97 of file Evaluator.cpp.
keyWord
keywordStruct Nelson::keyWord
Initial value:
=
    {
        { "abort", ABORT, NLS_KEYWORD_ABORT },
        { "break", BREAK, NLS_KEYWORD_BREAK },
        { "case", CASE, NLS_KEYWORD_CASE },
        { "catch", CATCH, NLS_KEYWORD_CATCH },
        { "continue", CONTINUE, NLS_KEYWORD_CONTINUE },
        { "else", ELSE, NLS_KEYWORD_ELSE },
        { "elseif", ELSEIF, NLS_KEYWORD_ELSEIF },
        { "end", END, NLS_KEYWORD_END },
        { "endfunction", ENDFUNCTION, NLS_KEYWORD_ENDFUNCTION },
        { "for", FOR, NLS_KEYWORD_FOR },
        { "function", FUNCTION, NLS_KEYWORD_FUNCTION },
        { "if", IF, NLS_KEYWORD_IF },
        { "otherwise", OTHERWISE, NLS_KEYWORD_OTHERWISE },
        { "parfor", FOR, NLS_KEYWORD_FOR },
        { "pause", PAUSE, NLS_KEYWORD_PAUSE },
        { "quit", QUIT, NLS_KEYWORD_QUIT },
        { "return", RETURN, NLS_KEYWORD_RETURN },
        { "switch", SWITCH, NLS_KEYWORD_SWITCH },
        { "try", TRY, NLS_KEYWORD_TRY },
        { "while", WHILE, NLS_KEYWORD_WHILE }
    }
NOTE: This list must be sorted alphabetically!
Definition at line 31 of file Keywords.cpp.
Referenced by printAST().
NLS_KEYWORD_BREAK
const unsigned int Nelson::NLS_KEYWORD_BREAK = 0
These keywords must be in alphabetical order.
Definition at line 34 of file Keywords.hpp.
Referenced by Nelson::Evaluator::statementType().