var searchData = [
  [
    "retcount",
    [
      "retCount",
      [
        "../class_nelson_1_1_built_in_function_def.html#aa5524bae97a1a03534c5bd4b7e6a8be6",
        1,
        "Nelson::BuiltInFunctionDef",
      ],
    ],
  ],
  [
    "returnvals",
    [
      "returnVals",
      [
        "../class_nelson_1_1_macro_function_def.html#a424429f3ae05e08dcf245bb5b27bc37b",
        1,
        "Nelson::MacroFunctionDef",
      ],
    ],
  ],
];
