Nelson: Nelson::ArrayOf Class Reference
Nelson::ArrayOf Class Reference
#include <ArrayOf.hpp>
Public Member Functions
void toOrdinalType ()
void ensureSingleOwner ()
ArrayOf ()
ArrayOf (const ArrayOf &copy)
ArrayOf (Class type)
ArrayOf (Class, const Dimensions &, void *, bool sparse=false, const stringVector &=stringVector())
~ArrayOf ()
void operator= (const ArrayOf &copy)
int getReferenceCount () const
indexType getLength () const
Dimensions getDimensions () const
stringVector getFieldNames () const
indexType getDimensionLength (int) const
const void * getDataPointer () const
const void * getSparseDataPointer () const
void * getReadWriteDataPointer ()
void setDataPointer (void *)
void resize (Dimensions &a)
void vectorResize (indexType)
void reshape (Dimensions &a)
Class getDataClass () const
indexType getElementSize () const
indexType getByteSize () const
const bool isPositive () const
const bool isSymmetric () const
const bool isRealAllZeros () const
const bool isSparse () const
const bool isSparseDouble () const
const bool isSparseLogical () const
void makeSparse ()
void makeDense ()
indexType getNonzeros () const
const bool testCaseMatchScalar (ArrayOf x) const
const bool testForCaseMatch (ArrayOf x) const
const bool isEmpty (bool allDimensionsIsZero=false) const
const bool isScalar () const
const bool is2D () const
const bool isVector () const
const bool isRowVector () const
const bool isColumnVector () const
const bool isReferenceType () const
const bool isComplex () const
const bool isReal () const
const bool allReal () const
const bool isDoubleSparseType () const
const bool isNdArrayDoubleType () const
const bool isDoubleType () const
const bool isSingleType () const
const bool isNdArraySingleType () const
const bool isString () const
const bool isSingleString () const
const bool isNdArrayStringType () const
const bool isIntegerType () const
const bool isNdArrayIntegerType () const
void copyElements (indexType srcIndex, void *dstPtr, indexType dstIndex, indexType count)
void promoteType (Class new_type, stringVector fieldNames)
void promoteType (Class new_type)
ArrayOf getValueAtIndex (uint64 index)
void setValueAtIndex (uint64 index, ArrayOf scalarValue)
ArrayOf getVectorSubset (ArrayOf &index)
ArrayOf getNDimSubset (ArrayOfVector &index)
ArrayOf getVectorContents (ArrayOf &index)
ArrayOf getNDimContents (ArrayOfVector &index)
ArrayOf getField (std::string fieldName)
ArrayOfVector getFieldAsList (std::string fieldName)
ArrayOfVector getVectorContentsAsList (ArrayOf &index)
ArrayOfVector getNDimContentsAsList (ArrayOfVector &index)
void setVectorSubset (ArrayOf &index, ArrayOf &data)
void setNDimSubset (ArrayOfVector &index, ArrayOf &data)
void setVectorContents (ArrayOf &index, ArrayOf &data)
void setNDimContents (ArrayOfVector &index, ArrayOf &data)
void setField (std::string fieldName, ArrayOf &data)
void setVectorContentsAsList (ArrayOf &index, ArrayOfVector &data)
void setNDimContentsAsList (ArrayOfVector &index, ArrayOfVector &data)
void setFieldAsList (std::string fieldName, ArrayOfVector &data)
void deleteVectorSubset (ArrayOf &ndx)
void deleteNDimSubset (ArrayOfVector &args)
void summarizeCellEntry () const
void printMe (int printLimit, sizeType termWidth=80) const
std::string getContentsAsCString (void) const
std::wstring getContentsAsWideString () const
std::wstring getContentsAsArrayOfCharacters () const
wstringVector getContentAsWideStringVector (bool bCheckVector=true) const
stringVector getContentAsCStringVector (bool bCheckVector=true) const
wstringVector getContentAsWideStringRowVector (void) const
stringVector getContentAsCStringRowVector (void) const
wstringVector getContentAsWideStringColumnVector (void) const
stringVector getContentAsCStringColumnVector (void) const
logical getContentAsLogicalScalar () const
int64 getContentsAsInteger64Scalar ()
int32 getContentsAsInteger32Scalar ()
double getContentsAsDoubleScalar ()
uint64 getContentsAsUnsignedInt64Scalar ()
indexType getContentAsScalarIndex (bool bWithZero=true)
indexType * getContentAsIndexPointer ()
doublecomplex getContentsAsDoubleComplexScalar ()
single getContentsAsSingleScalar ()
std::complex< single > getContentsAsSingleComplexScalar ()
indexType nnz ()
bool isCell ()
const bool isStruct () const
void setStructType (std::string structname)
void setStructType (std::wstring structname)
std::string getStructType () const
const bool isClassStruct () const
function_handle getContentsAsFunctionHandle ()
bool isFunctionHandle ()
const bool isLogical () const
const bool isNdArrayLogical () const
const bool isLogicalSparseType () const
const bool isNumeric () const
void scalarToMatrix (Dimensions newDimensions)
void deleteArrayOf (void *dp, Class dataclass)
Static Public Member Functions
static void * allocateArrayOf (Class, indexType length, const stringVector &names=stringVector())
static ArrayOf diagonalConstructor (ArrayOf src, int diagonalOrder)
static ArrayOf emptyConstructor (Dimensions dim, bool bIsSparse=false)
static ArrayOf emptyConstructor (indexType m=0, indexType n=0, bool bIsSparse=false)
static ArrayOf logicalConstructor (bool aval)
static ArrayOf uint8Constructor (uint8 aval)
static ArrayOf int8Constructor (int8 aval)
static ArrayOf uint16Constructor (uint16 aval)
static ArrayOf int16Constructor (int16 aval)
static ArrayOf uint32Constructor (uint32 aval)
static ArrayOf int32Constructor (int32 aval)
static ArrayOf uint64Constructor (uint64 aval)
static ArrayOf int64Constructor (int64 aval)
static ArrayOf singleConstructor (float aval)
static ArrayOf doubleConstructor (double aval)
static ArrayOf complexConstructor (float aval, float bval)
static ArrayOf dcomplexConstructor (double aval, double bval)
static ArrayOf stringConstructor (std::string aval)
static ArrayOf stringConstructor (std::wstring aval)
static ArrayOf int64VectorConstructor (int len)
static ArrayOf int32VectorConstructor (int len)
static ArrayOf doubleVectorConstructor (int len)
static ArrayOf integerRangeConstructor (indexType minval, indexType stepsize, indexType maxval, bool vertical)
static ArrayOf cellConstructor (ArrayOfMatrix &m)
static ArrayOf structConstructor (stringVector fNames, ArrayOfVector &values)
static ArrayOf structConstructor (wstringVector fNames, ArrayOfVector &values)
static ArrayOfVector emptyStructWithoutFields ()
static ArrayOf emptyStructConstructor (stringVector fNames, Dimensions dim)
static ArrayOf emptyStructConstructor (wstringVector fNames, Dimensions dim)
static bool isDataClassReferenceType (Class)
static void setArrayOfIOInterface (Interface *io)
static Interface * getArrayOfIOInterface ()
static ArrayOf functionHandleConstructor (std::wstring functionName, function_handle fptr)
Detailed Description
Ordered data array, the base Nelson data type. The ArrayOf class is the base class of all data types. It represents an ordered collection of data, indexed using an arbitrary number of dimensions. The ArrayOf class uses a seperate data class to store the data. It can contain an N-dimensional array of any of the following data types:
NLS_HANDLE
NLS_CELL_ARRAY - a heterogenous array - essentially an array of ArrayOfs
NLS_STRUCT_ARRAY - a structure array
NLS_UINT8 - unsigned, 8-bit integers
NLS_INT8 - signed, 8-bit integers
NLS_UINT16 - unsigned, 16-bit integers
NLS_INT16 - signed, 16-bit integers
NLS_UINT32 - unsigned, 32-bit integers
NLS_INT32 - signed, 32-bit integers
NLS_SINGLE - 32-bit floating point
NLS_DOUBLE - 64-bit floating point
NLS_SCOMPLEX - 32-bit complex floating point
NLS_DCOMPLEX - 64-bit complex floating point
NLS_STRING - a string class
The Dimensions class is used to record the dimensions of the given ArrayOf. The Dimension class represents an n-tuple of integers that record the number of elements along the array in each dimension. The data is stored in a generalization of "column-major" order. Note that the array class does not actually include the data - the data is stored in the Data class, to which ArrayOf contains a pointer. This design allows for rapid copying of ArrayOf objects.
Definition at line 91 of file ArrayOf.hpp.
Constructor & Destructor Documentation
ArrayOf() [1/4]
Nelson::ArrayOf::ArrayOf ()
Default constructor.
Definition at line 817 of file ArrayOf.cpp.
Referenced by allocateArrayOf(), cellConstructor(), complexConstructor(), dcomplexConstructor(), diagonalConstructor(), doubleConstructor(), doubleVectorConstructor(), emptyConstructor(), getElementSize(), getNDimSubset(), getValueAtIndex(), getVectorSubset(), int16Constructor(), int32Constructor(), int32VectorConstructor(), int64Constructor(), int64VectorConstructor(), int8Constructor(), integerRangeConstructor(), logicalConstructor(), setFieldAsList(), singleConstructor(), stringConstructor(), structConstructor(), uint16Constructor(), uint32Constructor(), uint64Constructor(), and uint8Constructor().
     {
         Dimensions dims(0, 0);
         dp = nullptr;
     }
ArrayOf() [2/4]
Nelson::ArrayOf::ArrayOf (const ArrayOf & copy)
Copy constructor.
Definition at line 2328 of file ArrayOf.cpp.
     {
         copyObject(copy);
     }
ArrayOf() [3/4]
Nelson::ArrayOf::ArrayOf (Class type)
Create an empty ArrayOf of the specified type.
Definition at line 831 of file ArrayOf.cpp.
     {
         Dimensions dims(0, 0);
         dp = new Data(type, dims, NULL);
     }
ArrayOf() [4/4]
Nelson::ArrayOf::ArrayOf (Class type, const Dimensions & dims, void * data, bool sparse = false, const stringVector & fnames = stringVector())
Create an ArrayOf with the specified contents.
Create a variable with the specified contents.
Definition at line 826 of file ArrayOf.cpp.
     {
         dp = new Data(type, dims, data, sparse, fnames);
     }
~ArrayOf()
Nelson::ArrayOf::~ArrayOf ()
Destructor - free the data object.
Definition at line 840 of file ArrayOf.cpp.
     {
         if (dp)
         {
             int m;
             m = dp->deleteCopy();
             if (m <= 1)
             {
                 delete dp;
             }
             dp = nullptr;
         }
     }
Member Function Documentation
allocateArrayOf()
void * Nelson::ArrayOf::allocateArrayOf (Class type, indexType length, const stringVector & names = stringVector()) static
Allocate an array.
Definition at line 267 of file ArrayOf.cpp.
Referenced by Nelson::And(), cellConstructor(), complexConstructor(), dcomplexConstructor(), deleteNDimSubset(), deleteVectorSubset(), diagonalConstructor(), Nelson::doPowerAssist(), doubleConstructor(), doubleVectorConstructor(), ensureSingleOwner(), getNDimSubset(), getValueAtIndex(), getVectorSubset(), int16Constructor(), int32Constructor(), int32VectorConstructor(), int64Constructor(), int64VectorConstructor(), int8Constructor(), integerRangeConstructor(), logicalConstructor(), Nelson::Negate(), Nelson::Not(), Nelson::Or(), promoteType(), resize(), setFieldAsList(), singleConstructor(), stringConstructor(), structConstructor(), uint16Constructor(), uint32Constructor(), uint64Constructor(), and uint8Constructor().
     {
         switch (type)
         {
             case NLS_HANDLE:
             {
                 return (void*)new_with_exception<nelson_handle>(length);
             }
             break;
             case NLS_CELL_ARRAY:
             {
                 ArrayOf *dp = new_with_exception<ArrayOf>(length);
                 for (indexType i = 0; i < length; i++)
                 {
                     dp[i] = ArrayOf(NLS_DOUBLE);
                 }
                 return dp;
             }
             case NLS_STRUCT_ARRAY:
             {
                 if (!haveValidFieldNames(names))
                 {
                     throw Exception(_W("Field names must be valid."));
                 }
                 if (!haveUniqueFieldNames(names))
                 {
                     throw Exception(_W("Duplicated field detected."));
                 }
                 indexType n = (indexType)(length * names.size());
                 ArrayOf *dp = new_with_exception<ArrayOf>(n);
                 for (indexType i = 0; i < (indexType)(n); i++)
                 {
                     dp[i] = ArrayOf(NLS_DOUBLE);
                 }
                 return dp;
             }
             case NLS_LOGICAL:
             {
                 return (void*)new_with_exception<logical>(length);
             }
             break;
             case NLS_UINT8:
             {
                 return (void*)new_with_exception<uint8>(length);
             }
             break;
             case NLS_INT8:
             {
                 return (void*)new_with_exception<int8>(length);
             }
             break;
             case NLS_UINT16:
             {
                 return (void*)new_with_exception<uint16>(length);
             }
             break;
             case NLS_INT16:
             {
                 return (void*)new_with_exception<int16>(length);
             }
             break;
             case NLS_UINT32:
             {
                 return (void*)new_with_exception<uint32>(length);
             }
             break;
             case NLS_INT32:
             {
                 return (void*)new_with_exception<int32>(length);
             }
             break;
             case NLS_UINT64:
             {
                 return (void*)new_with_exception<uint64>(length);
             }
             break;
             case NLS_INT64:
             {
                 return (void*)new_with_exception<int64>(length);
             }
             break;
             case NLS_SINGLE:
             {
                 return (void *)new_with_exception<float>(length);
             }
             break;
             case NLS_DOUBLE:
             {
                 return (void*)new_with_exception<double>(length);
             }
             break;
             case NLS_SCOMPLEX:
             {
                 return (void*)new_with_exception<float>(2 * length);
             }
             break;
             case NLS_DCOMPLEX:
             {
                 return (void*)new_with_exception<double>(2 * length);
             }
             break;
             case NLS_STRING:
             {
                 return (void*)new_with_exception<charType>(length);
             }
             break;
         }
         return nullptr;
     }
allReal()
const bool Nelson::ArrayOf::allReal () const
Returns TRUE if all values are real.
Definition at line 1722 of file ArrayOf.cpp.
     {
         bool res;
         switch (dp->dataClass)
         {
             case NLS_STRING:
             case NLS_LOGICAL:
             case NLS_UINT8:
             case NLS_INT8:
             case NLS_UINT16:
             case NLS_INT16:
             case NLS_UINT32:
             case NLS_INT32:
             case NLS_UINT64:
             case NLS_INT64:
             case NLS_SINGLE:
             case NLS_DOUBLE:
             {
                 res = true;
             }
             break;
             case NLS_SCOMPLEX:
             {
                 if (isEmpty(true))
                 {
                     res = true;
                 }
                 else
                 {
                     single* psingle = (single *)dp->getData();
                     singlecomplex* Bz = reinterpret_cast<singlecomplex*>(psingle);
                     Eigen::Map<Eigen::MatrixXcf> mat(Bz, 1, dp->getDimensions().getElementCount());
                     res = mat.imag().isZero(0);
                 }
             }
             break;
             case NLS_DCOMPLEX:
             {
                 if (isEmpty(true))
                 {
                     res = true;
                 }
                 else
                 {
                     double* pdouble = (double *)dp->getData();
                     doublecomplex* Bz = reinterpret_cast<doublecomplex*>(pdouble);
                     Eigen::Map<Eigen::MatrixXcd> mat(Bz, 1, dp->getDimensions().getElementCount());
                     res = mat.imag().isZero(0);
                 }
             }
             break;
             case NLS_HANDLE:
             case NLS_CELL_ARRAY:
             case NLS_STRUCT_ARRAY:
             default:
             {
                 res = false;
             }
         }
         return res;
     }
cellConstructor()
ArrayOf Nelson::ArrayOf::cellConstructor (ArrayOfMatrix & m) static
The constructor for a cell array is significantly simpler than the matrix constructor. The argument is a list of rowdefs. Each element in the rowdef is a ArrayOf pointer that we assign to our data pointer. The only thing we need to make sure of is that each row has the same number of elements in it. Throws an exception if the geometry of the argumens is incompatible.
If this is the first row in the matrix def, then we record its size in columnCount.
Otherwise, make sure the column counts are all the same...
At this point, we know how many columns our cell array has, and the number of rows is also known (size of m). So, set up our dimensions, and allocate the output.
Allocate storage space for the contents.
Loop through the rows.
Definition at line 29 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::cellDefinition().
     {
         indexType  columnCount = 0, rowCount = 0;
         ArrayOf* qp = nullptr;
         try
         {
             ArrayOfMatrix::iterator i = m.begin();
             while (i != m.end())
             {
                 ArrayOfVector ptr = *i;
                 if (i == m.begin())
                 {
                     columnCount = ptr.size();
                 }
                 else
                 {
                     if (ptr.size() != columnCount)
                     {
                         throw Exception(_W("Cell definition must have same number of elements in each row"));
                     }
                 }
                 ++i;
             }
             rowCount = m.size();
             Dimensions retDims(2);
             retDims[0] = rowCount;
             retDims[1] = columnCount;
             qp = (ArrayOf *)allocateArrayOf(NLS_CELL_ARRAY, retDims.getElementCount());
             ArrayOf *sp;
             sp = qp;
             i = m.begin();
             while (i != m.end())
             {
                 ArrayOfVector ptr = *i;
                 ArrayOf *cp= sp;
                 for (sizeType j = 0; j < (sizeType)ptr.size(); j++)
                 {
                     *cp = ptr[j];
                     cp += rowCount;
                 }
                 ++i;
                 sp++;
             }
             return ArrayOf(NLS_CELL_ARRAY, retDims, qp);
         }
         catch (Exception &e)
         {
             ArrayOf* rp = (ArrayOf*)qp;
             delete[] rp;
             rp = nullptr;
             qp = nullptr;
             e.what();
             throw;
         }
     }
complexConstructor()
ArrayOf Nelson::ArrayOf::complexConstructor (float aval, float bval) static
Complex constructor - Construct an NLS_SCOMPLEX object with a complex scalar value.
Definition at line 46 of file ArrayOf_SingleType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         float *data = (float *)allocateArrayOf(NLS_SCOMPLEX, 1);
         data[0] = aval;
         data[1] = bval;
         return ArrayOf(NLS_SCOMPLEX, dim, data);
     }
copyElements()
void Nelson::ArrayOf::copyElements (indexType srcIndex, void * dstPtr, indexType dstIndex, indexType count)
Copy data from our data array to the specified array. This is a deep copy, in the sense that pointers are copied by creating new objects. Copy count elements, starting at index srcIndex to the destination address starting at index dstIndex. The addresses are in terms of indices, not bytes.
Definition at line 1784 of file ArrayOf.cpp.
Referenced by deleteNDimSubset(), deleteVectorSubset(), diagonalConstructor(), ensureSingleOwner(), getNDimSubset(), getValueAtIndex(), getVectorSubset(), resize(), setNDimSubset(), and setVectorSubset().
     {
         indexType elSize(getElementSize());
         if (isSparse())
         {
             throw Exception(_W("copyElements not supported for sparse arrays."));
         }
         switch(dp->dataClass)
         {
             case NLS_CELL_ARRAY:
             {
                 const ArrayOf* sp = (const ArrayOf*) dp->getData();
                 ArrayOf* qp = (ArrayOf*) dstPtr;
                 for (indexType i = 0; i<count; i++)
                 {
                     qp[dstIndex+i] = sp[srcIndex+i];
                 }
             }
             break;
             case NLS_STRUCT_ARRAY:
             {
                 const ArrayOf* sp = (const ArrayOf*) dp->getData();
                 ArrayOf* qp = (ArrayOf*) dstPtr;
                 indexType fieldCount(dp->fieldNames.size());
                 for (indexType i = 0; i < count; i++)
                 {
                     for (indexType j = 0; j < (indexType)fieldCount; j++)
                     {
                         qp[(dstIndex + i)*fieldCount + j] = sp[(srcIndex + i)*fieldCount + j];
                     }
                 }
                 if (fieldCount > 0)
                 {
                     if (qp->getDataClass() == NLS_STRUCT_ARRAY)
                     {
                         qp->setStructType(dp->getStructTypeName());
                     }
                 }
             }
             break;
             default:
             {
                 const char* sp = (const char*) dp->getData();
                 if (sp != nullptr)
                 {
                     char* qp = (char *)dstPtr;
                     memcpy(qp + dstIndex*elSize, sp + srcIndex*elSize, count*elSize);
                 }
             }
             break;
         }
     }
dcomplexConstructor()
ArrayOf Nelson::ArrayOf::dcomplexConstructor (double aval, double bval) static
Complex constructor - Construct an NLS_DCOMPLEX object with a complex scalar value.
Definition at line 61 of file ArrayOf_DoubleType.cpp.
Referenced by Nelson::Evaluator::expression().
     {
         Dimensions dim;
         dim.makeScalar();
         double *data = (double *)allocateArrayOf(NLS_DCOMPLEX, 1);
         data[0] = aval;
         data[1] = bval;
         return ArrayOf(NLS_DCOMPLEX, dim, data);
     }
deleteNDimSubset()
void Nelson::ArrayOf::deleteNDimSubset (ArrayOfVector & args)
Delete a subset of this array using the arguments for n-Dimensional indexing. This method is the "planar" delete, meaning that its designed to delete all the entries in an N-ary array in one dimension. It cannot be used to create "holes" in an array. Throws an exception if the argument contains more than one non-colon index
Delete a subset of a variable.
Definition at line 3294 of file ArrayOf.cpp.
Referenced by setNDimSubset().
     {
         indexType singletonReferences = 0;
         indexType singletonDimension = 0;
         indexType i = 0;
         ArrayOf qp;
         bool *indxCovered = nullptr;
         bool *deletionMap = nullptr;
         void *cp = nullptr;
         try
         {
             // Our strategy is as follows.  To make the deletion, we need
             // one piece of information: the dimension to delete.
             // To do so, we first make a pass through the set of arguments,
             // checking each one to see if it "covers" its index set.
             //
             // However, to simplify the testing of
             // conditions later on, we must make sure that the length of
             // the index list matches our number of dimensions.  We extend
             // it using 1 references, and throw an exception if there are
             // more indices than our dimension set.
             for (i=0; i < (indexType)args.size(); i++)
             {
                 args[i].toOrdinalType();
             }
             // First, add enough "1" singleton references to pad the
             // index set out to the size of our variable.
             if ((indexType)args.size() < dp->dimensions.getLength())
                 for (i = args.size(); i<dp->dimensions.getLength(); i++)
                 {
                     args.push_back(ArrayOf::uint32Constructor(1));
                 }
             // Now cycle through indices one at a time.  Count
             // the number of non-covering indices.  Also track the
             // location of the last-occurring non-covering index.
             for (i = 0; i < (indexType)args.size(); i++)
             {
                 qp = args[i];
                 // Get a binary representation of each index over the range [0,dimensions[i]-1]
                 indxCovered = qp.getBinaryMap(dp->dimensions[i]);
                 // Scan the array, and make sure all elements are true.  If not,
                 // then this is the "singleton" dimension.  Kick the singleton
                 // reference counter, and record the current dimension.
                 bool allCovered = true;
                 for (indexType k=0; allCovered && (k<dp->dimensions[i]); k++)
                 {
                     allCovered = allCovered && indxCovered[k];
                 }
                 delete [] indxCovered;
                 indxCovered = nullptr;
                 if (!allCovered)
                 {
                     singletonReferences++;
                     singletonDimension = i;
                 }
             }
             // Now, we check the number of singleton references we
             // encountered.  There are three cases to check:
             //  Case 1. No singleton references.  This is OK - it
             //        means we wish to delete the entire variable.
             //        We set a flag, and proceed to validate the covering
             //        of each dimension by its corresponding index set.
             //  Case 2. One singleton reference.  This is OK - it
             //        means we wish to delete a single plane of
             //        data.  Retrieve the index of the plane, and store
             //        it in singletonIndex.
             //  Case 3. Two or more singleton references.  Can't do it -
             //        throw an error.
             if (singletonReferences > 1)
             {
                 throw Exception(_W("Statement A(...) = [] can only contain one non-colon index."));
             }
             if (singletonReferences == 0)
             {
                 singletonDimension = -1;
             }
             // If we got this far, the user either entered an expression like
             // A(:,:,...,:,s,:,...,:) = [], or something numerically equivalent,
             // or the user entered something like A(:,...,:) = [].
             // In the latter case (indicated by singletonReferences = 0), we simply
             // delete the entire variable, and make it an empty type.
             // In the former case, we will have more work to do...
             if (singletonReferences != 0)
             {
                 // We have to rescan our (now-identified) singleton
                 // dimension to build a deletion map.  The map is
                 // marked true for each plane we wish to delete.
                 // The map is the size of the _data_'s dimension.
                 indexType  M = dp->dimensions[singletonDimension];
                 deletionMap = args[singletonDimension].getBinaryMap(M);
                 // We can now calculate the new size of the variable in the singletonDimension
                 // by counting the number of "false" entries in deletionMap.
                 int newSize = 0;
                 for (i=0; (int)i<M; i++)
                     if (!deletionMap[i])
                     {
                         newSize++;
                     }
                 indexType  rowCount = dp->dimensions[0];
                 Dimensions retDims;
                 // Copy our current dimensions to the output dimensions.
                 retDims = dp->dimensions;
                 // Update the singleton dimension to the new size.
                 retDims[singletonDimension] = newSize;
                 // For sparse matrices, we branch here to call the sparse matrix deletion code
                 if (isSparse())
                 {
                     indexType  rows = getDimensionLength(0);
                     indexType  cols = getDimensionLength(1);
                     if (singletonDimension == 0)
                     {
 #ifdef __NLS_USE_SPARSE_EIGEN
                         dp = dp->putData(dp->dataClass, retDims,
                                          DeleteSparseMatrixRowsDynamicFunction(dp->dataClass, rows, cols,
                                                  dp->getData(), deletionMap), true);
 #else
                         dp = dp->putData(dp->dataClass, retDims,
                                          DeleteSparseMatrixRows(dp->dataClass, rows, cols,
                                                                 dp->getData(), deletionMap), true);
 #endif
                     }
                     else if (singletonDimension == 1)
                     {
 #ifdef __NLS_USE_SPARSE_EIGEN
                         dp = dp->putData(dp->dataClass, retDims,
                                          DeleteSparseMatrixColsDynamicFunction(dp->dataClass, rows, cols,
                                                  dp->getData(), deletionMap), true);
 #else
                         dp = dp->putData(dp->dataClass, retDims,
                                          DeleteSparseMatrixCols(dp->dataClass, rows, cols,
                                                                 dp->getData(), deletionMap), true);
 #endif
                     }
                     else
                     {
                         throw Exception(_W("sparse matrices do not support deleting n-dimensional planes - Only 2-D"));
                     }
                     delete [] deletionMap;
                     deletionMap = nullptr;
                     delete [] indxCovered;
                     indxCovered = nullptr;
                     return;
                 }
                 // Allocate space for the return objects data
                 cp = allocateArrayOf(dp->dataClass,retDims.getElementCount(),dp->fieldNames);
                 // Track our offset into the original data & our offset into
                 // the truncated data.
                 indexType srcIndex = 0;
                 indexType dstIndex = 0;
                 // Inintialize an ND pointer to the first element in the
                 // current data structure.
                 indexType L = dp->dimensions.getLength();
                 Dimensions curPos(L);
                 // Loop until we have exhausted the original data.
                 while (curPos.inside(dp->dimensions))
                 {
                     // Check to see if this column is to be skipped
                     if (!deletionMap[curPos[singletonDimension]])
                     {
                         // Copy the data from our original data structure to the
                         // new data structure, starting from srcIndex, and
                         // copying to dstIndex.
                         copyElements(srcIndex,cp,dstIndex,1);
                         // Advance the destination pointer. - we only do this on a copy
                         dstIndex ++;
                     }
                     // Advance the source pointer - we always do this
                     srcIndex ++;
                     curPos.incrementModulo(dp->dimensions,0);
                 }
                 delete [] deletionMap;
                 deletionMap = nullptr;
                 retDims.simplify();
                 dp = dp->putData(dp->dataClass,retDims,cp,dp->sparse,dp->fieldNames);
             }
             else
             {
                 /* here we need to return empty mxn and not only 0x0*/
                 /*
                     A = [0 2 1 ;
                          3 4 5];
                     A([1 2],:) = []
                 */
                 Dimensions newDims(0, 0);
                 Dimensions d = getDimensions();
                 indexType m = d[0];
                 for (size_t k = 1; k < d.getLength(); ++k)
                 {
                     if (m < d[k])
                     {
                         m = d[k];
                     }
                 }
                 indexType idxm = 0;
                 for (size_t k = 0; k < d.getLength(); ++k)
                 {
                     if (m == d[k])
                     {
                         break;
                     }
                     else
                     {
                         idxm++;
                     }
                 }
                 newDims[idxm] = m;
                 dp = dp->putData(dp->dataClass, newDims, NULL, dp->sparse, dp->fieldNames);
             }
         }
         catch (Exception &e)
         {
             delete[] deletionMap;
             deletionMap = nullptr;
             deleteArrayOf(cp, dp->dataClass);
             cp = nullptr;
             delete [] indxCovered;
             indxCovered = nullptr;
             e.what();
             throw;
         }
     }
deleteVectorSubset()
void Nelson::ArrayOf::deleteVectorSubset (ArrayOf & arg)
Delete a subset of this array using the argument for vector indexing. This is much simpler than the planar case. Here, we simply:
Create a deletion map from the index variable.
Adjust the size of the output, and reshape to a vector.
Copy (and skip) as necessary. The result is then resized using the same rules as in vectorResize.
Delete a vector subset of a variable.
Definition at line 3192 of file ArrayOf.cpp.
Referenced by setVectorSubset().
     {
         void *qp = nullptr;
         bool *deletionMap = nullptr;
         try
         {
             // First convert arg to an ordinal type.
             arg.toOrdinalType();
             if (isSparse())
             {
                 indexType rows = getDimensionLength(0);
                 indexType cols = getDimensionLength(1);
 #ifdef __NLS_USE_SPARSE_EIGEN
                 void *cp = DeleteSparseMatrixVectorSubsetDynamicFunction(dp->dataClass, rows, cols,
                            dp->getData(),
                            (const indexType *)
                            arg.getDataPointer(),
                            arg.getLength());
 #else
                 void *cp = DeleteSparseMatrixVectorSubset(dp->dataClass,rows,cols,
                            dp->getData(),
                            (const indexType *)
                            arg.getDataPointer(),
                            arg.getLength());
 #endif
                 Dimensions newdim;
                 newdim[0] = rows;
                 newdim[1] = cols;
                 dp = dp->putData(dp->dataClass,newdim,cp,true);
                 return;
             }
             // Next, build a deletion map.
             indexType N = getLength();
             indexType i = 0;
             deletionMap = arg.getBinaryMap(N);
             // Now, we count up the number of elements that remain after deletion.
             indexType newSize = 0;
             for (i = 0; i < N; i++)
             {
                 if (!deletionMap[i])
                 {
                     newSize++;
                 }
             }
             // Allocate a new space to hold the data.
             qp = allocateArrayOf(dp->dataClass,newSize,dp->fieldNames);
             // Loop through the indices - copy elements in that
             // have not been deleted.
             indexType dstIndex = 0;
             for (i = 0; i < N; i++)
             {
                 if (!deletionMap[i])
                 {
                     copyElements(i, qp, dstIndex++, 1);
                 }
             }
             delete [] deletionMap;
             deletionMap = nullptr;
             Dimensions newDim;
             if (dp->dimensions.isScalar())
             {
                 newDim.reset();
                 newDim[0] = 1;
                 newDim[1] = newSize;
             }
             else if (dp->dimensions.isVector())
             {
                 newDim = dp->dimensions;
                 if (dp->dimensions[0] != 1)
                 {
                     newDim[0] = newSize;
                 }
                 else
                 {
                     newDim[1] = newSize;
                 }
             }
             else
             {
                 newDim.reset();
                 newDim[0] = 1;
                 newDim[1] = newSize;
             }
             dp = dp->putData(dp->dataClass,newDim,qp,dp->sparse,dp->fieldNames);
         }
         catch (Exception &e)
         {
             deleteArrayOf(qp, dp->dataClass);
             qp = nullptr;
             delete [] deletionMap;
             deletionMap = nullptr;
             e.what();
             throw ;
         }
     }
diagonalConstructor()
ArrayOf Nelson::ArrayOf::diagonalConstructor (ArrayOf src, int diagonalOrder) static
Diagonal constructor - construct an array from a given vector, with the contents of the vector stored into the specified diagonal of the matrix. Throwsn an exception if the argument is not a vector.
Definition at line 2333 of file ArrayOf.cpp.
     {
         ArrayOf retval;
         if (!src.isVector())
         {
             throw Exception(_W("Argument to diagonal constructor must by a vector!"));
         }
         indexType length = src.getLength();
         indexType M = 0;
         // Calculate the size of the output matrix (square of size outLen + abs(diagonalOrder)).
         M = length + abs(diagonalOrder);
         Dimensions dims;
         dims[0] = M;
         dims[1] = M;
         // Allocate space for the output
         void *rp = allocateArrayOf(src.dp->dataClass,dims.getElementCount(),src.dp->fieldNames);
         indexType i = 0;
         indexType dstIndex = 0;
         if (diagonalOrder < 0)
         {
 #if defined(__NLS_WITH_OPENMP)
             #pragma omp parallel for
 #endif
             for (i=0; i<length; i++)
             {
                 dstIndex = -diagonalOrder + i * (M+1);
                 src.copyElements(i,rp,dstIndex,1);
             }
         }
         else
         {
 #if defined(__NLS_WITH_OPENMP)
             #pragma omp parallel for
 #endif
             for (i=0; i<length; i++)
             {
                 dstIndex = diagonalOrder*M + i * (M+1);
                 src.copyElements(i,rp,dstIndex,1);
             }
         }
         return ArrayOf(src.dp->dataClass,dims,rp,false,src.dp->fieldNames);
     }
doubleConstructor()
ArrayOf Nelson::ArrayOf::doubleConstructor (double aval) static
Scalar constructor - Construct an NLS_DOUBLE object with a scalar value.
Definition at line 43 of file ArrayOf_DoubleType.cpp.
Referenced by Nelson::Evaluator::expression(), and Nelson::Evaluator::simpleSubindexExpression().
     {
         Dimensions dim;
         dim.makeScalar();
         double *data = (double *)allocateArrayOf(NLS_DOUBLE, 1);
         *data = aval;
         return ArrayOf(NLS_DOUBLE, dim, data);
     }
doubleVectorConstructor()
ArrayOf Nelson::ArrayOf::doubleVectorConstructor (int len) static
Double vector constructor - Construct an NLS_DOUBLE object that is a (row) vector with the given length.
Definition at line 52 of file ArrayOf_DoubleType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         dim[1] = len;
         double *data = (double*)allocateArrayOf(NLS_DOUBLE, len);
         return ArrayOf(NLS_DOUBLE, dim, data);
     }
emptyConstructor()
ArrayOf Nelson::ArrayOf::emptyConstructor (Dimensions dim, bool bIsSparse = false) static
Empty constructor
Definition at line 2376 of file ArrayOf.cpp.
Referenced by Nelson::Context::addGlobalVariable(), Nelson::Context::addPersistentVariable(), Nelson::doPowerAssist(), Nelson::MacroFunctionDef::evaluateFunction(), Nelson::Evaluator::expression(), Nelson::Evaluator::functionExpression(), getNDimSubset(), getVectorSubset(), Nelson::LeftDivide(), Nelson::Power(), Nelson::Evaluator::rhsExpression(), Nelson::Evaluator::rhsExpressionSimple(), Nelson::RightDivide(), Nelson::Evaluator::simpleSubindexExpression(), and Nelson::Evaluator::statementType().
     {
         if (dim.getElementCount() == 0)
         {
             return ArrayOf(NLS_DOUBLE, dim, NULL, bIsSparse);
         }
         else
         {
             throw Exception(_W("Invalid dimensions."));
         }
         return ArrayOf();
     }
ensureSingleOwner()
void Nelson::ArrayOf::ensureSingleOwner ()
Ensure we have at most one owner for our data - allows us to modify the data without affecting other arrays.
Definition at line 945 of file ArrayOf.cpp.
Referenced by getReadWriteDataPointer(), reshape(), and resize().
     {
         if (dp->numberOfOwners() > 1)
         {
             if (!dp->sparse)
             {
                 void *np = allocateArrayOf(dp->dataClass, getLength(), dp->fieldNames);
                 if (isEmpty())
                 {
                     Dimensions dim = dp->getDimensions();
                     dp = dp->putData(dp->dataClass, dim, np, dp->sparse, dp->fieldNames);
                 }
                 else
                 {
                     copyElements(0, np, 0, getLength());
                     dp = dp->putData(dp->dataClass, dp->dimensions, np, dp->sparse, dp->fieldNames);
                 }
             }
             else
             {
 #ifdef              __NLS_USE_SPARSE_EIGEN
                 dp = dp->putData(dp->dataClass,dp->dimensions,
                                  CopySparseMatrixDynamicFunction(dp->dataClass,
                                          dp->dimensions[0],
                                          dp->dimensions[1],
                                          dp->getData()),
                                  dp->sparse,dp->fieldNames);
 #else
                 dp = dp->putData(dp->dataClass,dp->dimensions,
                                  CopySparseMatrix(dp->dataClass,
                                                   dp->dimensions[0],
                                                   dp->dimensions[1],
                                                   dp->getData()),
                                  dp->sparse,dp->fieldNames);
 #endif
             }
         }
     }
getArrayOfIOInterface()
Interface * Nelson::ArrayOf::getArrayOfIOInterface () static
Returns the IO interface being used by instances of the ArrayOf class.
Definition at line 86 of file ArrayOf.cpp.
     {
         return io;
     }
getByteSize()
indexType Nelson::ArrayOf::getByteSize () const
Calculate the bytes required to hold this array (element size * length)
Calculate the total number of bytes required to store this array.
Definition at line 1364 of file ArrayOf.cpp.
Referenced by emptyConstructor().
     {
         if (isSparse())
         {
             throw Exception(_W("Byte size calculation not supported for sparse arrays."));
         }
         return getElementSize()*getLength();
     }
getContentAsLogicalScalar()
logical Nelson::ArrayOf::getContentAsLogicalScalar () const
Get our contents as an logical scalar. Throws an exception if we are not a scalar logical type.
Definition at line 48 of file ArrayOf_LogicalType.cpp.
     {
         if (!isLogical())
         {
             throw Exception(ERROR_TYPE_LOGICAL_EXPECTED);
         }
         if (getLength() != 1)
         {
             throw Exception(ERROR_SIZE_SCALAR_EXPECTED);
         }
         logical *qp = (logical*)dp->getData();
         return (*qp);
     }
getContentAsScalarIndex()
indexType Nelson::ArrayOf::getContentAsScalarIndex (bool bWithZero = true)
Get our contents as a index type scalar. Throws an exception if we are not scalar or cannot meaningfully be converted to a index typevalue.
Definition at line 4234 of file ArrayOf.cpp.
     {
         indexType idx = 0;
         if (getLength() != 1)
         {
             throw Exception(_W("Expected a scalar."));
         }
         promoteType(NLS_DOUBLE);
         double *qp = (double*)dp->getData();
         if ((floor(*qp) == *qp) && IsFinite((*qp)))
         {
             double maxIndexType = (double)std::numeric_limits<indexType>::max();
             if ((*qp) > maxIndexType)
             {
                 idx = static_cast<indexType>(maxIndexType);
             }
             else if (*qp < 0)
             {
                 idx = 0;
             }
             else
             {
                 double dVal = (*qp);
                 idx = static_cast<indexType>(dVal);
             }
         }
         else
         {
             if (IsFinite(*qp))
             {
                 throw Exception(_W("Expected a integer."));
             }
             else
             {
                 throw Exception(_W("NaN and Inf not allowed."));
             }
         }
         if (!bWithZero)
         {
             if (idx == 0)
             {
                 throw Exception(_W("Dimension argument must be a positive integer scalar within indexing range."));
             }
         }
         return idx;
     }
getContentAsWideStringColumnVector()
wstringVector Nelson::ArrayOf::getContentAsWideStringColumnVector (void) const
Get our contents as a vector wide string (UTF-16). Only works for CELL of STRING types. Check if it is a cell with a column vector dimension
Definition at line 256 of file ArrayOf_StringType.cpp.
Referenced by getContentAsWideStringRowVector().
     {
         wstringVector res;
         if (dp->dataClass != NLS_CELL_ARRAY)
         {
             throw Exception(_W("A cell expected."));
         }
         if (isColumnVector())
         {
             ArrayOf *arg = (ArrayOf*)(getDataPointer());
             indexType nbElements = getDimensions().getElementCount();
             res.reserve(nbElements);
             for (indexType k = 0; k < nbElements; k++)
             {
                 if (arg[k].getDataClass() != NLS_STRING)
                 {
                     res.clear();
                     throw Exception(_W("A cell of string expected."));
                 }
                 else
                 {
                     res.push_back(arg[k].getContentsAsWideString());
                 }
             }
         }
         else
         {
             throw Exception(_W("A column vector expected."));
         }
         return res;
     }
getContentAsWideStringRowVector()
wstringVector Nelson::ArrayOf::getContentAsWideStringRowVector (void) const
Get our contents as a vector wide string (UTF-16). Only works for CELL of STRING types. Check if it is a cell with a row vector dimension
Definition at line 212 of file ArrayOf_StringType.cpp.
Referenced by getContentAsWideStringVector().
     {
         wstringVector res;
         if (dp->dataClass != NLS_CELL_ARRAY)
         {
             throw Exception(_W("A cell expected."));
         }
         if (isRowVector())
         {
             ArrayOf *arg = (ArrayOf*)(getDataPointer());
             indexType nbElements = getDimensions().getElementCount();
             res.reserve(nbElements);
             for (indexType k = 0; k < nbElements; k++)
             {
                 if (arg[k].getDataClass() != NLS_STRING)
                 {
                     res.clear();
                     throw Exception(_W("A cell of string expected."));
                 }
                 else
                 {
                     res.push_back(arg[k].getContentsAsWideString());
                 }
             }
         }
         else
         {
             throw Exception(_W("A row vector expected."));
         }
         return res;
     }
getContentAsWideStringVector()
wstringVector Nelson::ArrayOf::getContentAsWideStringVector (bool bCheckVector = true) const
Get our contents as a vector wide string (UTF-16). Only works for CELL of STRING types. no check on dimensions
Definition at line 135 of file ArrayOf_StringType.cpp.
Referenced by getContentsAsWideString().
     {
         wstringVector res;
         if (dp->dataClass == NLS_STRING)
         {
             if (is2D())
             {
                 indexType rows = getDimensions().getRows();
                 indexType columns = getDimensions().getColumns();
                 for (indexType i = 0; i < rows; i++)
                 {
                     std::wstring str;
                     charType *buffer = nullptr;
                     const charType *qp = nullptr;
                     qp = (const charType*)dp->getData();
                     for (indexType j = 0; j < columns; j++)
                     {
                         size_t idx = i + j * rows;
                         str.push_back(qp[idx]);
                     }
                     res.push_back(str);
                     str.clear();
                 }
             }
             else
             {
                 res.push_back(getContentsAsWideString());
             }
         }
         else
         {
             if (dp->dataClass != NLS_CELL_ARRAY)
             {
                 throw Exception(_W("A cell expected."));
             }
             else if (isEmpty())
             {
                 //                res.push_back(L"");
             }
             else if (isVector() || !bCheckVector)
             {
                 ArrayOf *arg = (ArrayOf*)(getDataPointer());
                 indexType nbElements = getDimensions().getElementCount();
                 res.reserve(nbElements);
                 for (indexType k = 0; k < nbElements; k++)
                 {
                     if (arg[k].getDataClass() != NLS_STRING)
                     {
                         res.clear();
                         throw Exception(_W("A cell of string expected."));
                     }
                     else
                     {
                         res.push_back(arg[k].getContentsAsWideString());
                     }
                 }
             }
             else
             {
                 throw Exception(_W("A vector expected."));
             }
         }
         return res;
     }
getContentsAsCString()
std::string Nelson::ArrayOf::getContentsAsCString (void) const
Get our contents as a C-string (UTF-8). Only works for STRING types. Throws an exception for non-string types.
Definition at line 67 of file ArrayOf_StringType.cpp.
Referenced by Nelson::Evaluator::rhsExpression(), and Nelson::Evaluator::simpleSubindexExpression().
     {
         return wstring_to_utf8(getContentsAsWideString());
     }
getContentsAsDoubleComplexScalar()
doublecomplex Nelson::ArrayOf::getContentsAsDoubleComplexScalar ()
Get our contents as a double complex scalar. Throws an exception if we are not scalar or cannot meaningfully be converted to a double precision value.
Definition at line 82 of file ArrayOf_DoubleType.cpp.
     {
         if (isReferenceType() || isString() || isSparse() || !isScalar())
         {
             throw Exception(_W("Expected a real valued scalar"));
         }
         promoteType(NLS_DCOMPLEX);
         double *qp = (double*)dp->getData();
         doublecomplex cx(qp[0], qp[1]);
         return cx;
     }
getContentsAsDoubleScalar()
double Nelson::ArrayOf::getContentsAsDoubleScalar ()
Get our contents as a double scalar. Throws an exception if we are not scalar or cannot meaningfully be converted to a double precision value.
Definition at line 71 of file ArrayOf_DoubleType.cpp.
Referenced by getVectorSubset().
     {
         if (isComplex() || isReferenceType() || isString() || isSparse() || !isScalar())
         {
             throw Exception(_W("Expected a real valued scalar."));
         }
         promoteType(NLS_DOUBLE);
         double *qp = (double*)dp->getData();
         return (*qp);
     }
getContentsAsInteger32Scalar()
int32 Nelson::ArrayOf::getContentsAsInteger32Scalar ()
Get our contents as an integer scalar. Throws an exception if we are not a scalar integer type.
Definition at line 205 of file ArrayOf_IntegersType.cpp.
Referenced by getVectorSubset().
     {
         int32 *qp;
         if (getLength() != 1)
         {
             throw Exception(_W("Expected a scalar."));
         }
         promoteType(NLS_INT32);
         qp = (int32*)dp->getData();
         return (*qp);
     }
getContentsAsInteger64Scalar()
int64 Nelson::ArrayOf::getContentsAsInteger64Scalar ()
Get our contents as an integer scalar 64. Throws an exception if we are not a scalar integer type.
Definition at line 217 of file ArrayOf_IntegersType.cpp.
     {
         int64 *qp;
         if (getLength() != 1)
         {
             throw Exception(_W("Expected a scalar."));
         }
         promoteType(NLS_INT64);
         qp = (int64*)dp->getData();
         return (*qp);
     }
getContentsAsSingleComplexScalar()
std::complex< single > Nelson::ArrayOf::getContentsAsSingleComplexScalar ()
Get our contents as a single complex scalar. Throws an exception if we are not scalar or cannot meaningfully be converted to a single precision value.
Definition at line 68 of file ArrayOf_SingleType.cpp.
     {
         if (isReferenceType() || isString())
         {
             throw Exception(_W("Expected a real valued scalar"));
         }
         promoteType(NLS_SCOMPLEX);
         single *qp = (single*)dp->getData();
         std::complex<single> cx(qp[0], qp[1]);
         return cx;
     }
getContentsAsSingleScalar()
single Nelson::ArrayOf::getContentsAsSingleScalar ()
Get our contents as a float scalar. Throws an exception if we are not scalar or cannot meaningfully be converted to a double precision value.
Definition at line 56 of file ArrayOf_SingleType.cpp.
     {
         single *qp;
         if (isComplex() || isReferenceType() || isString())
         {
             throw Exception(_W("Expected a real valued scalar"));
         }
         promoteType(NLS_SINGLE);
         qp = (single*)dp->getData();
         return (*qp);
     }
getContentsAsUnsignedInt64Scalar()
uint64 Nelson::ArrayOf::getContentsAsUnsignedInt64Scalar ()
Get our contents as an unsigned integer scalar 64. Throws an exception if we are not a scalar integer type.
Definition at line 229 of file ArrayOf_IntegersType.cpp.
     {
         uint64 *qp;
         if (getLength() != 1)
         {
             throw Exception(_W("Expected a scalar."));
         }
         promoteType(NLS_UINT64);
         qp = (uint64*)dp->getData();
         return (*qp);
     }
getContentsAsWideString()
std::wstring Nelson::ArrayOf::getContentsAsWideString (void) const
Get our contents as a wide string (UTF-16). Only works for STRING types. Throws an exception for non-string types.
Definition at line 94 of file ArrayOf_StringType.cpp.
Referenced by getContentAsWideStringColumnVector(), getContentAsWideStringRowVector(), getContentAsWideStringVector(), getContentsAsCString(), summarizeCellEntry(), and testCaseMatchScalar().
     {
         std::wstring str = L"";
         if (isSingleString())
         {
             charType *buffer = nullptr;
             const charType *qp = nullptr;
             indexType M = getLength();
             buffer = new_with_exception<charType>(M + 1);
             qp = (const charType*)dp->getData();
             memcpy(buffer, qp, M * sizeof(charType));
             buffer[M] = 0;
             str = buffer;
             delete[] buffer;
         }
         else
         {
             if (dp->dataClass != NLS_STRING)
             {
                 throw Exception(_W("Unable to convert supplied object to a string."));
             }
             if (!isRowVector())
             {
                 throw Exception(_W("Unable to convert supplied object to a single string."));
             }
         }
         return str;
     }
getDataClass()
Class Nelson::ArrayOf::getDataClass () const
Get our data class (of type Class).
Definition at line 1304 of file ArrayOf.cpp.
Referenced by copyElements(), Nelson::doPowerAssist(), Nelson::DotRightDivide(), Nelson::Equals(), Nelson::MacroFunctionDef::evaluateFunction(), getContentAsScalarIndex(), getContentAsWideStringColumnVector(), getContentAsWideStringRowVector(), getContentAsWideStringVector(), getFieldNames(), Nelson::GreaterEquals(), Nelson::GreaterThan(), Nelson::LessEquals(), Nelson::LessThan(), Nelson::NotEquals(), setNDimSubset(), setVectorSubset(), testCaseMatchScalar(), Nelson::Transpose(), and Nelson::TypeCheck().
     {
         if (dp)
         {
             return dp->dataClass;
         }
         else
         {
             return NLS_DOUBLE;
         }
     }
getDataPointer()
const void * Nelson::ArrayOf::getDataPointer () const
Get the contents of our data block as a (read-only) void* pointer. Get the contents of our data block as a void* pointer. The resulting pointer is read only, so that no modifications can be made to the contents of our array. To modify the contents, you must make a copy and use setDataPointer to replace the current data. This "copy-on-write" technique avoids copies on references to variables – a good thing in this interpreted environment where read-references dominate the accesses to variables. Another option is to use getReadWriteDataPointer, which returns a pointer that is free of object aliases.
Definition at line 929 of file ArrayOf.cpp.
Referenced by Nelson::And(), deleteVectorSubset(), Nelson::doPowerAssist(), Nelson::DotRightDivide(), emptyConstructor(), Nelson::Equals(), Nelson::MacroFunctionDef::evaluateFunction(), getContentAsWideStringColumnVector(), getContentAsWideStringRowVector(), getContentAsWideStringVector(), getNDimSubset(), Nelson::GreaterEquals(), Nelson::GreaterThan(), Nelson::LessEquals(), Nelson::LessThan(), Nelson::Not(), Nelson::NotEquals(), Nelson::Or(), setNDimSubset(), setVectorSubset(), and Nelson::Transpose().
     {
         if (isSparse())
         {
             throw Exception(_W("operation does not support sparse matrix arguments."));
         }
         if (dp)
         {
             return dp->getData();
         }
         else
         {
             return nullptr;
         }
     }
getDimensionLength()
indexType Nelson::ArrayOf::getDimensionLength (int t) const
Get our length along the given dimension.
Definition at line 915 of file ArrayOf.cpp.
Referenced by deleteNDimSubset(), deleteVectorSubset(), emptyConstructor(), getNDimSubset(), getValueAtIndex(), getVectorSubset(), nnz(), setNDimSubset(), and setVectorSubset().
     {
         if (dp)
         {
             return dp->dimensions[t];
         }
         else
         {
             return 0;
         }
     }
getDimensions()
Dimensions Nelson::ArrayOf::getDimensions () const
Get a copy of our dimensions vector.
Definition at line 902 of file ArrayOf.cpp.
Referenced by Nelson::And(), deleteNDimSubset(), Nelson::doPowerAssist(), Nelson::DotRightDivide(), Nelson::Equals(), getContentAsWideStringColumnVector(), getContentAsWideStringRowVector(), getContentAsWideStringVector(), Nelson::GreaterEquals(), Nelson::GreaterThan(), Nelson::LessEquals(), Nelson::LessThan(), Nelson::Not(), Nelson::NotEquals(), Nelson::Or(), Nelson::Evaluator::rhsExpression(), setDataPointer(), Nelson::Evaluator::simpleSubindexExpression(), and Nelson::Transpose().
     {
         if (dp)
         {
             return dp->dimensions;
         }
         else
         {
             return Dimensions();
         }
     }
getElementSize()
indexType Nelson::ArrayOf::getElementSize () const
Calculate the size of each element in this array.
Definition at line 1319 of file ArrayOf.cpp.
Referenced by copyElements(), emptyConstructor(), and getByteSize().
     {
         switch(dp->dataClass)
         {
             case NLS_HANDLE:
                 return sizeof(nelson_handle);
             case NLS_CELL_ARRAY:
                 return sizeof(ArrayOf);
             case NLS_STRUCT_ARRAY:
                 return (sizeof(ArrayOf) * dp->fieldNames.size());
             case NLS_LOGICAL:
                 return sizeof(logical);
             case NLS_UINT8:
                 return sizeof(uint8);
             case NLS_INT8:
                 return sizeof(int8);
             case NLS_UINT16:
                 return sizeof(uint16);
             case NLS_INT16:
                 return sizeof(int16);
             case NLS_UINT32:
                 return sizeof(uint32);
             case NLS_INT32:
                 return sizeof(int32);
             case NLS_UINT64:
                 return sizeof(uint64);
             case NLS_INT64:
                 return sizeof(int64);
             case NLS_SINGLE:
                 return sizeof(float);
             case NLS_DOUBLE:
                 return sizeof(double);
             case NLS_SCOMPLEX:
                 return sizeof(float)*2;
             case NLS_DCOMPLEX:
                 return sizeof(double)*2;
             case NLS_STRING:
                 return sizeof(charType);
         }
         return 0;
     }
getField()
ArrayOf Nelson::ArrayOf::getField (std::string fieldName)
Get the contents of a field from its field name. Again, like getVectorContents and getNDimContents, this function is meant for assignments only, and the argument must be a scalar structure. Throws an exection if we are a vector, or if the supplied field do not exist.
Definition at line 187 of file ArrayOf_StructType.cpp.
Referenced by Nelson::Evaluator::functionExpression(), Nelson::Evaluator::rhsExpression(), and Nelson::Evaluator::simpleSubindexExpression().
     {
         // First make sure that we are a scalar value.
         if (!isScalar())
         {
             throw Exception(_W("Cannot dereference a field of a multi-element structure array."));
         }
         if (isSparse())
         {
             throw Exception(_W("getField not supported for sparse arrays."));
         }
         // Then, find the field index.
         int64 ndx = getFieldIndex(fieldName);
         if (ndx < 0)
         {
             throw Exception(_("Reference to non-existent field") + " " + fieldName);
         }
         // Cast real part into a data pointer, and return a copy of what the caller asked for!
         const ArrayOf* qp = (const ArrayOf*)dp->getData();
         return qp[ndx];
     }
getFieldAsList()
ArrayOfVector Nelson::ArrayOf::getFieldAsList (std::string fieldName)
Get the contents of a field as an array from its field name. This is used when a structure array is used to supply a list of expressions. Throws an exception if
we are not a structure array
the field does not exist
Definition at line 209 of file ArrayOf_StructType.cpp.
Referenced by Nelson::Evaluator::rhsExpression().
     {
         if (!isStruct())
         {
             throw Exception(_W("Attempt to apply field-indexing to non structure-array object."));
         }
         if (isSparse())
         {
             throw Exception(_W("getFieldAsList not supported for sparse arrays."));
         }
         ArrayOfVector m;
         const ArrayOf *qp = (const ArrayOf*)dp->getData();
         indexType N = getLength();
         indexType fieldCount = dp->fieldNames.size();
         int64 ndx = getFieldIndex(fieldName);
         if (ndx < 0)
         {
             throw Exception(_("Reference to non-existent field") + " " + fieldName);
         }
         indexType i = 0;
         for (i = 0; i<N; i++)
         {
             m.push_back(qp[i*fieldCount + ndx]);
         }
         return m;
     }
getFieldNames()
stringVector Nelson::ArrayOf::getFieldNames () const
Get the fieldnames.
Definition at line 39 of file ArrayOf_StructType.cpp.
Referenced by printMe().
     {
         if (dp)
         {
             return dp->fieldNames;
         }
         else
         {
             return stringVector();
         }
     }
getLength()
indexType Nelson::ArrayOf::getLength () const
Get the length of the array as a vector. This is equivalent to computing length(this(:)).
Definition at line 890 of file ArrayOf.cpp.
Referenced by allocateArrayOf(), deleteVectorSubset(), diagonalConstructor(), Nelson::doPowerAssist(), emptyConstructor(), ensureSingleOwner(), Nelson::MacroFunctionDef::evaluateFunction(), Nelson::Evaluator::expressionList(), Nelson::Evaluator::forStatement(), getByteSize(), getContentAsLogicalScalar(), getContentAsScalarIndex(), getContentsAsCString(), getContentsAsInteger32Scalar(), getContentsAsInteger64Scalar(), getContentsAsUnsignedInt64Scalar(), getContentsAsWideString(), getFieldAsList(), getNDimContents(), getValueAtIndex(), getVectorContents(), getVectorContentsAsList(), getVectorSubset(), isEmpty(), isRealAllZeros(), nnz(), Nelson::Not(), promoteType(), reshape(), resize(), setFieldAsList(), setNDimSubset(), setVectorContents(), setVectorContentsAsList(), setVectorSubset(), Nelson::Evaluator::simpleSubindexExpression(), testForCaseMatch(), toOrdinalType(), and vectorResize().
     {
         if (dp)
         {
             return dp->dimensions.getElementCount();
         }
         else
         {
             return 0;
         }
     }
getNDimContents()
ArrayOf Nelson::ArrayOf::getNDimContents (ArrayOfVector & indexing)
Get a subset of an ArrayOf using contents-addressing. This is for NDim- indexing, meaning that the argument is assumed to refer to the elements in their N-Dimensional: meaning that x{10} is really x{10,1}. Like getVectorContents, this function is meant for assignments only. Throws an exception if
we are not a cell array
the indices do not define a single value
Return the contents of a cell array - indexed via a multi-dim index.
Definition at line 153 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (!this->isCell())
         {
             throw Exception(_W("Attempt to apply contents-indexing to non-cell array object."));
         }
         if (isSparse())
         {
             throw Exception(_W("getNDimContents not supported for sparse arrays."));
         }
         indexType L = indexing.size();
         Dimensions outPos(L);
         // Convert each of the indexing variables into an ordinal type.
         // We don't catch any exceptions - let them propogate up the
         // call chain.
         // The index HAS to be a scalar for contents-based addressing.
         for (indexType i = 0; i < L; i++)
         {
             indexing[i].toOrdinalType();
             if (indexing[i].getLength() != 1)
             {
                 throw Exception(_W("Content indexing must return a single value."));
             }
             constIndexPtr sp = (constIndexPtr)indexing[i].dp->getData();
             outPos[i] = *sp - 1;
         }
         indexType j = dp->dimensions.mapPoint(outPos);
         const ArrayOf* qp = (const ArrayOf*)dp->getData();
         return qp[j];
     }
getNDimContentsAsList()
ArrayOfVector Nelson::ArrayOf::getNDimContentsAsList (ArrayOfVector & index)
Get a subset of an ArrayOf using contents-addressing. This is used when a cell array is used to supply a list of expressions. Throws an exception if we are not a cell-array.
Return the contents of an cell array as a list.
Definition at line 228 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::rhsExpression().
     {
         if (!this->isCell())
         {
             throw Exception(_W("Attempt to apply contents-indexing to non cell-array object."));
         }
         if (isSparse())
         {
             throw Exception(_W("getNDimContentsAsList not supported for sparse arrays."));
         }
         // Store the return value here
         ArrayOfVector m;
         // Get the number of indexing dimensions
         indexType L = index.size();
         // Setup the data pointers
         Dimensions outDims(L);
         indexType i;
         for (i = 0; i<L; i++)
         {
             index[i].toOrdinalType();
         }
         constIndexPtr* indx = new_with_exception<constIndexPtr>(L);
         for (i = 0; i<L; i++)
         {
             outDims[i] = (index[i].getLength());
             indx[i] = (constIndexPtr)index[i].dp->getData();
         }
         Dimensions argPointer(L);
         Dimensions currentIndex(L);
         const ArrayOf *qp = (const ArrayOf*)dp->getData();
         indexType srcindex = 0;
         while (argPointer.inside(outDims))
         {
             for (indexType i = 0; i<L; i++)
             {
                 currentIndex[i] = indx[i][argPointer[i]] - 1;
             }
             srcindex = dp->dimensions.mapPoint(currentIndex);
             m.push_back(qp[srcindex]);
             argPointer.incrementModulo(outDims, 0);
         }
         delete[] indx;
         indx = nullptr;
         return m;
     }
getNDimSubset()
ArrayOf Nelson::ArrayOf::getNDimSubset (ArrayOfVector & index)
Get a subset of an ArrayOf. This if for n-Dimensional-indexing, meaning that x(10) is really x(10,1). Throws an exception if the variable is empty.
Take the current variable, and return a new array consisting of the elements in source indexed by the index argument. Indexing is done using ndimensional indices.
Definition at line 2621 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::rhsExpression(), and Nelson::Evaluator::simpleSubindexExpression().
     {
         constIndexPtr* indx = nullptr;
         void *qp = nullptr;
         indexType  i;
         if (isEmpty())
         {
             throw Exception(_W("Cannot index into empty variable."));
         }
         try
         {
             indexType  L = index.size();
             // Convert the indexing variables into an ordinal type.
             // We don't catch any exceptions - let them propogate up the
             // call chain.
             bool bEmpty = false;
             Dimensions dimsDest(L);
             for (i=0; i<L; i++)
             {
                 if (index[i].isEmpty())
                 {
                     bEmpty = true;
                     dimsDest[i] = 0;
                 }
                 else
                 {
                     index[i].toOrdinalType();
                     indexType *idx = (indexType *)index[i].getDataPointer();
                     dimsDest[i] = idx[index[i].getDimensions().getElementCount() - 1];
                 }
             }
             if (bEmpty)
             {
                 return ArrayOf::emptyConstructor(dimsDest, isSparse());
             }
             // Set up data pointers
             indx = new_with_exception<constIndexPtr>(L);
             // Calculate the size of the output.
             Dimensions outDims(L);
             for (i=0; i<L; i++)
             {
                 outDims[i] = (index[i].getLength());
                 indx[i] = (constIndexPtr) index[i].dp->getData();
             }
             if (outDims.getElementCount() == 0)
             {
                 if (isSparse())
                 {
                     return ArrayOf::emptyConstructor(outDims, false);
                 }
                 else
                 {
                     return ArrayOf::emptyConstructor(outDims, false);
                 }
             }
             else
             {
                 if (isSparse())
                 {
                     if (L > 2)
                     {
                         throw Exception(_W("multidimensional indexing (more than 2 dimensions) not legal for sparse arrays"));
                     }
                     if ((outDims[0] == 1) && (outDims[1] == 1))
                     {
 #ifdef                  __NLS_USE_SPARSE_EIGEN
                         return ArrayOf(dp->dataClass, outDims,
                                        GetSparseScalarElementDynamicFunction(dp->dataClass,
                                                getDimensionLength(0),
                                                getDimensionLength(1),
                                                dp->getData(),
                                                *((const indexType*)indx[0]),
                                                *((const indexType*)indx[1])),
                                        true);
 #else
                         return ArrayOf(dp->dataClass, outDims,
                                        GetSparseScalarElement(dp->dataClass,
                                                               getDimensionLength(0),
                                                               getDimensionLength(1),
                                                               dp->getData(),
                                                               *((const indexType*)indx[0]),
                                                               *((const indexType*)indx[1])),
                                        true);
 #endif
                     }
                     else
                     {
 #ifdef __NLS_USE_SPARSE_EIGEN
                         return ArrayOf(dp->dataClass, outDims,
                                        GetSparseNDimSubsetsDynamicFunction(dp->dataClass,
                                                getDimensionLength(0),
                                                getDimensionLength(1),
                                                dp->getData(),
                                                (const indexType*)indx[0],
                                                outDims[0],
                                                (const indexType*)indx[1],
                                                outDims[1]),
                                        true);
 #else
                         return ArrayOf(dp->dataClass, outDims,
                                        GetSparseNDimSubsets(dp->dataClass,
                                                             getDimensionLength(0),
                                                             getDimensionLength(1),
                                                             dp->getData(),
                                                             (const indexType*)indx[0],
                                                             outDims[0],
                                                             (const indexType*)indx[1],
                                                             outDims[1]),
                                        true);
 #endif
                     }
                 }
                 qp = allocateArrayOf(dp->dataClass, outDims.getElementCount(), dp->fieldNames);
                 Dimensions argPointer(L);
                 Dimensions currentIndex(L);
                 indexType srcindex = 0;
                 indexType dstindex = 0;
                 while (argPointer.inside(outDims))
                 {
                     for (indexType i = 0; i < L; i++)
                     {
                         currentIndex[i] = (int)indx[i][argPointer[i]] - 1;
                     }
                     srcindex = dp->dimensions.mapPoint(currentIndex);
                     copyElements(srcindex, qp, dstindex, 1);
                     dstindex++;
                     argPointer.incrementModulo(outDims, 0);
                 }
                 delete[] indx;
                 indx = nullptr;
                 outDims.simplify();
                 return ArrayOf(dp->dataClass, outDims, qp, dp->sparse, dp->fieldNames);
             }
         }
         catch (Exception &e)
         {
             delete [] indx;
             indx = nullptr;
             deleteArrayOf(qp, dp->dataClass);
             qp = nullptr;
             e.what();
             throw ;
         }
     }
getReadWriteDataPointer()
void * Nelson::ArrayOf::getReadWriteDataPointer ()
Get the contents of our data block as a read-write void* pointer. Get the contents of our data block as a read-write void* pointer. It ensures that our data block is not aliased (meaning that no other array objects share the data block), prior to returning the pointer. To do this, we have to go through the following steps:
Check the number of owners of our byte array.
If there is only one owner for the byte array, return a non-const pointer to the data
If there is more than one owner, copy our data.
Definition at line 984 of file ArrayOf.cpp.
Referenced by emptyConstructor(), Nelson::MacroFunctionDef::evaluateFunction(), Nelson::Evaluator::expressionList(), setField(), setFieldAsList(), setNDimContents(), setNDimContentsAsList(), setNDimSubset(), setVectorContents(), setVectorContentsAsList(), and setVectorSubset().
     {
         if (isSparse())
         {
             io->warningMessage(_W("Warning: sparse matrix converted to full for operation."));
             makeDense();
         }
         ensureSingleOwner();
         return dp->getWriteableData();
     }
getReferenceCount()
int Nelson::ArrayOf::getReferenceCount () const
Get the reference count to our data object - useful for debug purposes.
Definition at line 878 of file ArrayOf.cpp.
Referenced by getArrayOfIOInterface().
     {
         if (dp)
         {
             return dp->numberOfOwners();
         }
         else
         {
             return 0;
         }
     }
getValueAtIndex()
ArrayOf Nelson::ArrayOf::getValueAtIndex (uint64 index)
returns value as an array =A(index) simple extraction (fast used 'for' loop)
Definition at line 2444 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::forStatement(), and getVectorSubset().
     {
         uint64 length = (uint64)this->getLength();
         if (index >= length)
         {
             throw Exception(_W("Index exceeds matrix dimensions."));
         }
         // call extration overloading here for not supported types
         Dimensions retdims(1, 1);
         if (isSparse())
         {
             indexType indx = (indexType)(index - 1);
             indexType row = (indexType)(indx % getDimensionLength(0));
             indexType col = (indexType)(indx / getDimensionLength(0));
 #ifdef __NLS_USE_SPARSE_EIGEN
             return ArrayOf(dp->dataClass, retdims,
                            GetSparseScalarElementDynamicFunction(dp->dataClass,
                                    getDimensionLength(0),
                                    getDimensionLength(1),
                                    dp->getData(),
                                    row + 1, col + 1),
                            true);
 #else
             return ArrayOf(dp->dataClass, retdims,
                            GetSparseScalarElement(dp->dataClass,
                                                   getDimensionLength(0),
                                                   getDimensionLength(1),
                                                   dp->getData(),
                                                   row + 1, col + 1),
                            true);
 #endif
         }
         else
         {
             void *qp = nullptr;
             int ndx = (int)index;
             qp = allocateArrayOf(dp->dataClass, 1, dp->fieldNames);
             copyElements(ndx, qp, 0, 1);
             return ArrayOf(dp->dataClass, retdims, qp, dp->sparse, dp->fieldNames);
         }
         // never here
         return ArrayOf();
     }
getVectorContents()
ArrayOf Nelson::ArrayOf::getVectorContents (ArrayOf & indexing)
Get a subset of an ArrayOf using contents-addressing. This is for vector- indexing, meaning that the argument is assumed to refer to the elements in their order as a vector. So, x{10} is equivalent to x(:){10}, even if, say, x is 3 x 4. This function is only used in assignment calls of the form e.g., a{10} = 5. The vector argument must therefor be a scalar. Throws an exception if
we are not a cell array
the argument is empty
the argument defines more than a single value
the index exceeds the bounds of the array.
Return the contents of a cell array - must be a scalar...
Definition at line 106 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (this->isCell())
         {
             throw Exception(_W("Attempt to apply contents-indexing to non-cell array object."));
         }
         if (indexing.isEmpty())
         {
             throw Exception(_W("Empty contents indexing is not defined."));
         }
         if (isSparse())
         {
             throw Exception(_W("getVectorContents not supported for sparse arrays."));
         }
         indexing.toOrdinalType();
         //
         // The output is the same size as the _index_, not the
         // source variable (neat, huh?).  But it inherits the
         // type of the source variable.
         //
         // The index HAS to be a scalar for contents-based addressing
         if (indexing.getLength() != 1)
         {
             throw Exception(_W("Content indexing must return a single value."));
         }
         constIndexPtr index_p = (constIndexPtr)indexing.dp->getData();
         if (*index_p == 0)
         {
             throw Exception(_W("Index exceeds cell array dimensions"));
         }
         else
         {
             indexType ndx = *index_p - 1;
             indexType  bound = getLength();
             if (ndx >= bound)
             {
                 throw Exception(_W("Index exceeds cell array dimensions"));
             }
             const ArrayOf* srcPart = (const ArrayOf*)dp->getData();
             // Make a source of whatever is in that index, and return it.
             return srcPart[ndx];
         }
     }
getVectorContentsAsList()
ArrayOfVector Nelson::ArrayOf::getVectorContentsAsList (ArrayOf & index)
Get a subset of a (cell) ArrayOf using contents-addressing. This is used when a cell array is used to supply a list of expressions. Throws an exception if
we are not a cell-array
the indices exceed the array bounds
Return a subset of a cell array as a list.
Definition at line 187 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::rhsExpression().
     {
         ArrayOfVector m;
         if (!this->isCell())
         {
             throw Exception(_W("Attempt to apply contents-indexing to non cell-array object."));
         }
         if (isSparse())
         {
             throw Exception(_W("getVectorContentsAsList not supported for sparse arrays."));
         }
         if (index.isEmpty())
         {
             return ArrayOfVector();
         }
         index.toOrdinalType();
         // Get the maximum index
         indexType max_index = index.getMaxAsIndex();
         // Get our length
         indexType bound = getLength();
         if (max_index > bound)
         {
             throw Exception(_W("ArrayOf index exceeds bounds of cell-array"));
         }
         // Get the length of the index object
         indexType index_length = index.getLength();
         // Get a pointer to the index data set
         constIndexPtr index_p = (constIndexPtr)index.dp->getData();
         // Get a pointer to our data
         const ArrayOf* qp = (const ArrayOf*)dp->getData();
         // Now we copy data from dp to m
         for (indexType i = 0; i<index_length; i++)
         {
             m.push_back(qp[index_p[i] - 1]);
         }
         return m;
     }
getVectorSubset()
ArrayOf Nelson::ArrayOf::getVectorSubset (ArrayOf & index)
Get a subset of an ArrayOf. This is for vector-indexing, meaning that the argument is assumed to refer to the elements in their order as a vector. So, x(10) is equivalent to x(:)(10), even if, say, x is 3 x 4. Throws an exception if
the variable is empty
the argument subset exceeds our valid domain
Take the current variable, and return a new array consisting of the elements in source indexed by the index argument. Indexing is done using vector ordinals.
Definition at line 2494 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::rhsExpression(), and Nelson::Evaluator::simpleSubindexExpression().
     {
         void *qp = nullptr;
         try
         {
             if (index.getLength() == 1)
             {
                 double idx = index.getContentsAsDoubleScalar();
                 int64 iidx = (int64)idx;
                 if (idx != (double)iidx || idx < 0)
                 {
                     throw Exception(_W("index must either be real positive integers or logicals."));
                 }
                 if (isSparse())
                 {
                     return getValueAtIndex((uint64)idx);
                 }
                 else
                 {
                     return getValueAtIndex((uint64)(idx - 1));
                 }
             }
             else
             {
                 if (isEmpty() && index.isEmpty())
                 {
                     // Q = ones(3,0)
                     // Q(eye(2,0))
                     // Q(eye(0,2))
                     return ArrayOf(dp->dataClass, index.dp->dimensions, NULL, isSparse(), dp->fieldNames);
                 }
                 if (index.isEmpty())
                 {
                     // Q = 1:10
                     // Q(eye(2,0))
                     // Q(eye(0,2))
                     return ArrayOf::emptyConstructor(1, 0, isSparse());
                 }
                 index.toOrdinalType();
                 Dimensions retdims(index.dp->dimensions);
                 retdims.simplify();
                 if (isSparse())
                 {
                     if (index.getLength() == 1)
                     {
                         indexType  indx = index.getContentsAsInteger32Scalar() - 1;
                         indexType  row = indx % getDimensionLength(0);
                         indexType  col = indx / getDimensionLength(0);
 #ifdef __NLS_USE_SPARSE_EIGEN
                         return ArrayOf(dp->dataClass, retdims,
                                        GetSparseScalarElementDynamicFunction(dp->dataClass,
                                                getDimensionLength(0),
                                                getDimensionLength(1),
                                                dp->getData(),
                                                row + 1, col + 1),
                                        true);
 #else
                         return ArrayOf(dp->dataClass, retdims,
                                        GetSparseScalarElement(dp->dataClass,
                                                               getDimensionLength(0),
                                                               getDimensionLength(1),
                                                               dp->getData(),
                                                               row + 1, col + 1),
                                        true);
 #endif
                     }
                     else
 #ifdef __NLS_USE_SPARSE_EIGEN
                         return ArrayOf(dp->dataClass, retdims,
                                        GetSparseVectorSubsetsDynamicFunction(dp->dataClass,
                                                getDimensionLength(0),
                                                getDimensionLength(1),
                                                dp->getData(),
                                                (const indexType*)
                                                index.dp->getData(),
                                                index.getDimensionLength(0),
                                                index.getDimensionLength(1)),
                                        true);
 #else
                         return ArrayOf(dp->dataClass, retdims,
                                        GetSparseVectorSubsets(dp->dataClass,
                                                               getDimensionLength(0),
                                                               getDimensionLength(1),
                                                               dp->getData(),
                                                               (const indexType*)
                                                               index.dp->getData(),
                                                               index.getDimensionLength(0),
                                                               index.getDimensionLength(1)),
                                        true);
 #endif
                 }
                 //
                 // The output is the same size as the _index_, not the
                 // source variable (neat, huh?).  But it inherits the
                 // type of the source variable.
                 indexType length = index.getLength();
                 qp = allocateArrayOf(dp->dataClass, index.getLength(), dp->fieldNames);
                 // Get a pointer to the index data set
                 const indexType *index_p = (const indexType *)index.dp->getData();
                 indexType bound = getLength();
                 indexType ndx = 0;
                 for (indexType i = 0; i < length; i++)
                 {
                     ndx = index_p[i] - 1;
                     if (ndx < 0 || ndx >= bound)
                     {
                         throw Exception(_W("Index exceeds variable dimensions."));
                     }
                     copyElements(ndx, qp, i, 1);
                 }
                 return ArrayOf(dp->dataClass, retdims, qp, dp->sparse, dp->fieldNames);
             }
         }
         catch (Exception &e)
         {
             e.what();
             deleteArrayOf(qp, dp->dataClass);
             qp = nullptr;
             throw;
         }
     }
int16Constructor()
ArrayOf Nelson::ArrayOf::int16Constructor (int16 aval) static
Scalar constructor - Construct an NLS_INT16 object with a scalar value.
Definition at line 52 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         int16 *data = (int16 *)allocateArrayOf(NLS_INT16, 1);
         *data = aval;
         return ArrayOf(NLS_INT16, dim, data);
     }
int32Constructor()
ArrayOf Nelson::ArrayOf::int32Constructor (int32 aval) static
Scalar constructor - Construct an NLS_INT32 object with a scalar value.
Definition at line 70 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         int32 *data = (int32 *)allocateArrayOf(NLS_INT32, 1);
         *data = aval;
         return ArrayOf(NLS_INT32, dim, data);
     }
int32VectorConstructor()
ArrayOf Nelson::ArrayOf::int32VectorConstructor (int len) static
int32 vector constructor - Construct an NLS_INT32 object that is a (row) vector with the given length.
Definition at line 106 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         dim[1] = len;
         int32 *data = (int32*)allocateArrayOf(NLS_INT32, len);
         return ArrayOf(NLS_INT32, dim, data);
     }
int64Constructor()
ArrayOf Nelson::ArrayOf::int64Constructor (int64 aval) static
Scalar constructor - Construct an NLS_INT64 object with a scalar value.
Definition at line 88 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         int64 *data = (int64 *)allocateArrayOf(NLS_INT64, 1);
         *data = aval;
         return ArrayOf(NLS_INT64, dim, data);
     }
int64VectorConstructor()
ArrayOf Nelson::ArrayOf::int64VectorConstructor (int len) static
int64 vector constructor - Construct an NLS_INT64 object that is a (row) vector with the given length.
Definition at line 97 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         dim[1] = len;
         int64 *data = (int64*)allocateArrayOf(NLS_INT64, len);
         return ArrayOf(NLS_INT64, dim, data);
     }
int8Constructor()
ArrayOf Nelson::ArrayOf::int8Constructor (int8 aval) static
Scalar constructor - Construct an NLS_INT8 object with a scalar value.
Definition at line 34 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         int8 *data = (int8 *)allocateArrayOf(NLS_INT8, 1);
         *data = aval;
         return ArrayOf(NLS_INT8, dim, data);
     }
integerRangeConstructor()
ArrayOf Nelson::ArrayOf::integerRangeConstructor (indexType minval, indexType stepsize, indexType maxval, bool vertical) static
Construct a NLS_INT32 or NLS_INT64 (on x64 platform) vector (either vertical or horizontal) corresponding to minval:stepsize:maxval, with an optional transpose.
Definition at line 115 of file ArrayOf_IntegersType.cpp.
Referenced by Nelson::Evaluator::expressionList().
     {
         Dimensions Cdim;
         if (stepsize == 0)
         {
             Cdim[0] = 1;
             Cdim[1] = 0;
 #ifdef NLS_INDEX_TYPE_64
             return ArrayOf(NLS_INT32, Cdim, NULL, false);
 #else
             return ArrayOf(NLS_INT64, Cdim, NULL, false);
 #endif
         }
         if (minval < maxval)
         {
             if (stepsize < 0)
             {
                 Cdim[0] = 1;
                 Cdim[1] = 0;
 #ifdef NLS_INDEX_TYPE_64
                 return ArrayOf(NLS_INT64, Cdim, NULL, false);
 #else
                 return ArrayOf(NLS_INT32, Cdim, NULL, false);
 #endif
             }
         }
         if (minval > maxval)
         {
             if (stepsize > 0)
             {
                 Cdim[0] = 1;
                 Cdim[1] = 0;
 #ifdef NLS_INDEX_TYPE_64
                 return ArrayOf(NLS_INT64, Cdim, NULL, false);
 #else
                 return ArrayOf(NLS_INT32, Cdim, NULL, false);
 #endif
             }
         }
         double dn = (double)((((maxval - minval) / stepsize) + 1));
 #ifdef NLS_INDEX_TYPE_64
         int64 n = (int64)floor((double)(dn));
 #else
         int32 n = (int32)floor((double)(dn));
 #endif
         if (vert)
         {
             Cdim[0] = n;
             Cdim[1] = 1;
         }
         else
         {
             Cdim[0] = 1;
             Cdim[1] = n;
         }
 #ifdef NLS_INDEX_TYPE_64
         int64 *rp = (int64 *)allocateArrayOf(NLS_INT64, n);
 #else
         int32 *rp = (int32 *)allocateArrayOf(NLS_INT32, n);
 #endif
         if (dn == (double(n)))
         {
 #ifdef NLS_INDEX_TYPE_64
             Eigen::Map<Eigen::Matrix<int64, Eigen::Dynamic, 1>> Range(rp, n);
             Range = Eigen::Matrix<int64, Eigen::Dynamic, 1>::LinSpaced(n, minval, maxval);
 #else
             Eigen::Map<Eigen::VectorXi> Range(rp, n);
             Range = Eigen::VectorXi::LinSpaced(n, minval, maxval);
 #endif
         }
         else
         {
             // We must use another algo. in this case
             // 1:2:10
             indexType i = 0;
             indexType v = minval;
             while ((minval < maxval && v <= maxval) || (minval > maxval && v >= maxval))
             {
                 rp[i] = v;
                 v = v + stepsize;
                 i++;
             }
         }
 #ifdef NLS_INDEX_TYPE_64
         return ArrayOf(NLS_INT64, Cdim, rp);
 #else
         return ArrayOf(NLS_INT32, Cdim, rp);
 #endif
     }
is2D()
const bool Nelson::ArrayOf::is2D () const
Returns TRUE if we are 2-Dimensional.
Definition at line 1674 of file ArrayOf.cpp.
Referenced by getContentAsWideStringVector(), getContentsAsUnsignedInt64Scalar(), isDoubleSparseType(), isDoubleType(), isEmpty(), isNdArrayDoubleType(), isNdArraySingleType(), isSingleType(), isString(), and isSymmetric().
     {
         return dp->dimensions.is2D();
     }
isComplex()
const bool Nelson::ArrayOf::isComplex () const
Returns TRUE if we are a complex data type.
Definition at line 1709 of file ArrayOf.cpp.
Referenced by getContentsAsDoubleScalar(), getContentsAsSingleScalar(), and isReal().
     {
         return (dp->dataClass == NLS_DCOMPLEX || dp->dataClass == NLS_SCOMPLEX);
     }
isDataClassReferenceType()
bool Nelson::ArrayOf::isDataClassReferenceType (Class cls) static
Returns true if the given Class is either NLS_CELL_ARRAY or NLS_STRUCT_ARRAY.
Definition at line 4349 of file ArrayOf.cpp.
     {
         return (cls == NLS_CELL_ARRAY || cls == NLS_STRUCT_ARRAY);
     }
isDoubleSparseType()
const bool Nelson::ArrayOf::isDoubleSparseType () const
Returns TRUE if we are a sparse double or complex data type.
Returns TRUE if it is a double type (not ndarray, not sparse)
Definition at line 28 of file ArrayOf_DoubleType.cpp.
     {
         return (dp->dataClass == NLS_DOUBLE) || (dp->dataClass == NLS_DCOMPLEX) && (dp->sparse) && is2D();
     }
isDoubleType()
const bool Nelson::ArrayOf::isDoubleType () const
Returns TRUE if it is a ndarraydouble type (not sparse, not scalar, 2D matrix)
Definition at line 33 of file ArrayOf_DoubleType.cpp.
     {
         return (dp->dataClass == NLS_DOUBLE) || (dp->dataClass == NLS_DCOMPLEX) && (!dp->sparse) && is2D();
     }
isEmpty()
const bool Nelson::ArrayOf::isEmpty (bool allDimensionsIsZero = false) const
Returns TRUE if we are empty (we have no elements).
Definition at line 1633 of file ArrayOf.cpp.
Referenced by allReal(), Nelson::doPowerAssist(), ensureSingleOwner(), getContentAsWideStringVector(), getNDimSubset(), getVectorContents(), getVectorContentsAsList(), getVectorSubset(), isString(), nnz(), printMe(), promoteType(), resize(), Nelson::RightDivide(), setField(), setFieldAsList(), setNDimSubset(), setVectorSubset(), Nelson::Evaluator::simpleSubindexExpression(), summarizeCellEntry(), and vectorResize().
     {
         Dimensions dims = dp->getDimensions();
         if (allDimensionsIsZero)
         {
             Dimensions dims = dp->getDimensions();
             indexType l = dims.getLength();
             for (indexType k = 0; k < l; k++)
             {
                 if (dims.getDimensionLength(k) != 0)
                 {
                     return false;
                 }
             }
             return true;
         }
         else
         {
             if (getLength() == 0)
             {
                 return true;
             }
             else if (isSparse() || is2D())
             {
                 return (dims.getRows() == 0 || dims.getColumns() == 0);
             }
         }
         return false;
     }
isNdArrayDoubleType()
const bool Nelson::ArrayOf::isNdArrayDoubleType () const
Returns TRUE if it is a double type (not ndarray, not sparse)
Definition at line 38 of file ArrayOf_DoubleType.cpp.
     {
         return (dp->dataClass == NLS_DOUBLE) || (dp->dataClass == NLS_DCOMPLEX) && (!dp->sparse) && !is2D();
     }
isNdArraySingleType()
const bool Nelson::ArrayOf::isNdArraySingleType () const
Returns TRUE if it is a ndarraydouble type (not sparse, not scalar, 2D matrix)
Definition at line 32 of file ArrayOf_SingleType.cpp.
     {
         return (dp->dataClass == NLS_SINGLE) || (dp->dataClass == NLS_SCOMPLEX) && (!dp->sparse) && !is2D();
     }
isPositive()
const bool Nelson::ArrayOf::isPositive () const
Returns true if we are (meaningfully) positive. For the unsigned integer types, this is always true. For complex types, this is false. For the signed integer types or the floating point types, the result is based on a linear scan through the array.
Definition at line 1451 of file ArrayOf.cpp.
Referenced by Nelson::doPowerAssist().
     {
         if (dp->dataClass == NLS_UINT8 || dp->dataClass == NLS_UINT16 || dp->dataClass == NLS_UINT32 || dp->dataClass == NLS_UINT64)
         {
             return true;
         }
         if (dp->dataClass == NLS_SCOMPLEX || dp->dataClass == NLS_DCOMPLEX)
         {
             return false;
         }
         if (isSparse())
         {
             throw Exception(_W("isPositive not supported for sparse arrays."));
         }
         switch (dp->dataClass)
         {
                 caseMacro(NLS_SINGLE,float);
                 caseMacro(NLS_DOUBLE,double);
                 caseMacro(NLS_INT8,int8);
                 caseMacro(NLS_INT16,int16);
                 caseMacro(NLS_INT32,int32);
                 caseMacro(NLS_INT64, int64);
         }
         return false;
     }
isReal()
const bool Nelson::ArrayOf::isReal () const
Returns TRUE if we are a real data type.
Definition at line 1717 of file ArrayOf.cpp.
     {
         return (!isComplex());
     }
isRealAllZeros()
const bool Nelson::ArrayOf::isRealAllZeros () const
Returns true if our real part is all zeros. For integer types, this is an element-wise test. For complex types, we check only the real part. Throws an exception if we are a string, cell-array or struct-array type.
Definition at line 1478 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::whileStatement().
     {
         bool allZeros;
         indexType len = getLength();
         indexType i;
 #define caseMacro(caseLabel,dpType,testcode) \
   case caseLabel:\
   {\
      const dpType* qp = (const dpType*) dp->getData();\
      while (allZeros && (i<len)) {\
        allZeros = allZeros && (testcode);\
        i++;\
      }\
      return allZeros;\
   }
         allZeros = true;
         i = 0;
         if (isSparse())
         {
             throw Exception(_W("isPositive not supported for sparse arrays."));
         }
         switch (dp->dataClass)
         {
                 caseMacro(NLS_LOGICAL,logical,qp[i]==0);
                 caseMacro(NLS_UINT8,uint8,qp[i]==0);
                 caseMacro(NLS_INT8,int8,qp[i]==0);
                 caseMacro(NLS_UINT16,uint16,qp[i]==0);
                 caseMacro(NLS_INT16,int16,qp[i]==0);
                 caseMacro(NLS_UINT32,uint32,qp[i]==0);
                 caseMacro(NLS_INT32,int32,qp[i]==0);
                 caseMacro(NLS_UINT64, uint64, qp[i] == 0);
                 caseMacro(NLS_INT64, int64, qp[i] == 0);
                 caseMacro(NLS_SINGLE,float,qp[i]==0.0f);
                 caseMacro(NLS_DOUBLE,double,qp[i]==0.0);
                 caseMacro(NLS_SCOMPLEX,float,qp[i<<1]==0.0f);
                 caseMacro(NLS_DCOMPLEX,double,qp[i<<1]==0.0);
             default:
                 throw Exception(_W("Unable to convert variable type to test for if/while statement"));
         }
 #undef caseMacro
     }
isReferenceType()
const bool Nelson::ArrayOf::isReferenceType () const
Returns TRUE if we are a reference type (cell array or struct array).
Definition at line 1701 of file ArrayOf.cpp.
Referenced by getContentsAsDoubleComplexScalar(), getContentsAsDoubleScalar(), getContentsAsSingleComplexScalar(), getContentsAsSingleScalar(), isSymmetric(), and testForCaseMatch().
     {
         return (dp->dataClass == NLS_STRUCT_ARRAY) || (dp->dataClass == NLS_CELL_ARRAY);
     }
isScalar()
const bool Nelson::ArrayOf::isScalar () const
Returns TRUE if we have only a single element.
Definition at line 1666 of file ArrayOf.cpp.
Referenced by Nelson::And(), Nelson::doPowerAssist(), Nelson::DotRightDivide(), emptyConstructor(), Nelson::Equals(), getContentsAsDoubleComplexScalar(), getContentsAsDoubleScalar(), getField(), Nelson::GreaterEquals(), Nelson::GreaterThan(), Nelson::LessEquals(), Nelson::LessThan(), Nelson::NotEquals(), Nelson::Or(), setDataPointer(), setField(), setNDimContents(), setNDimSubset(), setVectorSubset(), structConstructor(), testCaseMatchScalar(), and testForCaseMatch().
     {
         return dp->dimensions.isScalar();
     }
isSingleType()
const bool Nelson::ArrayOf::isSingleType () const
Returns TRUE if it is a double type (not ndarray, not sparse)
Returns TRUE if it is a single type (not ndarray, not sparse)
Definition at line 27 of file ArrayOf_SingleType.cpp.
     {
         return (dp->dataClass == NLS_SINGLE) || (dp->dataClass == NLS_SCOMPLEX) && (!dp->sparse) && is2D();
     }
isString()
const bool Nelson::ArrayOf::isString () const
Returns TRUE if we are a string.
Definition at line 28 of file ArrayOf_StringType.cpp.
Referenced by getContentsAsDoubleComplexScalar(), getContentsAsDoubleScalar(), getContentsAsSingleComplexScalar(), getContentsAsSingleScalar(), and testForCaseMatch().
     {
         return (dp->dataClass == NLS_STRING) && (!dp->sparse);
     }
isSymmetric()
const bool Nelson::ArrayOf::isSymmetric () const
Returns true if we are symmetric, 2D and square.
Definition at line 1399 of file ArrayOf.cpp.
     {
         if (!is2D())
         {
             return false;
         }
         if (isReferenceType())
         {
             return false;
         }
         if (isSparse())
         {
             throw Exception(_W("Cannot determine symmetry of sparse arrays"));
         }
         switch(dp->dataClass)
         {
                 caseReal(NLS_INT8,int8);
                 caseReal(NLS_INT16,int16);
                 caseReal(NLS_INT32,int32);
                 caseReal(NLS_UINT8,uint8);
                 caseReal(NLS_UINT16,uint16);
                 caseReal(NLS_UINT32,uint32);
                 caseReal(NLS_INT64, int64);
                 caseReal(NLS_UINT64, uint64);
                 caseReal(NLS_SINGLE,float);
                 caseReal(NLS_DOUBLE,double);
                 caseComplex(NLS_SCOMPLEX,float);
                 caseComplex(NLS_DCOMPLEX,double);
         }
         return false;
     }
isVector()
const bool Nelson::ArrayOf::isVector () const
Returns TRUE if we are a vector.
Definition at line 1682 of file ArrayOf.cpp.
Referenced by diagonalConstructor(), and getContentAsWideStringVector().
     {
         return dp->dimensions.isVector();
     }
logicalConstructor()
ArrayOf Nelson::ArrayOf::logicalConstructor (bool aval) static
Scalar constructor - Construct an NLS_LOGICAL object with a scalar value.
Definition at line 39 of file ArrayOf_LogicalType.cpp.
Referenced by Nelson::Evaluator::functionExpression().
     {
         Dimensions dim;
         dim.makeScalar();
         logical *data = (logical *)allocateArrayOf(NLS_LOGICAL, 1);
         *data = (logical)aval;
         return ArrayOf(NLS_LOGICAL, dim, data);
     }
nnz()
indexType Nelson::ArrayOf::nnz ()
Returns the number of nonzero elements in the array. For reference types, this is a best-guess.
Definition at line 4386 of file ArrayOf.cpp.
     {
         if (isEmpty())
         {
             return 0;
         }
         if (isSparse())
         {
 #ifdef __NLS_USE_SPARSE_EIGEN
             return CountNonzerosDynamicFunction(dp->dataClass,
                                                 getDimensionLength(0),
                                                 getDimensionLength(1),
                                                 dp->getData());
 #else
             return CountNonzeros(dp->dataClass,
                                  getDimensionLength(0),
                                  getDimensionLength(1),
                                  dp->getData());
 #endif
         }
         // OK - its not sparse... now what?
         switch (dp->dataClass)
         {
             case NLS_HANDLE:
                 return DoCountNNZReal<nelson_handle>(dp->getData(), getLength());
             case NLS_LOGICAL:
                 return DoCountNNZReal<logical>(dp->getData(),getLength());
             case NLS_INT8:
                 return DoCountNNZReal<int8>(dp->getData(),getLength());
             case NLS_UINT8:
             case NLS_STRING:
                 return DoCountNNZReal<uint8>(dp->getData(),getLength());
             case NLS_INT16:
                 return DoCountNNZReal<int16>(dp->getData(),getLength());
             case NLS_UINT16:
                 return DoCountNNZReal<uint16>(dp->getData(),getLength());
             case NLS_INT32:
                 return DoCountNNZReal<int32>(dp->getData(),getLength());
             case NLS_UINT32:
                 return DoCountNNZReal<uint32>(dp->getData(),getLength());
             case NLS_INT64:
                 return DoCountNNZReal<int64>(dp->getData(), getLength());
             case NLS_UINT64:
                 return DoCountNNZReal<uint64>(dp->getData(), getLength());
             case NLS_SINGLE:
                 return DoCountNNZReal<float>(dp->getData(),getLength());
             case NLS_DOUBLE:
                 return DoCountNNZReal<double>(dp->getData(),getLength());
             case NLS_SCOMPLEX:
                 return DoCountNNZComplex<float>(dp->getData(),getLength());
             case NLS_DCOMPLEX:
                 return DoCountNNZComplex<double>(dp->getData(),getLength());
             case NLS_CELL_ARRAY:
                 return DoCountNNZReal<void*>(dp->getData(),getLength());
             case NLS_STRUCT_ARRAY:
                 return DoCountNNZReal<void*>(dp->getData(),getLength()*dp->fieldNames.size());
         }
         return 0;
     }
operator=()
void Nelson::ArrayOf::operator= (const ArrayOf & copy)
Assignment operator.
Definition at line 854 of file ArrayOf.cpp.
     {
         if (this == &copy)
         {
             return;
         }
         if (dp)
         {
             if (dp->deleteCopy() <= 1)
             {
                 delete dp;
             }
             dp = nullptr;
         }
         if (copy.dp)
         {
             dp = copy.dp->getCopy();
         }
         else
         {
             dp = nullptr;
         }
     }
printMe()
void Nelson::ArrayOf::printMe (int printLimit, sizeType termWidth = 80) const
Print some reasonable representation of this array to the the supplied stream.
Display this variable on the given output stream.
For N-ary arrays, data slice - start with [1,1,1,...,1]. We keep doing the matrix print , incrementing from the highest dimension, and rolling downwards.
Definition at line 3978 of file ArrayOf.cpp.
Referenced by getArrayOfIOInterface().
     {
         int nominalWidth;
         // Print the class...
         switch(dp->dataClass)
         {
             case NLS_HANDLE:
                 io->outputMessage("  <handle>  ");
                 nominalWidth = 5;
                 break;
             case NLS_UINT8:
                 io->outputMessage("  <uint8>  ");
                 nominalWidth = 5;
                 break;
             case NLS_INT8:
                 io->outputMessage("  <int8>  ");
                 nominalWidth = 6;
                 break;
             case NLS_UINT16:
                 io->outputMessage("  <uint16>  ");
                 nominalWidth = 7;
                 break;
             case NLS_INT16:
                 io->outputMessage("  <int16>  ");
                 nominalWidth = 8;
                 break;
             case NLS_UINT32:
                 io->outputMessage("  <uint32>  ");
                 nominalWidth = 14;
                 break;
             case NLS_INT32:
                 io->outputMessage("  <int32>  ");
                 nominalWidth = 15;
                 break;
             case NLS_UINT64:
                 io->outputMessage("  <uint64>  ");
                 nominalWidth = 14;
                 break;
             case NLS_INT64:
                 io->outputMessage("  <int64>  ");
                 nominalWidth = 15;
                 break;
             case NLS_SINGLE:
                 io->outputMessage("  <single>  ");
                 nominalWidth = 20;
                 break;
             case NLS_DOUBLE:
                 io->outputMessage("  <double>  ");
                 nominalWidth = 30;
                 break;
             case NLS_LOGICAL:
                 io->outputMessage("  <logical>  ");
                 nominalWidth = 2;
                 break;
             case NLS_STRING:
                 io->outputMessage("  <string>  ");
                 nominalWidth = 1;
                 break;
             case NLS_SCOMPLEX:
                 io->outputMessage("  <single>  ");
                 nominalWidth = 36;
                 break;
             case NLS_DCOMPLEX:
                 io->outputMessage("  <double>  ");
                 nominalWidth = 54;
                 break;
             case NLS_CELL_ARRAY:
                 io->outputMessage("  <cell> ");
                 nominalWidth = 10;
                 break;
             case NLS_STRUCT_ARRAY:
                 io->outputMessage("  <struct> ");
                 nominalWidth = 10;
                 break;
         }
         io->outputMessage("- size: ");
         dp->dimensions.printMe(io);
         io->outputMessage("\n");
         if (isEmpty())
         {
             if (isStruct())
             {
                 stringVector fieldsName = getFieldNames();
                 if (fieldsName.size() == 0)
                 {
                     io->outputMessage("  []\n");
                 }
                 else
                 {
                     for (size_t k = 0; k < fieldsName.size(); k++)
                     {
                         io->outputMessage("    ");
                         io->outputMessage(fieldsName[k]);
                         io->outputMessage("\n");
                     }
                 }
             }
             else
             {
                 io->outputMessage("  []\n");
             }
             return;
         }
         if (isSparse())
         {
             sprintf(msgBuffer, _("\tMatrix is sparse with %d nonzeros\n").c_str(),
                     getNonzeros());
             io->outputMessage(msgBuffer);
             return;
         }
         if (dp->dataClass == NLS_STRUCT_ARRAY)
         {
             if (dp->dimensions.isScalar())
             {
                 ArrayOf *ap;
                 ap = (ArrayOf *) dp->getData();
                 for (sizeType n=0; n< (sizeType)dp->fieldNames.size(); n++)
                 {
                     io->outputMessage("    ");
                     io->outputMessage(dp->fieldNames[n].c_str());
                     io->outputMessage(": ");
                     ap[n].summarizeCellEntry();
                     io->outputMessage("\n");
                 }
             }
             else
             {
                 if (dp->fieldNames.size() > 0)
                 {
                     io->outputMessage("  Fields\n");
                     for (sizeType n = 0; n < (sizeType)dp->fieldNames.size(); n++)
                     {
                         io->outputMessage("    ");
                         io->outputMessage(dp->fieldNames[n].c_str());
                         io->outputMessage("\n");
                     }
                 }
             }
         }
         else
         {
             const void *ap = dp->getData();
             if (dp->dimensions.getLength() == 2)
             {
                 indexType rows = dp->dimensions.getRows();
                 indexType  columns = dp->dimensions.getColumns();
                 int items_printed;
                 items_printed = 0;
                 // Determine how many columns will fit across
                 // the terminal width
                 indexType colsPerPage = (indexType)floor((termWidth - 1) / ((float)nominalWidth));
                 indexType pageCount = (indexType)ceil(columns / ((float)colsPerPage));
                 for (indexType k = 0; k<pageCount && (items_printed<printLimit); k++)
                 {
                     indexType colsInThisPage = columns - colsPerPage*k;
                     colsInThisPage = (colsInThisPage > colsPerPage) ?
                                      colsPerPage : colsInThisPage;
                     if (dp->dimensions.getElementCount() > 1 &&
                             dp->dataClass != NLS_STRING)
                     {
                         snprintf(msgBuffer, MSGBUFLEN, _("\nColumns %d to %d\n").c_str(),
                                  k*colsPerPage+1,k*colsPerPage+colsInThisPage);
                         io->outputMessage(msgBuffer);
                     }
                     memset(msgBuffer,0,MSGBUFLEN);
                     for (indexType i = 0; i<rows && (items_printed<printLimit); i++)
                     {
                         snprintf(msgBuffer,MSGBUFLEN," ");
                         io->outputMessage(msgBuffer);
                         memset(msgBuffer,0,MSGBUFLEN);
                         for (indexType j = 0; j<colsInThisPage && (items_printed<printLimit); j++)
{
                             emitElement(msgBuffer,
                                         ap,i+(k*colsPerPage+j)*rows,
                                         dp->dataClass);
                             items_printed++;
                         }
                         snprintf(msgBuffer,MSGBUFLEN,"\n");
                         io->outputMessage(msgBuffer);
                         memset(msgBuffer,0,MSGBUFLEN);
                     }
                 }
                 if (items_printed >= printLimit)
                 {
                     io->outputMessage(_W("\n... Output truncated - use setprintlimit function to see more of the output ...\n"));
                 }
             }
             else if (dp->dimensions.getLength() > 2)
             {
                 Dimensions wdims(dp->dimensions.getLength());
                 indexType rows(dp->dimensions.getRows());
                 indexType columns(dp->dimensions.getColumns());
                 int items_printed;
                 items_printed = 0;
                 indexType offset = 0;
                 while (wdims.inside(dp->dimensions) && (items_printed<printLimit))
                 {
                     snprintf(msgBuffer,MSGBUFLEN,"(:,:");
                     io->outputMessage(msgBuffer);
                     for (sizeType m=2; m<dp->dimensions.getLength(); m++)
                     {
                         snprintf(msgBuffer,MSGBUFLEN,",%d",wdims[m]+1);
                         io->outputMessage(msgBuffer);
                     }
                     snprintf(msgBuffer,MSGBUFLEN,") =\n\n");
                     io->outputMessage(msgBuffer);
                     // Determine how many columns will fit across
                     // the terminal width
                     indexType colsPerPage = (indexType)floor((termWidth - 1) / ((float)nominalWidth));
                     int pageCount;
                     pageCount = (int) ceil(columns/((float)colsPerPage));
                     for (int k=0; k<pageCount && (items_printed<printLimit); k++)
                     {
                         indexType colsInThisPage = columns - colsPerPage*k;
                         colsInThisPage = (colsInThisPage > colsPerPage) ?
                                          colsPerPage : colsInThisPage;
                         snprintf(msgBuffer,MSGBUFLEN,_("\nColumns %d to %d\n").c_str(),
                                  k*colsPerPage+1,k*colsPerPage+colsInThisPage);
                         io->outputMessage(msgBuffer);
                         memset(msgBuffer,0,MSGBUFLEN);
                         for (indexType i = 0; i<rows && (items_printed<printLimit); i++)
{
                             snprintf(msgBuffer,MSGBUFLEN," ");
                             io->outputMessage(msgBuffer);
                             memset(msgBuffer,0,MSGBUFLEN);
                             for (indexType j = 0; j<colsInThisPage && (items_printed<printLimit); j++)
{
                                 emitElement(msgBuffer,
                                             ap,i+(k*colsPerPage+j)*rows+offset,
                                             dp->dataClass);
                                 items_printed++;
                             }
                             snprintf(msgBuffer,MSGBUFLEN,"\n");
                             io->outputMessage(msgBuffer);
                             memset(msgBuffer,0,MSGBUFLEN);
                         }
                     }
                     offset += rows*columns;
                     wdims.incrementModulo(dp->dimensions,2);
                 }
                 if (items_printed >= printLimit)
                 {
                     io->outputMessage(_W("\n... Output truncated - use setprintlimit function to see more of the output ...\n"));
                 }
             }
         }
     }
promoteType() [1/2]
void Nelson::ArrayOf::promoteType (Class dstClass, stringVector fNames)
Promote our array to a new type. For empty arrays, this type promotion always succeeds. For cell arrays, this does nothing (except throw an error if we attempt to promote it to a different type). For structure arrays, promoting to a structure array has three possible outcomes:
If the fields match in order and contents then the promotion is successful.
If the fields match in contents but not in-order then the promotion involves reordering the data.
If the fields match in contents but the destination type has additional fields, then the promotion involves reordering the data and adding space. Throws an exception if
we try to convert a cell-array to another type.
we try to promote a structure-array to another array with an incompatible field setup (i.e., not one of the three outcomes listed above).
we try to convert a structure-array to a non-structure array type.
we try to convert any numerical types to a reference type.
Promote our data to a new type.
Copy data from our data array to the specified array, converting the data as we go. We can only convert data to or from base types. So if the source or destination types are reference types, we cannot perform the conversion.
For the remaining types, we have a matrix of possibilities. Here we list the conversion rules.
Source type
string
logical dest = (source == 0) ? 0 : 1
real dest = (double) source
complex dest = (double) source
logical
string dest = (char) source
real dest = (double) source
complex dest = (double) source
real
string dest = (char) source
logical dest = (source == 0) ? 0 : 1
complex dest = (double) source
complex
string dest = (char) real(source)
logical dest = (real(source) == 0 && imag(source) == 0) ? 0:1
real dest = real(source)
Definition at line 1867 of file ArrayOf.cpp.
Referenced by Nelson::doPowerAssist(), Nelson::Evaluator::expression(), Nelson::Evaluator::expressionList(), getContentAsScalarIndex(), getContentsAsDoubleComplexScalar(), getContentsAsDoubleScalar(), getContentsAsInteger32Scalar(), getContentsAsInteger64Scalar(), getContentsAsSingleComplexScalar(), getContentsAsSingleScalar(), getContentsAsUnsignedInt64Scalar(), Nelson::Not(), promoteType(), setField(), setFieldAsList(), setNDimContents(), setNDimContentsAsList(), setNDimSubset(), setVectorContents(), setVectorContentsAsList(), setVectorSubset(), testCaseMatchScalar(), and Nelson::TypeCheck().
     {
         indexType elCount = 0;
         void *dstPtr = nullptr;
         if (isEmpty())
         {
             dp = dp->putData(dstClass, dp->dimensions,NULL, isSparse(), fNames);
             return;
         }
         if (dp->dataClass == NLS_HANDLE)
             if (dstClass == NLS_HANDLE)
             {
                 return;
             }
             else
             {
                 throw Exception(_W("Cannot convert handle-arrays to any other type."));
             }
         // Handle the reference types.
         // Cell arrays can be promoted with no effort to cell arrays.
         if (dp->dataClass == NLS_CELL_ARRAY)
             if (dstClass == NLS_CELL_ARRAY)
             {
                 return;
             }
             else
             {
                 throw Exception(_W("Cannot convert cell-arrays to any other type."));
             }
         // Structure arrays can be promoted to structure arrays with different
         // field structures, but have to be rearranged.
         if (dp->dataClass == NLS_STRUCT_ARRAY)
             if (dstClass == NLS_STRUCT_ARRAY)
             {
                 // TODO: Generalize this code to allow for one more field in destination
                 // than in source...
                 if (dp->fieldNames.size() >  fNames.size())
                 {
                     throw Exception(_W("Cannot combine structures with different fields if the combination requires fields to be deleted from one of the structures."));
                 }
                 // We are promoting a struct array to a struct array.
                 // To do so, we have to make sure that the field names work out.
                 // The only thing we must check for is that every field name
                 // in fieldnames is present in fnames.
                 int extraCount = 0;
                 int matchCount = 0;
                 indexType i;
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (i=0; i<(int)fNames.size(); i++)
                 {
                     int64 ndx = getFieldIndex(fNames[i]);
                     if (ndx == -1)
                     {
                         extraCount++;
                     }
                     else
                     {
                         matchCount++;
                     }
                 }
                 // Now, matchCount should be equal to the size of fieldNames
                 if (matchCount != dp->fieldNames.size())
                 {
                     throw Exception(_W("Cannot combine structures with different fields if the combination requires fields to be deleted from one of the structures."));
                 }
                 void *dstPtr = allocateArrayOf(dp->dataClass,getLength(),fNames);
                 const ArrayOf *src_rp = (const ArrayOf*) dp->getData();
                 ArrayOf * dst_rp = (ArrayOf*) dstPtr;
                 indexType elCount(getLength());
                 indexType fieldCount(dp->fieldNames.size());
                 indexType newFieldCount(fNames.size());;
                 // Now we have to copy our existing fields into the new order...
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (i=0; i<fieldCount; i++)
                 {
                     int64 newNdx = getFieldIndexFromList(dp->fieldNames[i], fNames);
                     for (indexType j = 0; j<elCount; j++)
                     {
                         dst_rp[j*newFieldCount + newNdx] = src_rp[j*fieldCount + i];
                     }
                 }
                 dp = dp->putData(dp->dataClass,dp->dimensions,dstPtr,false,fNames);
                 return;
             }
             else
             {
                 throw Exception(_W("Cannot convert struct-arrays to any other type."));
             }
         // Catch attempts to convert data types to reference types.
         if ((dstClass == NLS_CELL_ARRAY) || (dstClass == NLS_STRUCT_ARRAY))
         {
             throw Exception(_W("Cannot convert base types to reference types."));
         }
         // Do nothing for promoting to same class (no-op).
         if (isSparse())
         {
 #ifdef          __NLS_USE_SPARSE_EIGEN
             dp = dp->putData(dstClass,dp->dimensions,
                              TypeConvertSparseDynamicFunction(dp->dataClass,
                                      dp->dimensions[0],
                                      dp->dimensions[1],
                                      dp->getData(),
                                      dstClass),
                              true);
 #else
             dp = dp->putData(dstClass, dp->dimensions,
                              TypeConvertSparse(dp->dataClass,
                                                dp->dimensions[0],
                                                dp->dimensions[1],
                                                dp->getData(),
                                                dstClass),
                              true);
 #endif
             return;
         }
         if (dstClass == dp->dataClass)
         {
             return;
         }
         elCount = getLength();
         // We have to promote...
         dstPtr = allocateArrayOf(dstClass,elCount);
         indexType count = elCount;
         switch (dp->dataClass)
         {
 #define caseMacro(caseLabel,dpType,convCode) \
 case caseLabel: \
 { dpType* qp = (dpType*) dstPtr; \
   for (indexType i=0;i<count;i++) convCode; \
 } \
 break;
             case NLS_STRING:
             {
                 charType* sp = (charType *)dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_LOGICAL:
             {
                 const logical* sp = (const logical *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_UINT8:
             {
                 const uint8* sp = (const uint8 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_INT8:
             {
                 const int8* sp = (const int8 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_UINT16:
             {
                 const uint16* sp = (const uint16 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_INT16:
             {
                 const int16* sp = (const int16 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_UINT32:
             {
                 const uint32* sp = (const uint32 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_INT32:
             {
                 const int32* sp = (const int32 *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_INT64:
             {
                 const int64* sp = (const int64 *)dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL, logical, qp[i] = (sp[i] == 0) ? 0 : 1);
                         caseMacro(NLS_UINT8, uint8, qp[i] = (uint8)sp[i]);
                         caseMacro(NLS_INT8, int8, qp[i] = (int8)sp[i]);
                         caseMacro(NLS_UINT16, uint16, qp[i] = (uint16)sp[i]);
                         caseMacro(NLS_INT16, int16, qp[i] = (int16)sp[i]);
                         caseMacro(NLS_UINT32, uint32, qp[i] = (uint32)sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE, float, qp[i] = (float)sp[i]);
                         caseMacro(NLS_DOUBLE, double, qp[i] = (double)sp[i]);
                         caseMacro(NLS_SCOMPLEX, float, qp[i << 1] = (float)sp[i]);
                         caseMacro(NLS_DCOMPLEX, double, qp[i << 1] = (double)sp[i]);
                 }
             }
             break;
             case NLS_UINT64:
             {
                 const uint64* sp = (const uint64 *)dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL, logical, qp[i] = (sp[i] == 0) ? 0 : 1);
                         caseMacro(NLS_UINT8, uint8, qp[i] = (uint8)sp[i]);
                         caseMacro(NLS_INT8, int8, qp[i] = (int8)sp[i]);
                         caseMacro(NLS_UINT16, uint16, qp[i] = (uint16)sp[i]);
                         caseMacro(NLS_INT16, int16, qp[i] = (int16)sp[i]);
                         caseMacro(NLS_UINT32, uint32, qp[i] = (uint32)sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE, float, qp[i] = (float)sp[i]);
                         caseMacro(NLS_DOUBLE, double, qp[i] = (double)sp[i]);
                         caseMacro(NLS_SCOMPLEX, float, qp[i << 1] = (float)sp[i]);
                         caseMacro(NLS_DCOMPLEX, double, qp[i << 1] = (double)sp[i]);
                 }
             }
             break;
             case NLS_SINGLE:
             {
                 const float* sp = (const float *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_DOUBLE:
             {
                 const double* sp = (const double *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = (sp[i]==0) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i]);
                         caseMacro(NLS_SCOMPLEX,float,qp[i<<1] = (float) sp[i]);
                         caseMacro(NLS_DCOMPLEX,double,qp[i<<1] = (double) sp[i]);
                 }
             }
             break;
             case NLS_SCOMPLEX:
             {
                 const float* sp = (const float *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i << 1]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = ((sp[i<<1]==0.0) && (sp[(i<<1) + 1] == 0.0)) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i<<1]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i<<1]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i<<1]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i<<1]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i<<1]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i<<1]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i << 1]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i << 1]);
                     case NLS_SINGLE:
                     {
                         singlecomplex* Az = reinterpret_cast<singlecomplex*>((single*)sp);
                         single* qp = (single*)dstPtr;
                         Eigen::Map<Eigen::MatrixXcf> matA(Az, 1, dp->dimensions.getElementCount());
                         Eigen::Map<Eigen::MatrixXf> matB(qp, 1, dp->dimensions.getElementCount());
                         matB = matA.real();
                     }
                     break;
                     caseMacro(NLS_DOUBLE,double,qp[i] = (double) sp[i<<1]);
                     caseMacro(NLS_DCOMPLEX,double, {qp[i<<1]=(double)sp[i<<1]; qp[(i<<1)+1]=(double)sp[(i<<1)+1];});
                 }
             }
             break;
             case NLS_DCOMPLEX:
             {
                 const double* sp = (const double *) dp->getData();
                 switch (dstClass)
                 {
                         caseMacro(NLS_STRING, charType, qp[i] = (charType)sp[i << 1]);
                         caseMacro(NLS_LOGICAL,logical,qp[i] = ((sp[i<<1]==0.0) && (sp[(i<<1) + 1] == 0.0)) ? 0 : 1);
                         caseMacro(NLS_UINT8,uint8,qp[i] = (uint8) sp[i<<1]);
                         caseMacro(NLS_INT8,int8,qp[i] = (int8) sp[i<<1]);
                         caseMacro(NLS_UINT16,uint16,qp[i] = (uint16) sp[i<<1]);
                         caseMacro(NLS_INT16,int16,qp[i] = (int16) sp[i<<1]);
                         caseMacro(NLS_UINT32,uint32,qp[i] = (uint32) sp[i<<1]);
                         caseMacro(NLS_INT32,int32,qp[i] = (int32) sp[i<<1]);
                         caseMacro(NLS_UINT64, uint64, qp[i] = (uint64)sp[i << 1]);
                         caseMacro(NLS_INT64, int64, qp[i] = (int64)sp[i << 1]);
                         caseMacro(NLS_SINGLE,float,qp[i] = (float) sp[i<<1]);
                     case NLS_DOUBLE:
                     {
                         doublecomplex* Az = reinterpret_cast<doublecomplex*>((double*)sp);
                         double* qp = (double*)dstPtr;
                         Eigen::Map<Eigen::MatrixXcd> matA(Az, 1, dp->dimensions.getElementCount());
                         Eigen::Map<Eigen::MatrixXd> matB(qp, 1, dp->dimensions.getElementCount());
                         matB = matA.real();
                     }
                     break;
                     caseMacro(NLS_SCOMPLEX,float, {qp[i<<1]=(float)sp[i<<1]; qp[(i<<1)+1]=(float)sp[(i<<1)+1];});
                 }
             }
             break;
         }
         dp = dp->putData(dstClass,dp->dimensions,dstPtr);
     }
promoteType() [2/2]
void Nelson::ArrayOf::promoteType (Class new_type)
Promote our array to a new type. This is a shortcut for when new_type is not NLS_STRUCT_ARRAY, so that the fieldNames argument is not needed.
Definition at line 2318 of file ArrayOf.cpp.
     {
         stringVector dummy;
         promoteType(dstClass,dummy);
     }
reshape()
void Nelson::ArrayOf::reshape (Dimensions & a)
Reshape an array. Reshape the array along a new set of dimensions. Valid provided that setting the dimensions of the array to a does not change the number of elements in the array. Throws an exception if the new dimension has a different number of elements than we currently have.
Reshape an array. This is only legal if the number of elements remains the same after reshaping.
Definition at line 1266 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::rhsExpression(), and vectorResize().
     {
         if (isClassStruct())
         {
             throw Exception(_W("Reshape operation not allowed for overloaded type."));
         }
         if (isFunctionHandle())
         {
             throw Exception(_W("Reshape operation not allowed for 'function_handle' type."));
         }
         if (a.getElementCount() != getLength())
         {
             throw Exception(_W("Reshape operation cannot change the number of elements in array."));
         }
         if (isSparse())
         {
             if (a.is2D() || a.isVector() || a.isScalar())
             {
                 void *reshapedSparseMatrix = ReshapeSparseMatrixDynamicFunction(dp->dataClass, dp->dimensions[0], dp->dimensions[1], a[0], a[1], dp->getData());
                 dp = dp->putData(dp->dataClass, a, reshapedSparseMatrix, true);
                 dp->dimensions = a;
             }
             else
             {
                 throw Exception(_W("Reshape operation not allowed with N Dimensions sparse arrays."));
             }
         }
         else
         {
             ensureSingleOwner();
             dp->dimensions = a;
         }
     }
resize()
void Nelson::ArrayOf::resize (Dimensions & a)
Resize an array. Resize the array to a new set of dimensions. This resize operation puts the contents of the array at the (0,...,0) corner of the new array.
Definition at line 1170 of file ArrayOf.cpp.
Referenced by setDataPointer(), setField(), setFieldAsList(), setNDimContents(), setNDimContentsAsList(), setNDimSubset(), and vectorResize().
     {
         Dimensions newSize;
         // Make a copy of the current dimension vector, and
         // compute the new dimension size.
         newSize = dp->dimensions;
         newSize.expandToCover(a);
         // Check to see if the dimensions are unchanged.
         if (newSize.equals(dp->dimensions))
         {
             return;
         }
         // Check to see if the total number of elements is unchanged.
         if (newSize.getElementCount() == getLength())
         {
             ensureSingleOwner();
             dp->dimensions = newSize;
             return;
         }
         if (isSparse())
         {
             throw Exception(_W("Cannot resize sparse arrays."));
         }
         // Allocate space for our new size.
         void *dst_data = allocateArrayOf(dp->dataClass,newSize.getElementCount(),dp->fieldNames);
         if (!isEmpty())
         {
             // Initialize a pointer to zero.
             Dimensions curPos(dp->dimensions.getLength());
             // Because we copy & convert data a column at a time, we retrieve
             // the number of rows in each column.
             indexType rowCount = dp->dimensions[0];
             // Track our offset into the original data.
             indexType srcIndex = 0;
             while (curPos.inside(dp->dimensions))
             {
                 // Get the destination index for the current source position.
                 indexType dstIndex = newSize.mapPoint(curPos);
                 // Copy the data from our original data structure to the
                 // new data structure, starting from the source index
                 // srcIndex, and moving to dstIndex.
                 copyElements(srcIndex,dst_data,dstIndex,rowCount);
                 // Update the column number (as we have just copied an
                 // entire column).
                 curPos.incrementModulo(dp->dimensions,1);
                 // Advance the source data pointer so that it points to the
                 // start of the next column.
                 srcIndex += rowCount;
             }
         }
         dp = dp->putData(dp->dataClass,newSize,dst_data,
                          dp->sparse,dp->fieldNames);
     }
setArrayOfIOInterface()
void Nelson::ArrayOf::setArrayOfIOInterface (Interface * io) static
Sets the IO interface used by instances of the ArrayOf class.
Definition at line 81 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::Evaluator().
     {
         io = a_io;
     }
setDataPointer()
void Nelson::ArrayOf::setDataPointer (void * rp)
Set the contents of our data block to the supplied pointer. Set the contents of our data block to the supplied pointer. Ownership of the data block is passed to the array, i.e., the caller should not manipulate the block in any way after calling this function. To avoid recopying, ownership of the byte-array is passed to the reference counting data object Data at this point. That means that the caller is not responsible for freeing the memory block.
Definition at line 995 of file ArrayOf.cpp.
Referenced by Nelson::Negate(), and Nelson::Not().
     {
         dp = dp->putData(dp->dataClass,dp->dimensions,rp,
                          dp->sparse,dp->fieldNames);
     }
setField()
void Nelson::ArrayOf::setField (std::string fieldName, ArrayOf & data)
Replace the contents of a field with the supplied array. Only valid for scalar structures. Throws an exception if we are not a structure array or we are a multi-element structure-array.
Set the contents of a field in a structure.
Definition at line 239 of file ArrayOf_StructType.cpp.
     {
         if (isEmpty())
         {
             stringVector newNames(dp->fieldNames);
             newNames.push_back(fieldName);
             promoteType(NLS_STRUCT_ARRAY, newNames);
             Dimensions a;
             a[0] = 1;
             a[1] = 1;
             resize(a);
         }
         if (isSparse())
         {
             throw Exception(_W("setField not supported for sparse arrays."));
         }
         if (dp->dataClass != NLS_STRUCT_ARRAY)
         {
             throw Exception(_W("Cannot apply A.field_name = B to non struct-array object A."));
         }
         if (!isScalar())
         {
             throw Exception(_W("Cannot apply A.field_name = B to multi-element structure array A."));
         }
         double field_ndx = (double)getFieldIndex(fieldName);
         if (field_ndx == -1)
         {
             field_ndx = (double)insertFieldName(fieldName);
         }
         ArrayOf *sp = (ArrayOf*)getReadWriteDataPointer();
         sp[(indexType)field_ndx] = data;
         dp->dimensions.simplify();
     }
setFieldAsList()
void Nelson::ArrayOf::setFieldAsList (std::string fieldName, ArrayOfVector & data)
Replace the contents of a field with the supplied array. This is used when a structure array is used to hold the return of a multi-function call, i.e.: [x.foo] = foo Throws an exception if
we are not a structure array
the number of elements in data is not equal to the number of elements in our array.
Set the contents of a field in a structure.
Definition at line 276 of file ArrayOf_StructType.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (isSparse())
         {
             throw Exception(_W("setFieldAsList not supported for sparse arrays."));
         }
         if (isEmpty())
         {
             bool bFieldAlreadyExist = false;
             for (size_t k = 0; k < dp->fieldNames.size(); k++)
             {
                 if (fieldName == dp->fieldNames[k])
                 {
                     bFieldAlreadyExist = true;
                     break;
                 }
             }
             stringVector names(dp->fieldNames);
             if (!bFieldAlreadyExist)
             {
                 names.push_back(fieldName);
             }
             promoteType(NLS_STRUCT_ARRAY, names);
             Dimensions a;
             a[0] = 1;
             a[1] = 1;
             resize(a);
             //       dp = dp->putData(NLS_STRUCT_ARRAY,dp->getDimensions(),NULL,names);
             //       return;
         }
         if (!this->isStruct())
         {
             throw Exception(_W("Cannot apply A.field_name = B to non struct-array object A."));
         }
         if ((int)data.size() < getLength())
         {
             throw Exception(_W("Not enough right hand values to satisfy left hand side expression."));
         }
         indexType indexLength = getLength();
         int64 field_ndx = getFieldIndex(fieldName);
         if (field_ndx == -1)
         {
             field_ndx = insertFieldName(fieldName);
         }
         indexType fieldCount = dp->fieldNames.size();
         ArrayOf *qp = (ArrayOf*)getReadWriteDataPointer();
         for (indexType i = 0; i<indexLength; i++)
         {
             qp[i*fieldCount + field_ndx] = data.front();
             //      data.pop_front();
             data.erase(data.begin());
         }
         dp->dimensions.simplify();
     }
setNDimContents()
void Nelson::ArrayOf::setNDimContents (ArrayOfVector & index, ArrayOf & data)
Set a subset of an ArrayOf. This if for n-Dimensional-indexing, meaning that x{10} is really x{10,1}. Throws an exception if the index is not a scalar
This is the multidimensional cell-replacement function. This is for content-based indexing (curly brackets).
Definition at line 314 of file ArrayOf_CellType.cpp.
     {
         promoteType(NLS_CELL_ARRAY, data.dp->fieldNames);
         if (isSparse())
         {
             throw Exception(_W("setNDimContents not supported for sparse arrays."));
         }
         indexType L = index.size();
         Dimensions outPos(L);
         indexType i;
         for (i = 0; i<L; i++)
         {
             index[i].toOrdinalType();
             if (!index[i].isScalar())
             {
                 throw Exception(_W("In expression A{I1,I2,...,IN} = B, (I1,...,IN) must reference a single element of cell-array A."));
             }
             constIndexPtr sp = (constIndexPtr)index[i].dp->getData();
             outPos[i] = *sp;
         }
         resize(outPos);
         for (i = 0; i<L; i++)
         {
             outPos[i] = outPos[i] - 1;
         }
         indexType j = dp->dimensions.mapPoint(outPos);
         ArrayOf *qp = (ArrayOf*)getReadWriteDataPointer();
         qp[j] = data;
         dp->dimensions.simplify();
     }
setNDimContentsAsList()
void Nelson::ArrayOf::setNDimContentsAsList (ArrayOfVector & index, ArrayOfVector & data)
Set a subset of an ArrayOf. This if for n-Dimensional-indexing, meaning that x{10} is really x{10,1}. This is used when a cell-array is used as the return of a multi-function call, i.e.: [x{1,3:5}] = foo. Throws an exception if the number of elements in data do not match the number of indices covered by index (which is the product of the number of elements in each dimension of index).
This is the multidimensional cell-replacement function. This is for content-based indexing (curly brackets).
Definition at line 390 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (isSparse())
         {
             throw Exception(_W("setNDimContentsAsList not supported for sparse arrays."));
         }
         promoteType(NLS_CELL_ARRAY);
         indexType L = index.size();
         // Convert the indexing variables into an ordinal type.
         indexType i;
         for (i = 0; i<L; i++)
         {
             index[i].toOrdinalType();
         }
         // Set up data pointers
         constIndexPtr* indx = new_with_exception<constIndexPtr>(L);
         try
         {
             Dimensions a(L);
             // First, we compute the maximum along each dimension.
             // We also get pointers to each of the index pointers.
             for (i = 0; i<L; i++)
             {
                 a[i] = index[i].getMaxAsIndex();
                 indx[i] = (constIndexPtr)index[i].dp->getData();
             }
             // Next, we compute the number of entries in each component.
             Dimensions argLengths(L);
             Dimensions argPointer(L);
             indexType  dataCount = 1;
             for (i = 0; i<L; i++)
             {
                 argLengths[i] = index[i].getLength();
                 dataCount *= argLengths[i];
             }
             if ((int)data.size() < dataCount)
             {
                 throw Exception(_W("Not enough right hand side values to satisfy left hand side expression"));
             }
             // Resize us as necessary
             resize(a);
             // Get a writable data pointer
             ArrayOf *qp = (ArrayOf*)getReadWriteDataPointer();
             // Now, we copy data from dp to our real part,
             // computing indices along the way.
             Dimensions currentIndex(dp->dimensions.getLength());
             indexType j;
             while (argPointer.inside(argLengths))
             {
                 for (i = 0; i<L; i++)
                 {
                     currentIndex[i] = (indexType)indx[i][argPointer[i]] - 1;
                 }
                 j = dp->dimensions.mapPoint(currentIndex);
                 qp[j] = data.front();
                 //  data.pop_front();
                 data.erase(data.begin());
                 argPointer.incrementModulo(argLengths, 0);
             }
             delete[] indx;
             indx = nullptr;
             dp->dimensions.simplify();
         }
         catch (Exception &e)
         {
             delete[] indx;
             indx = nullptr;
             e.what();
             throw;
         }
     }
setNDimSubset()
void Nelson::ArrayOf::setNDimSubset (ArrayOfVector & index, ArrayOf & data)
Set a subset of an ArrayOf. This if for n-Dimensional-indexing, meaning that x(10) is really x(10,1). Throws an exception if there is a size mismatch between the index and the data.
Take the contents of data, and insert this data.
This requires the following steps:
Compute the maximum along each dimension
Compute the dimensions of the right hand side
Check that data is either a scalar or the right size
If necessary, zero-extend the variable.
Copy in the result.
This is true for integer arguments - not for logical ones. Logical indices need to be converted into integer lists before they can be used.
Definition at line 3017 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         constIndexPtr* indx = nullptr;
         // If the RHS is empty, then we really want to do a delete...
         if (data.isEmpty())
         {
             deleteNDimSubset(index);
             return;
         }
         try
         {
             indexType L = index.size();
             indexType i = 0;
             // Convert the indexing variables into an ordinal type.
             for (i=0; i<L; i++)
             {
                 if (index[i].isEmpty())
                 {
                     return;
                 }
                 index[i].toOrdinalType();
             }
             // Check to see if any of the index variables are empty -
             bool anyEmpty = false;
             for (i=0; i<L; i++)
             {
                 anyEmpty = anyEmpty | (index[i].isEmpty());
             }
             // If any of the dimensions are empty, this entire method
             // is a NOP.  The reason we don't just return is because
             // of clean up.
             if (anyEmpty)
             {
                 return;
             }
             // Set up data pointers
             indx = new_with_exception<constIndexPtr>(L);
             Dimensions a(L);
             // First, we compute the maximum along each dimension.
             for (i=0; i<L; i++)
             {
                 a[i] = index[i].getMaxAsIndex();
                 indx[i] = (constIndexPtr) index[i].dp->getData();
             }
             // Next, we compute the number of entries in each component.
             Dimensions argLengths(L);
             Dimensions argPointer(L);
             indexType dataCount = 1;
             for (i=0; i<L; i++)
             {
                 argLengths[i] = index[i].getLength();
                 dataCount *= argLengths[i];
             }
             // Next, we compute the dimensions of the right hand side
             indexType advance = 0;
             if (data.isSparse())
             {
                 data.makeDense();
             }
             if (data.isScalar())
             {
                 advance = 0;
             }
             else if (!isEmpty() && (data.getLength() == dataCount))
             {
                 advance = 1;
             }
             else if (!isEmpty())
             {
                 throw Exception(_W("Size mismatch in assignment A(I1,I2,...,In) = B."));
             }
             else
             {
                 advance = 1;
             }
             // If the RHS type is superior to ours, we
             // force our type to agree with the inserted data.
             if (!isEmpty() &&
                     (data.getDataClass() == NLS_STRUCT_ARRAY) &&
                     (getDataClass() == NLS_STRUCT_ARRAY))
             {
                 if (data.dp->fieldNames.size() > dp->fieldNames.size())
                 {
                     promoteType(NLS_STRUCT_ARRAY,data.dp->fieldNames);
                 }
                 else
                 {
                     data.promoteType(NLS_STRUCT_ARRAY,dp->fieldNames);
                 }
             }
             else
             {
                 if (isEmpty() || data.getDataClass() > getDataClass())
                 {
                     promoteType(data.dp->dataClass,data.dp->fieldNames);
                 }
                 // If our type is superior to the RHS, we convert
                 // the RHS to our type
                 else if (data.dp->dataClass <= dp->dataClass)
                 {
                     data.promoteType(dp->dataClass,dp->fieldNames);
                 }
             }
             if (isSparse())
             {
                 if (L > 2)
                 {
                     throw Exception(_W("multidimensional indexing (more than 2 dimensions) not legal for sparse arrays in assignment A(I1,I2,...,IN) = B"));
                 }
                 indexType rows = getDimensionLength(0);
                 indexType cols = getDimensionLength(1);
 #ifdef __NLS_USE_SPARSE_EIGEN
                 void *qp = SetSparseNDimSubsetsDynamicFunction(dp->dataClass, rows, cols,
                            dp->getData(),
                            (const indexType*)indx[0],
                            argLengths[0],
                            (const indexType*)indx[1],
                            argLengths[1],
                            data.getDataPointer(), (int)advance);
 #else
                 void *qp = SetSparseNDimSubsets(dp->dataClass, rows, cols,
                                                 dp->getData(),
                                                 (const indexType*)indx[0],
                                                 argLengths[0],
                                                 (const indexType*)indx[1],
                                                 argLengths[1],
                                                 data.getDataPointer(), advance);
 #endif
                 Dimensions newdim;
                 newdim[0] = rows;
                 newdim[1] = cols;
                 dp = dp->putData(dp->dataClass,newdim,qp,true);
                 return;
             }
             // Now, resize us to fit this data
             resize(a);
             // Get a writable data pointer
             void *qp = getReadWriteDataPointer();
             // Now, we copy data from dp to our real part,
             // computing indices along the way.
             Dimensions currentIndex(dp->dimensions.getLength());
             indexType srcIndex = 0;
             indexType j;
             while (argPointer.inside(argLengths))
             {
                 for (indexType i = 0; i < L; i++)
                 {
                     currentIndex[i] = (indexType) indx[i][argPointer[i]] - 1;
                 }
                 j = dp->dimensions.mapPoint(currentIndex);
                 data.copyElements(srcIndex,qp,j,1);
                 srcIndex += advance;
                 argPointer.incrementModulo(argLengths,0);
             }
             delete [] indx;
             indx = nullptr;
             dp->dimensions.simplify();
         }
         catch (Exception &e)
         {
             delete[] indx;
             indx = nullptr;
             e.what();
             throw ;
         }
     }
setVectorContents()
void Nelson::ArrayOf::setVectorContents (ArrayOf & index, ArrayOf & data)
Set a subset of an ArrayOf using contents-indexing, meaning that the argument is assumed to refer to the elements in their order as a vector. So, x{10} is equivalent to x(:){10}, even if, say, x is 3 x 4. Throws an exception if
the index has more than one element in it
the index is less than 1
This is the vector version of the multidimensional cell-replacement function. This is for content-based indexing (curly brackets). Two points that make this function different than replaceData are
If the index is larger than the size, we resize to a vector of sufficient length.
Deletions do not occur.
Definition at line 282 of file ArrayOf_CellType.cpp.
     {
         promoteType(NLS_CELL_ARRAY, data.dp->fieldNames);
         if (isSparse())
         {
             throw Exception(_W("setVectorContents not supported for sparse arrays."));
         }
         index.toOrdinalType();
         if (index.getLength() == 0)
         {
             return;
         }
         if (index.getLength() != 1)
         {
             throw Exception(_W("In expression A{I} = B, I must reference a single element of cell-array A."));
         }
         constIndexPtr index_p = (constIndexPtr)index.dp->getData();
         if (*index_p == 0)
         {
             throw Exception(_W("Illegal negative index in expression A{I} = B."));
         }
         indexType ndx = *index_p - 1;
         vectorResize(ndx + 1);
         ArrayOf *qp = (ArrayOf*)getReadWriteDataPointer();
         qp[ndx] = data;
         dp->dimensions.simplify();
     }
setVectorContentsAsList()
void Nelson::ArrayOf::setVectorContentsAsList (ArrayOf & index, ArrayOfVector & data)
Set a subset of an ArrayOf using contents-indexing, meaning that the argument is assumed to refer to the elements in their order as a vector. So, x{10} is equivalent to x(:){10}, even if, say, x is 3 x 4. This is used when a cell-array is used as the return of a multi-function call, i.e.: [x{3:5}] = foo. Throws an exception if the number of elements in data do not match the number of indices in index.
This is the vector version of the multidimensional cell-replacement function. This is for content-based indexing (curly brackets). Two points that make this function different than replaceData are
If the index is larger than the size, we resize to a vector of sufficient length.
Deletions do not occur.
Definition at line 353 of file ArrayOf_CellType.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (isSparse())
         {
             throw Exception(_W("setVectorContentsAsList not supported for sparse arrays."));
         }
         promoteType(NLS_CELL_ARRAY);
         index.toOrdinalType();
         if ((indexType)data.size() < index.getLength())
         {
             throw Exception(_W("Not enough right hand side values to satisy left hand side expression."));
         }
         // Get the maximum index
         indexType max_index = index.getMaxAsIndex();
         // Resize us as necessary.
         vectorResize(max_index);
         // Get a pointer to the dataset
         ArrayOf *qp = (ArrayOf*)getReadWriteDataPointer();
         // Get a pointer to the index data set
         constIndexPtr index_p = (constIndexPtr)index.dp->getData();
         // Get the length of the index object
         indexType index_length = index.getLength();
         // Copy in the data
         for (indexType i = 0; i<index_length; i++)
         {
             indexType ndx = index_p[i] - 1;
             qp[ndx] = data.front();
             //      data.pop_front();
             data.erase(data.begin());
         }
         dp->dimensions.simplify();
     }
setVectorSubset()
void Nelson::ArrayOf::setVectorSubset (ArrayOf & index, ArrayOf & data)
Set a subset of an ArrayOf. Uses vector-indexing, meaning that the argument is assumed to refer to the elements in their order as a vector. So, x(10) is equivalent to x(:)(10), even if, say, x is 3 x 4. Throws an exception if there is a size mismatch between the index and the data.
This is the vector version of the multidimensional replacement function.
This requires the following steps:
Compute the maximum along each dimension
Check that data is either scalar or the right size.
Definition at line 2886 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::simpleSubindexExpression().
     {
         if (index.isEmpty())
         {
             return;
         }
         // Check the right-hand-side - if it is empty, then
         // we have a delete command in disguise.
         if (data.isEmpty())
         {
             deleteVectorSubset(index);
             return;
         }
         // Make sure the index is an ordinal type
         index.toOrdinalType();
         indexType index_length = index.getLength();
         if (index_length == 0)
         {
             return;
         }
         // Get a pointer to the index data set
         constIndexPtr index_p = (constIndexPtr) index.dp->getData();
         int advance;
         // Set the right hand side advance pointer to
         //  - 0 if the rhs is a scalar
         //  - 1 else
         if (data.isSparse())
         {
             data.makeDense();
         }
         if (data.isScalar())
         {
             advance = 0;
         }
         else if (data.getLength() == index_length)
         {
             advance = 1;
         }
         else
         {
             throw Exception(_W("Size mismatch in assignment A(I) = B."));
         }
         // Compute the maximum index
         indexType max_index = index.getMaxAsIndex();
         // If the RHS type is superior to ours, we
         // force our type to agree with the inserted data.
         // Also, if we are empty, we promote ourselves (regardless of
         // our type).
         if (!isEmpty() &&
                 (data.getDataClass() == NLS_STRUCT_ARRAY) &&
                 (getDataClass() == NLS_STRUCT_ARRAY))
         {
             if (data.dp->fieldNames.size() > dp->fieldNames.size())
             {
                 promoteType(NLS_STRUCT_ARRAY,data.dp->fieldNames);
             }
             else
             {
                 data.promoteType(NLS_STRUCT_ARRAY,dp->fieldNames);
             }
         }
         else
         {
             if (isEmpty() || data.getDataClass() > getDataClass())
             {
                 promoteType(data.getDataClass(),data.dp->fieldNames);
             }
             // If our type is superior to the RHS, we convert
             // the RHS to our type
             else if (data.getDataClass() <= dp->dataClass)
             {
                 data.promoteType(dp->dataClass,dp->fieldNames);
             }
         }
         if (isSparse())
         {
             indexType rows = getDimensionLength(0);
             indexType cols = getDimensionLength(1);
 #ifdef __NLS_USE_SPARSE_EIGEN
             void *qp = SetSparseVectorSubsetsDynamicFunction(dp->dataClass, rows, cols, dp->getData(),
                        (const indexType*)index.dp->getData(),
                        index.getDimensionLength(0),
                        index.getDimensionLength(1),
                        data.getDataPointer(),
                        advance);
 #else
             void *qp = SetSparseVectorSubsets(dp->dataClass, rows, cols, dp->getData(),
                                               (const indexType*)index.dp->getData(),
                                               index.getDimensionLength(0),
                                               index.getDimensionLength(1),
                                               data.getDataPointer(),
                                               advance);
 #endif
             Dimensions newdim;
             newdim[0] = rows;
             newdim[1] = cols;
             dp = dp->putData(dp->dataClass,newdim,qp,true);
             return;
         }
         // If the max index is larger than our current length, then
         // we have to resize ourselves - but this is only legal if we are
         // a vector.
         vectorResize(max_index);
         // Get a writable data pointer
         void *qp = getReadWriteDataPointer();
         // Now, we copy data from the RHS to our real part,
         // computing indices along the way.
         indexType srcIndex = 0;
         indexType j = 0;
         for (indexType i = 0; i < index_length; i++)
         {
             j = index_p[i] - 1;
             data.copyElements(srcIndex,qp,j,1);
             srcIndex += advance;
         }
     }
singleConstructor()
ArrayOf Nelson::ArrayOf::singleConstructor (float aval) static
Scalar constructor - Construct an NLS_SINGLE object with a scalar value.
Definition at line 37 of file ArrayOf_SingleType.cpp.
Referenced by Nelson::Evaluator::expression().
     {
         Dimensions dim;
         dim.makeScalar();
         float *data = (float *)allocateArrayOf(NLS_SINGLE, 1);
         *data = aval;
         return ArrayOf(NLS_SINGLE, dim, data);
     }
stringConstructor() [1/2]
ArrayOf Nelson::ArrayOf::stringConstructor (std::string aval) static
String constructor - Construct an NLS_STRING object with the given string as a value.
Definition at line 61 of file ArrayOf_StringType.cpp.
Referenced by Nelson::Evaluator::expression(), and Nelson::Evaluator::specialFunctionCall().
     {
         std::wstring str = utf8_to_wstring(astr);
         return stringConstructor(str);
     }
stringConstructor() [2/2]
ArrayOf Nelson::ArrayOf::stringConstructor (std::wstring aval) static
String constructor - Construct an NLS_STRING object with the given string as a value.
Definition at line 43 of file ArrayOf_StringType.cpp.
     {
         charType *cp = nullptr;
         indexType length = astr.length();
         Dimensions dim(0, length);
         if (length == 0)
         {
             dim[0] = 0;
         }
         else
         {
             dim[0] = 1;
         }
         cp = (charType *)allocateArrayOf(NLS_STRING, length);
         memcpy(cp, astr.c_str(), length * sizeof(charType));
         return ArrayOf(NLS_STRING, dim, cp);
     }
structConstructor()
ArrayOf Nelson::ArrayOf::structConstructor (stringVector fNames, ArrayOfVector & values) static
Structure constructor - this is equivalent to the built in struct command. First, we have to make sure that each entry of "values" have
cell arrays of the same size (say MxN)
single element cell arrays,
single values. With such a setup, the output is a structure array of size MxN. Elements which are defined by a single value or a single-element cell array are replicated throughout all MxN entries. Remaining elements take their values from the cell-array. Throws an exception if
the number of entries in the fieldnames vector does not match the number of entries in the values vector
the non-scalar values do not agree in dimension
First, we have to make sure that each entry of "values" have
cell arrays of the same size,
single element cell arrays,
single values.
Check the type of the entry. If its a non-cell array, then then ignore this entry.
This is a cell-array, so look for non-scalar cell-arrays.
At this point we can construct the dimensions of the output.
The dimensions of the object have been identified. Set the dimensions of the object and the field names. Then allocate the space.
Work through the values, and copy the values back one at a time.
Definition at line 74 of file ArrayOf_StructType.cpp.
Referenced by setFieldAsList().
     {
         const ArrayOf* rptr;
         Dimensions dims;
         sizeType i, j;
         ArrayOf *qp = nullptr;
         try
         {
             if (fNames.size() != values.size())
             {
                 throw Exception(_W("Number of field names must match number of values in structure constructor."));
             }
             bool nonSingularFound = false;
             for (i = 0; i < (sizeType)values.size(); i++)
             {
                 if (values[i].dp->dataClass == NLS_CELL_ARRAY)
                 {
                     if (!values[i].isScalar())
                     {
                         if (!nonSingularFound)
{
                             nonSingularFound = true;
                             dims = values[i].dp->dimensions;
                         }
                         else if (!dims.equals(values[i].dp->dimensions))
{
                             throw Exception(_W("ArrayOf dimensions of non-scalar entries must agree in structure construction."));
                         }
                     }
                 }
             }
             if (!nonSingularFound)
             {
                 dims.reset();
                 dims[0] = 1;
                 dims[1] = 1;
             }
             qp = (ArrayOf*)allocateArrayOf(NLS_STRUCT_ARRAY, dims.getElementCount(), fNames);
             indexType  length = dims.getElementCount();
             indexType  offset = 0;
             for (j = 0; j<length; j++)
                 for (i = 0; i < (sizeType)fNames.size(); i++)
                 {
                     ArrayOf rval = values[i];
                     if (rval.isSparse())
                     {
                         throw Exception(_W("sparse arrays not supported for struct constructor."));
                     }
                     rptr = (const ArrayOf*)rval.dp->getData();
                     if (rval.dp->dataClass == NLS_CELL_ARRAY)
                     {
                         if (rval.isScalar())
{
                             qp[offset] = rptr[0];
                         }
                         else
{
                             qp[offset] = rptr[j];
                         }
                     }
                     else
                     {
                         qp[offset] = rval;
                     }
                     offset++;
                 }
             return ArrayOf(NLS_STRUCT_ARRAY, dims, qp, false, fNames);
         }
         catch (Exception &e)
         {
             e.what();
             ArrayOf* rp = (ArrayOf*)qp;
             delete[] rp;
             rp = nullptr;
             qp = nullptr;
             throw;
         }
     }
summarizeCellEntry()
void Nelson::ArrayOf::summarizeCellEntry () const
Summarize this array when it appears in a Cell array.
Print this object when it is an element of a cell array. This is generally a shorthand summary of the description of the object.
Definition at line 3524 of file ArrayOf.cpp.
Referenced by printMe(), and summarizeCellEntry().
     {
         if (isEmpty())
         {
             if (dp->dataClass == NLS_STRING)
             {
                 io->outputMessage("''");
             }
             else
             {
                 io->outputMessage("[]");
             }
         }
         else
         {
             switch(dp->dataClass)
             {
                 case NLS_CELL_ARRAY:
                     io->outputMessage("{");
                     dp->dimensions.printMe(io);
                     io->outputMessage(" cell }");
                     break;
                 case NLS_STRUCT_ARRAY:
                     io->outputMessage(" ");
                     dp->dimensions.printMe(io);
                     if (dp->getStructTypeName() == NLS_FUNCTION_HANDLE_STR)
                     {
                         io->outputMessage(std::string(" ") + NLS_FUNCTION_HANDLE_STR);
                     }
                     else if (dp->getStructTypeName() == NLS_STRUCT_ARRAY_STR)
                     {
                         io->outputMessage(" struct array");
                     }
                     else
                     {
                         io->outputMessage(std::string(" class ") + dp->getStructTypeName());
                     }
                     break;
                 case NLS_STRING:
                 {
                     Dimensions dims = dp->dimensions;
                     if (dims.isRowVector())
                     {
                         if (dims.getColumns() < (indexType)(io->getTerminalWidth() - 3))
{
                             std::wstring str = getContentsAsWideString();
                             str = L"\'" + str + L"\'";
                             io->outputMessage(str);
                             return;
                         }
                     }
                     io->outputMessage("[");
                     dp->dimensions.printMe(io);
                     io->outputMessage(" string]");
                 }
                 break;
                 case NLS_HANDLE:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer, MSGBUFLEN, "[%d]", *((const nelson_handle*)dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" handle]");
                     }
                     break;
                 case NLS_LOGICAL:
                     if (!isSparse() && dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const logical*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         if (isSparse())
{
                             io->outputMessage(" sparse");
                         }
                         io->outputMessage(" logical]");
                     }
                     break;
                 case NLS_UINT8:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const uint8*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" uint8]");
                     }
                     break;
                 case NLS_INT8:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const int8*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" int8]");
                     }
                     break;
                 case NLS_UINT16:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const uint16*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" uint16]");
                     }
                     break;
                 case NLS_INT16:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const int16*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" int16]");
                     }
                     break;
                 case NLS_UINT32:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const uint32*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" uint32]");
                     }
                     break;
                 case NLS_INT32:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%d]",*((const int32*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" int32]");
                     }
                     break;
                 case NLS_UINT64:
                 {
                     if (dp->dimensions.isScalar())
                     {
                         uint64 val = *((const uint64*)dp->getData());
                         std::string msg = "[" + std::to_string(val) + "]";
                         //snprintf(msgBuffer, MSGBUFLEN, "[" PRIu64 "]", *((const uint64*)dp->getData()));
                         //io->outputMessage(msgBuffer);
                         io->outputMessage(msg.c_str());
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" uint64]");
                     }
                 }
                 break;
                 case NLS_INT64:
                 {
                     if (dp->dimensions.isScalar())
                     {
                         int64 value = *((const int64*)dp->getData());
                         std::string msg = std::string("[") + std::to_string(value) + std::string("]");
                         //snprintf(msgBuffer, MSGBUFLEN, "[" PRId64 "]", *((const int64*)dp->getData()));
                         io->outputMessage(msg.c_str());
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" int64]");
                     }
                 }
                 break;
                 case NLS_DOUBLE:
                     if (!isSparse() && dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%lf]",*((const double*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         if (isSparse())
{
                             io->outputMessage(" sparse");
                         }
                         io->outputMessage(" double]");
                     }
                     break;
                 case NLS_DCOMPLEX:
                     if (!isSparse() && dp->dimensions.isScalar())
                     {
                         const double *ap = (const double*) dp->getData();
                         snprintf(msgBuffer,MSGBUFLEN,"[%lf+%lfi]",ap[0],ap[1]);
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         if (isSparse())
{
                             io->outputMessage(" sparse");
                         }
                         io->outputMessage(" dcomplex]");
                     }
                     break;
                 case NLS_SINGLE:
                     if (dp->dimensions.isScalar())
                     {
                         snprintf(msgBuffer,MSGBUFLEN,"[%f]",*((const float*) dp->getData()));
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" float]");
                     }
                     break;
                 case NLS_SCOMPLEX:
                     if (dp->dimensions.isScalar())
                     {
                         const float *ap = (const float*) dp->getData();
                         snprintf(msgBuffer,MSGBUFLEN,"[%f+%fi]",ap[0],ap[1]);
                         io->outputMessage(msgBuffer);
                     }
                     else
                     {
                         io->outputMessage("[");
                         dp->dimensions.printMe(io);
                         io->outputMessage(" complex]");
                     }
                     break;
             }
         }
     }
testCaseMatchScalar()
const bool Nelson::ArrayOf::testCaseMatchScalar (ArrayOf x) const
Returns true if we match the scalar value in x. For strings, this is done by doing a string compare. For numerical values, we promote to a common type and do a comparison.
Definition at line 1532 of file ArrayOf.cpp.
Referenced by testForCaseMatch().
     {
         if (isSparse())
         {
             throw Exception(_W("isPositive not supported for sparse arrays."));
         }
         // Now we have to compare ourselves to the argument.  Check for the
         // case that we are a string type
         if (isSingleString())
         {
             // If x is not a string, we cannot match
             if (!x.isSingleString())
             {
                 return false;
             }
             // if x is a string do a string, string compare.
             std::wstring s1 = getContentsAsWideString();
             std::wstring s2 = x.getContentsAsWideString();
             bool retval = (s1.compare(s2) == 0);
             return retval;
         }
         if (!x.isScalar())
         {
             return false;
         }
         //  OK - we are not a string, so we have a numerical comparison.  To do this,
         // we have to make both objects the same type.
         ArrayOf y = *this;
         if (x.getDataClass() > y.getDataClass())
         {
             y.promoteType(x.getDataClass());
         }
         else
         {
             x.promoteType(y.getDataClass());
         }
         // Finally, we can do a compare....
         const void *x_dp = x.dp->getData();
         const void *y_dp = y.dp->getData();
         bool retval = false;
         switch(x.dp->dataClass)
         {
                 caseMacroReal(NLS_LOGICAL,logical);
                 caseMacroReal(NLS_UINT8,uint8);
                 caseMacroReal(NLS_INT8,int8);
                 caseMacroReal(NLS_UINT16,uint16);
                 caseMacroReal(NLS_INT16,int16);
                 caseMacroReal(NLS_UINT32,uint32);
                 caseMacroReal(NLS_INT32,int32);
                 caseMacroReal(NLS_UINT64, uint64);
                 caseMacroReal(NLS_INT64, int64);
                 caseMacroReal(NLS_SINGLE,float);
                 caseMacroReal(NLS_DOUBLE,double);
                 caseMacroComplex(NLS_SCOMPLEX,float);
                 caseMacroComplex(NLS_DCOMPLEX,double);
         }
         return retval;
     }
testForCaseMatch()
const bool Nelson::ArrayOf::testForCaseMatch (ArrayOf x) const
Returns true if we match the argument x, or if x is a cell-array, returns true if we match any of the cells in x. Uses ArrayOf::testCaseMatchScalar to do the actual testing. Throws an exception for non-scalars (apart from strings) or reference types. Also throws an exception if the argument is not either a scalar or a cell array.
Definition at line 1593 of file ArrayOf.cpp.
Referenced by Nelson::Evaluator::testCaseStatement().
     {
         if (isSparse())
         {
             throw Exception(_W("isPositive not supported for sparse arrays."));
         }
         // We had better be a scalar
         if (!(isScalar() || isString()))
         {
             throw Exception(_W("Switch argument must be a scalar or a string"));
         }
         // And we had better not be a reference type
         if (isReferenceType())
         {
             throw Exception(_W("Switch argument cannot be a reference type (struct or cell array)"));
         }
         // If x is a scalar, we just need to call the scalar version
         if (x.isScalar() || x.isSingleString())
         {
             return testCaseMatchScalar(x);
         }
         if (x.dp->dataClass != NLS_CELL_ARRAY)
         {
             throw Exception(_W("Case arguments must either be a scalar or a cell array"));
         }
         const ArrayOf* qp = (const ArrayOf*) x.dp->getData();
         indexType len = x.getLength();
         bool foundMatch = false;
         indexType i = 0;
         while (i<len && !foundMatch)
         {
             foundMatch = testCaseMatchScalar(qp[i]);
             i++;
         }
         return foundMatch;
     }
toOrdinalType()
void Nelson::ArrayOf::toOrdinalType ()
Convert us to an index type Convert the current object to an ordinal one. This has different meanings for different data types.
For string types, this conversion is not defined.
For logical types, this is accomplished using a linear search (done in two passes - one to identify the length of the final array, and another to identify the indices of non-zero values.
For double types, this is done by typecasting (truncation). A warning is emitted if the source value is fractional (non-integer) or invalid (zero or negative).
For complex types, this is done by typecasting. The complex part is ignored, and a warning that this is the case is emitted also. Throws an exception for string, cell, structure types, or if a zero or negative index is encountered.
Definition at line 424 of file ArrayOf.cpp.
Referenced by deleteNDimSubset(), deleteVectorSubset(), getVectorContents(), getVectorContentsAsList(), getVectorSubset(), setVectorContents(), setVectorContentsAsList(), and setVectorSubset().
     {
         if (isSparse())
         {
             makeDense();
         }
         switch(dp->dataClass)
         {
             case NLS_LOGICAL:
             {
                 // We make a first pass through the array, and count the number of
                 // non-zero entries.
                 const logical *rp = (const logical *) dp->getData();
                 int indexCount = 0;
                 indexType len = getLength();
                 indexType i = 0;
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (i=0; i<len; i++)
                     if (rp[i] != 0)
                     {
                         indexCount++;
                     }
                 // Allocate space to hold the new type.
                 //indexType *lp = (indexType *) Malloc(indexCount*sizeof(indexType));
                 indexType *lp = new_with_exception<indexType>(indexCount);
                 indexType *qp = lp;
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (i=0; i<len; i++)
                     if (rp[i] != 0)
                     {
                         *qp++ = (indexType) (i+1);
                     }
                 // Reset our data pointer to the new vector.
                 Dimensions dimensions;
                 dimensions[1] = 1;
                 dimensions[0] = indexCount;
                 // Change the class to an NLS_UINT32.
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64,dimensions,lp);
 #else
                 dp = dp->putData(NLS_UINT32, dimensions, lp);
 #endif
             }
             break;
             case NLS_STRING:
             {
                 throw Exception(_W("Cannot convert string data types to indices."));
             }
             break;
             case NLS_DCOMPLEX:
             {
                 io->warningMessage(_W("Imaginary part of complex index ignored.\n"));
                 // We convert complex values into real values
                 const double *rp = (const double *) dp->getData();
                 indexType len = getLength();
                 indexType ndx = 0;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
                 for (indexType i=0; i<len; i++)
                 {
                     ndx = (indexType) rp[i<<1];
                     if ((double) ndx != rp[i<<1])
                     {
                         throw Exception(_W("index must either be real positive integers or logicals."));
                     }
                     if (ndx <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64,dp->getDimensions(),lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_SCOMPLEX:
             {
                 io->warningMessage("Imaginary part of complex index ignored.\n");
                 // We convert complex values into real values
                 const float *rp = (const float *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
                 for (indexType i=0; i<len; i++)
                 {
                     ndx = (indexType) rp[i<<1];
                     if ((double) ndx != rp[i<<1])
                     {
                         throw Exception(_W("index must either be real positive integers or logicals."));
                     }
                     if (ndx <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_DOUBLE:
             {
                 const double *rp = (const double *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
                 for (indexType i=0; i<len; i++)
                 {
                     ndx = (indexType) rp[i];
                     if ((double) ndx != rp[i])
                     {
                         throw Exception(_W("index must either be real positive integers or logicals."));
                     }
                     if (ndx <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64,dp->getDimensions(),lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_SINGLE:
             {
                 const float *rp = (const float *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
                 for (indexType i=0; i<len; i++)
                 {
                     ndx = (indexType) rp[i];
                     if ((double) ndx != rp[i])
                     {
                         throw Exception(_W("index must either be real positive integers or logicals."));
                     }
                     if (ndx <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64,dp->getDimensions(),lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_INT64:
             {
                 const int64 *rp = (const int64 *)dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
                 for (indexType i = 0; i<len; i++)
                 {
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     ndx = (indexType)rp[i];
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_UINT64:
             {
                 const uint64 *rp = (const uint64 *)dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     if (rp[i] > std::numeric_limits<indexType>::max())
                     {
                         throw Exception(_W("Too big index encountered."));
                     }
                     ndx = (indexType)rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_INT32:
             {
                 const int32 *rp = (const int32 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64,dp->getDimensions(),lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_UINT32:
             {
                 const uint32 *rp = (const uint32 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_INT16:
             {
                 const int16 *rp = (const int16 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_UINT16:
             {
                 const uint16 *rp = (const uint16 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_INT8:
             {
                 const int8 *rp = (const int8 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_UINT8:
             {
                 const uint8 *rp = (const uint8 *) dp->getData();
                 indexType len = getLength();
                 indexType ndx;
                 // Allocate space to hold the new type
                 indexType *lp = new_with_exception<indexType>(len);
 #if defined(__NLS_WITH_OPENMP)
                 #pragma omp parallel for
 #endif
                 for (indexType i = 0; i<len; i++)
                 {
                     ndx = rp[i];
                     if (rp[i] <= 0)
                     {
                         throw Exception(_W("Zero or negative index encountered."));
                     }
                     lp[i] = ndx;
                 }
 #ifdef NLS_INDEX_TYPE_64
                 dp = dp->putData(NLS_UINT64, dp->getDimensions(), lp);
 #else
                 dp = dp->putData(NLS_UINT32, dp->getDimensions(), lp);
 #endif
             }
             break;
             case NLS_HANDLE:
             {
                 throw Exception(_W("Cannot convert handle arrays to indices."));
             }
             break;
             case NLS_CELL_ARRAY:
             {
                 throw Exception(_W("Cannot convert cell arrays to indices."));
             }
             break;
             case NLS_STRUCT_ARRAY:
             {
                 throw Exception(_W("Cannot convert structure arrays to indices."));
             }
             break;
         }
     }
uint16Constructor()
ArrayOf Nelson::ArrayOf::uint16Constructor (uint16 aval) static
Scalar constructor - Construct an NLS_UINT16 object with a scalar value.
Definition at line 43 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         uint16 *data = (uint16 *)allocateArrayOf(NLS_UINT16, 1);
         *data = aval;
         return ArrayOf(NLS_UINT16, dim, data);
     }
uint32Constructor()
ArrayOf Nelson::ArrayOf::uint32Constructor (uint32 aval) static
Scalar constructor - Construct an NLS_UINT32 object with a scalar value.
Definition at line 61 of file ArrayOf_IntegersType.cpp.
Referenced by deleteNDimSubset().
     {
         Dimensions dim;
         dim.makeScalar();
         uint32 *data = (uint32 *)allocateArrayOf(NLS_UINT32, 1);
         *data = aval;
         return ArrayOf(NLS_UINT32, dim, data);
     }
uint64Constructor()
ArrayOf Nelson::ArrayOf::uint64Constructor (uint64 aval) static
Scalar constructor - Construct an NLS_UINT64 object with a scalar value.
Definition at line 79 of file ArrayOf_IntegersType.cpp.
Referenced by Nelson::Evaluator::expression().
     {
         Dimensions dim;
         dim.makeScalar();
         uint64 *data = (uint64 *)allocateArrayOf(NLS_UINT64, 1);
         *data = aval;
         return ArrayOf(NLS_UINT64, dim, data);
     }
uint8Constructor()
ArrayOf Nelson::ArrayOf::uint8Constructor (uint8 aval) static
Scalar constructor - Construct an NLS_UINT8 object with a scalar value.
Definition at line 25 of file ArrayOf_IntegersType.cpp.
     {
         Dimensions dim;
         dim.makeScalar();
         uint8 *data = (uint8 *)allocateArrayOf(NLS_UINT8, 1);
         *data = aval;
         return ArrayOf(NLS_UINT8, dim, data);
     }
vectorResize()
void Nelson::ArrayOf::vectorResize (indexType max_index)
Resize an array based on a vector indexing expression. This method resizes an object so that an index of the type this(n) is valid. In particular, if "this" is a scalar, then this(n) extends the array in the column dimension. If "this" is a column vector, then this(n) extends the array in the row dimension. If "this" is a row vector, then this(n) extends the array in the column direction. For an arbitrarily dimensioned array, this(n) makes the array into a row vector of length n.
Definition at line 1224 of file ArrayOf.cpp.
Referenced by Nelson::MacroFunctionDef::evaluateFunction(), setVectorContents(), setVectorContentsAsList(), and setVectorSubset().
     {
         if (max_index > getLength())
         {
             Dimensions newDim;
             if (isEmpty() || dp->dimensions.isScalar())
             {
                 newDim.reset();
                 newDim[0] = 1;
                 newDim[1] = max_index;
             }
             else if (dp->dimensions.isVector())
             {
                 newDim = dp->dimensions;
                 if (dp->dimensions[0] != 1)
                 {
                     newDim[0] = max_index;
                 }
                 else
                 {
                     newDim[1] = max_index;
                 }
             }
             else
             {
                 // First reshape it
                 Dimensions tDim(2);
                 tDim[0] = 1;
                 tDim[1] = getLength();
                 reshape(tDim);
                 newDim.reset();
                 newDim[0] = 1;
                 newDim[1] = max_index;
             }
             resize(newDim);
         }
     }
The documentation for this class was generated from the following files:
F:/Developpements/GitHub/nelson/modules/types/src/include/ArrayOf.hpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_CellType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_DoubleType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_FunctionHandleType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_IntegersType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_LogicalType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_SingleType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_SparseType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_StringType.cpp
F:/Developpements/GitHub/nelson/modules/types/src/cpp/ArrayOf_StructType.cpp